/* Generated by scripts/media/prepare-hero-van-sequence.mjs. Do not edit manually. */
export const HERO_VAN_BASELINE_Y = 0.97053407;
export const HERO_VAN_FRAMES = [
  {
    "id": "yaw-000",
    "yaw": 0,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-000-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-000-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "001_000deg.png"
  },
  {
    "id": "yaw-005",
    "yaw": 5,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-005-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-005-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "002_005deg.png"
  },
  {
    "id": "yaw-010",
    "yaw": 10,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-010-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-010-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "003_010deg.png"
  },
  {
    "id": "yaw-015",
    "yaw": 15,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-015-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-015-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "004_015deg.png"
  },
  {
    "id": "yaw-020",
    "yaw": 20,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-020-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-020-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "005_020deg.png"
  },
  {
    "id": "yaw-025",
    "yaw": 25,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-025-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-025-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "006_025deg.png"
  },
  {
    "id": "yaw-030",
    "yaw": 30,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-030-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-030-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "007_030deg.png"
  },
  {
    "id": "yaw-035",
    "yaw": 35,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-035-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-035-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "008_035deg.png"
  },
  {
    "id": "yaw-040",
    "yaw": 40,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-040-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-040-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "009_040deg.png"
  },
  {
    "id": "yaw-045",
    "yaw": 45,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-045-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-045-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "010_045deg.png"
  },
  {
    "id": "yaw-050",
    "yaw": 50,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-050-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-050-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "011_050deg.png"
  },
  {
    "id": "yaw-055",
    "yaw": 55,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-055-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-055-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "012_055deg.png"
  },
  {
    "id": "yaw-060",
    "yaw": 60,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-060-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-060-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "013_060deg.png"
  },
  {
    "id": "yaw-065",
    "yaw": 65,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-065-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-065-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "014_065deg.png"
  },
  {
    "id": "yaw-070",
    "yaw": 70,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-070-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-070-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "015_070deg.png"
  },
  {
    "id": "yaw-075",
    "yaw": 75,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-075-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-075-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "016_075deg.png"
  },
  {
    "id": "yaw-080",
    "yaw": 80,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-080-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-080-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "017_080deg.png"
  },
  {
    "id": "yaw-085",
    "yaw": 85,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-085-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-085-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "018_085deg.png"
  },
  {
    "id": "yaw-090",
    "yaw": 90,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-090-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-090-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "019_090deg_true_front.png"
  }
] as const;
export const HERO_VAN_SEQUENCE: readonly string[] = HERO_VAN_FRAMES.map((frame) => frame.id);
