/* Generated by scripts/media/prepare-hero-van-sequence.mjs. Do not edit manually. */
export const HERO_VAN_CANVAS_ASPECT = 1.3333333333333333;
export const HERO_VAN_VISIBLE_HEIGHT_RATIO = 0.5524861878453039;
export const HERO_VAN_BASELINE_Y = 0.9401473296500921;
export const HERO_VAN_VISIBLE_CENTER_X = 0.5;
export const HERO_VAN_VISIBLE_CENTER_Y = 0.664364640883978;
export const HERO_VAN_FRAMES = [
  {
    "id": "yaw-000",
    "yaw": 0,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-000-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-000-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "001_000deg.png",
    "sourceBounds": {
      "left": 25,
      "top": 237,
      "right": 1444,
      "bottom": 893,
      "visibleWidth": 1420,
      "visibleHeight": 657,
      "visibleCenterX": 734.5,
      "visibleCenterY": 565
    },
    "normalizedBounds": {
      "left": 78,
      "top": 422,
      "right": 1371,
      "bottom": 1021,
      "visibleWidth": 1294,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-005",
    "yaw": 5,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-005-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-005-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "002_005deg.png",
    "sourceBounds": {
      "left": 23,
      "top": 240,
      "right": 1424,
      "bottom": 893,
      "visibleWidth": 1402,
      "visibleHeight": 654,
      "visibleCenterX": 723.5,
      "visibleCenterY": 566.5
    },
    "normalizedBounds": {
      "left": 82,
      "top": 422,
      "right": 1367,
      "bottom": 1021,
      "visibleWidth": 1286,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-010",
    "yaw": 10,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-010-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-010-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "003_010deg.png",
    "sourceBounds": {
      "left": 26,
      "top": 237,
      "right": 1428,
      "bottom": 890,
      "visibleWidth": 1403,
      "visibleHeight": 654,
      "visibleCenterX": 727,
      "visibleCenterY": 563.5
    },
    "normalizedBounds": {
      "left": 81,
      "top": 422,
      "right": 1368,
      "bottom": 1021,
      "visibleWidth": 1288,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-015",
    "yaw": 15,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-015-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-015-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "004_015deg.png",
    "sourceBounds": {
      "left": 21,
      "top": 226,
      "right": 1424,
      "bottom": 891,
      "visibleWidth": 1404,
      "visibleHeight": 666,
      "visibleCenterX": 722.5,
      "visibleCenterY": 558.5
    },
    "normalizedBounds": {
      "left": 92,
      "top": 422,
      "right": 1357,
      "bottom": 1021,
      "visibleWidth": 1266,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-020",
    "yaw": 20,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-020-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-020-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "005_020deg.png",
    "sourceBounds": {
      "left": 19,
      "top": 225,
      "right": 1428,
      "bottom": 906,
      "visibleWidth": 1410,
      "visibleHeight": 682,
      "visibleCenterX": 723.5,
      "visibleCenterY": 565.5
    },
    "normalizedBounds": {
      "left": 104,
      "top": 422,
      "right": 1345,
      "bottom": 1021,
      "visibleWidth": 1242,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-025",
    "yaw": 25,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-025-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-025-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "006_025deg.png",
    "sourceBounds": {
      "left": 25,
      "top": 225,
      "right": 1431,
      "bottom": 924,
      "visibleWidth": 1407,
      "visibleHeight": 700,
      "visibleCenterX": 728,
      "visibleCenterY": 574.5
    },
    "normalizedBounds": {
      "left": 122,
      "top": 422,
      "right": 1326,
      "bottom": 1021,
      "visibleWidth": 1205,
      "visibleHeight": 600,
      "visibleCenterX": 724,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-030",
    "yaw": 30,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-030-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-030-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "007_030deg.png",
    "sourceBounds": {
      "left": 28,
      "top": 214,
      "right": 1435,
      "bottom": 940,
      "visibleWidth": 1408,
      "visibleHeight": 727,
      "visibleCenterX": 731.5,
      "visibleCenterY": 577
    },
    "normalizedBounds": {
      "left": 144,
      "top": 422,
      "right": 1304,
      "bottom": 1021,
      "visibleWidth": 1161,
      "visibleHeight": 600,
      "visibleCenterX": 724,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-035",
    "yaw": 35,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-035-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-035-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "008_035deg.png",
    "sourceBounds": {
      "left": 28,
      "top": 195,
      "right": 1418,
      "bottom": 926,
      "visibleWidth": 1391,
      "visibleHeight": 732,
      "visibleCenterX": 723,
      "visibleCenterY": 560.5
    },
    "normalizedBounds": {
      "left": 154,
      "top": 422,
      "right": 1295,
      "bottom": 1021,
      "visibleWidth": 1142,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-040",
    "yaw": 40,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-040-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-040-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "009_040deg.png",
    "sourceBounds": {
      "left": 31,
      "top": 179,
      "right": 1412,
      "bottom": 923,
      "visibleWidth": 1382,
      "visibleHeight": 745,
      "visibleCenterX": 721.5,
      "visibleCenterY": 551
    },
    "normalizedBounds": {
      "left": 170,
      "top": 422,
      "right": 1279,
      "bottom": 1021,
      "visibleWidth": 1110,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-045",
    "yaw": 45,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-045-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-045-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "010_045deg.png",
    "sourceBounds": {
      "left": 30,
      "top": 164,
      "right": 1418,
      "bottom": 930,
      "visibleWidth": 1389,
      "visibleHeight": 767,
      "visibleCenterX": 724,
      "visibleCenterY": 547
    },
    "normalizedBounds": {
      "left": 181,
      "top": 422,
      "right": 1267,
      "bottom": 1021,
      "visibleWidth": 1087,
      "visibleHeight": 600,
      "visibleCenterX": 724,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-050",
    "yaw": 50,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-050-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-050-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "011_050deg.png",
    "sourceBounds": {
      "left": 52,
      "top": 163,
      "right": 1403,
      "bottom": 964,
      "visibleWidth": 1352,
      "visibleHeight": 802,
      "visibleCenterX": 727.5,
      "visibleCenterY": 563.5
    },
    "normalizedBounds": {
      "left": 220,
      "top": 422,
      "right": 1228,
      "bottom": 1021,
      "visibleWidth": 1009,
      "visibleHeight": 600,
      "visibleCenterX": 724,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-055",
    "yaw": 55,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-055-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-055-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "012_055deg.png",
    "sourceBounds": {
      "left": 50,
      "top": 163,
      "right": 1403,
      "bottom": 963,
      "visibleWidth": 1354,
      "visibleHeight": 801,
      "visibleCenterX": 726.5,
      "visibleCenterY": 563
    },
    "normalizedBounds": {
      "left": 219,
      "top": 422,
      "right": 1230,
      "bottom": 1021,
      "visibleWidth": 1012,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-060",
    "yaw": 60,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-060-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-060-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "013_060deg.png",
    "sourceBounds": {
      "left": 57,
      "top": 172,
      "right": 1403,
      "bottom": 964,
      "visibleWidth": 1347,
      "visibleHeight": 793,
      "visibleCenterX": 730,
      "visibleCenterY": 568
    },
    "normalizedBounds": {
      "left": 214,
      "top": 422,
      "right": 1235,
      "bottom": 1021,
      "visibleWidth": 1022,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-065",
    "yaw": 65,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-065-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-065-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "014_065deg.png",
    "sourceBounds": {
      "left": 77,
      "top": 161,
      "right": 1384,
      "bottom": 973,
      "visibleWidth": 1308,
      "visibleHeight": 813,
      "visibleCenterX": 730.5,
      "visibleCenterY": 567
    },
    "normalizedBounds": {
      "left": 242,
      "top": 422,
      "right": 1206,
      "bottom": 1021,
      "visibleWidth": 965,
      "visibleHeight": 600,
      "visibleCenterX": 724,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-070",
    "yaw": 70,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-070-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-070-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "015_070deg.png",
    "sourceBounds": {
      "left": 105,
      "top": 140,
      "right": 1363,
      "bottom": 977,
      "visibleWidth": 1259,
      "visibleHeight": 838,
      "visibleCenterX": 734,
      "visibleCenterY": 558.5
    },
    "normalizedBounds": {
      "left": 274,
      "top": 422,
      "right": 1175,
      "bottom": 1021,
      "visibleWidth": 902,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-075",
    "yaw": 75,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-075-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-075-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "016_075deg.png",
    "sourceBounds": {
      "left": 123,
      "top": 104,
      "right": 1393,
      "bottom": 1025,
      "visibleWidth": 1271,
      "visibleHeight": 922,
      "visibleCenterX": 758,
      "visibleCenterY": 564.5
    },
    "normalizedBounds": {
      "left": 312,
      "top": 422,
      "right": 1136,
      "bottom": 1021,
      "visibleWidth": 825,
      "visibleHeight": 600,
      "visibleCenterX": 724,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-080",
    "yaw": 80,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-080-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-080-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "017_080deg.png",
    "sourceBounds": {
      "left": 221,
      "top": 87,
      "right": 1333,
      "bottom": 1021,
      "visibleWidth": 1113,
      "visibleHeight": 935,
      "visibleCenterX": 777,
      "visibleCenterY": 554
    },
    "normalizedBounds": {
      "left": 368,
      "top": 422,
      "right": 1081,
      "bottom": 1021,
      "visibleWidth": 714,
      "visibleHeight": 600,
      "visibleCenterX": 724.5,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-085",
    "yaw": 85,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-085-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-085-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "018_085deg.png",
    "sourceBounds": {
      "left": 306,
      "top": 91,
      "right": 1267,
      "bottom": 1029,
      "visibleWidth": 962,
      "visibleHeight": 939,
      "visibleCenterX": 786.5,
      "visibleCenterY": 560
    },
    "normalizedBounds": {
      "left": 417,
      "top": 422,
      "right": 1031,
      "bottom": 1021,
      "visibleWidth": 615,
      "visibleHeight": 600,
      "visibleCenterX": 724,
      "visibleCenterY": 721.5
    }
  },
  {
    "id": "yaw-090",
    "yaw": 90,
    "desktopSrc": "/media/public/protagonists/hero-van/yaw-090-desktop.webp",
    "mobileSrc": "/media/public/protagonists/hero-van/yaw-090-mobile.webp",
    "sourceCanvasWidth": 1448,
    "sourceCanvasHeight": 1086,
    "aspectRatio": 1.3333333333333333,
    "sourceFilename": "019_090deg_true_front.png",
    "sourceBounds": {
      "left": 227,
      "top": 90,
      "right": 1220,
      "bottom": 1017,
      "visibleWidth": 994,
      "visibleHeight": 928,
      "visibleCenterX": 723.5,
      "visibleCenterY": 553.5
    },
    "normalizedBounds": {
      "left": 404,
      "top": 422,
      "right": 1044,
      "bottom": 1021,
      "visibleWidth": 641,
      "visibleHeight": 600,
      "visibleCenterX": 724,
      "visibleCenterY": 721.5
    }
  }
] as const;
export const HERO_VAN_SEQUENCE: readonly string[] = HERO_VAN_FRAMES.map((frame) => frame.id);
