import { describe, expect, it } from "vitest";
import { CatalogMediaStorageError } from "@/lib/catalog/media/catalog-media-storage-adapter";
import { DeterministicCatalogMediaStorageAdapter } from "@/lib/catalog/media/deterministic-catalog-media-storage-adapter";
import { CatalogMediaIntakeService } from "@/lib/services/catalog-media-intake.service";
import { MemoryCatalogMediaRepository, catalogMediaHarness, catalogPngFixture } from "@/tests/catalog/catalog-media-test-fixtures";

async function readyHarness() { const harness = catalogMediaHarness(); const bytes = catalogPngFixture(); const created = await harness.service.createUploadIntent({ actorUserId: "user-a", ownerType: "STORE", storeId: "store-a", purpose: "PRODUCT_IMAGE", declaredMimeType: "image/png", declaredByteSize: bytes.byteLength, operationId: "service-upload-1" }); await harness.service.receiveUploadBytes({ actorUserId: "user-a", storeId: "store-a", uploadReference: created.upload.publicReference, operationId: "service-bytes-1", bytes }); const completed = await harness.service.completeUpload({ actorUserId: "user-a", storeId: "store-a", uploadReference: created.upload.publicReference, operationId: "service-complete-1" }); return { ...harness, created, completed }; }

describe("catalog media intake service", () => {
  it("resolves store and platform ownership without cross-store access", async () => { const { service } = catalogMediaHarness(); const bytes = catalogPngFixture(); const store = await service.createUploadIntent({ actorUserId: "user-a", ownerType: "STORE", storeId: "store-a", purpose: "PRODUCT_IMAGE", declaredMimeType: "image/png", declaredByteSize: bytes.byteLength, operationId: "owner-store-1" }); expect(store.upload.asset).toMatchObject({ ownerType: "STORE", ownerStoreId: "store-a" }); const platform = await service.createUploadIntent({ actorUserId: "admin-a", ownerType: "PLATFORM", purpose: "CATEGORY_IMAGE", declaredMimeType: "image/png", declaredByteSize: bytes.byteLength, operationId: "owner-platform-1" }); expect(platform.upload.asset).toMatchObject({ ownerType: "PLATFORM", ownerStoreId: null }); await expect(service.receiveUploadBytes({ actorUserId: "user-b", storeId: "store-b", uploadReference: store.upload.publicReference, operationId: "cross-store-1", bytes })).rejects.toMatchObject({ code: "CATALOG_MEDIA_UPLOAD_FORBIDDEN" }); });
  it("moves valid bytes through UPLOADED VALIDATING and READY", async () => { const { completed, repository } = await readyHarness(); expect(completed.asset).toMatchObject({ status: "READY", mimeType: "image/png", width: 400, height: 400 }); const stored = await repository.findAsset(completed.asset.publicReference); expect(stored?.checksum).toMatch(/^[0-9a-f]{64}$/); });
  it("keeps duplicate bytes isolated under separate owners", async () => { const { service, repository } = catalogMediaHarness(); const bytes = catalogPngFixture(); for (const [index, storeId] of ["store-a", "store-b"].entries()) { const actor = `user-${index}`; const created = await service.createUploadIntent({ actorUserId: actor, ownerType: "STORE", storeId, purpose: "PRODUCT_IMAGE", declaredMimeType: "image/png", declaredByteSize: bytes.byteLength, operationId: `duplicate-upload-${index}` }); await service.receiveUploadBytes({ actorUserId: actor, storeId, uploadReference: created.upload.publicReference, operationId: `duplicate-bytes-${index}`, bytes }); await service.completeUpload({ actorUserId: actor, storeId, uploadReference: created.upload.publicReference, operationId: `duplicate-complete-${index}` }); } const assets = await repository.listAssets(); expect(assets).toHaveLength(2); expect(assets[0]?.checksum).toBe(assets[1]?.checksum); expect(assets[0]?.ownerStoreId).not.toBe(assets[1]?.ownerStoreId); });
  it("rejects MIME mismatch and invalid magic bytes", async () => { const { service } = catalogMediaHarness(); const bytes = catalogPngFixture(); const created = await service.createUploadIntent({ actorUserId: "user-a", ownerType: "STORE", storeId: "store-a", purpose: "PRODUCT_IMAGE", declaredMimeType: "image/jpeg", declaredByteSize: bytes.byteLength, operationId: "mime-upload-1" }); await service.receiveUploadBytes({ actorUserId: "user-a", storeId: "store-a", uploadReference: created.upload.publicReference, operationId: "mime-bytes-1", bytes }); await expect(service.completeUpload({ actorUserId: "user-a", storeId: "store-a", uploadReference: created.upload.publicReference, operationId: "mime-complete-1" })).rejects.toMatchObject({ code: "CATALOG_MEDIA_MIME_MISMATCH" }); });
  it("rejects received size mismatch and unsupported magic bytes", async () => { const first = catalogMediaHarness(); const bytes = catalogPngFixture(); const sized = await first.service.createUploadIntent({ actorUserId: "user-a", ownerType: "STORE", storeId: "store-a", purpose: "PRODUCT_IMAGE", declaredMimeType: "image/png", declaredByteSize: bytes.byteLength + 1, operationId: "size-upload-1" }); await expect(first.service.receiveUploadBytes({ actorUserId: "user-a", storeId: "store-a", uploadReference: sized.upload.publicReference, operationId: "size-bytes-1", bytes })).rejects.toMatchObject({ code: "CATALOG_MEDIA_SIZE_MISMATCH" }); expect((await first.repository.findIntentByReference(sized.upload.publicReference))?.asset.status).toBe("REJECTED"); const second = catalogMediaHarness(); const invalid = Uint8Array.of(1, 2, 3, 4); const created = await second.service.createUploadIntent({ actorUserId: "user-b", ownerType: "STORE", storeId: "store-b", purpose: "PRODUCT_IMAGE", declaredMimeType: "image/png", declaredByteSize: invalid.byteLength, operationId: "magic-upload-1" }); await second.service.receiveUploadBytes({ actorUserId: "user-b", storeId: "store-b", uploadReference: created.upload.publicReference, operationId: "magic-bytes-1", bytes: invalid }); await expect(second.service.completeUpload({ actorUserId: "user-b", storeId: "store-b", uploadReference: created.upload.publicReference, operationId: "magic-complete-1" })).rejects.toMatchObject({ code: "CATALOG_MEDIA_MAGIC_BYTES_INVALID" }); });
  it("quarantines uncertain adapter failures", async () => { class UncertainAdapter extends DeterministicCatalogMediaStorageAdapter { override async openForValidation(_input: any): Promise<Uint8Array> { throw new CatalogMediaStorageError("CATALOG_MEDIA_STORAGE_FAILURE", "uncertain"); } } const repository = new MemoryCatalogMediaRepository(); const storage = new UncertainAdapter(); const service = new CatalogMediaIntakeService(repository, storage as any, { approved: true, adapterCode: "DETERMINISTIC_TEST" }); const bytes = catalogPngFixture(); const created = await service.createUploadIntent({ actorUserId: "user-a", ownerType: "STORE", storeId: "store-a", purpose: "PRODUCT_IMAGE", declaredMimeType: "image/png", declaredByteSize: bytes.byteLength, operationId: "quarantine-upload-1" }); await service.receiveUploadBytes({ actorUserId: "user-a", storeId: "store-a", uploadReference: created.upload.publicReference, operationId: "quarantine-bytes-1", bytes }); await expect(service.completeUpload({ actorUserId: "user-a", storeId: "store-a", uploadReference: created.upload.publicReference, operationId: "quarantine-complete-1" })).rejects.toThrow(); expect((await repository.findIntentByReference(created.upload.publicReference))?.asset.status).toBe("QUARANTINED"); });
  it("expires incomplete intents and archives READY evidence without deletion", async () => { let now = new Date("2026-07-18T10:00:00.000Z"); const { service } = catalogMediaHarness(() => now); const bytes = catalogPngFixture(); const created = await service.createUploadIntent({ actorUserId: "user-a", ownerType: "STORE", storeId: "store-a", purpose: "PRODUCT_IMAGE", declaredMimeType: "image/png", declaredByteSize: bytes.byteLength, operationId: "expiry-upload-1" }); now = new Date("2026-07-18T11:00:00.000Z"); await expect(service.receiveUploadBytes({ actorUserId: "user-a", storeId: "store-a", uploadReference: created.upload.publicReference, operationId: "expiry-bytes-1", bytes })).rejects.toMatchObject({ code: "CATALOG_MEDIA_UPLOAD_EXPIRED" }); const ready = await readyHarness(); expect((await ready.service.archiveStoreAsset({ actorUserId: "user-a", storeId: "store-a", publicReference: ready.completed.asset.publicReference, operationId: "archive-media-1" })).status).toBe("ARCHIVED"); expect(ready.storage.hasObjectForTesting((await ready.repository.findAsset(ready.completed.asset.publicReference))?.storageKey ?? "")).toBe(true); });
});
