import { Prisma } from "@prisma/client";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { assertCommittedMarketplaceAdjustmentFunding } from "@/lib/services/marketplace-adjustment-refund-authority";
import { resolveRefundHeldAccount } from "@/lib/services/refund-held-account.service";
import { refundCreationHash } from "@/lib/refunds/refund-idempotency";
const f = vi.hoisted(() => ({ lock: vi.fn(), adjustment: vi.fn(), held: vi.fn(), journals: vi.fn(), refund: vi.fn() }));
const tx = { $queryRaw: f.lock, marketplaceStoreOrderAdjustment: { findUnique: f.adjustment }, ledgerAccount: { findUnique: f.held, findFirst: f.held }, ledgerJournal: { findMany: f.journals }, paymentRefund: { findFirst: f.refund } } as unknown as Prisma.TransactionClient;
const input = { adjustmentReference: "adjustment", paymentId: "payment", customerUserId: "customer", operationId: "original-operation:refund", amount: "10.00" };
function source() { return { status: "APPLYING", sourceVersion: 1, refundAmount: new Prisma.Decimal(10), deliveryFeeAmount: new Prisma.Decimal(0), storeOrder: { marketplaceOrder: { paymentId: "payment", customerUserId: "customer" }, settlementSnapshots: [{ settlementVersion: 1, commissionAccrualReference: "accrual", storeEarningReference: "earning" }] }, financialEvidence: { phase21CommittedReversals: { operationId: "original-operation", refundAmount: "10.00", commissionReversalReferences: ["journal"] } } }; }
beforeEach(() => { vi.resetAllMocks(); f.adjustment.mockResolvedValue(source()); f.held.mockResolvedValue({ id: "held" }); f.journals.mockResolvedValue([{ reference: "journal", type: "ACCOUNT_TRANSFER", currency: "ZAR", totalDebits: new Prisma.Decimal(10), totalCredits: new Prisma.Decimal(10), metadata: { operationId: "original-operation:commission:allocation", accrualReference: "accrual" }, entries: [{ direction: "DEBIT", accountId: "allocation", amount: new Prisma.Decimal(10) }, { direction: "CREDIT", accountId: "held", amount: new Prisma.Decimal(10) }] }]); f.refund.mockResolvedValue(null); });
describe("committed partial adjustment funding authority (T1 doubles)", () => {
  it("requires immutable balanced journals for exactly the bound amount", async () => { await expect(assertCommittedMarketplaceAdjustmentFunding(tx, input)).resolves.toBeUndefined(); });
  it.each([{ paymentId: "foreign" }, { customerUserId: "foreign" }, { amount: "10.01" }, { operationId: "foreign-operation:refund" }])("denies mismatched source authority %j", async changed => { await expect(assertCommittedMarketplaceAdjustmentFunding(tx, { ...input, ...changed })).rejects.toMatchObject({ code: "REFUND_FUNDING_UNAVAILABLE" }); });
  it("refuses a source claim without real restored-money journals", async () => { f.journals.mockResolvedValue([]); await expect(assertCommittedMarketplaceAdjustmentFunding(tx, input)).rejects.toMatchObject({ code: "REFUND_FUNDING_UNAVAILABLE" }); });
  it("refuses another accrual's otherwise balanced journal", async () => { const journals = await f.journals(); journals[0].metadata.accrualReference = "foreign"; await expect(assertCommittedMarketplaceAdjustmentFunding(tx, input)).rejects.toMatchObject({ code: "REFUND_FUNDING_UNAVAILABLE" }); });
  it("refuses a duplicated journal reference", async () => { const adjustment = source(); adjustment.financialEvidence.phase21CommittedReversals.commissionReversalReferences.push("journal"); f.adjustment.mockResolvedValue(adjustment); await expect(assertCommittedMarketplaceAdjustmentFunding(tx, input)).rejects.toMatchObject({ code: "REFUND_FUNDING_UNAVAILABLE" }); });
  it("binds refund command hashes to their original adjustment", () => { const base = { paymentId: "payment", customerUserId: "customer", amount: "10.00", method: "ORIGINAL_PAYMENT_METHOD" as const, reasonCode: "SERVICE_NOT_PROVIDED" as const, customerNote: null, policyVersion: 1 }; expect(refundCreationHash({ ...base, sourceAdjustmentReference: "first" })).not.toBe(refundCreationHash({ ...base, sourceAdjustmentReference: "second" })); });
  it("resolves a guest reserve only in the exact platform namespace", async () => { await resolveRefundHeldAccount(tx, null); expect(f.held).toHaveBeenCalledWith({ where: expect.objectContaining({ code: "PLATFORM-GUEST-REFUND-HELD-ZAR", wallet: { ownerType: "PLATFORM", ownerId: "platform", currency: "ZAR", status: "ACTIVE" } }) }); });
});
