export type StoreEarningErrorCode =
  | "STORE_EARNING_INVALID_COMMAND"
  | "STORE_EARNING_INVALID_SNAPSHOT"
  | "STORE_EARNING_NOT_FOUND"
  | "STORE_EARNING_FORBIDDEN"
  | "STORE_EARNING_ACCOUNT_INVALID"
  | "STORE_EARNING_PAYMENT_INVALID"
  | "STORE_EARNING_COMMISSION_INVALID"
  | "STORE_EARNING_COMMISSION_OVER_ATTRIBUTED"
  | "STORE_EARNING_IDEMPOTENCY_CONFLICT"
  | "STORE_EARNING_SETTLEMENT_ALREADY_ACCRUED"
  | "STORE_EARNING_INSUFFICIENT_HELD_FUNDS"
  | "STORE_EARNING_INVALID_STATE"
  | "STORE_EARNING_RELEASE_NOT_ELIGIBLE"
  | "STORE_EARNING_REVERSAL_NOT_ALLOWED"
  | "STORE_EARNING_REFUND_EVIDENCE_REQUIRED"
  | "STORE_EARNING_REFUND_AFTER_RELEASE"
  | "STORE_EARNING_RECONCILIATION_REQUIRED"
  | "STORE_EARNING_PRODUCTION_LOCKED";

export class StoreEarningError extends Error {
  constructor(
    readonly code: StoreEarningErrorCode,
    message: string,
    readonly details?: Readonly<Record<string, string | readonly string[]>>,
  ) {
    super(message);
    this.name = "StoreEarningError";
  }
}
