import { PERMISSIONS, type PermissionKey } from "@/lib/auth/permission-keys";

export type ProcessorTriggerType = "CRON" | "EVENT" | "MANUAL";

export type ProcessorClassification =
  | "READ_ONLY"
  | "IDEMPOTENT_ITEM_PROCESSOR"
  | "SINGLETON_MUTATING_PROCESSOR"
  | "PARTITIONED_MUTATING_PROCESSOR"
  | "EXTERNAL_DELIVERY_PROCESSOR"
  | "MAINTENANCE_PROCESSOR";

export interface RegisteredProcessor {
  readonly name: string;
  readonly version: string;
  readonly purpose: string;
  readonly triggerType: ProcessorTriggerType;
  readonly classification: ProcessorClassification;
  readonly leaseRequired: boolean;
  readonly defaultPartition: string;
  readonly defaultBatchSize: number;
  readonly maxBatchSize: number;
  readonly maxExecutionDurationSeconds: number;
  readonly retryPolicy: string;
  readonly idempotencyStrategy: string;
  readonly dryRunSupported: boolean;
  readonly manualExecutionAllowed: boolean;
  readonly requiredPermission: PermissionKey;
  readonly operationalOwnerCategory: string;
}

export const PROCESSOR_REGISTRY: Record<string, RegisteredProcessor> = {
  "consume-verified-payment-events": {
    name: "consume-verified-payment-events",
    version: "1.0.0",
    purpose: "Processes outbox payment events to ensure idempotent delivery downstream",
    triggerType: "EVENT",
    classification: "IDEMPOTENT_ITEM_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "payments",
    defaultBatchSize: 50,
    maxBatchSize: 200,
    maxExecutionDurationSeconds: 120,
    retryPolicy: "EXPONENTIAL_BACKOFF",
    idempotencyStrategy: "CONSUMER_RECEIPT_UNIQUENESS",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.PAYMENTS_READ,
    operationalOwnerCategory: "Payments & Ledger",
  },
  "finalize-paid-marketplace-checkouts": {
    name: "finalize-paid-marketplace-checkouts",
    version: "1.0.0",
    purpose: "Finalizes marketplace checkout instances following verified payment confirmation",
    triggerType: "CRON",
    classification: "SINGLETON_MUTATING_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "default",
    defaultBatchSize: 25,
    maxBatchSize: 100,
    maxExecutionDurationSeconds: 180,
    retryPolicy: "RETRY_UP_TO_MAX",
    idempotencyStrategy: "CHECKOUT_STATUS_TRANSITION",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.MARKETPLACE_CHECKOUT_RECONCILE,
    operationalOwnerCategory: "Marketplace Commerce",
  },
  "process-subscription-renewals": {
    name: "process-subscription-renewals",
    version: "1.0.0",
    purpose: "Evaluates active subscription contracts due for renewal and billing",
    triggerType: "CRON",
    classification: "PARTITIONED_MUTATING_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "billing",
    defaultBatchSize: 50,
    maxBatchSize: 200,
    maxExecutionDurationSeconds: 300,
    retryPolicy: "DUNNING_RETRY_SCHEDULE",
    idempotencyStrategy: "INVOICE_BILLING_PERIOD_UNIQUE",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.SUBSCRIPTION_BILLING_RECONCILE,
    operationalOwnerCategory: "Subscriptions",
  },
  "scan-refund-reconciliation": {
    name: "scan-refund-reconciliation",
    version: "1.0.0",
    purpose: "Identifies stalled or mismatched refund execution attempts",
    triggerType: "CRON",
    classification: "READ_ONLY",
    leaseRequired: false,
    defaultPartition: "default",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 120,
    retryPolicy: "NO_RETRY",
    idempotencyStrategy: "RECONCILIATION_CASE_IDEMPOTENT_OPEN",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.REFUNDS_RECONCILE,
    operationalOwnerCategory: "Refunds & Finance",
  },
  "scan-withdrawal-reconciliation": {
    name: "scan-withdrawal-reconciliation",
    version: "1.0.0",
    purpose: "Scans pending withdrawal requests for payout discrepancies",
    triggerType: "CRON",
    classification: "READ_ONLY",
    leaseRequired: false,
    defaultPartition: "default",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 120,
    retryPolicy: "NO_RETRY",
    idempotencyStrategy: "RECONCILIATION_CASE_IDEMPOTENT_OPEN",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.WITHDRAWALS_RECONCILE,
    operationalOwnerCategory: "Withdrawals & Finance",
  },
  "release-mature-store-earnings": {
    name: "release-mature-store-earnings",
    version: "1.0.0",
    purpose: "Releases held store earnings past mature clearance threshold",
    triggerType: "CRON",
    classification: "PARTITIONED_MUTATING_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "store-settlement",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 240,
    retryPolicy: "RETRY_NEXT_CYCLE",
    idempotencyStrategy: "EARNING_STATUS_MATURING_CHECK",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.STORE_EARNINGS_RECONCILE,
    operationalOwnerCategory: "Store Settlement",
  },
  "release-mature-driver-earnings": {
    name: "release-mature-driver-earnings",
    version: "1.0.0",
    purpose: "Releases held driver earnings past clearance window",
    triggerType: "CRON",
    classification: "PARTITIONED_MUTATING_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "driver-settlement",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 240,
    retryPolicy: "RETRY_NEXT_CYCLE",
    idempotencyStrategy: "DRIVER_EARNING_STATUS_CHECK",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.DRIVER_EARNINGS_RECONCILE,
    operationalOwnerCategory: "Driver Operations",
  },
  "process-promoter-qualifications": {
    name: "process-promoter-qualifications",
    version: "1.0.0",
    purpose: "Evaluates pending referral attributions for qualification",
    triggerType: "CRON",
    classification: "IDEMPOTENT_ITEM_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "promoters",
    defaultBatchSize: 50,
    maxBatchSize: 250,
    maxExecutionDurationSeconds: 180,
    retryPolicy: "RETRY_UP_TO_MAX",
    idempotencyStrategy: "ATTRIBUTION_QUALIFICATION_UNIQUE",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.PROMOTER_RECONCILIATION_MANAGE,
    operationalOwnerCategory: "Promoters & Growth",
  },
  "end-expired-promotions": {
    name: "end-expired-promotions",
    version: "1.0.0",
    purpose: "Deactivates store promotion campaigns past effective end date",
    triggerType: "CRON",
    classification: "MAINTENANCE_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "promotions",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 120,
    retryPolicy: "IMMEDIATE_RETRY",
    idempotencyStrategy: "PROMOTION_STATUS_EXPIRED",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.PROMOTIONS_RECONCILIATION_MANAGE,
    operationalOwnerCategory: "Promotions",
  },
  "process-valid-click-charges": {
    name: "process-valid-click-charges",
    version: "1.0.0",
    purpose: "Aggregates ad click logs and posts billing charges to advertising accounts",
    triggerType: "CRON",
    classification: "PARTITIONED_MUTATING_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "ad-billing",
    defaultBatchSize: 200,
    maxBatchSize: 1000,
    maxExecutionDurationSeconds: 300,
    retryPolicy: "RETRY_UP_TO_MAX",
    idempotencyStrategy: "CLICK_BATCH_LOG_HASH",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.ADVERTISING_RECONCILIATION_MANAGE,
    operationalOwnerCategory: "Advertising",
  },
  "deliver-notifications": {
    name: "deliver-notifications",
    version: "1.0.0",
    purpose: "Dispatches pending queued notifications to channel providers",
    triggerType: "EVENT",
    classification: "EXTERNAL_DELIVERY_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "notifications",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 180,
    retryPolicy: "EXPONENTIAL_BACKOFF",
    idempotencyStrategy: "DELIVERY_ATTEMPT_IDEMPOTENCY",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.NOTIFICATION_RECONCILIATION_RETRY,
    operationalOwnerCategory: "Notifications",
  },
  "deliver-developer-webhooks": {
    name: "deliver-developer-webhooks",
    version: "1.0.0",
    purpose: "Delivers developer API webhook event payloads with signature validation",
    triggerType: "EVENT",
    classification: "EXTERNAL_DELIVERY_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "webhooks",
    defaultBatchSize: 50,
    maxBatchSize: 200,
    maxExecutionDurationSeconds: 180,
    retryPolicy: "EXPONENTIAL_BACKOFF",
    idempotencyStrategy: "WEBHOOK_DELIVERY_ATTEMPT_UNIQUE",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.DEVELOPER_RECONCILIATION_RETRY,
    operationalOwnerCategory: "Developer Platform",
  },
  "generate-report-jobs": {
    name: "generate-report-jobs",
    version: "1.0.0",
    purpose: "Executes asynchronous report export queries and compiles safe artifacts",
    triggerType: "CRON",
    classification: "SINGLETON_MUTATING_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "reports",
    defaultBatchSize: 10,
    maxBatchSize: 50,
    maxExecutionDurationSeconds: 600,
    retryPolicy: "SINGLE_RETRY",
    idempotencyStrategy: "REPORT_JOB_STATUS_CLAIM",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.REPORT_RECONCILIATION_RETRY,
    operationalOwnerCategory: "Reporting",
  },
  "expire-report-artifacts": {
    name: "expire-report-artifacts",
    version: "1.0.0",
    purpose: "Purges expired report export files from object storage safely",
    triggerType: "CRON",
    classification: "MAINTENANCE_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "artifact-cleanup",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 180,
    retryPolicy: "RETRY_NEXT_CYCLE",
    idempotencyStrategy: "STORAGE_OBJECT_DELETION_IDEMPOTENT",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.REPORT_RECONCILIATION_RETRY,
    operationalOwnerCategory: "Reporting",
  },
  "process-privacy-requests": {
    name: "process-privacy-requests",
    version: "1.0.0",
    purpose: "Executes identity-verified privacy request access and hold-checked minimization",
    triggerType: "MANUAL",
    classification: "IDEMPOTENT_ITEM_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "privacy",
    defaultBatchSize: 10,
    maxBatchSize: 50,
    maxExecutionDurationSeconds: 300,
    retryPolicy: "RETRY_UP_TO_MAX",
    idempotencyStrategy: "PRIVACY_FULFILMENT_EVIDENCE_UNIQUE",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.PRIVACY_REQUESTS_MANAGE,
    operationalOwnerCategory: "Governance & Privacy",
  },
  "process-data-retention": {
    name: "process-data-retention",
    version: "1.0.0",
    purpose: "Applies typed retention policy rules with hold evaluation and payload minimization",
    triggerType: "CRON",
    classification: "MAINTENANCE_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "retention",
    defaultBatchSize: 500,
    maxBatchSize: 2000,
    maxExecutionDurationSeconds: 600,
    retryPolicy: "RETRY_NEXT_CYCLE",
    idempotencyStrategy: "RETENTION_POLICY_REPLAYABLE",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.SETTINGS_UPDATE,
    operationalOwnerCategory: "Governance & Privacy",
  },
  "expire-developer-api-credentials": {
    name: "expire-developer-api-credentials",
    version: "1.0.0",
    purpose: "Revokes developer API keys and credentials past expiration date",
    triggerType: "CRON",
    classification: "MAINTENANCE_PROCESSOR",
    leaseRequired: true,
    defaultPartition: "default",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 120,
    retryPolicy: "IMMEDIATE_RETRY",
    idempotencyStrategy: "CREDENTIAL_STATUS_EXPIRED",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.DEVELOPER_APPLICATION_READ,
    operationalOwnerCategory: "Developer Platform",
  },
  "scan-payment-reconciliation": {
    name: "scan-payment-reconciliation",
    version: "1.0.0",
    purpose: "Scans payment providers and ledger for status discrepancies",
    triggerType: "CRON",
    classification: "READ_ONLY",
    leaseRequired: false,
    defaultPartition: "default",
    defaultBatchSize: 100,
    maxBatchSize: 500,
    maxExecutionDurationSeconds: 180,
    retryPolicy: "NO_RETRY",
    idempotencyStrategy: "RECONCILIATION_CASE_IDEMPOTENT_OPEN",
    dryRunSupported: true,
    manualExecutionAllowed: true,
    requiredPermission: PERMISSIONS.PAYMENT_RECONCILIATION_READ,
    operationalOwnerCategory: "Payments & Ledger",
  },
};
