import { prisma } from "@/lib/db/prisma";
import { verifyMarketplaceGuestSecret } from "@/lib/marketplace-checkout/tokens";
import { StoreOrderError } from "@/lib/store-orders/errors";

/** A minimal owner projection, without private inventory, finance or actors. */
export async function getCustomerStoreOrderActions(input: { marketplaceOrderReference: string; storeOrderReference: string; customerUserId?: string; guestSecret?: string }) {
  if (input.customerUserId && !await prisma.user.findFirst({ where: { id: input.customerUserId, role: "CUSTOMER", status: "ACTIVE" }, select: { id: true } })) throw new StoreOrderError("STORE_ORDER_CUSTOMER_ACCESS_DENIED", "Active customer order ownership is required.");
  const order = await prisma.marketplaceStoreOrder.findFirst({ where: { publicReference: input.storeOrderReference, marketplaceOrder: { publicReference: input.marketplaceOrderReference } }, select: { id: true, publicReference: true, storeId: true, acceptanceStatus: true, preparationStatus: true, financialResolutionStatus: true, marketplaceOrder: { select: { customerUserId: true, guestConfirmationHash: true } }, lines: { select: { id: true, title: true, quantity: true, fulfilment: { select: { substitutionPreference: true, issues: { where: { status: { in: ["OPEN", "CUSTOMER_ACTION_REQUIRED", "REFUND_PENDING"] } }, select: { id: true } } } } } }, substitutions: { where: { status: "PROPOSED", expiresAt: { gt: new Date() } }, select: { publicReference: true, substituteProductReference: true, substituteVariantReference: true, substituteQuantity: true, customerCharge: true, originalRemainingCharge: true, expiresAt: true } } } });
  if (!order || !(input.customerUserId ? order.marketplaceOrder.customerUserId === input.customerUserId : !order.marketplaceOrder.customerUserId && verifyMarketplaceGuestSecret(input.guestSecret, order.marketplaceOrder.guestConfirmationHash))) throw new StoreOrderError("STORE_ORDER_CUSTOMER_ACCESS_DENIED", "Customer order ownership is required.");
  const preferences = await prisma.marketplaceStoreOrderHistory.findMany({ where: { marketplaceStoreOrderId: order.id, eventType: "SUBSTITUTION_PREFERENCE_UPDATED" }, orderBy: { createdAt: "desc" }, select: { safeEvidence: true } });
  const selectedChoices = new Map<string, string[]>();
  for (const preference of preferences) {
    const evidence = preference.safeEvidence as { orderLineId?: unknown; choices?: unknown } | null;
    if (typeof evidence?.orderLineId !== "string" || selectedChoices.has(evidence.orderLineId)) continue;
    selectedChoices.set(evidence.orderLineId, Array.isArray(evidence.choices) ? evidence.choices.flatMap(choice => typeof choice?.offerReference === "string" ? [choice.offerReference] : []) : []);
  }
  const variants = order.substitutions.length ? await prisma.catalogProductVariant.findMany({ where: { publicReference: { in: order.substitutions.map(proposal => proposal.substituteVariantReference) } }, select: { publicReference: true, title: true, product: { select: { title: true } } } }) : [];
  const replacementRows = await prisma.storeCatalogOffer.findMany({ where: { storeId: order.storeId, status: "ACTIVE", publicationStatus: "PUBLISHED" }, select: { publicReference: true, product: { select: { title: true } }, variant: { select: { publicReference: true, title: true } }, priceVersions: { where: { status: "ACTIVE", currency: "ZAR", effectiveFrom: { lte: new Date() }, OR: [{ effectiveUntil: null }, { effectiveUntil: { gt: new Date() } }] }, orderBy: { versionNumber: "desc" }, take: 1, select: { amount: true } } }, orderBy: { publicReference: "asc" }, take: 100 });
  const replacements = replacementRows.filter(item => item.priceVersions.length).map(item => ({ offerReference: item.publicReference, variantReference: item.variant.publicReference, label: `${item.product.title} — ${item.variant.title} · R ${item.priceVersions[0].amount.toFixed(2)}` }));
  return { replacements, financialStatus: order.financialResolutionStatus, storeOrderReference: order.publicReference, canCancel: ["PENDING_STORE_REVIEW", "REVIEWING", "CUSTOMER_ACTION_REQUIRED"].includes(order.acceptanceStatus) && order.preparationStatus === "NOT_STARTED", lines: order.lines.filter(line => line.fulfilment).map(line => ({ id: line.id, title: line.title, quantity: line.quantity, selectedChoiceReferences: selectedChoices.get(line.id) ?? [], preference: line.fulfilment!.substitutionPreference, canChange: order.preparationStatus === "NOT_STARTED" && !["ACCEPTED", "REJECTED", "TIMED_OUT"].includes(order.acceptanceStatus) && line.fulfilment!.issues.length === 0 })), proposals: order.substitutions.map(proposal => ({ reference: proposal.publicReference, title: variants.find(variant => variant.publicReference === proposal.substituteVariantReference)?.product.title ?? "Replacement item", variantTitle: variants.find(variant => variant.publicReference === proposal.substituteVariantReference)?.title ?? "Standard item", quantity: proposal.substituteQuantity, amount: proposal.customerCharge.toFixed(2), originalAmount: proposal.originalRemainingCharge.toFixed(2), expiresAt: proposal.expiresAt.toISOString() })) };
}
export type CustomerStoreOrderActions = Awaited<ReturnType<typeof getCustomerStoreOrderActions>>;
