import { prisma } from "@/lib/db/prisma";
import { verifyMarketplaceGuestSecret } from "@/lib/marketplace-checkout/tokens";
import { StoreOrderError } from "@/lib/store-orders/errors";

/** A minimal owner projection, without private inventory, finance or actors. */
export async function getCustomerStoreOrderActions(input: { marketplaceOrderReference: string; storeOrderReference: string; customerUserId?: string; guestSecret?: string }) {
  if (input.customerUserId && !await prisma.user.findFirst({ where: { id: input.customerUserId, role: "CUSTOMER", status: "ACTIVE" }, select: { id: true } })) throw new StoreOrderError("STORE_ORDER_CUSTOMER_ACCESS_DENIED", "Active customer order ownership is required.");
  const order = await prisma.marketplaceStoreOrder.findFirst({ where: { publicReference: input.storeOrderReference, marketplaceOrder: { publicReference: input.marketplaceOrderReference } }, select: { publicReference: true, acceptanceStatus: true, preparationStatus: true, marketplaceOrder: { select: { customerUserId: true, guestConfirmationHash: true } }, lines: { select: { id: true, title: true, quantity: true, fulfilment: { select: { substitutionPreference: true, issues: { where: { status: { in: ["OPEN", "CUSTOMER_ACTION_REQUIRED", "REFUND_PENDING"] } }, select: { id: true } } } } } }, substitutions: { where: { status: "PROPOSED", expiresAt: { gt: new Date() } }, select: { publicReference: true, substituteProductReference: true, substituteVariantReference: true, substituteQuantity: true, customerCharge: true, originalRemainingCharge: true, expiresAt: true } } } });
  if (!order || !(input.customerUserId ? order.marketplaceOrder.customerUserId === input.customerUserId : !order.marketplaceOrder.customerUserId && verifyMarketplaceGuestSecret(input.guestSecret, order.marketplaceOrder.guestConfirmationHash))) throw new StoreOrderError("STORE_ORDER_CUSTOMER_ACCESS_DENIED", "Customer order ownership is required.");
  const variants = order.substitutions.length ? await prisma.catalogProductVariant.findMany({ where: { publicReference: { in: order.substitutions.map(proposal => proposal.substituteVariantReference) } }, select: { publicReference: true, title: true, product: { select: { title: true } } } }) : [];
  return { storeOrderReference: order.publicReference, canCancel: ["PENDING_STORE_REVIEW", "REVIEWING", "CUSTOMER_ACTION_REQUIRED"].includes(order.acceptanceStatus) && order.preparationStatus === "NOT_STARTED", lines: order.lines.filter(line => line.fulfilment).map(line => ({ id: line.id, title: line.title, quantity: line.quantity, preference: line.fulfilment!.substitutionPreference, canChange: order.preparationStatus === "NOT_STARTED" && !["ACCEPTED", "REJECTED", "TIMED_OUT"].includes(order.acceptanceStatus) && line.fulfilment!.issues.length === 0 })), proposals: order.substitutions.map(proposal => ({ reference: proposal.publicReference, title: variants.find(variant => variant.publicReference === proposal.substituteVariantReference)?.product.title ?? "Replacement item", variantTitle: variants.find(variant => variant.publicReference === proposal.substituteVariantReference)?.title ?? "Standard item", quantity: proposal.substituteQuantity, amount: proposal.customerCharge.toFixed(2), originalAmount: proposal.originalRemainingCharge.toFixed(2), expiresAt: proposal.expiresAt.toISOString() })) };
}
export type CustomerStoreOrderActions = Awaited<ReturnType<typeof getCustomerStoreOrderActions>>;
