/* eslint-disable @typescript-eslint/no-explicit-any -- Phase 17 Prisma Client generation and model type proof are intentionally deferred. */
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { DriverEarningError } from "@/lib/driver-earnings/errors";
import { formatDriverEarningMoney } from "@/lib/driver-earnings/driver-earning-money";

const db = prisma as any; const zero = () => new Prisma.Decimal(0);
async function owner(userId: string) { const user = await prisma.user.findUnique({ where: { id: userId }, select: { role: true, status: true, driverProfile: { select: { id: true, active: true, status: true, onboardingStatus: true } } } }); if (!user || user.role !== "DRIVER" || user.status !== "ACTIVE" || !user.driverProfile?.active || user.driverProfile.status !== "ACTIVE" || user.driverProfile.onboardingStatus !== "APPROVED") throw new DriverEarningError("DRIVER_EARNING_FORBIDDEN", "An active canonical driver is required to read earning totals."); return user.driverProfile.id; }
export async function getDriverEarningSummaryForOwner(userId: string) { return summarizeDriverEarnings(await owner(userId)); }
export async function summarizeDriverEarnings(driverId?: string) {
  const where = { ...(driverId ? { driverId } : {}) }; const periodStart = new Date(); periodStart.setUTCDate(1); periodStart.setUTCHours(0, 0, 0, 0);
  const [rows, payable, reconciliationCount, oldestRows, releases, totals] = await Promise.all([
    db.driverEarning.findMany({ where, select: { amount: true, refundReservedAmount: true, refundedAmount: true, releasedAmount: true, reversedAmount: true, status: true, releaseEligibleAt: true } }),
    prisma.ledgerAccount.aggregate({ where: { purpose: "DRIVER_EARNINGS_PAYABLE", category: "LIABILITY", currency: "ZAR", status: "ACTIVE", ...(driverId ? { wallet: { ownerType: "DRIVER", ownerId: driverId } } : {}) }, _sum: { currentBalance: true } }),
    db.driverEarningReconciliationCase.count({ where: { status: { in: ["OPEN", "MONITORING"] }, ...(driverId ? { driverEarning: { driverId } } : {}) } }),
    db.driverEarning.findMany({ where: { ...where, status: { in: ["ACCRUED", "RECONCILIATION_REQUIRED"] } }, select: { publicReference: true, assignmentPublicReference: true, amount: true, createdAt: true }, orderBy: [{ createdAt: "asc" }, { id: "asc" }], take: 10 }),
    db.driverEarning.findMany({ where: { ...where, status: "RELEASED" }, select: { publicReference: true, releasedAmount: true, releasedAt: true }, orderBy: [{ releasedAt: "desc" }, { id: "desc" }], take: 10 }),
    db.driverEarning.groupBy({ by: ["driverId"], where: { ...where, createdAt: { gte: periodStart } }, _sum: { amount: true }, orderBy: { driverId: "asc" } }),
  ]);
  const drivers = await prisma.driverProfile.findMany({ where: { id: { in: totals.map((row: any) => row.driverId) } }, select: { id: true, driverCode: true } }); const refs = new Map(drivers.map((d) => [d.id, d.driverCode])); const now = new Date(); const total = (field: string) => rows.reduce((sum: Prisma.Decimal, row: any) => sum.add(row[field]), zero());
  const eligible = rows.filter((row: any) => row.status === "ACCRUED" && row.releaseEligibleAt && row.releaseEligibleAt <= now && row.refundReservedAmount.isZero()).reduce((sum: Prisma.Decimal, row: any) => sum.add(row.amount.sub(row.refundedAmount).sub(row.releasedAmount).sub(row.reversedAmount)), zero());
  return Object.freeze({ currency: "ZAR" as const, totalAccrued: formatDriverEarningMoney(total("amount")), payableBalance: formatDriverEarningMoney(payable._sum.currentBalance ?? zero()), refundReserved: formatDriverEarningMoney(total("refundReservedAmount")), refunded: formatDriverEarningMoney(total("refundedAmount")), releaseEligible: formatDriverEarningMoney(eligible), releasedToOwnerWithdrawable: formatDriverEarningMoney(total("releasedAmount")), reversed: formatDriverEarningMoney(total("reversedAmount")), reconciliationCount, oldestUnreleased: oldestRows[0] ? Object.freeze({ publicReference: oldestRows[0].publicReference, assignmentPublicReference: oldestRows[0].assignmentPublicReference, amount: formatDriverEarningMoney(oldestRows[0].amount), accruedAt: oldestRows[0].createdAt.toISOString() }) : null, oldestUnreleasedEarnings: Object.freeze(oldestRows.map((row: any) => Object.freeze({ publicReference: row.publicReference, assignmentPublicReference: row.assignmentPublicReference, amount: formatDriverEarningMoney(row.amount), accruedAt: row.createdAt.toISOString() }))), recentReleases: Object.freeze(releases.map((row: any) => Object.freeze({ publicReference: row.publicReference, amount: formatDriverEarningMoney(row.releasedAmount), releasedAt: row.releasedAt?.toISOString() ?? null }))), driverTotalsByPeriod: Object.freeze({ from: periodStart.toISOString(), drivers: Object.freeze(totals.map((row: any) => Object.freeze({ driverPublicReference: refs.get(row.driverId) ?? "UNKNOWN", amount: formatDriverEarningMoney(row._sum.amount ?? zero()) }))) }) });
}
