/* eslint-disable @typescript-eslint/no-explicit-any -- Phase 17 Prisma Client generation and model type proof are intentionally deferred. */
import { randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { DriverEarningError } from "@/lib/driver-earnings/errors";
import { RefundError } from "@/lib/refunds/errors";
import { formatDriverEarningMoney } from "@/lib/driver-earnings/driver-earning-money";
import { validateDriverEarningRefundSnapshot, type DriverEarningRefundSnapshot } from "@/lib/driver-earnings/driver-earning-refund-adjustment";
import { openDriverEarningReconciliationWithinTransaction } from "./driver-earning-reconciliation.service";

const reference = (prefix: string) => `${prefix}-${randomUUID().replaceAll("-", "").toUpperCase()}`;
export type PreparedDriverEarningRefundFunding = Readonly<{ blocked: false; publicReference: string; sourceType: "DRIVER_EARNINGS_PAYABLE"; ledgerAccountId: string; commissionAccrualId: null; commissionAllocationId: null; commissionAllocationReference: null; storeEarningId: null; driverEarningId: string; driverEarningPublicReference: string; amount: string }>;

export async function assertGenericRefundHasNoDriverEarningExposure(tx: any, paymentId: string): Promise<void> {
  const rows = await tx.driverEarning.findMany({ where: { paymentId, status: { in: ["ACCRUED", "RELEASED", "RECONCILIATION_REQUIRED"] } }, select: { amount: true, refundedAmount: true, releasedAmount: true, reversedAmount: true } });
  if (rows.some((row: any) => row.amount.sub(row.refundedAmount).sub(row.releasedAmount).sub(row.reversedAmount).greaterThan(0))) throw new RefundError("REFUND_FUNDING_UNAVAILABLE", "An authoritative driver-level refund snapshot is required before reserving driver settlement proceeds.");
}

async function openReleasedRefundCases(tx: any, earning: any, snapshot: DriverEarningRefundSnapshot) {
  await openDriverEarningReconciliationWithinTransaction(tx, { caseKey: `driver-earning:refund-after-release:${earning.id}:${snapshot.refundId}`, driverEarningId: earning.id, refundId: snapshot.refundId, reason: "REFUND_AFTER_RELEASE", priority: "CRITICAL", safeSummary: "Released driver earnings cannot be debited from payable or owner-withdrawable without a future coordinated clawback policy." });
  await tx.refundReconciliationCase.upsert({ where: { caseKey: `refund:${snapshot.refundPublicReference}:released-driver-earning:${earning.publicReference}` }, update: { observationCount: { increment: 1 }, lastObservedAt: new Date(), status: "OPEN" }, create: { publicReference: reference("RRC"), caseKey: `refund:${snapshot.refundPublicReference}:released-driver-earning:${earning.publicReference}`, refundId: snapshot.refundId, reason: "REFUND_LEDGER_AMOUNT_MISMATCH", status: "OPEN", priority: "CRITICAL", safeSummary: "Refund has released driver-earning exposure and requires future coordinated owner-liability clawback policy." } });
}

export async function prepareDriverEarningRefundFundingWithinTransaction(tx: any, snapshotInput: DriverEarningRefundSnapshot): Promise<PreparedDriverEarningRefundFunding | Readonly<{ blocked: true; driverEarningId: string; driverEarningPublicReference: string; blockReason: "REFUND_AFTER_RELEASE" }>> {
  const locked = await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "DriverEarning" WHERE "id"=${snapshotInput.driverEarningId} FOR UPDATE`); if (locked.length !== 1) throw new DriverEarningError("DRIVER_EARNING_NOT_FOUND", "Driver earning was not found for refund allocation.");
  const earning = await tx.driverEarning.findUnique({ where: { id: snapshotInput.driverEarningId }, include: { payableAccount: true } });
  if (!earning || earning.publicReference !== snapshotInput.driverEarningPublicReference || earning.assignmentPublicReference !== snapshotInput.assignmentReference || earning.settlementVersion !== snapshotInput.settlementVersion) throw new DriverEarningError("DRIVER_EARNING_INVALID_SNAPSHOT", "Driver refund snapshot does not match immutable earning evidence.");
  const snapshot = validateDriverEarningRefundSnapshot(snapshotInput, formatDriverEarningMoney(earning.amount));
  if (earning.status === "RELEASED" || earning.releaseLedgerJournalId || !earning.releasedAmount.isZero()) { await openReleasedRefundCases(tx, earning, snapshot); return Object.freeze({ blocked: true as const, driverEarningId: earning.id, driverEarningPublicReference: earning.publicReference, blockReason: "REFUND_AFTER_RELEASE" as const }); }
  if (earning.status !== "ACCRUED" || earning.reversalLedgerJournalId) throw new DriverEarningError("DRIVER_EARNING_INVALID_STATE", "Driver earning is not available for refund reservation.");
  const prior = earning.refundReservedAmount.add(earning.refundedAmount); if (!prior.equals(snapshot.priorDriverRefundReservedOrCompletedAmount)) throw new DriverEarningError("DRIVER_EARNING_INVALID_SNAPSHOT", "Driver refund prior adjustment differs from stored projections.");
  const amount = new Prisma.Decimal(snapshot.currentDriverEarningAdjustment); const remaining = earning.amount.sub(earning.refundReservedAmount).sub(earning.refundedAmount).sub(earning.releasedAmount).sub(earning.reversedAmount);
  if (!amount.greaterThan(0) || amount.greaterThan(remaining) || earning.payableAccount.currentBalance.lessThan(amount)) throw new DriverEarningError("DRIVER_EARNING_INVALID_SNAPSHOT", "Driver refund adjustment exceeds remaining payable entitlement.");
  return Object.freeze({ blocked: false as const, publicReference: reference("RFA"), sourceType: "DRIVER_EARNINGS_PAYABLE" as const, ledgerAccountId: earning.payableAccountId, commissionAccrualId: null, commissionAllocationId: null, commissionAllocationReference: null, storeEarningId: null, driverEarningId: earning.id, driverEarningPublicReference: earning.publicReference, amount: formatDriverEarningMoney(amount) });
}

export async function applyDriverEarningRefundReservationWithinTransaction(tx: any, input: Readonly<{ refundId: string; funding: PreparedDriverEarningRefundFunding; actorUserId?: string }>) { const amount = new Prisma.Decimal(input.funding.amount); await tx.refundFundingAllocation.create({ data: { publicReference: input.funding.publicReference, refundId: input.refundId, sourceType: "DRIVER_EARNINGS_PAYABLE", ledgerAccountId: input.funding.ledgerAccountId, driverEarningId: input.funding.driverEarningId, amount, currency: "ZAR" } }); await tx.driverEarning.update({ where: { id: input.funding.driverEarningId }, data: { refundReservedAmount: { increment: amount }, version: { increment: 1 }, statusHistory: { create: { fromStatus: "ACCRUED", toStatus: "ACCRUED", actorType: input.actorUserId ? "USER" : "SYSTEM", actorId: input.actorUserId ?? null, reasonCode: "REFUND_AMOUNT_RESERVED", safeMetadata: { refundId: input.refundId, amount: input.funding.amount } } } } }); }

async function grouped(tx: any, refundId: string) { const allocations = await tx.refundFundingAllocation.findMany({ where: { refundId, sourceType: "DRIVER_EARNINGS_PAYABLE", driverEarningId: { not: null } }, select: { driverEarningId: true, amount: true }, orderBy: { driverEarningId: "asc" } }); const result = new Map<string, Prisma.Decimal>(); for (const row of allocations) if (row.driverEarningId) result.set(row.driverEarningId, (result.get(row.driverEarningId) ?? new Prisma.Decimal(0)).add(row.amount)); return [...result.entries()].sort(([a], [b]) => a.localeCompare(b)); }
export async function releaseDriverEarningRefundReservationsWithinTransaction(tx: any, input: Readonly<{ refundId: string; refundPublicReference: string; actorUserId?: string }>) { for (const [id, amount] of await grouped(tx, input.refundId)) { await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "DriverEarning" WHERE "id"=${id} FOR UPDATE`); const earning = await tx.driverEarning.findUnique({ where: { id } }); if (!earning || earning.refundReservedAmount.lessThan(amount)) throw new DriverEarningError("DRIVER_EARNING_RECONCILIATION_REQUIRED", "Driver refund reservation release differs from stored projection."); await tx.driverEarning.update({ where: { id }, data: { refundReservedAmount: { decrement: amount }, version: { increment: 1 }, statusHistory: { create: { fromStatus: earning.status, toStatus: earning.status, actorType: input.actorUserId ? "USER" : "SYSTEM", actorId: input.actorUserId ?? null, reasonCode: "REFUND_RESERVATION_RELEASED", safeMetadata: { refundReference: input.refundPublicReference, amount: formatDriverEarningMoney(amount) } } } } }); } }
export async function completeDriverEarningRefundProjectionsWithinTransaction(tx: any, input: Readonly<{ refundId: string; refundPublicReference: string; actorUserId?: string }>) { for (const [id, amount] of await grouped(tx, input.refundId)) { await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "DriverEarning" WHERE "id"=${id} FOR UPDATE`); const earning = await tx.driverEarning.findUnique({ where: { id } }); if (!earning || earning.refundReservedAmount.lessThan(amount) || earning.releaseLedgerJournalId || !earning.releasedAmount.isZero()) throw new DriverEarningError("DRIVER_EARNING_RECONCILIATION_REQUIRED", "Driver refund completion conflicts with release or reservation evidence."); const refunded = earning.refundedAmount.add(amount); const full = refunded.equals(earning.amount) && earning.reversedAmount.isZero() && earning.releasedAmount.isZero(); await tx.driverEarning.update({ where: { id }, data: { refundReservedAmount: { decrement: amount }, refundedAmount: { increment: amount }, status: full ? "FULLY_REFUNDED" : earning.status, version: { increment: 1 }, statusHistory: { create: { fromStatus: earning.status, toStatus: full ? "FULLY_REFUNDED" : earning.status, actorType: input.actorUserId ? "USER" : "SYSTEM", actorId: input.actorUserId ?? null, reasonCode: "REFUND_COMPLETED", safeMetadata: { refundReference: input.refundPublicReference, amount: formatDriverEarningMoney(amount) } } } } }); } }
