/* eslint-disable @typescript-eslint/no-explicit-any -- Phase 17 Prisma Client generation and model type proof are intentionally deferred. */
import { randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { withLedgerRetry } from "@/lib/ledger/retry";
import { DriverEarningError } from "@/lib/driver-earnings/errors";
import { assertAuthoritativeAssignment } from "@/lib/driver-earnings/driver-earning-assignment-policy";
import { assertDriverCommissionAttribution } from "@/lib/driver-earnings/driver-commission-attribution";
import { hashDriverEarningCalculation } from "@/lib/driver-earnings/driver-earning-idempotency";
import { driverEarningAccrualPosting } from "@/lib/driver-earnings/driver-earning-ledger-policy";
import { formatDriverEarningMoney } from "@/lib/driver-earnings/driver-earning-money";
import { assertDriverEarningsProductionReady } from "@/lib/driver-earnings/driver-earning-production-readiness";
import { validateDriverSettlementSnapshot, type DriverSettlementSnapshot } from "@/lib/driver-earnings/driver-settlement-snapshot";
import { assignmentPublicReference } from "@/lib/driver-earnings/driver-earning-subject";
import { ensureDriverEarningPayableAccount, resolveDriverEarningAccountsWithinTransaction } from "./driver-earning-account.service";
import { postLedgerJournalWithinTransaction } from "./ledger-posting.service";

const db = prisma as any;
const OPERATION = /^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/;
const ref = (prefix: string) => `${prefix}-${randomUUID().replaceAll("-", "").toUpperCase()}`;
const journalInclude = { accrualLedgerJournal: { select: { reference: true } }, releaseLedgerJournal: { select: { reference: true } }, reversalLedgerJournal: { select: { reference: true } } } as const;

function dto(row: any) { return Object.freeze({ id: row.id, publicReference: row.publicReference, status: row.status, settlementBasisAmount: formatDriverEarningMoney(row.settlementBasisAmount), attributedCommissionAmount: formatDriverEarningMoney(row.attributedCommissionAmount), amount: formatDriverEarningMoney(row.amount), currency: row.currency, accrualLedgerJournalReference: row.accrualLedgerJournal.reference, releaseLedgerJournalReference: row.releaseLedgerJournal?.reference ?? null, reversalLedgerJournalReference: row.reversalLedgerJournal?.reference ?? null }); }
function assertPayment(payment: any, snapshot: DriverSettlementSnapshot) { const webhook = payment?.successWebhookEvent; if (!payment || payment.orderId !== snapshot.orderId || payment.publicReference !== snapshot.paymentPublicReference || payment.status !== "SUCCEEDED" || payment.currency !== "ZAR" || payment.successfulAttempt?.status !== "SUCCEEDED" || payment.successLedgerJournal?.type !== "EXTERNAL_PAYMENT_RECEIPT" || !webhook || webhook.processingStatus !== "APPLIED" || !webhook.signatureVerified || !webhook.merchantVerified || !webhook.amountVerified || !webhook.providerDataVerified) throw new DriverEarningError("DRIVER_EARNING_PAYMENT_INVALID", "A verified successful matching ZAR payment is required."); if (!payment.totalRefundedAmount.isZero() || !payment.totalRefundReservedAmount.isZero() || payment.reconciliationStatus !== "CLEAR") throw new DriverEarningError("DRIVER_EARNING_REFUND_EVIDENCE_REQUIRED", "Payment has incompatible refund or reconciliation exposure."); }
const paymentInclude = { successfulAttempt: { select: { status: true } }, successWebhookEvent: { select: { processingStatus: true, signatureVerified: true, merchantVerified: true, amountVerified: true, providerDataVerified: true } }, successLedgerJournal: { select: { type: true, currency: true } } };
function assignmentEvidence(row: any) { return { id: row.id, publicReference: assignmentPublicReference(row.id), version: String(row.version), driverId: row.driverProfileId, orderId: row.orderId, status: row.status, completedAt: row.completedAt?.toISOString() ?? null, podAssignmentId: row.proofOfDelivery?.assignmentId ?? null, podDriverId: row.proofOfDelivery?.driverProfileId ?? null, podOrderId: row.proofOfDelivery?.orderId ?? null, podDeliveredAt: row.proofOfDelivery?.deliveredAt?.toISOString() ?? null, hasDeliveryCompletedEvent: row.operationalEvents.some((e: any) => e.eventType === "DELIVERY_COMPLETED"), hasAssignmentCompletedEvent: row.events.some((e: any) => e.eventType === "ASSIGNMENT_COMPLETED") }; }

export async function accrueDriverEarning(command: Readonly<{ operationId: string; snapshot: DriverSettlementSnapshot; actorUserId?: string }>, options?: Readonly<{ allowTestOnlyBypass?: boolean }>) {
  assertDriverEarningsProductionReady(options);
  if (!OPERATION.test(command.operationId)) throw new DriverEarningError("DRIVER_EARNING_INVALID_COMMAND", "A valid internal operation ID is required.");
  const snapshot = validateDriverSettlementSnapshot(command.snapshot); const calculationHash = hashDriverEarningCalculation(snapshot);
  const provisioned = await ensureDriverEarningPayableAccount(snapshot.driverId);
  if (provisioned.driver.publicReference !== snapshot.driverPublicReference || provisioned.wallet.id !== snapshot.walletId) throw new DriverEarningError("DRIVER_EARNING_ACCOUNT_INVALID", "Snapshot driver wallet does not match the canonical owner.");
  const earningReference = ref("DE");
  const run = () => db.$transaction(async (tx: any) => {
    const replay = await tx.driverEarning.findUnique({ where: { creationIdempotencyKey: command.operationId }, include: journalInclude });
    if (replay) { if (replay.creationRequestHash !== calculationHash) throw new DriverEarningError("DRIVER_EARNING_IDEMPOTENCY_CONFLICT", "Operation ID was used with different settlement evidence."); return replay; }
    await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "OrderAssignment" WHERE "id"=${snapshot.assignmentId} FOR UPDATE`);
    const assignment = await tx.orderAssignment.findUnique({ where: { id: snapshot.assignmentId }, include: { proofOfDelivery: true, operationalEvents: { select: { eventType: true } }, events: { select: { eventType: true } } } });
    if (!assignment) throw new DriverEarningError("DRIVER_EARNING_ASSIGNMENT_INVALID", "Authoritative assignment was not found.");
    assertAuthoritativeAssignment(assignmentEvidence(assignment), snapshot);
    await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "Payment" WHERE "id"=${snapshot.paymentId} FOR UPDATE`);
    const payment = await tx.payment.findUnique({ where: { id: snapshot.paymentId }, include: paymentInclude }); assertPayment(payment, snapshot);
    const ids = snapshot.commissionCharges.map((row) => row.commissionAllocationId).sort();
    if (ids.length) await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "CommissionAllocation" WHERE "id" IN (${Prisma.join(ids)}) ORDER BY "id" FOR UPDATE`);
    const allocations = ids.length ? await tx.commissionAllocation.findMany({ where: { id: { in: ids } }, include: { accrual: { select: { subjectType: true, subjectId: true, status: true } } }, orderBy: { id: "asc" } }) : [];
    if (allocations.some((row: any) => row.accrual.subjectType !== "COURIER_ORDER" || row.accrual.subjectId !== snapshot.orderId || row.currency !== "ZAR" || row.downstreamReleaseJournalId)) throw new DriverEarningError("DRIVER_EARNING_COMMISSION_INVALID", "Commission allocation is unrelated or downstream-released.");
    assertDriverCommissionAttribution(snapshot.commissionCharges, allocations.map((row: any) => ({ ...row, accrualStatus: row.accrual.status })));
    const duplicate = await tx.driverEarning.findFirst({ where: { subjectType: snapshot.subjectType, subjectId: snapshot.subjectId, assignmentId: snapshot.assignmentId, driverId: snapshot.driverId, settlementVersion: snapshot.settlementVersion }, select: { id: true } });
    if (duplicate) throw new DriverEarningError("DRIVER_EARNING_SETTLEMENT_ALREADY_ACCRUED", "This assignment, driver, and settlement version is already accrued.");
    const accounts = await resolveDriverEarningAccountsWithinTransaction(tx, { driverId: snapshot.driverId, walletId: snapshot.walletId, payableAccountId: provisioned.account.id });
    const held = await tx.ledgerAccount.findFirst({ where: { purpose: "HELD", category: "LIABILITY", currency: "ZAR", status: "ACTIVE", allowNegative: false, wallet: { ownerType: "PLATFORM", ownerId: "platform", currency: "ZAR", status: "ACTIVE" } } });
    const amount = new Prisma.Decimal(snapshot.netDriverEarningAmount); if (!held || held.currentBalance.lessThan(amount)) throw new DriverEarningError("DRIVER_EARNING_INSUFFICIENT_HELD_FUNDS", "Customer funds held are insufficient.");
    const journal = await postLedgerJournalWithinTransaction(tx, driverEarningAccrualPosting({ earningReference, amount: snapshot.netDriverEarningAmount, customerFundsHeldAccountId: held.id, driverPayableAccountId: accounts.payable.id, driverPublicReference: snapshot.driverPublicReference, assignmentPublicReference: snapshot.assignmentPublicReference, assignmentVersion: snapshot.assignmentVersion, orderPublicReference: snapshot.orderPublicReference, settlementVersion: snapshot.settlementVersion, completionEvidenceReference: snapshot.completionEvidenceReference, actorUserId: command.actorUserId }));
    for (const charge of snapshot.commissionCharges) await tx.commissionAllocation.update({ where: { id: charge.commissionAllocationId }, data: { driverAttributedAmount: { increment: new Prisma.Decimal(charge.amount) } } });
    return tx.driverEarning.create({ data: { publicReference: earningReference, driverId: snapshot.driverId, driverPublicReference: snapshot.driverPublicReference, walletId: snapshot.walletId, payableAccountId: accounts.payable.id, subjectType: snapshot.subjectType, subjectId: snapshot.subjectId, subjectPublicReference: snapshot.subjectPublicReference, assignmentId: snapshot.assignmentId, assignmentPublicReference: snapshot.assignmentPublicReference, assignmentVersion: snapshot.assignmentVersion, orderId: snapshot.orderId, orderPublicReference: snapshot.orderPublicReference, paymentId: snapshot.paymentId, paymentPublicReference: snapshot.paymentPublicReference, settlementReference: snapshot.settlementReference, settlementVersion: snapshot.settlementVersion, calculationVersion: snapshot.calculationVersion, completionEvidenceReference: snapshot.completionEvidenceReference, serviceCompletedAt: new Date(snapshot.serviceCompletedAt), authoritativeAt: new Date(snapshot.authoritativeAt), releaseEligibleAt: snapshot.releaseEligibleAt ? new Date(snapshot.releaseEligibleAt) : null, settlementBasisAmount: new Prisma.Decimal(snapshot.driverSettlementBasisAmount), attributedCommissionAmount: new Prisma.Decimal(snapshot.attributedCommissionAmount), amount, currency: "ZAR", status: "ACCRUED", creationIdempotencyKey: command.operationId, creationRequestHash: calculationHash, calculationHash, accrualLedgerJournalId: journal.id, commissionCharges: { create: snapshot.commissionCharges.map((charge) => ({ publicReference: ref("DEC"), commissionAllocationId: charge.commissionAllocationId, amount: new Prisma.Decimal(charge.amount), currency: "ZAR" })) }, statusHistory: { create: [{ fromStatus: null, toStatus: "ACCRUED", actorType: command.actorUserId ? "USER" : "SYSTEM", actorId: command.actorUserId ?? null, reasonCode: "ACCRUAL_POSTED", safeMetadata: { ledgerReference: journal.reference, settlementReference: snapshot.settlementReference } }, { fromStatus: null, toStatus: "ACCRUED", actorType: "SYSTEM", reasonCode: "COMMISSION_CHARGES_ATTRIBUTED", safeMetadata: { chargeCount: String(snapshot.commissionCharges.length) } }] } }, include: journalInclude });
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
  try { return dto(await withLedgerRetry(run)); } catch (error) { const winner = await db.driverEarning.findUnique({ where: { creationIdempotencyKey: command.operationId }, include: journalInclude }); if (winner && winner.creationRequestHash === calculationHash) return dto(winner); throw error; }
}
