/* eslint-disable @typescript-eslint/no-explicit-any -- Phase 17 Prisma Client generation and model type proof are intentionally deferred. */
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { withLedgerRetry } from "@/lib/ledger/retry";
import { DriverEarningError } from "@/lib/driver-earnings/errors";
import { assertAuthoritativeAssignment } from "@/lib/driver-earnings/driver-earning-assignment-policy";
import { driverEarningReleasePosting } from "@/lib/driver-earnings/driver-earning-ledger-policy";
import { formatDriverEarningMoney } from "@/lib/driver-earnings/driver-earning-money";
import { DRIVER_EARNINGS_PRODUCTION_VALIDATION_APPROVED, assertDriverEarningsProductionReady } from "@/lib/driver-earnings/driver-earning-production-readiness";
import { assertDriverEarningReleaseEligible } from "@/lib/driver-earnings/driver-earning-release-policy";
import { assignmentPublicReference } from "@/lib/driver-earnings/driver-earning-subject";
import { postLedgerJournalWithinTransaction } from "./ledger-posting.service";

const db = prisma as any;
const OPERATION = /^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/;
const open = (status: string) => status === "OPEN" || status === "MONITORING";
function evidence(row: any) { return { id: row.id, publicReference: assignmentPublicReference(row.id), version: String(row.version), driverId: row.driverProfileId, orderId: row.orderId, status: row.status, completedAt: row.completedAt?.toISOString() ?? null, podAssignmentId: row.proofOfDelivery?.assignmentId ?? null, podDriverId: row.proofOfDelivery?.driverProfileId ?? null, podOrderId: row.proofOfDelivery?.orderId ?? null, podDeliveredAt: row.proofOfDelivery?.deliveredAt?.toISOString() ?? null, hasDeliveryCompletedEvent: row.operationalEvents.some((e: any) => e.eventType === "DELIVERY_COMPLETED"), hasAssignmentCompletedEvent: row.events.some((e: any) => e.eventType === "ASSIGNMENT_COMPLETED") }; }

export async function releaseDriverEarning(input: Readonly<{ earningId: string; operationId: string; actorUserId?: string; now?: Date }>, options?: Readonly<{ allowTestOnlyBypass?: boolean }>) {
  assertDriverEarningsProductionReady(options); if (!OPERATION.test(input.operationId)) throw new DriverEarningError("DRIVER_EARNING_INVALID_COMMAND", "A valid internal release operation ID is required.");
  return withLedgerRetry(() => db.$transaction(async (tx: any) => {
    const locked = await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "DriverEarning" WHERE "id"=${input.earningId} FOR UPDATE`); if (locked.length !== 1) throw new DriverEarningError("DRIVER_EARNING_NOT_FOUND", "Driver earning was not found.");
    const earning = await tx.driverEarning.findUnique({ where: { id: input.earningId }, include: { driver: { include: { user: { select: { role: true, status: true } } } }, wallet: { include: { accounts: { where: { purpose: "OWNER_WITHDRAWABLE", currency: "ZAR" } } } }, payableAccount: true, releaseLedgerJournal: { select: { reference: true } }, reconciliationCases: { select: { status: true, reason: true } }, fundingAllocations: { include: { refund: { include: { reconciliationCases: { select: { status: true } } } } } }, commissionCharges: { include: { commissionAllocation: { include: { accrual: { select: { status: true } } } } } }, payment: { include: { reconciliationCases: { select: { status: true } } } } } });
    if (!earning) throw new DriverEarningError("DRIVER_EARNING_NOT_FOUND", "Driver earning was not found."); if (earning.status === "RELEASED" && earning.releaseLedgerJournal) return Object.freeze({ publicReference: earning.publicReference, status: earning.status, releasedAmount: formatDriverEarningMoney(earning.releasedAmount), releaseLedgerJournalReference: earning.releaseLedgerJournal.reference, idempotent: true });
    await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "OrderAssignment" WHERE "id"=${earning.assignmentId} FOR UPDATE`);
    const assignment = await tx.orderAssignment.findUnique({ where: { id: earning.assignmentId }, include: { proofOfDelivery: true, operationalEvents: { select: { eventType: true } }, events: { select: { eventType: true } } } });
    let completionValid = true; try { if (!assignment) throw new Error(); assertAuthoritativeAssignment(evidence(assignment), { assignmentId: earning.assignmentId, assignmentPublicReference: earning.assignmentPublicReference, assignmentVersion: earning.assignmentVersion, driverId: earning.driverId, orderId: earning.orderId, serviceCompletedAt: earning.serviceCompletedAt.toISOString() }); } catch { completionValid = false; }
    const allocationIds = earning.commissionCharges.map((row: any) => row.commissionAllocationId).sort(); if (allocationIds.length) await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "CommissionAllocation" WHERE "id" IN (${Prisma.join(allocationIds)}) ORDER BY "id" FOR UPDATE`);
    const commissionCoherent = earning.commissionCharges.every((charge: any) => charge.commissionAllocation.status === "ACCRUED" && charge.commissionAllocation.accrual.status === "ACCRUED" && charge.commissionAllocation.driverAttributedAmount.greaterThanOrEqualTo(charge.amount) && charge.commissionAllocation.storeAttributedAmount.add(charge.commissionAllocation.driverAttributedAmount).lessThanOrEqualTo(charge.commissionAllocation.amount));
    const remaining = earning.amount.sub(earning.refundedAmount).sub(earning.reversedAmount).sub(earning.releasedAmount); const destination = earning.wallet.accounts.find((a: any) => a.status === "ACTIVE" && a.category === "LIABILITY" && !a.allowNegative);
    const hasRefundCase = earning.fundingAllocations.some((f: any) => f.refund.reconciliationCases.some((r: any) => open(r.status))); const incident = earning.reconciliationCases.some((r: any) => open(r.status) && ["DELIVERY_EVIDENCE_MISSING", "DELIVERY_EVIDENCE_CONFLICT", "ASSIGNMENT_DRIVER_MISMATCH", "ASSIGNMENT_VERSION_MISMATCH", "RELEASE_WITH_OPEN_INCIDENT"].includes(r.reason));
    assertDriverEarningReleaseEligible({ status: earning.status, productionValidationApproved: DRIVER_EARNINGS_PRODUCTION_VALIDATION_APPROVED || options?.allowTestOnlyBypass === true, completionEvidenceValid: completionValid, assignmentDriverMatch: completionValid, releaseEligibleAt: earning.releaseEligibleAt, now: input.now ?? new Date(), refundReservedAmount: earning.refundReservedAmount, remainingAmount: remaining, hasOpenEarningReconciliation: earning.reconciliationCases.some((r: any) => open(r.status)), hasOpenRefundReconciliation: hasRefundCase, hasOpenPaymentReconciliation: earning.payment.reconciliationStatus !== "CLEAR" || earning.payment.reconciliationCases.some((r: any) => open(r.status)), hasOpenDeliveryIncidentOrAssignmentConflict: incident, commissionAttributionCoherent: commissionCoherent, activeFinanciallyEligibleDriver: earning.driver.active && earning.driver.status === "ACTIVE" && earning.driver.onboardingStatus === "APPROVED" && earning.driver.user.role === "DRIVER" && earning.driver.user.status === "ACTIVE", activeDriverWallet: earning.wallet.status === "ACTIVE", validDriverPayableAccount: earning.payableAccount.status === "ACTIVE" && earning.payableAccount.category === "LIABILITY" && earning.payableAccount.purpose === "DRIVER_EARNINGS_PAYABLE" && !earning.payableAccount.allowNegative, validOwnerWithdrawableAccount: Boolean(destination), releaseLedgerJournalId: earning.releaseLedgerJournalId, reversalLedgerJournalId: earning.reversalLedgerJournalId });
    if (!destination || earning.payableAccount.currentBalance.lessThan(remaining)) throw new DriverEarningError("DRIVER_EARNING_RELEASE_NOT_ELIGIBLE", "Driver payable cannot fund the exact release.");
    const accountIds = [earning.payableAccountId, destination.id].sort(); await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "LedgerAccount" WHERE "id" IN (${Prisma.join(accountIds)}) ORDER BY "id" FOR UPDATE`);
    const amount = formatDriverEarningMoney(remaining); const journal = await postLedgerJournalWithinTransaction(tx, driverEarningReleasePosting({ earningReference: earning.publicReference, amount, driverPayableAccountId: earning.payableAccountId, ownerWithdrawableAccountId: destination.id, driverPublicReference: earning.driverPublicReference, assignmentPublicReference: earning.assignmentPublicReference, assignmentVersion: earning.assignmentVersion, orderPublicReference: earning.orderPublicReference, settlementVersion: earning.settlementVersion, completionEvidenceReference: earning.completionEvidenceReference, releaseEligibleAt: earning.releaseEligibleAt.toISOString(), actorUserId: input.actorUserId }));
    const now = new Date(); await tx.driverEarning.update({ where: { id: earning.id }, data: { status: "RELEASED", releasedAmount: remaining, releaseLedgerJournalId: journal.id, releasedAt: now, version: { increment: 1 }, statusHistory: { create: { fromStatus: "ACCRUED", toStatus: "RELEASED", actorType: input.actorUserId ? "USER" : "SYSTEM", actorId: input.actorUserId ?? null, reasonCode: "RELEASE_COMPLETED", safeMetadata: { ledgerReference: journal.reference } } } } });
    return Object.freeze({ publicReference: earning.publicReference, status: "RELEASED" as const, releasedAmount: amount, releaseLedgerJournalReference: journal.reference, idempotent: false });
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }));
}
