/* eslint-disable @typescript-eslint/no-explicit-any -- Phase 17 Prisma Client generation and model type proof are intentionally deferred. */
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { withLedgerRetry } from "@/lib/ledger/retry";
import { DriverEarningError } from "@/lib/driver-earnings/errors";
import { assertAuthoritativeAssignment } from "@/lib/driver-earnings/driver-earning-assignment-policy";
import { driverEarningReversalPosting } from "@/lib/driver-earnings/driver-earning-ledger-policy";
import { formatDriverEarningMoney } from "@/lib/driver-earnings/driver-earning-money";
import { assertDriverEarningsProductionReady } from "@/lib/driver-earnings/driver-earning-production-readiness";
import { assertDriverEarningReversalPolicy, DRIVER_EARNING_REVERSAL_REASON_CODES, type DriverEarningReversalReasonCode } from "@/lib/driver-earnings/driver-earning-reversal-policy";
import { assignmentPublicReference } from "@/lib/driver-earnings/driver-earning-subject";
import { postLedgerJournalWithinTransaction } from "./ledger-posting.service";
import { openDriverEarningReconciliationWithinTransaction, resolveDriverEarningReconciliationsWithinTransaction } from "./driver-earning-reconciliation.service";

const db = prisma as any; const OPERATION = /^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/; const EVIDENCE = /^[A-Za-z0-9][A-Za-z0-9._:-]{7,159}$/;
function assignmentEvidence(row: any) { return { id: row.id, publicReference: assignmentPublicReference(row.id), version: String(row.version), driverId: row.driverProfileId, orderId: row.orderId, status: row.status, completedAt: row.completedAt?.toISOString() ?? null, podAssignmentId: row.proofOfDelivery?.assignmentId ?? null, podDriverId: row.proofOfDelivery?.driverProfileId ?? null, podOrderId: row.proofOfDelivery?.orderId ?? null, podDeliveredAt: row.proofOfDelivery?.deliveredAt?.toISOString() ?? null, hasDeliveryCompletedEvent: row.operationalEvents.some((event: any) => event.eventType === "DELIVERY_COMPLETED"), hasAssignmentCompletedEvent: row.events.some((event: any) => event.eventType === "ASSIGNMENT_COMPLETED") }; }
export async function reverseDriverEarning(input: Readonly<{ earningId: string; operationId: string; reasonCode: DriverEarningReversalReasonCode; reversalEvidenceReference: string; actorUserId: string; safeNote?: string }>, options?: Readonly<{ allowTestOnlyBypass?: boolean }>) {
  assertDriverEarningsProductionReady(options); if (!OPERATION.test(input.operationId) || !DRIVER_EARNING_REVERSAL_REASON_CODES.includes(input.reasonCode) || !EVIDENCE.test(input.reversalEvidenceReference) || (input.safeNote?.length ?? 0) > 240) throw new DriverEarningError("DRIVER_EARNING_INVALID_COMMAND", "A reviewed bounded reversal command and opaque evidence reference are required.");
  return withLedgerRetry(() => db.$transaction(async (tx: any) => {
    const locked = await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "DriverEarning" WHERE "id"=${input.earningId} FOR UPDATE`); if (locked.length !== 1) throw new DriverEarningError("DRIVER_EARNING_NOT_FOUND", "Driver earning was not found.");
    const earning = await tx.driverEarning.findUnique({ where: { id: input.earningId }, include: { payableAccount: true, reversalLedgerJournal: { select: { reference: true } }, commissionCharges: { include: { commissionAllocation: { include: { accrual: { select: { id: true, status: true } } } } } }, reconciliationCases: { select: { reason: true, status: true } } } });
    if (!earning) throw new DriverEarningError("DRIVER_EARNING_NOT_FOUND", "Driver earning was not found."); if (earning.status === "REVERSED" && earning.reversalLedgerJournal) return Object.freeze({ publicReference: earning.publicReference, status: earning.status, reversedAmount: formatDriverEarningMoney(earning.reversedAmount), reversalLedgerJournalReference: earning.reversalLedgerJournal.reference, idempotent: true });
    if (earning.releaseLedgerJournalId || !earning.releasedAmount.isZero() || earning.status === "RELEASED") { await openDriverEarningReconciliationWithinTransaction(tx, { caseKey: `driver-earning:reversal-after-release:${earning.id}`, driverEarningId: earning.id, reason: "REVERSAL_AFTER_RELEASE", priority: "CRITICAL", safeSummary: "Direct payable reversal is blocked after owner-withdrawable release." }); return Object.freeze({ publicReference: earning.publicReference, status: earning.status, reversalBlocked: true, blockReason: "REVERSAL_AFTER_RELEASE" as const }); }
    await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "OrderAssignment" WHERE "id"=${earning.assignmentId} FOR UPDATE`);
    const assignment = await tx.orderAssignment.findUnique({ where: { id: earning.assignmentId }, include: { proofOfDelivery: true, operationalEvents: { select: { eventType: true } }, events: { select: { eventType: true } } } });
    let completionEvidenceCurrentlyValid = true; try { if (!assignment) throw new Error(); assertAuthoritativeAssignment(assignmentEvidence(assignment), { assignmentId: earning.assignmentId, assignmentPublicReference: earning.assignmentPublicReference, assignmentVersion: earning.assignmentVersion, driverId: earning.driverId, orderId: earning.orderId, serviceCompletedAt: earning.serviceCompletedAt.toISOString() }); } catch { completionEvidenceCurrentlyValid = false; }
    const ids = earning.commissionCharges.map((c: any) => c.commissionAllocationId).sort(); if (ids.length) await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "CommissionAllocation" WHERE "id" IN (${Prisma.join(ids)}) ORDER BY "id" FOR UPDATE`);
    const commissionCoherent = earning.commissionCharges.every((c: any) => c.commissionAllocation.status === "REVERSED" && c.commissionAllocation.accrual.status === "REVERSED");
    if (!commissionCoherent) { const accrualId = earning.commissionCharges.find((c: any) => c.commissionAllocation.accrual.status !== "REVERSED")?.commissionAllocation.accrual.id; await openDriverEarningReconciliationWithinTransaction(tx, { caseKey: `driver-earning:commission-reversal:${earning.id}`, driverEarningId: earning.id, commissionAccrualId: accrualId, reason: "REVERSAL_BLOCKED_BY_COMMISSION", priority: "HIGH", safeSummary: "Attributed commission must be canonically reversed before driver entitlement reversal." }); return Object.freeze({ publicReference: earning.publicReference, status: "RECONCILIATION_REQUIRED" as const, reversalBlocked: true, blockReason: "REVERSAL_BLOCKED_BY_COMMISSION" as const }); }
    const remaining = earning.amount.sub(earning.refundedAmount).sub(earning.reversedAmount); assertDriverEarningReversalPolicy({ status: earning.status, releasedAmount: earning.releasedAmount, refundReservedAmount: earning.refundReservedAmount, remainingAmount: remaining, releaseLedgerJournalId: earning.releaseLedgerJournalId, reversalLedgerJournalId: earning.reversalLedgerJournalId, commissionTreatmentCoherent: true, reviewedReconciliation: earning.status === "RECONCILIATION_REQUIRED" && earning.reconciliationCases.some((r: any) => r.reason === "REVERSAL_BLOCKED_BY_COMMISSION" && ["OPEN", "MONITORING"].includes(r.status)), reversalEvidenceReference: input.reversalEvidenceReference });
    const held = await tx.ledgerAccount.findFirst({ where: { purpose: "HELD", category: "LIABILITY", currency: "ZAR", status: "ACTIVE", allowNegative: false, wallet: { ownerType: "PLATFORM", ownerId: "platform", currency: "ZAR", status: "ACTIVE" } } }); if (!held || earning.payableAccount.currentBalance.lessThan(remaining)) throw new DriverEarningError("DRIVER_EARNING_REVERSAL_NOT_ALLOWED", "Canonical payable or held account cannot fund reversal.");
    const accountIds = [earning.payableAccountId, held.id].sort(); await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "LedgerAccount" WHERE "id" IN (${Prisma.join(accountIds)}) ORDER BY "id" FOR UPDATE`);
    const amount = formatDriverEarningMoney(remaining); const journal = await postLedgerJournalWithinTransaction(tx, driverEarningReversalPosting({ earningReference: earning.publicReference, amount, driverPayableAccountId: earning.payableAccountId, customerFundsHeldAccountId: held.id, driverPublicReference: earning.driverPublicReference, assignmentPublicReference: earning.assignmentPublicReference, assignmentVersion: earning.assignmentVersion, orderPublicReference: earning.orderPublicReference, settlementVersion: earning.settlementVersion, completionEvidenceReference: earning.completionEvidenceReference, reasonCode: input.reasonCode, reversalEvidenceReference: input.reversalEvidenceReference, actorUserId: input.actorUserId }));
    await tx.driverEarning.update({ where: { id: earning.id }, data: { status: "REVERSED", reversedAmount: remaining, reversalLedgerJournalId: journal.id, reversedAt: new Date(), reversalReasonCode: input.reasonCode, reversalEvidenceReference: input.reversalEvidenceReference, version: { increment: 1 }, statusHistory: { create: { fromStatus: earning.status, toStatus: "REVERSED", actorType: "USER", actorId: input.actorUserId, reasonCode: input.reasonCode, safeMetadata: { ledgerReference: journal.reference, reversalEvidenceReference: input.reversalEvidenceReference, completionEvidenceCurrentlyValid, safeNote: input.safeNote ?? "" } } } } }); await resolveDriverEarningReconciliationsWithinTransaction(tx, { driverEarningId: earning.id, canonicalOperationReference: journal.reference, resolutionCode: "CANONICAL_REVERSAL" });
    return Object.freeze({ publicReference: earning.publicReference, status: "REVERSED" as const, reversedAmount: amount, reversalLedgerJournalReference: journal.reference, idempotent: false });
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }));
}
