/* eslint-disable @typescript-eslint/no-explicit-any -- Phase 17 Prisma Client generation and model type proof are intentionally deferred. */
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import type { DriverEarningDetailDto, DriverEarningListItemDto, FinanceDriverEarningListItemDto } from "@/lib/dto/driver-earning.dto";
import { DriverEarningError } from "@/lib/driver-earnings/errors";
import { formatDriverEarningMoney } from "@/lib/driver-earnings/driver-earning-money";

const db = prisma as any;
const include = { accrualLedgerJournal: { select: { reference: true } }, releaseLedgerJournal: { select: { reference: true } }, reversalLedgerJournal: { select: { reference: true } }, commissionCharges: { include: { commissionAllocation: { select: { publicReference: true, amount: true, storeAttributedAmount: true, driverAttributedAmount: true, allocationType: true, status: true, accrual: { select: { publicReference: true, status: true } } } } }, orderBy: { createdAt: "asc" } }, fundingAllocations: { include: { refund: { select: { publicReference: true, status: true } } }, orderBy: { createdAt: "asc" } }, statusHistory: { orderBy: { createdAt: "asc" }, select: { fromStatus: true, toStatus: true, actorType: true, reasonCode: true, safeMetadata: true, createdAt: true } }, reconciliationCases: { orderBy: { lastObservedAt: "desc" }, select: { publicReference: true, reason: true, status: true, priority: true, safeSummary: true, safeEvidence: true, observationCount: true, openedAt: true, lastObservedAt: true, resolvedAt: true, resolutionCode: true } } };
export type DriverEarningListQuery = Readonly<{ page: number; pageSize: number; status?: "ACCRUED" | "RECONCILIATION_REQUIRED" | "RELEASED" | "FULLY_REFUNDED" | "REVERSED"; from?: string; to?: string }>;
export type FinanceDriverEarningListQuery = DriverEarningListQuery & Readonly<{ driverReference?: string; assignmentReference?: string; orderReference?: string; paymentReference?: string; reconciliation?: boolean }>;
const available = (row: any) => { const value = row.amount.sub(row.refundReservedAmount).sub(row.refundedAmount).sub(row.releasedAmount).sub(row.reversedAmount); return value.isNegative() ? new Prisma.Decimal(0) : value; };
function driverItem(row: any): DriverEarningListItemDto { return Object.freeze({ publicReference: row.publicReference, assignmentPublicReference: row.assignmentPublicReference, orderPublicReference: row.orderPublicReference, settlementReference: row.settlementReference, originalEarningAmount: formatDriverEarningMoney(row.amount), refundReservedAmount: formatDriverEarningMoney(row.refundReservedAmount), refundedAmount: formatDriverEarningMoney(row.refundedAmount), releasedAmount: formatDriverEarningMoney(row.releasedAmount), availablePayableAmount: formatDriverEarningMoney(available(row)), currency: "ZAR", status: row.status, serviceCompletedAt: row.serviceCompletedAt.toISOString(), releaseEligibleAt: row.releaseEligibleAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString() }); }
function driverDetail(row: any): DriverEarningDetailDto { return Object.freeze({ ...driverItem(row), history: Object.freeze(row.statusHistory.map((event: any) => Object.freeze({ status: event.toStatus, reasonCode: event.reasonCode, createdAt: event.createdAt.toISOString() }))), productionLock: Object.freeze({ active: true as const, blockReason: "CONSOLIDATED_VALIDATION_NOT_APPROVED" as const }) }); }
function financeItem(row: any): FinanceDriverEarningListItemDto { return Object.freeze({ ...driverItem(row), id: row.id, driverPublicReference: row.driverPublicReference, paymentPublicReference: row.paymentPublicReference, assignmentVersion: row.assignmentVersion, settlementVersion: row.settlementVersion, settlementBasisAmount: formatDriverEarningMoney(row.settlementBasisAmount), attributedCommissionAmount: formatDriverEarningMoney(row.attributedCommissionAmount), reversedAmount: formatDriverEarningMoney(row.reversedAmount), reconciliationRequired: row.status === "RECONCILIATION_REQUIRED" || row.reconciliationCases.some((record: any) => ["OPEN", "MONITORING"].includes(record.status)) }); }
function financeDetail(row: any) { return Object.freeze({ ...financeItem(row), subjectPublicReference: row.subjectPublicReference, completionEvidenceReference: row.completionEvidenceReference, calculationVersion: row.calculationVersion, authoritativeAt: row.authoritativeAt.toISOString(), journals: Object.freeze({ accrual: row.accrualLedgerJournal.reference, release: row.releaseLedgerJournal?.reference ?? null, reversal: row.reversalLedgerJournal?.reference ?? null }), commissionCharges: Object.freeze(row.commissionCharges.map((charge: any) => Object.freeze({ publicReference: charge.publicReference, commissionAllocationReference: charge.commissionAllocation.publicReference, commissionAccrualReference: charge.commissionAllocation.accrual.publicReference, amount: formatDriverEarningMoney(charge.amount), currency: "ZAR", allocationType: charge.commissionAllocation.allocationType, allocationStatus: charge.commissionAllocation.status, commissionAccrualStatus: charge.commissionAllocation.accrual.status, allocationOriginalAmount: formatDriverEarningMoney(charge.commissionAllocation.amount), allocationStoreAttributedAmount: formatDriverEarningMoney(charge.commissionAllocation.storeAttributedAmount), allocationDriverAttributedAmount: formatDriverEarningMoney(charge.commissionAllocation.driverAttributedAmount) }))), refunds: Object.freeze(row.fundingAllocations.map((allocation: any) => Object.freeze({ fundingReference: allocation.publicReference, refundReference: allocation.refund.publicReference, status: allocation.refund.status, amount: formatDriverEarningMoney(allocation.amount), currency: "ZAR" }))), history: Object.freeze(row.statusHistory.map((event: any) => Object.freeze({ fromStatus: event.fromStatus, toStatus: event.toStatus, actorType: event.actorType, reasonCode: event.reasonCode, safeMetadata: event.safeMetadata, createdAt: event.createdAt.toISOString() }))), reconciliation: Object.freeze(row.reconciliationCases.map((record: any) => Object.freeze({ ...record, openedAt: record.openedAt.toISOString(), lastObservedAt: record.lastObservedAt.toISOString(), resolvedAt: record.resolvedAt?.toISOString() ?? null }))), productionLock: Object.freeze({ active: true, blockReason: "CONSOLIDATED_VALIDATION_NOT_APPROVED" }) }); }
async function owner(userId: string) { const user = await prisma.user.findUnique({ where: { id: userId }, select: { role: true, status: true, driverProfile: { select: { id: true, active: true, status: true, onboardingStatus: true } } } }); if (!user || user.role !== "DRIVER" || user.status !== "ACTIVE" || !user.driverProfile || !user.driverProfile.active || user.driverProfile.status !== "ACTIVE" || user.driverProfile.onboardingStatus !== "APPROVED") throw new DriverEarningError("DRIVER_EARNING_FORBIDDEN", "An active canonical driver is required to read earnings."); return user.driverProfile; }
const dates = (q: DriverEarningListQuery) => q.from || q.to ? { ...(q.from ? { gte: new Date(q.from) } : {}), ...(q.to ? { lte: new Date(q.to) } : {}) } : undefined;
const pagination = (page: number, pageSize: number, total: number) => Object.freeze({ page, pageSize, total, totalPages: Math.ceil(total / pageSize) });
export async function listDriverEarningsForOwner(userId: string, query: DriverEarningListQuery) { const driver = await owner(userId); const where = { driverId: driver.id, ...(query.status ? { status: query.status } : {}), ...(dates(query) ? { createdAt: dates(query) } : {}) }; const [total, rows] = await db.$transaction([db.driverEarning.count({ where }), db.driverEarning.findMany({ where, include, orderBy: [{ createdAt: "desc" }, { id: "desc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize })]); return Object.freeze({ data: Object.freeze(rows.map(driverItem)), pagination: pagination(query.page, query.pageSize, total) }); }
export async function getDriverEarningForOwner(userId: string, publicReference: string) { const driver = await owner(userId); const row = await db.driverEarning.findFirst({ where: { publicReference, driverId: driver.id }, include }); return row ? driverDetail(row) : null; }
export async function listFinanceDriverEarnings(query: FinanceDriverEarningListQuery) { const where = { ...(query.status ? { status: query.status } : {}), ...(query.driverReference ? { driverPublicReference: { contains: query.driverReference, mode: "insensitive" } } : {}), ...(query.assignmentReference ? { assignmentPublicReference: { contains: query.assignmentReference, mode: "insensitive" } } : {}), ...(query.orderReference ? { orderPublicReference: { contains: query.orderReference, mode: "insensitive" } } : {}), ...(query.paymentReference ? { paymentPublicReference: { contains: query.paymentReference, mode: "insensitive" } } : {}), ...(query.reconciliation === true ? { reconciliationCases: { some: { status: { in: ["OPEN", "MONITORING"] } } } } : query.reconciliation === false ? { reconciliationCases: { none: { status: { in: ["OPEN", "MONITORING"] } } } } : {}), ...(dates(query) ? { createdAt: dates(query) } : {}) }; const [total, rows] = await db.$transaction([db.driverEarning.count({ where }), db.driverEarning.findMany({ where, include, orderBy: [{ createdAt: "desc" }, { id: "desc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize })]); return Object.freeze({ data: Object.freeze(rows.map(financeItem)), pagination: pagination(query.page, query.pageSize, total) }); }
export async function getFinanceDriverEarning(id: string) { const row = await db.driverEarning.findUnique({ where: { id }, include }); return row ? financeDetail(row) : null; }
export async function listDriverEarningReconciliation(query: Readonly<{ page: number; pageSize: number; status?: string; reason?: string }>) { const where = { ...(query.status ? { status: query.status } : {}), ...(query.reason ? { reason: query.reason } : {}) }; const [total, rows] = await db.$transaction([db.driverEarningReconciliationCase.count({ where }), db.driverEarningReconciliationCase.findMany({ where, include: { driverEarning: { select: { id: true, publicReference: true, driverPublicReference: true, assignmentPublicReference: true, amount: true, status: true } }, refund: { select: { publicReference: true } }, commissionAccrual: { select: { publicReference: true } } }, orderBy: [{ lastObservedAt: "desc" }, { id: "desc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize })]); return Object.freeze({ data: Object.freeze(rows.map((row: any) => Object.freeze({ publicReference: row.publicReference, earningId: row.driverEarning.id, earningReference: row.driverEarning.publicReference, driverPublicReference: row.driverEarning.driverPublicReference, assignmentPublicReference: row.driverEarning.assignmentPublicReference, earningAmount: formatDriverEarningMoney(row.driverEarning.amount), earningStatus: row.driverEarning.status, refundReference: row.refund?.publicReference ?? null, commissionAccrualReference: row.commissionAccrual?.publicReference ?? null, reason: row.reason, status: row.status, priority: row.priority, safeSummary: row.safeSummary, observationCount: row.observationCount, openedAt: row.openedAt.toISOString(), lastObservedAt: row.lastObservedAt.toISOString(), resolvedAt: row.resolvedAt?.toISOString() ?? null, resolutionCode: row.resolutionCode }))), pagination: pagination(query.page, query.pageSize, total) }); }
export async function getDriverEarningReconciliation(publicReference: string) { const row = await db.driverEarningReconciliationCase.findUnique({ where: { publicReference }, include: { driverEarning: { select: { id: true, publicReference: true, driverPublicReference: true, assignmentPublicReference: true, amount: true, status: true } }, refund: { select: { publicReference: true, status: true } }, commissionAccrual: { select: { publicReference: true, status: true } } } }); return row ? Object.freeze({ ...row, earning: Object.freeze({ ...row.driverEarning, amount: formatDriverEarningMoney(row.driverEarning.amount), currency: "ZAR" }), driverEarning: undefined, openedAt: row.openedAt.toISOString(), lastObservedAt: row.lastObservedAt.toISOString(), resolvedAt: row.resolvedAt?.toISOString() ?? null }) : null; }
