export type CommissionErrorCode =
  | "COMMISSION_INVALID_COMMAND"
  | "COMMISSION_INVALID_BASIS"
  | "COMMISSION_INVALID_RULE"
  | "COMMISSION_INVALID_PLAN"
  | "COMMISSION_INVALID_STATE"
  | "COMMISSION_PLAN_NOT_FOUND"
  | "COMMISSION_POLICY_NOT_FOUND"
  | "COMMISSION_POLICY_OVERLAP"
  | "COMMISSION_PRODUCTION_LOCKED"
  | "COMMISSION_MAKER_CHECKER_REQUIRED"
  | "COMMISSION_IDEMPOTENCY_CONFLICT"
  | "COMMISSION_SETTLEMENT_ALREADY_ACCRUED"
  | "COMMISSION_TOTAL_EXCEEDS_BASIS"
  | "COMMISSION_BENEFICIARY_REQUIRED"
  | "COMMISSION_BENEFICIARY_INVALID"
  | "COMMISSION_ACCOUNT_INVALID"
  | "COMMISSION_ACCRUAL_NOT_FOUND"
  | "COMMISSION_REVERSAL_NOT_ALLOWED"
  | "COMMISSION_DOWNSTREAM_RELEASE_EXISTS"
  | "COMMISSION_PRODUCTION_VALIDATION_REQUIRED";

export class CommissionError extends Error {
  readonly code: CommissionErrorCode;

  constructor(code: CommissionErrorCode, message: string, readonly options?: Readonly<{ retryable?: boolean }>) {
    super(message);
    this.name = "CommissionError";
    this.code = code;
  }
}
