-- Phase 28 is deliberately additive and follows Phase 27 (20260726000000).
-- It creates developer API and outbound-webhook authorities only; it contains
-- no data seeds, plaintext credentials, endpoint URLs, signing secrets, or
-- operational applications.
CREATE TYPE "DeveloperApplicationStatus" AS ENUM ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','ACTIVE','SUSPENDED','REVOKED','ARCHIVED','REJECTED');
CREATE TYPE "DeveloperApplicationEnvironment" AS ENUM ('TEST','LIVE');
CREATE TYPE "DeveloperCredentialStatus" AS ENUM ('ACTIVE','EXPIRING','EXPIRED','REVOKED','COMPROMISED');
CREATE TYPE "DeveloperScopeGrantStatus" AS ENUM ('DRAFT','APPROVED','ACTIVE','RETIRED');
CREATE TYPE "DeveloperTermsStatus" AS ENUM ('APPROVED','RETIRED');
CREATE TYPE "ApiRequestOutcome" AS ENUM ('ALLOWED','DENIED','RATE_LIMITED','QUOTA_EXCEEDED','VALIDATION_FAILED','LOCKED');
CREATE TYPE "ApiIdempotencyStatus" AS ENUM ('RECORDED','COMPLETED','FAILED','EXPIRED');
CREATE TYPE "ApiRateLimitDecision" AS ENUM ('ALLOWED','LIMITED');
CREATE TYPE "ApiQuotaPeriod" AS ENUM ('DAY');
CREATE TYPE "DeveloperWebhookStatus" AS ENUM ('DRAFT','VERIFYING','VERIFICATION_FAILED','ACTIVE','PAUSED','DISABLED','REVOKED');
CREATE TYPE "DeveloperWebhookVerificationStatus" AS ENUM ('PENDING','SUCCEEDED','FAILED','EXPIRED');
CREATE TYPE "DeveloperWebhookSecretStatus" AS ENUM ('CURRENT','NEXT','RETIRED','REVOKED');
CREATE TYPE "DeveloperWebhookEventStatus" AS ENUM ('PROJECTED','DELIVERIES_CREATED','SUPPRESSED','EXPIRED');
CREATE TYPE "DeveloperWebhookDeliveryStatus" AS ENUM ('PENDING','CLAIMED','SENDING','SUCCEEDED','FAILED_RETRYABLE','FAILED_PERMANENT','ENDPOINT_DISABLED','EXPIRED','CANCELLED');
CREATE TYPE "DeveloperWebhookAttemptStatus" AS ENUM ('STARTED','SUCCEEDED','FAILED');
CREATE TYPE "DeveloperWebhookFailureClass" AS ENUM ('TRANSIENT_NETWORK','RATE_LIMIT','SERVER_ERROR','INVALID_ENDPOINT','BLOCKED_DESTINATION','INVALID_TLS','REDIRECT','RESPONSE_TOO_LARGE','CLIENT_ERROR','EXPIRED');
CREATE TYPE "DeveloperReconciliationReason" AS ENUM ('API_CREDENTIAL_HASH_CONFLICT','API_CREDENTIAL_WITHOUT_ACTIVE_APPLICATION','API_SCOPE_GRANT_MISMATCH','API_APPLICATION_OWNER_MISMATCH','API_IDEMPOTENCY_RESULT_MISSING','API_IDEMPOTENCY_HASH_CONFLICT','API_RATE_LIMIT_COUNTER_MISMATCH','API_QUOTA_COUNTER_MISMATCH','WEBHOOK_EVENT_WITHOUT_DELIVERY','WEBHOOK_DELIVERY_WITHOUT_ATTEMPT','WEBHOOK_DUPLICATE_DELIVERY','WEBHOOK_ATTEMPT_STUCK','WEBHOOK_ENDPOINT_NOT_VERIFIED','WEBHOOK_ENDPOINT_RESOLVES_PRIVATE','WEBHOOK_SECRET_VERSION_MISSING','WEBHOOK_SIGNATURE_INPUT_INVALID','WEBHOOK_SUBSCRIPTION_SCOPE_MISMATCH','WEBHOOK_EVENT_OWNER_MISMATCH','WEBHOOK_RETRY_SCHEDULE_MISMATCH','WEBHOOK_SUCCESS_WITHOUT_HTTP_SUCCESS','WEBHOOK_ACTIVE_WITHOUT_VALID_CREDENTIAL_OWNER');
CREATE TYPE "DeveloperReconciliationStatus" AS ENUM ('OPEN','IN_PROGRESS','CONVERGED');

CREATE TABLE "DeveloperApplication" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"ownerUserId" TEXT NOT NULL,"storeId" TEXT,"environment" "DeveloperApplicationEnvironment" NOT NULL,"name" TEXT NOT NULL,"businessPurpose" TEXT NOT NULL,"status" "DeveloperApplicationStatus" NOT NULL DEFAULT 'DRAFT',"approvedOwnerSnapshot" JSONB,"approvedEnvironment" "DeveloperApplicationEnvironment","version" INTEGER NOT NULL DEFAULT 1,"submittedAt" TIMESTAMP(3),"approvedAt" TIMESTAMP(3),"approvedByUserId" TEXT,"suspendedAt" TIMESTAMP(3),"revokedAt" TIMESTAMP(3),"archivedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,UNIQUE("ownerUserId","environment","name"));
CREATE TABLE "DeveloperApplicationReview" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"applicationId" TEXT NOT NULL,"reviewerUserId" TEXT,"decision" TEXT NOT NULL,"safeReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DeveloperTermsVersion" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"version" TEXT UNIQUE NOT NULL,"status" "DeveloperTermsStatus" NOT NULL DEFAULT 'APPROVED',"publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"retiredAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DeveloperTermsAcceptance" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"termsVersionId" TEXT NOT NULL,"applicationId" TEXT NOT NULL,"ownerUserId" TEXT NOT NULL,"actorUserId" TEXT,"sourceEvidence" JSONB,"acceptedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("applicationId","termsVersionId"));
CREATE TABLE "DeveloperScopeDefinition" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"key" TEXT UNIQUE NOT NULL,"description" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DeveloperScopeGrant" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"applicationId" TEXT NOT NULL,"version" INTEGER NOT NULL,"status" "DeveloperScopeGrantStatus" NOT NULL DEFAULT 'DRAFT',"ownerUserId" TEXT NOT NULL,"storeId" TEXT,"environment" "DeveloperApplicationEnvironment" NOT NULL,"scopes" JSONB NOT NULL,"apiVersion" TEXT NOT NULL,"quotaPolicyReference" TEXT,"rateLimitPolicyReference" TEXT,"approvedByUserId" TEXT,"approvedAt" TIMESTAMP(3),"effectiveAt" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("applicationId","version"));
CREATE TABLE "DeveloperScopeGrantVersion" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"grantId" TEXT NOT NULL,"version" INTEGER NOT NULL,"frozenSnapshot" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("grantId","version"));
CREATE TABLE "DeveloperApiCredential" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"applicationId" TEXT NOT NULL,"scopeGrantId" TEXT NOT NULL,"environment" "DeveloperApplicationEnvironment" NOT NULL,"prefix" TEXT NOT NULL,"fingerprint" TEXT UNIQUE NOT NULL,"credentialHash" TEXT NOT NULL,"maskedDisplay" TEXT NOT NULL,"status" "DeveloperCredentialStatus" NOT NULL DEFAULT 'ACTIVE',"expiresAt" TIMESTAMP(3),"lastUsedAt" TIMESTAMP(3),"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("applicationId","prefix"));
CREATE TABLE "DeveloperApiCredentialRotation" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"previousCredentialId" TEXT NOT NULL,"replacementCredentialId" TEXT UNIQUE NOT NULL,"overlapEndsAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DeveloperApiRequestAudit" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"requestId" TEXT UNIQUE NOT NULL,"applicationId" TEXT,"credentialFingerprint" TEXT,"environment" "DeveloperApplicationEnvironment","scope" TEXT,"method" TEXT NOT NULL,"route" TEXT NOT NULL,"outcome" "ApiRequestOutcome" NOT NULL,"responseStatus" INTEGER NOT NULL,"durationMs" INTEGER NOT NULL,"rateLimitDecision" "ApiRateLimitDecision","idempotencyResult" TEXT,"resourceOwnerType" TEXT,"safeResourceReference" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DeveloperApiIdempotencyRecord" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"credentialId" TEXT NOT NULL,"applicationId" TEXT NOT NULL,"environment" "DeveloperApplicationEnvironment" NOT NULL,"method" TEXT NOT NULL,"normalizedRoute" TEXT NOT NULL,"idempotencyKeyHash" TEXT NOT NULL,"requestHash" TEXT NOT NULL,"responseStatus" INTEGER,"responseBody" JSONB,"responseBodyHash" TEXT,"canonicalResultReference" TEXT,"status" "ApiIdempotencyStatus" NOT NULL DEFAULT 'RECORDED',"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("credentialId","method","normalizedRoute","idempotencyKeyHash"));
CREATE TABLE "DeveloperApiRateLimitPolicyVersion" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"version" INTEGER NOT NULL,"routeClass" TEXT NOT NULL,"maximumRequests" INTEGER NOT NULL,"windowSeconds" INTEGER NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("routeClass","version"));
CREATE TABLE "DeveloperApiRateUsage" ("id" TEXT PRIMARY KEY,"policyId" TEXT NOT NULL,"identityHash" TEXT NOT NULL,"windowStartedAt" TIMESTAMP(3) NOT NULL,"count" INTEGER NOT NULL DEFAULT 0,"updatedAt" TIMESTAMP(3) NOT NULL,UNIQUE("policyId","identityHash","windowStartedAt"));
CREATE TABLE "DeveloperApiQuotaPolicyVersion" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"version" INTEGER NOT NULL,"name" TEXT NOT NULL,"limits" JSONB NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("name","version"));
CREATE TABLE "DeveloperApiQuotaUsage" ("id" TEXT PRIMARY KEY,"applicationId" TEXT NOT NULL,"policyId" TEXT NOT NULL,"period" "ApiQuotaPeriod" NOT NULL,"periodStartedAt" TIMESTAMP(3) NOT NULL,"counters" JSONB NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL,UNIQUE("applicationId","policyId","period","periodStartedAt"));
CREATE TABLE "DeveloperWebhookEventType" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"key" TEXT UNIQUE NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DeveloperWebhookEventVersion" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"eventTypeId" TEXT NOT NULL,"version" INTEGER NOT NULL,"schemaReference" TEXT NOT NULL,"scopes" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("eventTypeId","version"));
CREATE TABLE "DeveloperWebhookSubscription" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"applicationId" TEXT NOT NULL,"environment" "DeveloperApplicationEnvironment" NOT NULL,"endpointFingerprint" TEXT NOT NULL,"encryptedEndpoint" TEXT NOT NULL,"maskedEndpoint" TEXT NOT NULL,"status" "DeveloperWebhookStatus" NOT NULL DEFAULT 'DRAFT',"version" INTEGER NOT NULL DEFAULT 1,"eventSelection" JSONB NOT NULL,"verifiedAt" TIMESTAMP(3),"pausedAt" TIMESTAMP(3),"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,UNIQUE("applicationId","environment","endpointFingerprint"));
CREATE TABLE "DeveloperWebhookSubscriptionVersion" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"subscriptionId" TEXT NOT NULL,"version" INTEGER NOT NULL,"endpointFingerprint" TEXT NOT NULL,"eventSelection" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("subscriptionId","version"));
CREATE TABLE "DeveloperWebhookVerification" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"subscriptionId" TEXT NOT NULL,"challengeHash" TEXT NOT NULL,"encryptedChallenge" TEXT NOT NULL,"status" "DeveloperWebhookVerificationStatus" NOT NULL DEFAULT 'PENDING',"attempts" INTEGER NOT NULL DEFAULT 0,"expiresAt" TIMESTAMP(3) NOT NULL,"verifiedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DeveloperWebhookSecret" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"subscriptionId" TEXT NOT NULL,"version" INTEGER NOT NULL,"encryptedSecret" TEXT NOT NULL,"fingerprint" TEXT NOT NULL,"maskedDisplay" TEXT NOT NULL,"status" "DeveloperWebhookSecretStatus" NOT NULL DEFAULT 'CURRENT',"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("subscriptionId","version"));
CREATE TABLE "DeveloperWebhookPublicEvent" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"sourceAuthority" TEXT NOT NULL,"sourceEventReference" TEXT NOT NULL,"eventType" TEXT NOT NULL,"subjectReference" TEXT NOT NULL,"ownerUserId" TEXT NOT NULL,"storeId" TEXT,"payload" JSONB NOT NULL,"payloadHash" TEXT NOT NULL,"status" "DeveloperWebhookEventStatus" NOT NULL DEFAULT 'PROJECTED',"occurredAt" TIMESTAMP(3) NOT NULL,"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("sourceAuthority","sourceEventReference","eventType"));
CREATE TABLE "DeveloperWebhookDelivery" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"publicEventId" TEXT NOT NULL,"subscriptionId" TEXT NOT NULL,"endpointVersion" INTEGER NOT NULL,"secretVersion" INTEGER NOT NULL,"status" "DeveloperWebhookDeliveryStatus" NOT NULL DEFAULT 'PENDING',"attemptCount" INTEGER NOT NULL DEFAULT 0,"nextAttemptAt" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"lastAttemptedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,UNIQUE("publicEventId","subscriptionId"));
CREATE TABLE "DeveloperWebhookAttempt" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"deliveryId" TEXT NOT NULL,"attemptNumber" INTEGER NOT NULL,"operationId" TEXT UNIQUE NOT NULL,"endpointVersion" INTEGER NOT NULL,"secretVersion" INTEGER NOT NULL,"status" "DeveloperWebhookAttemptStatus" NOT NULL DEFAULT 'STARTED',"httpStatus" INTEGER,"responsePreviewHash" TEXT,"failureClass" "DeveloperWebhookFailureClass","startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),"nextAttemptAt" TIMESTAMP(3),UNIQUE("deliveryId","attemptNumber"));
CREATE TABLE "DeveloperApiAuditEvent" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"entityReference" TEXT,"safeEvidence" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DeveloperApiReconciliationCase" ("id" TEXT PRIMARY KEY,"publicReference" TEXT UNIQUE NOT NULL,"reason" "DeveloperReconciliationReason" NOT NULL,"status" "DeveloperReconciliationStatus" NOT NULL DEFAULT 'OPEN',"applicationId" TEXT,"safeSummary" TEXT NOT NULL,"safeEvidence" JSONB,"openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"lastObservedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"convergedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);

CREATE INDEX "DeveloperApplication_ownerUserId_status_idx" ON "DeveloperApplication"("ownerUserId","status");
CREATE INDEX "DeveloperApiCredential_applicationId_status_idx" ON "DeveloperApiCredential"("applicationId","status");
CREATE INDEX "DeveloperApiCredential_expiresAt_idx" ON "DeveloperApiCredential"("expiresAt");
CREATE INDEX "DeveloperApiRequestAudit_applicationId_createdAt_idx" ON "DeveloperApiRequestAudit"("applicationId","createdAt");
CREATE INDEX "DeveloperApiRequestAudit_credentialFingerprint_createdAt_idx" ON "DeveloperApiRequestAudit"("credentialFingerprint","createdAt");
CREATE INDEX "DeveloperApiRateUsage_policyId_windowStartedAt_idx" ON "DeveloperApiRateUsage"("policyId","windowStartedAt");
CREATE INDEX "DeveloperApiQuotaUsage_applicationId_period_periodStartedAt_idx" ON "DeveloperApiQuotaUsage"("applicationId","period","periodStartedAt");
CREATE INDEX "DeveloperWebhookSubscription_applicationId_status_idx" ON "DeveloperWebhookSubscription"("applicationId","status");
CREATE INDEX "DeveloperWebhookVerification_status_expiresAt_idx" ON "DeveloperWebhookVerification"("status","expiresAt");
CREATE INDEX "DeveloperWebhookPublicEvent_status_createdAt_idx" ON "DeveloperWebhookPublicEvent"("status","createdAt");
CREATE INDEX "DeveloperWebhookDelivery_status_nextAttemptAt_idx" ON "DeveloperWebhookDelivery"("status","nextAttemptAt");
CREATE INDEX "DeveloperApiReconciliationCase_status_createdAt_idx" ON "DeveloperApiReconciliationCase"("status","createdAt");
