import { expect, test } from "@playwright/test";
import { Prisma } from "@prisma/client";
import { login } from "./fixtures/auth";
import { createPaidCheckout } from "./fixtures/store-order";
import { assertBalancedRefundJournal, balance, refundControl } from "./fixtures/refund";

for (const width of [1440, 390]) test(`distinct finance actors complete wallet once and retain Paystack uncertainty at ${width}px`, async ({ page }, testInfo) => {
  test.setTimeout(300_000);
  const { reference } = await createPaidCheckout(page, `finance-${width}`, width);
  const baseline = await refundControl(reference);
  const reserved = await refundControl(reference, "reserve-wallet", { amount: "25.00" });
  const refund = reserved.refunds[0];
  await login(page, "superadmin@ktcouriers.local");
  await page.goto("/admin/refunds"); await expect(page.getByRole("heading", { name: "Refunds", exact: true })).toBeVisible();
  await page.goto(`/admin/refunds/${refund.id}`);
  await expect(page.getByRole("heading", { name: "Canonical refund evidence", exact: true })).toBeVisible();
  await expect(page.getByRole("table", { name: "Refund funding", exact: true })).toContainText("25.00");
  for (const action of ["review", "approve"]) {
    const responsePromise = page.waitForResponse(r => r.url().endsWith(`/api/admin/refunds/${refund.id}/${action}`) && r.request().method() === "POST");
    await page.getByRole("button", { name: action === "review" ? "Start review" : "Approve", exact: true }).click();
    const response = await responsePromise; expect(response.status(), await response.text()).toBe(200); await page.reload();
  }
  const approved = await refundControl(reference); expect(approved.refunds[0].status).toBe("APPROVED");
  await expect(page.getByText("Refund completion is inactive pending consolidated validation approval.", { exact: true })).toBeVisible();
  expect((await page.request.post(`/api/admin/refunds/${refund.id}/complete-wallet`, { data: { operationId: crypto.randomUUID() }, headers: { origin: new URL(page.url()).origin } })).status()).toBe(503);
  expect((await refundControl(reference)).payment).toEqual(approved.payment);
  const completed = await refundControl(reference, "complete-wallet", { reference: refund.reference });
  expect(completed.refunds[0].status).toBe("SUCCEEDED"); expect(completed.payment).toMatchObject({ reserved: "0.00", refunded: "25.00", status: "SUCCEEDED" });
  expect(balance(completed, "CUSTOMER_WALLET_AVAILABLE")).toBe("25.00"); expect(balance(completed, "CUSTOMER_REFUND_HELD")).toBe("0.00");
  assertBalancedRefundJournal(completed.refunds[0].completion, "REFUND_WALLET_CREDIT", "25.00");
  expect((await refundControl(reference, "complete-wallet", { reference: refund.reference })).refunds).toEqual(completed.refunds);
  await login(page, `e2e-paystack-finance-${width}@ktcouriers.local`); await page.goto("/account/wallet");
  await expect(page.getByRole("heading", { name: "Wallet", exact: true })).toBeVisible();
  const wallet = await page.request.get("/api/customer-wallet"); expect(wallet.status()).toBe(200); expect((await wallet.json()).wallet).toMatchObject({ availableBalance: "25.00", refundHeldBalance: "0.00", spendingEnabled: false });
  const history = await page.request.get("/api/customer-wallet/transactions"); expect(history.status()).toBe(200); expect((await history.json()).data).toEqual([expect.objectContaining({ type: "REFUND_WALLET_CREDIT", amount: "25.00", direction: "CREDIT" })]);
  const original = await refundControl(reference, "reserve-original", { amount: "10.00" });
  const external = original.refunds.find(r => r.method === "ORIGINAL_PAYMENT_METHOD")!;
  await refundControl(reference, "approve", { reference: external.reference });
  const unknown = await refundControl(reference, "start-provider", { reference: external.reference, outcome: "unrecognized" });
  const unknownRefund = unknown.refunds.find(r => r.reference === external.reference)!;
  expect(unknownRefund).toMatchObject({ status: "RECONCILIATION_REQUIRED", completion: null, attempts: [{ provider: "PAYSTACK", status: "UNKNOWN", number: 1 }] });
  expect(unknownRefund.reconciliation).toEqual([{ reason: "UNKNOWN_PROVIDER_OUTCOME", status: "OPEN" }]);
  expect(unknown.payment).toMatchObject({ reserved: "10.00", refunded: "25.00" }); expect(balance(unknown, "CUSTOMER_REFUND_HELD")).toBe("10.00"); expect(unknown.provider?.calls).toBe(1);
  await expect(refundControl(reference, "start-provider", { reference: external.reference, operationId: crypto.randomUUID() })).rejects.toThrow("not eligible");
  expect((await refundControl(reference)).provider?.calls).toBe(1);
  await login(page, "superadmin@ktcouriers.local"); await page.goto(`/admin/refunds/${external.id}`);
  await expect(page.getByText("Provider status queries remain validation-locked.", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: /mark.*success|mark.*paid|Start provider refund/i })).toHaveCount(0);
  const externalCompleted = await refundControl(reference, "query-provider", { reference: external.reference, outcome: "processed" });
  const succeeded = externalCompleted.refunds.find(r => r.reference === external.reference)!;
  expect(succeeded.status, JSON.stringify({ reconciliation: succeeded.reconciliation, history: succeeded.history, attempts: succeeded.attempts, provider: externalCompleted.provider })).toBe("SUCCEEDED"); assertBalancedRefundJournal(succeeded.completion, "REFUND_EXTERNAL_PAYOUT", "10.00");
  expect(externalCompleted.payment).toMatchObject({ reserved: "0.00", refunded: "35.00" });
  expect(balance(externalCompleted, "CASH_CLEARING")).toBe(new Prisma.Decimal(balance(baseline, "CASH_CLEARING")).sub("10.00").toFixed(2));
  await login(page, "e2e-ledger-denied@ktcouriers.local");
  expect((await page.request.get(`/api/admin/refunds/${external.id}`)).status()).toBe(403);
  expect((await page.request.post(`/api/admin/refunds/${external.id}/approve`, { data: { operationId: crypto.randomUUID() }, headers: { origin: new URL(page.url()).origin } })).status()).toBe(403);
  await page.goto(`/admin/refunds/${external.id}`); await expect(page.getByRole("button", { name: /Approve|Reject and release|Start review/ })).toHaveCount(0);
  expect((await refundControl(reference)).payment).toEqual(externalCompleted.payment);
  await testInfo.attach("canonical-postgres-finance-wallet-paystack-proof", { body: JSON.stringify({ baseline, reserved, approved, completed, unknown, externalCompleted }), contentType: "application/json" });
});
