import { Prisma } from "@prisma/client";
import { expect, test } from "@playwright/test";
import { login } from "./fixtures/auth";
import { prepareStoreOrder, storeAction, storeControl, customerAction } from "./fixtures/store-order";
import { refundControl, assertBalancedRefundJournal } from "./fixtures/refund";

for (const width of [1440, 390]) test(`native owned replacement approval and exact original-method refund at ${width}px`, async ({ page }, info) => {
  test.setTimeout(240_000);
  const f = await prepareStoreOrder(page, `store-positive-${width}`, width);
  await page.goto(`/order-confirmation/${f.order.publicReference}`);
  const decisions = page.getByRole("region", { name: `Order decisions for ${f.storeReference}`, exact: true });
  await decisions.getByRole("combobox").selectOption("CONTACT_ME");
  const preference = page.waitForResponse(r => r.url().endsWith(`/store-orders/${f.storeReference}/actions`) && r.request().method() === "POST");
  await decisions.getByRole("button", { name: "Save item preference", exact: true }).click(); expect((await preference).status()).toBe(200);
  await login(page, "e2e-store@ktcouriers.local");
  expect((await storeAction(page, f.storeReference, { action: "begin-review" })).status()).toBe(200);
  const unavailable = await storeAction(page, f.storeReference, { action: "confirm-availability", orderLineId: f.baseline.lines[0].id, availableQuantity: 0 }); expect(unavailable.status(), await unavailable.text()).toBe(200);
  await page.goto(`/store/marketplace-orders/${f.storeReference}`);
  const proposalForm = page.getByRole("form", { name: /Propose replacement for/ });
  await proposalForm.getByLabel("Replacement item", { exact: true }).selectOption("off_headphones");
  const proposalResponse = page.waitForResponse(r => r.url().endsWith(`/api/store/orders/${f.storeReference}/actions`) && r.request().method() === "POST");
  await proposalForm.getByRole("button", { name: "Propose replacement", exact: true }).click(); const proposed = await proposalResponse; expect(proposed.status(), await proposed.text()).toBe(200);
  const proposal = (await proposed.json()).result;
  const reserved = await storeControl(f.storeReference);
  expect(reserved.proposals).toEqual([expect.objectContaining({ status: "PROPOSED", reservation: { status: "ACTIVE" } })]);
  const body = { action: "decide-substitution", proposalReference: proposal.proposalReference, decision: "APPROVE", operationId: crypto.randomUUID() };
  await login(page, "e2e-checkout-other@ktcouriers.local");
  expect((await page.request.get(`/api/marketplace-orders/${f.order.publicReference}/store-orders/${f.storeReference}/actions`)).status()).toBe(404);
  expect((await customerAction(page, f.order.publicReference, f.storeReference, body)).status()).toBe(404);
  expect(await storeControl(f.storeReference)).toEqual(reserved);
  await login(page, `e2e-paystack-store-positive-${width}@ktcouriers.local`); await page.goto(`/order-confirmation/${f.order.publicReference}`);
  await expect(decisions.getByRole("heading", { name: /Proposed replacement/ })).toBeVisible();
  const approvedResponse = page.waitForResponse(r => r.url().endsWith(`/store-orders/${f.storeReference}/actions`) && r.request().method() === "POST");
  await decisions.getByRole("button", { name: "Approve replacement", exact: true }).click(); const approved = await approvedResponse; expect(approved.status(), await approved.text()).toBe(200);
  const command = approved.request().postDataJSON(); expect((await customerAction(page, f.order.publicReference, f.storeReference, command)).status()).toBe(200);
  const decided = await storeControl(f.storeReference);
  expect(decided.proposals[0]).toMatchObject({ status: "APPROVED", reservation: { status: "CONSUMED" } });
  expect(decided.stock.every(row => row.onHand === row.available + row.reserved)).toBe(true);
  expect(decided.adjustments).toHaveLength(1); const adjustment = decided.adjustments[0];
  const expectedRefund = new Prisma.Decimal(proposal.originalRemainingCharge).sub(proposal.customerCharge).toFixed(2);
  expect(new Prisma.Decimal(adjustment.refundAmount).toFixed(2)).toBe(expectedRefund); expect(new Prisma.Decimal(expectedRefund).greaterThan(0)).toBe(true);
  expect(decided.payment).toEqual(f.baseline.payment);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await info.attach(`owned-replacement-${width}`, { body: await page.screenshot({ fullPage: true }), contentType: "image/png" });
  await login(page, "e2e-store@ktcouriers.local");
  expect((await storeAction(page, f.storeReference, { action: "accept", preparationMinutes: 30, pickupInstructions: "Disposable collection" })).status()).toBe(422);
  const funded = await refundControl(f.reference, "apply-store-adjustment", { storeOrderReference: f.storeReference, adjustmentReference: adjustment.publicReference });
  const refund = funded.refunds.find(row => row.reference === funded.result?.reference)!;
  expect(refund).toMatchObject({ method: "ORIGINAL_PAYMENT_METHOD", amount: expectedRefund }); assertBalancedRefundJournal(refund.reserve, "REFUND_RESERVE", expectedRefund);
  await refundControl(f.reference, "approve", { reference: refund.reference });
  const completed = await refundControl(f.reference, "start-provider", { reference: refund.reference, outcome: "processed" });
  expect(completed.refunds[0].status).toBe("SUCCEEDED"); assertBalancedRefundJournal(completed.refunds[0].completion, "REFUND_EXTERNAL_PAYOUT", expectedRefund);
  expect(completed.payment).toMatchObject({ reserved: "0.00", refunded: expectedRefund }); expect(completed.provider?.calls).toBe(1);
  expect((await refundControl(f.reference, "start-provider", { reference: refund.reference, outcome: "processed" })).refunds).toEqual(completed.refunds);
  const resolved = await storeControl(f.storeReference); expect(resolved.adjustments[0].status).toBe("COMPLETED"); expect(resolved.resolutionStatus).toBe("RESOLVED"); expect(resolved.stock).toEqual(decided.stock);
  const accepted = await storeAction(page, f.storeReference, { action: "accept", preparationMinutes: 30, pickupInstructions: "Disposable resolved collection" }); expect(accepted.status(), await accepted.text()).toBe(200);
  expect((await storeControl(f.storeReference)).acceptanceStatus).toBe("ACCEPTED");
  await info.attach("replacement-refund-postgres", { body: JSON.stringify({ reserved, decided, funded, completed, resolved }), contentType: "application/json" });
});
