import { customerOrderNotificationDefinitions, customerOrderRecipientPolicyKey, customerOrderRouteKey } from "./customer-order-configuration";

export const requiredDomainNotificationDefinitions = [
  ...customerOrderNotificationDefinitions.map((definition) => ({ ...definition, sourceAuthority: "LEGACY_ORDER", recipientPolicyKey: customerOrderRecipientPolicyKey, subject: "CUSTOMER" as const, routeKey: customerOrderRouteKey(definition.eventType), variables: definition.eventType === "ORDER_CONFIRMED" ? ["orderNumber"] : ["orderNumber", "status"], actionRoute: "/account/orders", recipientSummary: "The customer recorded on the courier order." })),
  { sourceAuthority: "MARKETPLACE", eventType: "MARKETPLACE_ORDER_CONFIRMED", categoryKey: "MARKETPLACE_ORDER_STATUS", templateKey: "CLIENT_MARKETPLACE_ORDER_CONFIRMED", recipientPolicyKey: "CLIENT_MARKETPLACE_CUSTOMER", subject: "MARKETPLACE_CUSTOMER" as const, routeKey: "CLIENT_MARKETPLACE_ORDER_CONFIRMED", title: "KT Couriers: marketplace order {{orderNumber}} confirmed", body: "Your marketplace order {{orderNumber}} is confirmed. Keep this reference when contacting KT Couriers for assistance.", variables: ["orderNumber"], actionRoute: null, recipientSummary: "The account customer or verified guest contact recorded on the marketplace checkout." },
  { sourceAuthority: "STORE_ORDERS", eventType: "STORE_ORDER_RECEIVED", categoryKey: "STORE_ORDER_RECEIVED", templateKey: "CLIENT_VENDOR_ORDER_RECEIVED", recipientPolicyKey: "CLIENT_VENDOR_ORDER_OWNER", subject: "STORE_OWNER" as const, routeKey: "CLIENT_VENDOR_ORDER_RECEIVED", title: "KT Couriers: new store order {{orderNumber}}", body: "Store order {{orderNumber}} is ready for review in your store account.", variables: ["orderNumber"], actionRoute: "/store/orders", recipientSummary: "The current active owner of the store recorded on the paid store order." },
  ...["STORE_ORDER_ACCEPTED", "STORE_ORDER_REJECTED", "STORE_ORDER_READY_FOR_HANDOFF", "COURIER_ORDER_BRIDGED"].map((eventType) => ({ sourceAuthority: "STORE_ORDERS", eventType, categoryKey: "STORE_ORDER_STATUS", templateKey: `CLIENT_${eventType}`, recipientPolicyKey: "CLIENT_MARKETPLACE_CUSTOMER", subject: "MARKETPLACE_CUSTOMER" as const, routeKey: `CLIENT_${eventType}`, title: "KT Couriers: store order {{orderNumber}} update", body: "Store order {{orderNumber}}: {{status}}. Keep this reference when contacting KT Couriers for assistance.", variables: ["orderNumber", "status"], actionRoute: null, recipientSummary: "The account customer or verified guest contact on the parent marketplace checkout." })),
  { sourceAuthority: "PAYMENT", eventType: "PAYMENT_SUCCEEDED_VERIFIED", categoryKey: "PAYMENT_STATUS", templateKey: "CLIENT_PAYMENT_SUCCEEDED_VERIFIED", recipientPolicyKey: "CLIENT_PAYMENT_CUSTOMER", subject: "PAYMENT_CUSTOMER" as const, routeKey: "CLIENT_PAYMENT_SUCCEEDED_VERIFIED", title: "KT Couriers: payment {{paymentReference}} confirmed", body: "Payment {{paymentReference}} for R{{amount}} has been verified. Keep this reference when contacting KT Couriers for assistance.", variables: ["paymentReference", "amount"], actionRoute: null, recipientSummary: "The payer on the canonical payment, or the verified guest contact on its checkout." },
  { sourceAuthority: "PAYMENT", eventType: "PAYMENT_STATUS_CHANGED", categoryKey: "PAYMENT_STATUS", templateKey: "CLIENT_PAYMENT_STATUS_CHANGED", recipientPolicyKey: "CLIENT_PAYMENT_CUSTOMER", subject: "PAYMENT_CUSTOMER" as const, routeKey: "CLIENT_PAYMENT_STATUS_CHANGED", title: "KT Couriers: payment {{paymentReference}} update", body: "Payment {{paymentReference}}: {{status}}. Keep this reference when contacting KT Couriers for assistance.", variables: ["paymentReference", "status"], actionRoute: null, recipientSummary: "The payer on the canonical payment, or the verified guest contact on its checkout." },
  { sourceAuthority: "REFUND", eventType: "REFUND_STATUS_CHANGED", categoryKey: "REFUND_STATUS", templateKey: "CLIENT_REFUND_STATUS_CHANGED", recipientPolicyKey: "CLIENT_PAYMENT_CUSTOMER", subject: "PAYMENT_CUSTOMER" as const, routeKey: "CLIENT_REFUND_STATUS_CHANGED", title: "KT Couriers: refund {{refundReference}} update", body: "Refund {{refundReference}} for R{{amount}}: {{status}}. Keep this reference when contacting KT Couriers for assistance.", variables: ["refundReference", "amount", "status"], actionRoute: null, recipientSummary: "The customer on the refund and payment, or the verified guest contact on that payment's checkout." },
] as const;

export const requiredDomainDefinition = (sourceAuthority: string, eventType: string) => requiredDomainNotificationDefinitions.find((definition) => definition.sourceAuthority === sourceAuthority && definition.eventType === eventType);
