/* eslint-disable @typescript-eslint/no-explicit-any -- Prisma client generation is intentionally deferred. */
import { NextResponse } from "next/server";
import { z } from "zod";
import { parsePagination, paginated } from "@/lib/api/response";
import { PERMISSIONS } from "@/lib/auth/permission-keys";
import { prisma } from "@/lib/db/prisma";
import { notificationAdminAccess, notificationFailure, parseNotificationBody } from "@/lib/notifications/admin-api";
const body = z.object({ userId: z.string().min(1).optional(), endpointFingerprint: z.string().length(64).optional(), channel: z.enum(["IN_APP", "EMAIL", "SMS", "WEB_PUSH", "ANDROID_PUSH"]).optional(), purpose: z.enum(["SECURITY", "LEGAL", "TRANSACTIONAL", "OPERATIONAL", "SERVICE_ANNOUNCEMENT", "MARKETING"]).optional(), reason: z.enum(["HARD_BOUNCE", "COMPLAINT", "INVALID_PHONE", "SMS_OPT_OUT", "INVALID_PUSH_ENDPOINT", "USER_REVOCATION", "ADMIN_SECURITY_BLOCK", "MARKETING_CONSENT_REVOKED", "REPEATED_PERMANENT_FAILURE"]), evidence: z.record(z.string(), z.unknown()).optional() }).refine((input) => Boolean(input.userId || input.endpointFingerprint));
export async function GET(request: Request) { const access = await notificationAdminAccess(request, PERMISSIONS.NOTIFICATION_SUPPRESSION_READ); if ("response" in access) return access.response; const { page, pageSize, skip } = parsePagination(new URL(request.url).searchParams); const db: any = prisma; const [data, total] = await Promise.all([db.notificationSuppression.findMany({ orderBy: { createdAt: "desc" }, skip, take: pageSize, select: { publicReference: true, channel: true, purpose: true, reason: true, active: true, createdAt: true, reviewedAt: true } }), db.notificationSuppression.count()]); return paginated(data, total, page, pageSize); }
export async function POST(request: Request) { const access = await notificationAdminAccess(request, PERMISSIONS.NOTIFICATION_SUPPRESSION_MANAGE, true); if ("response" in access) return access.response; const parsed = await parseNotificationBody(request, body); if ("response" in parsed) return parsed.response; try { return NextResponse.json({ data: await access.authority.suppressions.suppress(parsed.data) }, { status: 201 }); } catch (error) { return notificationFailure(error); } }
