export type SubscriptionErrorCode =
  | "SUBSCRIPTION_ACCESS_DENIED"
  | "SUBSCRIPTION_INVALID_INPUT"
  | "SUBSCRIPTION_PLAN_NOT_OFFERABLE"
  | "SUBSCRIPTION_PLAN_TRANSITION_INVALID"
  | "SUBSCRIPTION_CONTRACT_CONFLICT"
  | "SUBSCRIPTION_CONTRACT_TRANSITION_INVALID"
  | "SUBSCRIPTION_REVIEW_STALE"
  | "SUBSCRIPTION_ACKNOWLEDGEMENT_STALE"
  | "SUBSCRIPTION_PAYMENT_SUBJECT_INVALID"
  | "SUBSCRIPTION_ENTITLEMENT_INVALID"
  | "SUBSCRIPTION_ENTITLEMENT_EXHAUSTED"
  | "SUBSCRIPTION_RECONCILIATION_REQUIRED"
  | "PROVIDER_TOKEN_STORAGE_UNAVAILABLE"
  | "SUBSCRIPTION_PROVIDER_PROTOCOL_INVALID"
  | "CONSOLIDATED_VALIDATION_NOT_APPROVED";

export class SubscriptionError extends Error {
  constructor(
    readonly code: SubscriptionErrorCode,
    message: string,
    readonly retryable = false,
  ) {
    super(message);
    this.name = "SubscriptionError";
  }
}
