/**
 * DB-level type re-exports from Prisma.
 *
 * These types are generated by `npx prisma generate` and reflect the schema
 * exactly. Import from here rather than from "@prisma/client" directly so
 * import paths stay consistent across the app.
 *
 * Requires: `npx prisma generate` must be run before this file can be used
 * in type-checked code. See docs/database-foundation.md.
 */

export type {
  User,
  CustomerProfile,
  StoreProfile,
  AdminProfile,
  DriverProfile,
  Session,
  OtpCode,
  PasswordResetToken,
  LoginHistory,
  SecurityEvent,
  Permission,
  RolePermission,
  UserPermission,
  Store,
  Address,
  Order,
  OrderStatusHistory,
  DeliveryRegion,
  PricingRule,
  PricingAuditLog,
  EmailLog,
  ContactMessage,
  AdminActivityLog,
  SystemSetting,
  DriverServiceRegion,
  DriverDocument,
  OrderAssignment,
  OrderAssignmentEvent,
  OrderOperationalEvent,
  ProofOfDelivery,
  DeliveryOtp,
  DeliveryAttempt,
  DriverOperationCommand,
  Payment,
  PaymentAttempt,
  PaymentStatusHistory,
  PaymentWebhookEvent,
  PaymentReconciliationCase,
  PaymentRefund,
  RefundFundingAllocation,
  RefundExecutionAttempt,
  RefundStatusHistory,
  RefundReconciliationCase,
  Wallet,
  WalletTransaction,
  LedgerAccount,
  LedgerJournal,
  LedgerEntry,
  WithdrawalRequest,
  PayoutDestination,
  WithdrawalPolicy,
  WithdrawalPayoutAttempt,
  WithdrawalStatusHistory,
  WithdrawalReconciliationCase,
  LegacyCommissionRule,
  CommissionPlan,
  CommissionPlanStatusHistory,
  CommissionRule,
  CommissionAccrual,
  CommissionAllocation,
  CommissionStatusHistory,
  CommissionReconciliationCase,
  StoreEarning,
  StoreEarningCommissionCharge,
  StoreEarningStatusHistory,
  StoreEarningReconciliationCase,
  CommissionTransaction,
  LegacySubscriptionPlan,
  LegacyStoreSubscription,
  LegacySubscriptionInvoice,
  SubscriptionProgram,
  SubscriptionStoreBillingAuthority,
  SubscriptionPlanVersion,
  SubscriptionBenefitDefinition,
  SubscriptionDunningPolicy,
  SubscriptionContract,
  SubscriptionReview,
  SubscriptionAcknowledgement,
  SubscriptionPaymentAuthority,
  SubscriptionBillingCycle,
  SubscriptionInvoice,
  SubscriptionRenewalJob,
  SubscriptionEntitlementGrant,
  SubscriptionEntitlementUsage,
  SubscriptionContractChange,
  SubscriptionReconciliationCase,
  SubscriptionEventIntent,
  ProductCategory,
  Product,
  ProductImage,
  InventoryItem,
  InventoryMovement,
  Cart,
  CartItem,
  OrderItem,
  LegacyPromotion,
  LegacyCoupon,
  LegacyPromotionRedemption,
  PromotionCampaign,
  PromotionCampaignVersion,
  PromotionCampaignVersionTarget,
  PromotionCampaignVersionEligibility,
  PromotionCampaignVersionCustomerAllowlist,
  PromotionCode,
  PromotionCodeBatch,
  PromotionBudget,
  PromotionBudgetMovement,
  PromotionReservation,
  PromotionRedemption,
  PromotionFinancialAllocation,
  PromotionReconciliationCase,
  PromotionStatusHistory,
  PromotionEventIntent,
  PromotionOperation,
  AdPlacement,
  AdCampaign,
  PromoterProfile,
  ReferralCode,
  ReferralEvent,
  ApiClient,
  ApiKey,
  ApiRequestLog,
  WebhookEndpoint,
  WebhookDelivery,
  Vacancy,
  RecruitmentApplication,
  ApplicationDocument,
  ApplicationStatusHistory,
  Notification,
  ReportJob,
} from "@prisma/client";

export {
  UserRole,
  UserStatus,
  PermissionEffect,
  OtpPurpose,
  StoreStatus,
  OrderStatus,
  OrderSource,
  DeliveryType,
  AddressType,
  PricingRuleType,
  PricingQuoteStatus,
  PricingQuoteOwnerType,
  PricingLineItemCode,
  EmailTemplateType,
  EmailStatus,
  ContactMessageStatus,
  AdminActionType,
  SystemSettingType,
  DriverStatus,
  DriverAvailability,
  DriverOnboardingStatus,
  VehicleType,
  DocumentType,
  DocumentStatus,
  OrderAssignmentStatus,
  OrderAssignmentEventType,
  OrderOperationalEventType,
  PickupFailureReason,
  ParcelCondition,
  ProofOfDeliveryMethod,
  DeliveryExceptionReason,
  RecordStatus,
  VerificationStatus,
  ProcessingStatus,
  PaymentProvider,
  PaymentPurpose,
  PaymentStatus,
  PaymentAttemptStatus,
  PaymentProviderFailureCategory,
  PaymentHistoryActorType,
  PaymentProviderEnvironment,
  PaymentCustomerActionType,
  PaymentWebhookNormalizedStatus,
  PaymentWebhookProcessingStatus,
  PaymentReconciliationReason,
  PaymentReconciliationCaseStatus,
  PaymentReconciliationPriority,
  PaymentReconciliationState,
  RefundMethod,
  RefundStatus,
  RefundReasonCode,
  RefundFundingSourceType,
  RefundAttemptStatus,
  RefundFailureCategory,
  RefundHistoryActorType,
  RefundReconciliationReason,
  RefundReconciliationCaseStatus,
  RefundReconciliationPriority,
  WalletOwnerType,
  WalletTransactionDirection,
  WalletTransactionType,
  WalletTransactionStatus,
  LedgerCurrency,
  LedgerAccountPurpose,
  LedgerAccountCategory,
  LedgerAccountStatus,
  LedgerJournalType,
  LedgerEntryDirection,
  WithdrawalStatus,
  PayoutMethod,
  PayoutDestinationStatus,
  PayoutAttemptStatus,
  PayoutFailureCategory,
  WithdrawalHistoryActorType,
  WithdrawalReconciliationReason,
  WithdrawalReconciliationCaseStatus,
  WithdrawalReconciliationPriority,
  CommissionOwnerType,
  CommissionRuleType,
  CommissionValueType,
  CommissionTransactionStatus,
  CommissionSubjectType,
  CommissionPlanStatus,
  CommissionBasisType,
  CommissionAllocationType,
  CommissionBeneficiaryType,
  CommissionCalculationMethod,
  CommissionAccrualStatus,
  CommissionAllocationStatus,
  CommissionHistoryActorType,
  CommissionReconciliationReason,
  CommissionReconciliationStatus,
  CommissionReconciliationPriority,
  StoreEarningSubjectType,
  StoreEarningStatus,
  StoreEarningHistoryActorType,
  StoreEarningReconciliationReason,
  StoreEarningReconciliationStatus,
  StoreEarningReconciliationPriority,
  SubscriptionPlanCode,
  SubscriptionStatus,
  LegacySubscriptionInvoiceStatus,
  SubscriptionProgramSubjectType,
  SubscriptionProgramStatus,
  SubscriptionStoreBillingAuthorityStatus,
  SubscriptionPlanVersionStatus,
  SubscriptionContractTermType,
  SubscriptionBillingInterval,
  SubscriptionContractStatus,
  SubscriptionPaymentAuthorityMode,
  SubscriptionPaymentAuthorityStatus,
  SubscriptionBillingCycleStatus,
  SubscriptionInvoiceStatus,
  SubscriptionRenewalJobStatus,
  SubscriptionBenefitType,
  SubscriptionBenefitValueType,
  SubscriptionBenefitConsumingPhase,
  SubscriptionBenefitStackingPolicy,
  SubscriptionBenefitReversalPolicy,
  SubscriptionEntitlementGrantStatus,
  SubscriptionEntitlementUsageAction,
  SubscriptionEntitlementUsageSourceType,
  SubscriptionReviewStatus,
  SubscriptionContractChangeType,
  SubscriptionContractChangeStatus,
  SubscriptionDunningPolicyStatus,
  SubscriptionReconciliationReason,
  SubscriptionReconciliationCaseStatus,
  SubscriptionReconciliationPriority,
  SubscriptionEventIntentType,
  ProductStatus,
  InventoryChangeType,
  CartStatus,
  LegacyPromotionStatus,
  LegacyDiscountType,
  PromotionCampaignOwnerType,
  PromotionCampaignStatus,
  PromotionCampaignVersionStatus,
  PromotionApplicationMethod,
  PromotionDiscountScope,
  PromotionDiscountMechanism,
  PromotionFundingType,
  PromotionTargetType,
  PromotionTargetMode,
  PromotionEligibilityRule,
  PromotionCodeStatus,
  PromotionCodeBatchStatus,
  PromotionReservationStatus,
  PromotionRedemptionStatus,
  PromotionBudgetStatus,
  PromotionBudgetMovementType,
  PromotionRedemptionReusePolicy,
  PromotionReconciliationReason,
  PromotionReconciliationStatus,
  AdPlacementType,
  AdCampaignStatus,
  ReferralOwnerType,
  ReferralTargetType,
  ReferralStatus,
  ApiClientStatus,
  WebhookDeliveryStatus,
  VacancyStatus,
  RecruitmentApplicationStatus,
  NotificationChannel,
  NotificationStatus,
  ReportJobStatus,
} from "@prisma/client";

// Convenience type for a User with their profile loaded.
export type {
  Prisma,
} from "@prisma/client";

export enum PromotionStackingOutcome {
  COMBINABLE = "COMBINABLE",
  EXCLUSIVE = "EXCLUSIVE",
  BEST_VALUE_ONLY = "BEST_VALUE_ONLY",
}

// ─── Phase 26: Recruitment Enums ─────────────────────────────────────────────

export enum RecruitmentTrack {
  INTERNAL_EMPLOYEE = "INTERNAL_EMPLOYEE",
  DRIVER_NETWORK = "DRIVER_NETWORK",
}

export enum RecruitmentPositionFamilyStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  RETIRED = "RETIRED",
}

export enum RecruitmentRequisitionStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  FILLED = "FILLED",
  CLOSED = "CLOSED",
}

export enum RecruitmentOpeningStatus {
  DRAFT = "DRAFT",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  PUBLISHED = "PUBLISHED",
  PAUSED = "PAUSED",
  CLOSED = "CLOSED",
  CANCELLED = "CANCELLED",
  ARCHIVED = "ARCHIVED",
}

export enum RecruitmentVersionStatus {
  DRAFT = "DRAFT",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  PUBLISHED = "PUBLISHED",
  RETIRED = "RETIRED",
}

export enum RecruitmentLocationPolicy {
  ON_SITE = "ON_SITE",
  HYBRID = "HYBRID",
  REMOTE = "REMOTE",
  SERVICE_REGION = "SERVICE_REGION",
}

export enum RecruitmentCompensationDisplayPolicy {
  EXACT = "EXACT",
  RANGE = "RANGE",
  HIDDEN = "HIDDEN",
}

export enum RecruitmentQuestionType {
  SHORT_TEXT = "SHORT_TEXT",
  LONG_TEXT = "LONG_TEXT",
  SINGLE_SELECT = "SINGLE_SELECT",
  MULTI_SELECT = "MULTI_SELECT",
  BOOLEAN = "BOOLEAN",
  DATE = "DATE",
  NUMBER = "NUMBER",
  ADDRESS_REGION = "ADDRESS_REGION",
  LICENCE_TYPE = "LICENCE_TYPE",
  FILE_REFERENCE = "FILE_REFERENCE",
  CONSENT = "CONSENT",
  DECLARATION = "DECLARATION",
}

export enum RecruitmentQuestionClassification {
  IDENTITY = "IDENTITY",
  CONTACT = "CONTACT",
  WORK_AUTHORIZATION = "WORK_AUTHORIZATION",
  EXPERIENCE = "EXPERIENCE",
  QUALIFICATION = "QUALIFICATION",
  ROLE_ELIGIBILITY = "ROLE_ELIGIBILITY",
  DRIVER_CREDENTIAL = "DRIVER_CREDENTIAL",
  AVAILABILITY = "AVAILABILITY",
  ACCOMMODATION = "ACCOMMODATION",
  EMPLOYMENT_EQUITY = "EMPLOYMENT_EQUITY",
  CONSENT = "CONSENT",
}

export enum RecruitmentProfileStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  RESTRICTED = "RESTRICTED",
}

export enum RecruitmentWorkAuthorizationStatus {
  CITIZEN = "CITIZEN",
  PERMANENT_RESIDENT = "PERMANENT_RESIDENT",
  CRITICAL_SKILLS_WORK_PERMIT = "CRITICAL_SKILLS_WORK_PERMIT",
  GENERAL_WORK_PERMIT = "GENERAL_WORK_PERMIT",
  ASYLUM_SEEKER_PERMIT = "ASYLUM_SEEKER_PERMIT",
  SPONSORSHIP_REQUIRED = "SPONSORSHIP_REQUIRED",
  UNAUTHORIZED = "UNAUTHORIZED",
}

export enum RecruitmentAgeEligibilityStatus {
  VERIFIED_ADULT = "VERIFIED_ADULT",
  UNDER_18_APPLICATION_NOT_SUPPORTED = "UNDER_18_APPLICATION_NOT_SUPPORTED",
}

export enum RecruitmentApplicationState {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  COMPLETENESS_REVIEW = "COMPLETENESS_REVIEW",
  ELIGIBILITY_REVIEW = "ELIGIBILITY_REVIEW",
  HUMAN_REVIEW = "HUMAN_REVIEW",
  INTERVIEW = "INTERVIEW",
  CONDITIONAL_CHECKS = "CONDITIONAL_CHECKS",
  OFFER_APPROVAL = "OFFER_APPROVAL",
  OFFERED = "OFFERED",
  OFFER_ACCEPTED = "OFFER_ACCEPTED",
  ONBOARDING_HANDOFF = "ONBOARDING_HANDOFF",
  COMPLETED = "COMPLETED",
  WITHDRAWN = "WITHDRAWN",
  INELIGIBLE_PENDING_CONFIRMATION = "INELIGIBLE_PENDING_CONFIRMATION",
  REJECTED = "REJECTED",
  OFFER_DECLINED = "OFFER_DECLINED",
  OFFER_EXPIRED = "OFFER_EXPIRED",
  OPENING_CANCELLED = "OPENING_CANCELLED",
  DUPLICATE = "DUPLICATE",
  FRAUD_REVIEW = "FRAUD_REVIEW",
  RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED",
}

export enum RecruitmentConsentType {
  APPLICATION_PROCESSING_NOTICE_ACKNOWLEDGEMENT = "APPLICATION_PROCESSING_NOTICE_ACKNOWLEDGEMENT",
  REFERENCE_CHECK = "REFERENCE_CHECK",
  BACKGROUND_CHECK = "BACKGROUND_CHECK",
  CREDIT_CHECK = "CREDIT_CHECK",
  TALENT_POOL = "TALENT_POOL",
  EMPLOYMENT_EQUITY_DECLARATION = "EMPLOYMENT_EQUITY_DECLARATION",
  ACCOMMODATION_PROCESSING = "ACCOMMODATION_PROCESSING",
}

export enum RecruitmentConsentStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  WITHDRAWN = "WITHDRAWN",
  EXPIRED = "EXPIRED",
}

export enum RecruitmentEEDeclarationStatus {
  DECLARED = "DECLARED",
  DECLINED_TO_STATE = "DECLINED_TO_STATE",
  WITHDRAWN = "WITHDRAWN",
}

export enum RecruitmentEEUseMode {
  REPORTING_ONLY = "REPORTING_ONLY",
  LAWFUL_SELECTION_SUPPORT = "LAWFUL_SELECTION_SUPPORT",
}

export enum RecruitmentEmployerDesignationStatus {
  UNKNOWN = "UNKNOWN",
  NON_DESIGNATED = "NON_DESIGNATED",
  DESIGNATED = "DESIGNATED",
}

export enum RecruitmentScreeningOutcome {
  PASS = "PASS",
  REVIEW_REQUIRED = "REVIEW_REQUIRED",
  POTENTIAL_INELIGIBILITY = "POTENTIAL_INELIGIBILITY",
  INCOMPLETE = "INCOMPLETE",
}

export enum RecruitmentReviewAssignmentType {
  INITIAL_REVIEW = "INITIAL_REVIEW",
  HIRING_MANAGER_REVIEW = "HIRING_MANAGER_REVIEW",
  TECHNICAL_REVIEW = "TECHNICAL_REVIEW",
  DRIVER_OPERATIONS_REVIEW = "DRIVER_OPERATIONS_REVIEW",
  COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW",
  OFFER_APPROVAL = "OFFER_APPROVAL",
}

export enum RecruitmentReviewAssignmentStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CONFLICT_DECLARED = "CONFLICT_DECLARED",
  CANCELLED = "CANCELLED",
}

export enum RecruitmentRubricCriteriaCategory {
  ESSENTIAL_REQUIREMENT = "ESSENTIAL_REQUIREMENT",
  DESIRABLE_REQUIREMENT = "DESIRABLE_REQUIREMENT",
  EXPERIENCE = "EXPERIENCE",
  ROLE_KNOWLEDGE = "ROLE_KNOWLEDGE",
  OPERATIONAL_JUDGEMENT = "OPERATIONAL_JUDGEMENT",
  COMMUNICATION = "COMMUNICATION",
  SAFETY = "SAFETY",
  DRIVER_CREDENTIAL_READINESS = "DRIVER_CREDENTIAL_READINESS",
}

export enum RecruitmentDecisionType {
  PROGRESS = "PROGRESS",
  HOLD = "HOLD",
  REQUEST_INFORMATION = "REQUEST_INFORMATION",
  CONFIRM_INELIGIBILITY = "CONFIRM_INELIGIBILITY",
  REJECT = "REJECT",
  APPROVE_OFFER = "APPROVE_OFFER",
  CANCEL = "CANCEL",
}

export enum RecruitmentInterviewType {
  PHONE = "PHONE",
  VIDEO = "VIDEO",
  IN_PERSON = "IN_PERSON",
  PRACTICAL = "PRACTICAL",
  DRIVING_ASSESSMENT = "DRIVING_ASSESSMENT",
  TECHNICAL = "TECHNICAL",
  PANEL = "PANEL",
}

export enum RecruitmentInterviewStatus {
  PLANNED = "PLANNED",
  SLOTS_OFFERED = "SLOTS_OFFERED",
  SCHEDULED = "SCHEDULED",
  RESCHEDULE_REQUESTED = "RESCHEDULE_REQUESTED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  NO_SHOW = "NO_SHOW",
}

export enum RecruitmentScorecardDecision {
  STRONG_RECOMMEND = "STRONG_RECOMMEND",
  RECOMMEND = "RECOMMEND",
  NEUTRAL = "NEUTRAL",
  DO_NOT_RECOMMEND = "DO_NOT_RECOMMEND",
}

export enum RecruitmentAccommodationStatus {
  REQUESTED = "REQUESTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED_PROVIDED = "APPROVED_PROVIDED",
  CANNOT_ACCOMMODATE_SAFELY = "CANNOT_ACCOMMODATE_SAFELY",
  WITHDRAWN = "WITHDRAWN",
}

export enum RecruitmentCheckType {
  IDENTITY = "IDENTITY",
  WORK_AUTHORIZATION = "WORK_AUTHORIZATION",
  QUALIFICATION = "QUALIFICATION",
  EMPLOYMENT_REFERENCE = "EMPLOYMENT_REFERENCE",
  DRIVING_LICENCE = "DRIVING_LICENCE",
  PROFESSIONAL_DRIVING_PERMIT = "PROFESSIONAL_DRIVING_PERMIT",
  VEHICLE_DOCUMENT = "VEHICLE_DOCUMENT",
  ROLE_RELATED_CRIMINAL = "ROLE_RELATED_CRIMINAL",
  ROLE_RELATED_CREDIT = "ROLE_RELATED_CREDIT",
  ROLE_REQUIRED_MEDICAL_FITNESS = "ROLE_REQUIRED_MEDICAL_FITNESS",
  APPROVED_PSYCHOMETRIC = "APPROVED_PSYCHOMETRIC",
}

export enum RecruitmentCheckCaseStatus {
  NOT_REQUIRED = "NOT_REQUIRED",
  CONSENT_REQUIRED = "CONSENT_REQUIRED",
  READY = "READY",
  REQUESTED = "REQUESTED",
  IN_PROGRESS = "IN_PROGRESS",
  PASSED = "PASSED",
  REVIEW_REQUIRED = "REVIEW_REQUIRED",
  FAILED = "FAILED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
  RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED",
}

export enum RecruitmentMedicalPolicyStatus {
  REQUIREMENT_SATISFIED = "REQUIREMENT_SATISFIED",
  REVIEW_REQUIRED = "REVIEW_REQUIRED",
  REQUIREMENT_NOT_SATISFIED = "REQUIREMENT_NOT_SATISFIED",
  EXPIRED = "EXPIRED",
}

export enum RecruitmentOfferStatus {
  DRAFT = "DRAFT",
  UNDER_APPROVAL = "UNDER_APPROVAL",
  APPROVED = "APPROVED",
  ISSUED = "ISSUED",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  EXPIRED = "EXPIRED",
  WITHDRAWN = "WITHDRAWN",
  SUPERSEDED = "SUPERSEDED",
}

export enum RecruitmentHandoffTargetType {
  EMPLOYEE = "EMPLOYEE",
  DRIVER = "DRIVER",
}

export enum RecruitmentHandoffStatus {
  PENDING = "PENDING",
  READY = "READY",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED",
}

export enum RecruitmentDataRequestType {
  ACCESS = "ACCESS",
  CORRECTION = "CORRECTION",
  DELETION = "DELETION",
  RESTRICTION = "RESTRICTION",
  CONSENT_WITHDRAWAL = "CONSENT_WITHDRAWAL",
  TALENT_POOL_WITHDRAWAL = "TALENT_POOL_WITHDRAWAL",
}

export enum RecruitmentDataRequestStatus {
  SUBMITTED = "SUBMITTED",
  IN_REVIEW = "IN_REVIEW",
  FULFILLED = "FULFILLED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

export enum RecruitmentFraudOutcome {
  PASS = "PASS",
  REVIEW = "REVIEW",
  BLOCK_SUBMISSION = "BLOCK_SUBMISSION",
  BLOCK_DECISION = "BLOCK_DECISION",
  BLOCK_OFFER = "BLOCK_OFFER",
  BLOCK_HANDOFF = "BLOCK_HANDOFF",
}

export enum RecruitmentReconciliationReason {
  OPENING_WITHOUT_APPROVED_REQUISITION = "OPENING_WITHOUT_APPROVED_REQUISITION",
  PUBLISHED_MUTABLE_OPENING_VERSION = "PUBLISHED_MUTABLE_OPENING_VERSION",
  APPLICATION_WITHOUT_FROZEN_VERSION = "APPLICATION_WITHOUT_FROZEN_VERSION",
  APPLICATION_SUBMITTED_INCOMPLETE = "APPLICATION_SUBMITTED_INCOMPLETE",
  DECISION_WITHOUT_HUMAN_REVIEWER = "DECISION_WITHOUT_HUMAN_REVIEWER",
  REJECTION_WITHOUT_SCORECARD = "REJECTION_WITHOUT_SCORECARD",
  INTERVIEW_WITHOUT_APPROVED_PLAN = "INTERVIEW_WITHOUT_APPROVED_PLAN",
  CHECK_WITHOUT_POLICY = "CHECK_WITHOUT_POLICY",
  CHECK_WITHOUT_REQUIRED_CONSENT = "CHECK_WITHOUT_REQUIRED_CONSENT",
  OFFER_WITHOUT_APPROVAL = "OFFER_WITHOUT_APPROVAL",
  OFFER_EXCEEDS_APPROVED_HEADCOUNT = "OFFER_EXCEEDS_APPROVED_HEADCOUNT",
  ACCEPTANCE_VERSION_MISMATCH = "ACCEPTANCE_VERSION_MISMATCH",
  HANDOFF_WITHOUT_ACCEPTED_OFFER = "HANDOFF_WITHOUT_ACCEPTED_OFFER",
  EMPLOYEE_HANDOFF_MISMATCH = "EMPLOYEE_HANDOFF_MISMATCH",
  DRIVER_HANDOFF_MISMATCH = "DRIVER_HANDOFF_MISMATCH",
  RETENTION_POLICY_MISMATCH = "RETENTION_POLICY_MISMATCH",
  SPECIAL_INFORMATION_ACCESS_VIOLATION = "SPECIAL_INFORMATION_ACCESS_VIOLATION",
  APPLICATION_FAILURE = "APPLICATION_FAILURE",
}

export enum RecruitmentReconciliationStatus {
  OPEN = "OPEN",
  MONITORING = "MONITORING",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}


