export type MarketplaceCheckoutErrorCode =
  | "CART_NOT_FOUND" | "CART_ACCESS_DENIED" | "CART_VERSION_CONFLICT" | "CART_OPERATION_CONFLICT"
  | "CART_MUTATION_NOT_ALLOWED" | "CART_LINE_INVALID" | "CHECKOUT_NOT_FOUND" | "CHECKOUT_ACCESS_DENIED"
  | "CHECKOUT_VERSION_CONFLICT" | "CHECKOUT_OPERATION_CONFLICT" | "CHECKOUT_REVIEW_REQUIRED"
  | "CHECKOUT_CHANGES_UNACKNOWLEDGED" | "PRODUCTION_LOCKED" | "PAYMENT_PREPARATION_BLOCKED"
  | "SELLER_IDENTITY_INCOMPLETE" | "SELLER_IDENTITY_VERSION_INVALID"
  | "COMMISSION_PLAN_MISSING" | "COMMISSION_PLAN_NOT_APPROVED" | "COMMISSION_PLAN_VERSION_INVALID"
  | "SETTLEMENT_BASIS_INVALID" | "SETTLEMENT_ALLOCATION_MISMATCH"
  | "DELIVERY_FEE_INCLUDED_IN_SELLER_BASIS" | "LINE_ALLOCATION_ROUNDING_MISMATCH"
  | "SELLER_SETTLEMENT_EVIDENCE_INCOMPLETE";

export class MarketplaceCheckoutError extends Error {
  constructor(readonly code: MarketplaceCheckoutErrorCode, message: string) {
    super(message);
    this.name = "MarketplaceCheckoutError";
  }
}
