import { phase5Reference, phase5Repository, safeOperationalText } from "@/lib/operations/phase5-repository";
import { recordAdminActivity } from "@/lib/services/admin-activity.service";
import { safeSensitiveMetadata } from "./sensitive-data.service";
export class ProviderGovernanceError extends Error { constructor(readonly code: string) { super(code); } }
const statuses: Record<string, string[]> = { PENDING_REVIEW: ["ACTIVE", "DISABLED", "REVIEW_REQUIRED"], REVIEW_REQUIRED: ["ACTIVE", "DISABLED"], ACTIVE: ["INACTIVE", "REVIEW_REQUIRED", "DISABLED"], INACTIVE: ["ACTIVE", "DISABLED"], DISABLED: [] };
export async function listProviderGovernance() { return phase5Repository.providerPrivacyGovernance.findMany({ orderBy: { createdAt: "desc" }, take: 200 }); }
export async function getProviderGovernance(publicReference: string) { const record = await phase5Repository.providerPrivacyGovernance.findUnique({ where: { publicReference } }); if (!record) throw new ProviderGovernanceError("PROVIDER_GOVERNANCE_NOT_FOUND"); const dataClasses = await phase5Repository.providerPrivacyDataClass.findMany({ where: { providerGovernanceId: String(record.id) }, take: 50 }); return { ...record, dataClasses }; }
export async function updateProviderGovernance(input: { actorUserId: string; publicReference: string; documentationReference?: string; safeNotes?: string; regionMetadata?: Record<string, unknown>; capabilityState?: string }) { const record = await phase5Repository.providerPrivacyGovernance.findUnique({ where: { publicReference: input.publicReference } }); if (!record) throw new ProviderGovernanceError("PROVIDER_GOVERNANCE_NOT_FOUND"); const updated = await phase5Repository.providerPrivacyGovernance.update({ where: { id: String(record.id) }, data: { documentationReference: input.documentationReference ? safeOperationalText(input.documentationReference, 200) : record.documentationReference, safeNotes: input.safeNotes ? safeOperationalText(input.safeNotes, 512) : record.safeNotes, regionMetadata: input.regionMetadata ? safeSensitiveMetadata(input.regionMetadata) : record.regionMetadata, capabilityState: input.capabilityState ? safeOperationalText(input.capabilityState, 80) : record.capabilityState } }); await recordAdminActivity({ actorUserId: input.actorUserId, action: "UPDATE", entityType: "ProviderPrivacyGovernance", entityId: String(record.id), message: "Updated safe provider governance metadata", metadata: { providerCode: record.providerCode } }); return updated; }
export async function registerProviderGovernance(input: { actorUserId: string; providerCode: string; providerCategory: string; servicePurpose: string; processingRole: string; capabilityState?: string; regionMetadata?: Record<string, unknown>; documentationReference?: string; safeNotes?: string; sensitiveDataClassIds: string[] }) { const versioned = await phase5Repository.providerPrivacyGovernance.findMany({ where: { providerCode: input.providerCode }, orderBy: { effectiveVersion: "desc" }, take: 1 }); const record = await phase5Repository.providerPrivacyGovernance.create({ data: { publicReference: phase5Reference("PPG"), providerCode: safeOperationalText(input.providerCode, 80), providerCategory: safeOperationalText(input.providerCategory, 80), servicePurpose: safeOperationalText(input.servicePurpose, 80), processingRole: safeOperationalText(input.processingRole, 80), capabilityState: safeOperationalText(input.capabilityState ?? "NOT_CONFIGURED", 80), regionMetadata: input.regionMetadata ? safeSensitiveMetadata(input.regionMetadata) : null, documentationReference: input.documentationReference ? safeOperationalText(input.documentationReference, 200) : null, safeNotes: input.safeNotes ? safeOperationalText(input.safeNotes, 512) : null, effectiveVersion: Number(versioned[0]?.effectiveVersion ?? 0) + 1 } }); for (const sensitiveDataClassId of input.sensitiveDataClassIds.slice(0, 20)) await phase5Repository.providerPrivacyDataClass.create({ data: { providerGovernanceId: String(record.id), sensitiveDataClassId } }); await recordAdminActivity({ actorUserId: input.actorUserId, action: "CREATE", entityType: "ProviderPrivacyGovernance", entityId: String(record.id), message: "Registered provider governance metadata", metadata: { providerCode: record.providerCode, dataClassCount: input.sensitiveDataClassIds.length } }); return record; }
export async function transitionProviderReview(input: { actorUserId: string; publicReference: string; nextStatus: string; operationId: string; safeNote?: string }) { const record = await phase5Repository.providerPrivacyGovernance.findUnique({ where: { publicReference: input.publicReference } }); if (!record) throw new ProviderGovernanceError("PROVIDER_GOVERNANCE_NOT_FOUND"); if (!statuses[String(record.governanceStatus)]?.includes(input.nextStatus)) throw new ProviderGovernanceError("PROVIDER_REVIEW_REQUIRED"); const updated = await phase5Repository.providerPrivacyGovernance.update({ where: { id: String(record.id) }, data: { governanceStatus: input.nextStatus, reviewedAt: new Date(), reviewedByUserId: input.actorUserId, safeNotes: input.safeNote ? safeOperationalText(input.safeNote, 512) : record.safeNotes } }); await recordAdminActivity({ actorUserId: input.actorUserId, action: "STATUS_CHANGE", entityType: "ProviderPrivacyGovernance", entityId: String(record.id), message: "Reviewed provider governance record", metadata: { operationId: input.operationId, nextStatus: input.nextStatus } }); return updated; }
