"use client";

import { useState } from "react";

export function FinanceWithdrawalActions({ id, status, payoutAttemptReference, canReview, canApprove, canProcess, completionLocked }: Readonly<{ id: string; status: string; payoutAttemptReference: string | null; canReview: boolean; canApprove: boolean; canProcess: boolean; completionLocked: boolean }>) {
  const [externalPayoutReference, setExternalPayoutReference] = useState(""); const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false);
  async function post(path: string, body: Record<string, string>) { setPending(true); setMessage(null); try { const response = await fetch(`/api/admin/withdrawals/${id}/${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ operationId: crypto.randomUUID(), ...body }) }); const payload = await response.json() as { error?: string }; setMessage(response.ok ? "Action recorded. Refresh to view the updated immutable history." : payload.error ?? "Action could not be recorded."); } catch { setMessage("Action could not be recorded."); } finally { setPending(false); } }
  return <section aria-label="Finance withdrawal actions" className="space-y-3"><h2 className="text-lg font-semibold">Finance actions</h2>
    {(status === "REQUESTED" && canReview) && <button disabled={pending} onClick={() => post("review", {})} className="rounded border px-3 py-2">Start review</button>}
    {(status === "REQUESTED" || status === "UNDER_REVIEW") && <>{canApprove ? <button disabled={pending} onClick={() => post("approve", {})} className="ml-2 rounded border px-3 py-2">Approve</button> : null}{canReview ? <button disabled={pending} onClick={() => post("reject", { reasonCode: "FINANCE_REJECTED" })} className="ml-2 rounded border px-3 py-2">Reject and release</button> : null}</>}
    {status === "APPROVED" && canProcess ? <button disabled={pending} onClick={() => post("start-processing", {})} className="rounded border px-3 py-2">Start payout processing</button> : null}
    {status === "PROCESSING" && payoutAttemptReference && canProcess ? <><button disabled={pending} onClick={() => post("payout-failed", { payoutAttemptPublicReference: payoutAttemptReference, failureCategory: "OPERATOR_CONFIRMED", failureCode: "NO_EXTERNAL_PAYOUT" })} className="rounded border px-3 py-2">Record definite failure</button><button disabled={pending} onClick={() => post("payout-unknown", { payoutAttemptPublicReference: payoutAttemptReference })} className="ml-2 rounded border px-3 py-2">Record unknown outcome</button>{completionLocked ? <p role="status" className="mt-3 text-sm text-amber-800">Payout completion is inactive pending consolidated validation approval.</p> : <div className="mt-3"><label htmlFor="external-payout-reference" className="block text-sm font-medium">Verified external payout reference</label><input id="external-payout-reference" value={externalPayoutReference} onChange={(event) => setExternalPayoutReference(event.target.value)} placeholder="manual-bank:opaque-reference" className="mt-1 rounded border p-2" /><button disabled={pending || !externalPayoutReference} onClick={() => post("complete-payout", { payoutAttemptPublicReference: payoutAttemptReference, externalPayoutReference })} className="ml-2 rounded bg-slate-900 px-3 py-2 text-white">Record verified payout</button></div>}</> : null}
    {message ? <p role="status" className="text-sm">{message}</p> : null}
  </section>;
}
