"use client";

import { useState } from "react";

export function PayoutDestinationCreateForm() {
  const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/admin/payout-destinations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ownerType: form.get("ownerType"), ownerId: form.get("ownerId"), externalReference: form.get("externalReference"), maskedLabel: form.get("maskedLabel"), institutionName: form.get("institutionName") || undefined, accountLast4: form.get("accountLast4") || undefined, countryCode: form.get("countryCode") || undefined, operationId: crypto.randomUUID() }) }); const payload = await response.json() as { error?: string }; setMessage(response.ok ? "Payout destination registered for review." : payload.error ?? "Destination could not be registered."); } catch { setMessage("Destination could not be registered."); } finally { setPending(false); } }
  return <form onSubmit={submit} className="space-y-3" aria-label="Register payout destination"><h2 className="text-lg font-semibold">Register opaque payout destination</h2><div className="grid gap-3 md:grid-cols-2"><div><label htmlFor="destination-owner-type">Owner type</label><select id="destination-owner-type" name="ownerType" className="mt-1 w-full rounded border p-2"><option>STORE</option><option>DRIVER</option><option>PROMOTER</option></select></div><div><label htmlFor="destination-owner-id">Owner reference</label><input id="destination-owner-id" name="ownerId" required className="mt-1 w-full rounded border p-2" /></div><div><label htmlFor="destination-external-reference">Opaque external reference</label><input id="destination-external-reference" name="externalReference" placeholder="manual-finance:opaque-reference" required className="mt-1 w-full rounded border p-2" /></div><div><label htmlFor="destination-masked-label">Masked label</label><input id="destination-masked-label" name="maskedLabel" required className="mt-1 w-full rounded border p-2" /></div><div><label htmlFor="destination-institution">Institution name (optional)</label><input id="destination-institution" name="institutionName" className="mt-1 w-full rounded border p-2" /></div><div><label htmlFor="destination-last-four">Last four (optional)</label><input id="destination-last-four" name="accountLast4" maxLength={4} className="mt-1 w-full rounded border p-2" /></div></div><p className="text-xs text-slate-600">Do not enter account numbers, credentials, or bank documents. The external financial system remains the source of sensitive details.</p><button type="submit" disabled={pending} className="rounded bg-slate-900 px-3 py-2 text-white">{pending ? "Registering…" : "Register destination"}</button>{message ? <p role="status">{message}</p> : null}</form>;
}

export function PayoutDestinationStatusActions({ publicReference, status }: Readonly<{ publicReference: string; status: string }>) {
  const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false);
  async function act(action: "activate" | "suspend" | "revoke") { setPending(true); try { const response = await fetch(`/api/admin/payout-destinations/${publicReference}/${action}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ operationId: crypto.randomUUID() }) }); const payload = await response.json() as { error?: string }; setMessage(response.ok ? `Destination ${action} action recorded. Refresh to inspect current status.` : payload.error ?? "Destination action failed."); } catch { setMessage("Destination action failed."); } finally { setPending(false); } }
  return <section aria-label="Payout destination actions" className="space-y-2"><h2 className="text-lg font-semibold">Destination actions</h2>{status !== "ACTIVE" && status !== "REVOKED" ? <button disabled={pending} onClick={() => act("activate")} className="rounded border px-3 py-2">Activate</button> : null}{status === "ACTIVE" ? <button disabled={pending} onClick={() => act("suspend")} className="rounded border px-3 py-2">Suspend</button> : null}{status !== "REVOKED" ? <button disabled={pending} onClick={() => act("revoke")} className="ml-2 rounded border px-3 py-2">Revoke</button> : null}{message ? <p role="status">{message}</p> : null}</section>;
}
