-- Phase B ENG-PRIV-009/010 and ENG-POLICY-001/002 safe metadata authorities.
CREATE TABLE "SensitiveDataClass" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "classificationLevel" TEXT NOT NULL, "storageRequirement" TEXT NOT NULL, "loggingRule" TEXT NOT NULL, "retentionDataClass" TEXT, "accessAuditRequired" BOOLEAN NOT NULL DEFAULT false, "exportable" BOOLEAN NOT NULL DEFAULT false, "allowedPurposes" JSONB NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SensitiveDataClass_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "SensitiveDataClass_code_key" ON "SensitiveDataClass"("code");
CREATE TABLE "SensitiveDataResourceMapping" ("id" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceField" TEXT, "sensitiveDataClassId" TEXT NOT NULL, "purpose" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SensitiveDataResourceMapping_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "SensitiveDataResourceMapping_resourceType_resourceField_sensitiveDataClassId_key" ON "SensitiveDataResourceMapping"("resourceType", "resourceField", "sensitiveDataClassId");
CREATE INDEX "SensitiveDataResourceMapping_sensitiveDataClassId_idx" ON "SensitiveDataResourceMapping"("sensitiveDataClassId");
CREATE TABLE "ProviderPrivacyGovernance" ("id" TEXT NOT NULL, "publicReference" TEXT NOT NULL, "providerCode" TEXT NOT NULL, "providerCategory" TEXT NOT NULL, "servicePurpose" TEXT NOT NULL, "processingRole" TEXT NOT NULL, "governanceStatus" TEXT NOT NULL DEFAULT 'PENDING_REVIEW', "capabilityState" TEXT NOT NULL DEFAULT 'NOT_CONFIGURED', "regionMetadata" JSONB, "documentationReference" TEXT, "safeNotes" TEXT, "reviewedAt" TIMESTAMP(3), "reviewedByUserId" TEXT, "nextReviewAt" TIMESTAMP(3), "effectiveVersion" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProviderPrivacyGovernance_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ProviderPrivacyGovernance_publicReference_key" ON "ProviderPrivacyGovernance"("publicReference"); CREATE UNIQUE INDEX "ProviderPrivacyGovernance_providerCode_effectiveVersion_key" ON "ProviderPrivacyGovernance"("providerCode", "effectiveVersion"); CREATE INDEX "ProviderPrivacyGovernance_providerCode_governanceStatus_idx" ON "ProviderPrivacyGovernance"("providerCode", "governanceStatus");
CREATE TABLE "ProviderPrivacyDataClass" ("id" TEXT NOT NULL, "providerGovernanceId" TEXT NOT NULL, "sensitiveDataClassId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProviderPrivacyDataClass_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "ProviderPrivacyDataClass_providerGovernanceId_sensitiveDataClassId_key" ON "ProviderPrivacyDataClass"("providerGovernanceId", "sensitiveDataClassId");
CREATE TABLE "PolicyRuntimeLink" ("id" TEXT NOT NULL, "legalDocumentVersionId" TEXT NOT NULL, "runtimeDomain" TEXT NOT NULL, "runtimeReference" TEXT NOT NULL, "runtimeVersion" TEXT NOT NULL, "createdByUserId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PolicyRuntimeLink_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "PolicyRuntimeLink_legalDocumentVersionId_runtimeDomain_runtimeReference_runtimeVersion_key" ON "PolicyRuntimeLink"("legalDocumentVersionId", "runtimeDomain", "runtimeReference", "runtimeVersion"); CREATE INDEX "PolicyRuntimeLink_runtimeDomain_runtimeReference_idx" ON "PolicyRuntimeLink"("runtimeDomain", "runtimeReference");
ALTER TABLE "SensitiveDataResourceMapping" ADD CONSTRAINT "SensitiveDataResourceMapping_sensitiveDataClassId_fkey" FOREIGN KEY ("sensitiveDataClassId") REFERENCES "SensitiveDataClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProviderPrivacyDataClass" ADD CONSTRAINT "ProviderPrivacyDataClass_providerGovernanceId_fkey" FOREIGN KEY ("providerGovernanceId") REFERENCES "ProviderPrivacyGovernance"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ProviderPrivacyDataClass" ADD CONSTRAINT "ProviderPrivacyDataClass_sensitiveDataClassId_fkey" FOREIGN KEY ("sensitiveDataClassId") REFERENCES "SensitiveDataClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
