import { afterAll, describe, expect, it } from "vitest";
import { PaymentProviderRegistry } from "@/lib/payments/providers/payment-provider-registry";
import { prepareOrderPayment } from "@/lib/services/payment-preparation.service";
import { createProviderCheckoutSession } from "@/lib/services/payment-provider-session.service";
import { FakePaymentProvider } from "../payments/fake-payment-provider";
import { createPayableOrder, paymentPrisma, testCallbackUrls } from "./payment-fixtures";
afterAll(async () => paymentPrisma.$disconnect());
describe("Phase 10 live payment concurrency and rollback", () => {
  it("allocates no duplicate number/reference during concurrent distinct commands", async () => { const fixture = await createPayableOrder(); const payment = await prepareOrderPayment({ id: fixture.user.id, email: fixture.user.email }, { orderId: fixture.order.id, idempotencyKey: `${fixture.tag}:prepare` }); const registry = new PaymentProviderRegistry({ adapters: [new FakePaymentProvider("failure")] }); const first = await createProviderCheckoutSession({ id: fixture.user.id }, { paymentId: payment.id, provider: "PAYFAST", idempotencyKey: `${fixture.tag}:first` }, { registry, callbackUrls: testCallbackUrls }); expect(first.paymentStatus).toBe("FAILED"); const retryRegistry = new PaymentProviderRegistry({ adapters: [new FakePaymentProvider("processing")] }); const settled = await Promise.allSettled([1, 2].map((number) => createProviderCheckoutSession({ id: fixture.user.id }, { paymentId: payment.id, provider: "PAYFAST", idempotencyKey: `${fixture.tag}:retry:${number}` }, { registry: retryRegistry, callbackUrls: testCallbackUrls }))); expect(settled.filter((entry) => entry.status === "fulfilled")).toHaveLength(1); const attempts = await paymentPrisma.paymentAttempt.findMany({ where: { paymentId: payment.id } }); expect(new Set(attempts.map((entry) => entry.attemptNumber)).size).toBe(attempts.length); expect(new Set(attempts.map((entry) => entry.merchantReference)).size).toBe(attempts.length); });
  it("does not consume a reservation when its transaction rolls back", async () => { const fixture = await createPayableOrder(); const payment = await prepareOrderPayment({ id: fixture.user.id, email: fixture.user.email }, { orderId: fixture.order.id, idempotencyKey: `${fixture.tag}:prepare` }); await paymentPrisma.payment.update({ where: { id: payment.id }, data: { provider: "PAYFAST" } }); await expect(paymentPrisma.$transaction(async (tx) => { await tx.paymentAttempt.create({ data: { paymentId: payment.id, attemptNumber: 1, provider: "PAYFAST", idempotencyKey: `${fixture.tag}:rollback`, requestHash: "a".repeat(64), merchantReference: `kt:payment:${payment.publicReference}:attempt:1`, status: "RESERVED", amount: "115.00", currency: "ZAR" } }); throw new Error("injected reservation rollback"); })).rejects.toThrow("injected reservation rollback"); expect(await paymentPrisma.paymentAttempt.count({ where: { idempotencyKey: `${fixture.tag}:rollback` } })).toBe(0); });
});

