import { createHash, randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { prisma } from "../../lib/db/prisma";
import { ExistingPhaseFinancialAdjustmentAuthority } from "../../lib/store-orders/financial-adjustment-composition";
import { confirmStoreOrderLineAvailability, applyMarketplaceStoreOrderAdjustment } from "../../lib/store-orders/store-order.service";
import { reverseCommissionInTransaction, reverseCommissionAccrual } from "../../lib/services/commission-reversal.service";
import { adjustStoreEarningInTransaction } from "../../lib/services/store-earning-reversal.service";
import { createRefundRequest } from "../../lib/services/refund-request.service";
import { approveRefund } from "../../lib/services/refund-finance-review.service";
import { startProviderRefund } from "../../lib/services/refund-provider-execution.service";
import { prepareStoreOrder } from "../e2e/fixtures/store-order";
import { withCanonicalBrowser } from "./marketplace-canonical-support";
import { assertCanonicalRefundDatabase, CanonicalOfflineRefundClient, refundActors, protectedRefundState, assertJournalMoney } from "./refund-canonical-support";
import { RefundProviderRegistry } from "../../lib/refunds/providers/refund-provider-registry";
import { PaystackRefundAdapter } from "../../lib/refunds/providers/paystack/paystack-refund-adapter";
import { assertDisposablePaystackAcceptance } from "../../lib/testing/disposable-paystack-policy";

describe("canonical settled-store financial reversal recovery", () => {
  it("persists bounded reversals before the refund lock, retries without duplicate money and recovers through one canonical reservation and payout", async () => {
    await withCanonicalBrowser(async page => {
      await assertCanonicalRefundDatabase();
      const f = await prepareStoreOrder(page, "pg-financial-recovery", 390);
      const actors = await refundActors();
      const owner = await prisma.user.findUniqueOrThrow({ where: { email: "e2e-store@ktcouriers.local" } });
      const source = await prisma.payment.findUniqueOrThrow({ where: { id: f.snapshot.payment.id }, include: { successfulAttempt: true } });
      const command = () => { const operationId = randomUUID(); return { actorUserId: owner.id, storeOrderReference: f.storeReference, operationId, requestHash: createHash("sha256").update(operationId).digest("hex") }; };
      await confirmStoreOrderLineAvailability({ ...command(), orderLineId: f.baseline.lines[0].id, availableQuantity: 0 });
      const adjustment = await prisma.marketplaceStoreOrderAdjustment.findFirstOrThrow({ where: { marketplaceStoreOrderId: f.order.storeOrders[0].id } });
      const snapshot = await prisma.marketplaceSettlementSnapshot.findFirstOrThrow({ where: { marketplaceStoreOrderId: f.order.storeOrders[0].id, status: "COMPLETED" } });
      const accrual = await prisma.commissionAccrual.findUniqueOrThrow({ where: { publicReference: snapshot.commissionAccrualReference! }, include: { allocations: { orderBy: { publicReference: "asc" } } } });
      const earning = await prisma.storeEarning.findUniqueOrThrow({ where: { publicReference: snapshot.storeEarningReference! } });
      const balances = () => prisma.ledgerAccount.findMany({ where: { id: { in: [...accrual.allocations.map(a => a.ledgerAccountId), earning.payableAccountId] } }, select: { id: true, currentBalance: true }, orderBy: { id: "asc" } });
      const operation = { ...command(), adjustmentReference: adjustment.publicReference };
      await expect(applyMarketplaceStoreOrderAdjustment(operation)).rejects.toMatchObject({ code: "REFUND_PRODUCTION_NOT_READY" });
      const committed = await prisma.marketplaceStoreOrderAdjustment.findUniqueOrThrow({ where: { id: adjustment.id } });
      expect(committed.status).toBe("RECONCILIATION_REQUIRED");
      const evidence = (committed.financialEvidence as { phase21CommittedReversals: { commissionReversalReferences: string[]; storeEarningReversalReference: string; operationId: string } }).phase21CommittedReversals;
      expect(evidence.operationId).toBe(operation.operationId); expect(evidence.commissionReversalReferences).toHaveLength(accrual.allocations.filter(a => a.amount.greaterThan(0)).length);
      const references = [...evidence.commissionReversalReferences, evidence.storeEarningReversalReference];
      const journals = await prisma.ledgerJournal.findMany({ where: { reference: { in: references } }, include: { entries: true }, orderBy: { reference: "asc" } });
      expect(journals).toHaveLength(references.length);
      expect(journals.every(j => j.totalDebits.equals(j.totalCredits))).toBe(true);
      const reversalTotal = journals.reduce((sum, j) => sum.add(j.totalDebits), new Prisma.Decimal(0));
      expect(reversalTotal.equals(adjustment.refundAmount)).toBe(true);
      expect((await prisma.storeEarning.findUniqueOrThrow({ where: { id: earning.id } })).reversedAmount.equals(earning.amount)).toBe(true);
      expect(await prisma.paymentRefund.count({ where: { paymentId: source.id } })).toBe(0);
      const after = await balances();
      const allocation = accrual.allocations.find(a => a.amount.greaterThan(0))!;
      const commissionOriginal = { accrualPublicReference: accrual.publicReference, allocationPublicReference: allocation.publicReference, originalAmount: allocation.amount.toFixed(2), previouslyReversedAmount: "0.00" };
      const commissionOperation = { operationId: `${operation.operationId}:commission:${allocation.publicReference}`, reasonCode: "MARKETPLACE_STORE_ADJUSTMENT" };
      const earningOriginal = { publicReference: earning.publicReference, originalSellerBasis: earning.settlementBasisAmount.toFixed(2), originalCommission: earning.attributedCommissionAmount.toFixed(2), originalAmount: earning.amount.toFixed(2), previouslyAdjustedAmount: "0.00" };
      const earningDelta = { sellerBasisAmount: earning.settlementBasisAmount.toFixed(2), commissionAmount: earning.attributedCommissionAmount.toFixed(2), storeEarningAmount: earning.amount.toFixed(2) };
      const earningOperation = { operationId: `${operation.operationId}:store-earning`, reasonCode: "MARKETPLACE_STORE_ADJUSTMENT" };
      expect((await prisma.$transaction(tx => reverseCommissionInTransaction(tx, commissionOriginal, { amount: allocation.amount.toFixed(2) }, commissionOperation))).replayed).toBe(true);
      expect((await prisma.$transaction(tx => adjustStoreEarningInTransaction(tx, earningOriginal, earningDelta, earningOperation))).replayed).toBe(true);
      await expect(prisma.$transaction(tx => reverseCommissionInTransaction(tx, commissionOriginal, { amount: allocation.amount.toFixed(2) }, { ...commissionOperation, actorUserId: actors.approver.id }))).rejects.toMatchObject({ code: "LEDGER_IDEMPOTENCY_CONFLICT" });
      await expect(prisma.$transaction(tx => adjustStoreEarningInTransaction(tx, earningOriginal, earningDelta, { ...earningOperation, actorUserId: actors.approver.id }))).rejects.toMatchObject({ code: "LEDGER_IDEMPOTENCY_CONFLICT" });
      expect(await balances()).toEqual(after);
      await expect(applyMarketplaceStoreOrderAdjustment({ ...command(), adjustmentReference: adjustment.publicReference })).rejects.toMatchObject({ code: "REFUND_PRODUCTION_NOT_READY" });
      expect(await balances()).toEqual(after);
      expect(await prisma.ledgerJournal.findMany({ where: { reference: { in: references } }, include: { entries: true }, orderBy: { reference: "asc" } })).toEqual(journals);
      expect((await prisma.storeEarning.findUniqueOrThrow({ where: { id: earning.id } })).reversedAmount.equals(earning.amount)).toBe(true);
      expect(await prisma.marketplaceStoreOrderReconciliationCase.count({ where: { marketplaceStoreOrderId: f.order.storeOrders[0].id, reasonCode: "FINANCIAL_COMPOSITION_FAILED" } })).toBe(2);
      const client = new CanonicalOfflineRefundClient(source.successfulAttempt!.providerReference!);
      const registry = new RefundProviderRegistry([new PaystackRefundAdapter(client)]);
      const dependencies = { assertProductionReady: () => assertDisposablePaystackAcceptance(), providerRegistry: registry, registry };
      const recover = { ...command(), adjustmentReference: adjustment.publicReference, dependencies: { financialAuthority: new ExistingPhaseFinancialAdjustmentAuthority(dependencies) } };
      const recovered = await applyMarketplaceStoreOrderAdjustment(recover);
      expect(recovered).toMatchObject({ financialStatus: "REFUND_RESERVED", commissionReversalReferences: evidence.commissionReversalReferences, storeEarningReversalReference: evidence.storeEarningReversalReference });
      if (!("refundReference" in recovered) || typeof recovered.refundReference !== "string") throw new Error("Recovered adjustment must expose its canonical refund reference.");
      const refund = await prisma.paymentRefund.findUniqueOrThrow({ where: { publicReference: recovered.refundReference } });
      expect((await prisma.marketplaceStoreOrderAdjustment.findUniqueOrThrow({ where: { id: adjustment.id } })).refundId).toBe(refund.id);
      expect((await applyMarketplaceStoreOrderAdjustment(recover)).replayed).toBe(true);
      await expect(applyMarketplaceStoreOrderAdjustment({ ...recover, requestHash: "0".repeat(64) })).rejects.toMatchObject({ code: "STORE_ORDER_IDEMPOTENCY_CONFLICT" });
      expect(await balances()).toEqual(after);
      let refundState = await protectedRefundState(source.id);
      expect(refundState.payment.totalRefundReservedAmount.equals(adjustment.refundAmount)).toBe(true); expect(refundState.refunds).toHaveLength(1);
      assertJournalMoney(refundState.refunds[0].reserveLedgerJournal, "REFUND_RESERVE", adjustment.refundAmount.toFixed(2));
      await approveRefund({ actorUserId: actors.approver.id, publicReference: refund.publicReference, operationId: randomUUID() });
      await startProviderRefund({ actorUserId: actors.processor.id, publicReference: refund.publicReference, operationId: randomUUID() }, dependencies);
      refundState = await protectedRefundState(source.id);
      assertJournalMoney(refundState.refunds[0].completionLedgerJournal, "REFUND_EXTERNAL_PAYOUT", adjustment.refundAmount.toFixed(2));
      expect(refundState.payment.totalRefundedAmount.equals(adjustment.refundAmount)).toBe(true); expect(refundState.payment.totalRefundReservedAmount.isZero()).toBe(true); expect(client.calls).toBe(1);
      await expect(createRefundRequest({ actorUserId: source.userId!, paymentPublicReference: source.publicReference, amount: source.amount.sub(adjustment.refundAmount).add("0.01").toFixed(2), method: "ORIGINAL_PAYMENT_METHOD", reasonCode: "SERVICE_NOT_PROVIDED", operationId: randomUUID() }, dependencies)).rejects.toMatchObject({ code: "REFUND_AMOUNT_EXCEEDS_REMAINING" });
      await expect(reverseCommissionAccrual({ accrualId: accrual.id, operationId: randomUUID(), reasonCode: "MARKETPLACE_STORE_ADJUSTMENT", actorUserId: actors.approver.id }, { allowTestOnlyBypass: true })).rejects.toMatchObject({ code: "COMMISSION_REVERSAL_NOT_ALLOWED" });
      await expect(prisma.$transaction(tx => reverseCommissionInTransaction(tx, { accrualPublicReference: accrual.publicReference, allocationPublicReference: allocation.publicReference, originalAmount: allocation.amount.toFixed(2), previouslyReversedAmount: "0.00" }, { amount: "0.01" }, { operationId: randomUUID(), reasonCode: "MARKETPLACE_STORE_ADJUSTMENT" }))).rejects.toMatchObject({ code: "COMMISSION_REVERSAL_NOT_ALLOWED" });
      await expect(prisma.$transaction(tx => adjustStoreEarningInTransaction(tx, { publicReference: earning.publicReference, originalSellerBasis: earning.settlementBasisAmount.toFixed(2), originalCommission: earning.attributedCommissionAmount.toFixed(2), originalAmount: earning.amount.toFixed(2), previouslyAdjustedAmount: "0.00" }, { sellerBasisAmount: "0.01", commissionAmount: "0.00", storeEarningAmount: "0.01" }, { operationId: randomUUID(), reasonCode: "MARKETPLACE_STORE_ADJUSTMENT" }))).rejects.toMatchObject({ code: "STORE_EARNING_REVERSAL_NOT_ALLOWED" });
      expect(await balances()).toEqual(after); expect(await protectedRefundState(source.id)).toEqual(refundState);
    });
  }, 180_000);
});
