/* Generated by scripts/media/prepare-home-cinematic-assets.mjs. Do not edit. */
export type HomeCinematicAsset = { id: string; family: string; sourceFile: string; desktopSrc: string; mobileSrc: string; width: number; height: number; sourceWidth: number; sourceHeight: number; aspectRatio: number; hasAlpha: boolean; visibleBounds?: { x: number; y: number; width: number; height: number }; index: number };
export const HOME_CINEMATIC_ASSETS = [
  {
    "id": "box-00",
    "family": "box",
    "sourceFile": "public/media/public/images/KT_BOX_SEQUENCE_8_FRAMES/box_00_open_master.png",
    "desktopSrc": "/media/public/home-cinematic/box/box-box-00-open-master-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/box/box-box-00-open-master-mobile.webp",
    "width": 512,
    "height": 512,
    "sourceWidth": 512,
    "sourceHeight": 512,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 49,
      "y": 98,
      "width": 413,
      "height": 368
    },
    "index": 0
  },
  {
    "id": "box-01",
    "family": "box",
    "sourceFile": "public/media/public/images/KT_BOX_SEQUENCE_8_FRAMES/box_01_side_flaps_early.png",
    "desktopSrc": "/media/public/home-cinematic/box/box-box-01-side-flaps-early-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/box/box-box-01-side-flaps-early-mobile.webp",
    "width": 512,
    "height": 512,
    "sourceWidth": 512,
    "sourceHeight": 512,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 66,
      "y": 96,
      "width": 379,
      "height": 370
    },
    "index": 1
  },
  {
    "id": "box-02",
    "family": "box",
    "sourceFile": "public/media/public/images/KT_BOX_SEQUENCE_8_FRAMES/box_02_side_flaps_mid.png",
    "desktopSrc": "/media/public/home-cinematic/box/box-box-02-side-flaps-mid-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/box/box-box-02-side-flaps-mid-mobile.webp",
    "width": 512,
    "height": 512,
    "sourceWidth": 512,
    "sourceHeight": 512,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 81,
      "y": 96,
      "width": 350,
      "height": 370
    },
    "index": 2
  },
  {
    "id": "box-03",
    "family": "box",
    "sourceFile": "public/media/public/images/KT_BOX_SEQUENCE_8_FRAMES/box_03_side_flaps_closed.png",
    "desktopSrc": "/media/public/home-cinematic/box/box-box-03-side-flaps-closed-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/box/box-box-03-side-flaps-closed-mobile.webp",
    "width": 512,
    "height": 512,
    "sourceWidth": 512,
    "sourceHeight": 512,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 105,
      "y": 95,
      "width": 302,
      "height": 371
    },
    "index": 3
  },
  {
    "id": "box-04",
    "family": "box",
    "sourceFile": "public/media/public/images/KT_BOX_SEQUENCE_8_FRAMES/box_04_rear_flap_early.png",
    "desktopSrc": "/media/public/home-cinematic/box/box-box-04-rear-flap-early-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/box/box-box-04-rear-flap-early-mobile.webp",
    "width": 512,
    "height": 512,
    "sourceWidth": 512,
    "sourceHeight": 512,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 98,
      "y": 130,
      "width": 315,
      "height": 336
    },
    "index": 4
  },
  {
    "id": "box-05",
    "family": "box",
    "sourceFile": "public/media/public/images/KT_BOX_SEQUENCE_8_FRAMES/box_05_rear_flap_near_closed.png",
    "desktopSrc": "/media/public/home-cinematic/box/box-box-05-rear-flap-near-closed-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/box/box-box-05-rear-flap-near-closed-mobile.webp",
    "width": 512,
    "height": 512,
    "sourceWidth": 512,
    "sourceHeight": 512,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 99,
      "y": 162,
      "width": 313,
      "height": 304
    },
    "index": 5
  },
  {
    "id": "box-06",
    "family": "box",
    "sourceFile": "public/media/public/images/KT_BOX_SEQUENCE_8_FRAMES/box_06_front_flap_mid.png",
    "desktopSrc": "/media/public/home-cinematic/box/box-box-06-front-flap-mid-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/box/box-box-06-front-flap-mid-mobile.webp",
    "width": 512,
    "height": 512,
    "sourceWidth": 512,
    "sourceHeight": 512,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 100,
      "y": 160,
      "width": 311,
      "height": 306
    },
    "index": 6
  },
  {
    "id": "box-07",
    "family": "box",
    "sourceFile": "public/media/public/images/KT_BOX_SEQUENCE_8_FRAMES/box_07_closed.png",
    "desktopSrc": "/media/public/home-cinematic/box/box-box-07-closed-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/box/box-box-07-closed-mobile.webp",
    "width": 512,
    "height": 512,
    "sourceWidth": 512,
    "sourceHeight": 512,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 108,
      "y": 169,
      "width": 296,
      "height": 297
    },
    "index": 7
  },
  {
    "id": "route-van-00",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_01_right.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-01-right-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-01-right-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 25,
      "y": 375,
      "width": 1206,
      "height": 529
    },
    "index": 0
  },
  {
    "id": "route-van-01",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_02_turn_15.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-02-turn-15-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-02-turn-15-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 21,
      "y": 362,
      "width": 1209,
      "height": 638
    },
    "index": 1
  },
  {
    "id": "route-van-02",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_03_turn_30.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-03-turn-30-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-03-turn-30-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 18,
      "y": 167,
      "width": 1171,
      "height": 958
    },
    "index": 2
  },
  {
    "id": "route-van-03",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_04_turn_45.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-04-turn-45-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-04-turn-45-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 21,
      "y": 65,
      "width": 1176,
      "height": 1150
    },
    "index": 3
  },
  {
    "id": "route-van-04",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_05_turn_60.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-05-turn-60-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-05-turn-60-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 69,
      "y": 78,
      "width": 1100,
      "height": 1113
    },
    "index": 4
  },
  {
    "id": "route-van-05",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_06_turn_75.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-06-turn-75-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-06-turn-75-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 390,
      "y": 30,
      "width": 536,
      "height": 1175
    },
    "index": 5
  },
  {
    "id": "route-van-06",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_07_down.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-07-down-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-07-down-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 352,
      "y": 21,
      "width": 543,
      "height": 1207
    },
    "index": 6
  },
  {
    "id": "handoff-00",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_01_approach.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-01-approach-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-01-approach-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 47,
      "y": 23,
      "width": 1134,
      "height": 1163
    },
    "index": 0
  },
  {
    "id": "handoff-01",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_02_arrival.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-02-arrival-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-02-arrival-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 193,
      "y": 15,
      "width": 895,
      "height": 1197
    },
    "index": 1
  },
  {
    "id": "handoff-02",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_03_recipient_reach.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-03-recipient-reach-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-03-recipient-reach-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 191,
      "y": 15,
      "width": 907,
      "height": 1197
    },
    "index": 2
  },
  {
    "id": "handoff-03",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_04_first_contact.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-04-first-contact-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-04-first-contact-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 192,
      "y": 15,
      "width": 909,
      "height": 1198
    },
    "index": 3
  },
  {
    "id": "handoff-04",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_05_shared_parcel.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-05-shared-parcel-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-05-shared-parcel-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 191,
      "y": 13,
      "width": 915,
      "height": 1201
    },
    "index": 4
  },
  {
    "id": "handoff-05",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_06_weight_transfer.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-06-weight-transfer-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-06-weight-transfer-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 191,
      "y": 13,
      "width": 917,
      "height": 1204
    },
    "index": 5
  },
  {
    "id": "handoff-06",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_07_release.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-07-release-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-07-release-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 191,
      "y": 12,
      "width": 921,
      "height": 1203
    },
    "index": 6
  },
  {
    "id": "handoff-07",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_08_withdrawal.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-08-withdrawal-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-08-withdrawal-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 190,
      "y": 11,
      "width": 927,
      "height": 1207
    },
    "index": 7
  },
  {
    "id": "handoff-08",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_09_separation_begin.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-09-separation-begin-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-09-separation-begin-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 129,
      "y": 13,
      "width": 1063,
      "height": 1199
    },
    "index": 8
  },
  {
    "id": "handoff-09",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_10_departure_step.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-10-departure-step-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-10-departure-step-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 46,
      "y": 12,
      "width": 1208,
      "height": 1191
    },
    "index": 9
  },
  {
    "id": "handoff-10",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_11_walking_apart.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-11-walking-apart-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-11-walking-apart-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 12,
      "y": 111,
      "width": 1242,
      "height": 1076
    },
    "index": 10
  },
  {
    "id": "handoff-11",
    "family": "handoff",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_12_final_separation.png",
    "desktopSrc": "/media/public/home-cinematic/handoff/handoff-handoff-12-final-separation-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/handoff/handoff-handoff-12-final-separation-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 0,
      "y": 148,
      "width": 1254,
      "height": 1020
    },
    "index": 11
  },
  {
    "id": "pickup-00",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A00_van_closed_right.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a00-van-closed-right-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a00-van-closed-right-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 0
  },
  {
    "id": "pickup-01",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A01_door_15.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a01-door-15-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a01-door-15-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 1
  },
  {
    "id": "pickup-02",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A02_door_35.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a02-door-35-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a02-door-35-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 2
  },
  {
    "id": "pickup-03",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A03_door_60.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a03-door-60-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a03-door-60-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 3
  },
  {
    "id": "pickup-04",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A04_door_85.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a04-door-85-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a04-door-85-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 4
  },
  {
    "id": "pickup-05",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A05_door_open.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a05-door-open-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a05-door-open-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 5
  },
  {
    "id": "pickup-06",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A06_courier_approach_box.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a06-courier-approach-box-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a06-courier-approach-box-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 737,
      "width": 1400,
      "height": 755
    },
    "index": 6
  },
  {
    "id": "pickup-07",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A07_courier_at_door.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a07-courier-at-door-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a07-courier-at-door-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 737,
      "width": 1400,
      "height": 755
    },
    "index": 7
  },
  {
    "id": "pickup-08",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A08_load_start.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a08-load-start-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a08-load-start-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 420,
      "y": 752,
      "width": 1229,
      "height": 596
    },
    "index": 8
  },
  {
    "id": "pickup-09",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A09_load_half.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a09-load-half-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a09-load-half-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 419,
      "y": 751,
      "width": 1232,
      "height": 601
    },
    "index": 9
  },
  {
    "id": "pickup-10",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A10_load_near_inside.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a10-load-near-inside-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a10-load-near-inside-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 419,
      "y": 751,
      "width": 1231,
      "height": 599
    },
    "index": 10
  },
  {
    "id": "pickup-11",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A11_parcel_released.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a11-parcel-released-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a11-parcel-released-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 419,
      "y": 751,
      "width": 1232,
      "height": 598
    },
    "index": 11
  },
  {
    "id": "pickup-12",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A12_courier_withdraw.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a12-courier-withdraw-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a12-courier-withdraw-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 416,
      "y": 759,
      "width": 1234,
      "height": 673
    },
    "index": 12
  },
  {
    "id": "pickup-13",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A13_courier_clear.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a13-courier-clear-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a13-courier-clear-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 415,
      "y": 749,
      "width": 1225,
      "height": 694
    },
    "index": 13
  },
  {
    "id": "pickup-14",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A14_door_closing_60.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a14-door-closing-60-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a14-door-closing-60-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 14
  },
  {
    "id": "pickup-15",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A15_door_closing_25.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a15-door-closing-25-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a15-door-closing-25-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 15
  },
  {
    "id": "pickup-16",
    "family": "pickup",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A16_ready_depart.png",
    "desktopSrc": "/media/public/home-cinematic/performance/pickup-pickup-a16-ready-depart-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/pickup-pickup-a16-ready-depart-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 275,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 16
  },
  {
    "id": "delivery-00",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B00_van_closed_left.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b00-van-closed-left-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b00-van-closed-left-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 0
  },
  {
    "id": "delivery-01",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B01_door_15.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b01-door-15-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b01-door-15-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 1
  },
  {
    "id": "delivery-02",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B02_door_35.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b02-door-35-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b02-door-35-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 2
  },
  {
    "id": "delivery-03",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B03_door_60.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b03-door-60-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b03-door-60-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 3
  },
  {
    "id": "delivery-04",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B04_door_85.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b04-door-85-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b04-door-85-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 4
  },
  {
    "id": "delivery-05",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B05_door_open.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b05-door-open-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b05-door-open-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 5
  },
  {
    "id": "delivery-06",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B06_courier_emerging.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b06-courier-emerging-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b06-courier-emerging-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 416,
      "y": 778,
      "width": 1220,
      "height": 596
    },
    "index": 6
  },
  {
    "id": "delivery-07",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B07_courier_threshold_box.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b07-courier-threshold-box-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b07-courier-threshold-box-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 423,
      "y": 799,
      "width": 1205,
      "height": 562
    },
    "index": 7
  },
  {
    "id": "delivery-08",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B08_courier_out_box.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b08-courier-out-box-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b08-courier-out-box-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 424,
      "y": 798,
      "width": 1204,
      "height": 631
    },
    "index": 8
  },
  {
    "id": "delivery-09",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B09_walk_right_01.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b09-walk-right-01-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b09-walk-right-01-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 754
    },
    "index": 9
  },
  {
    "id": "delivery-10",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B10_walk_right_02.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b10-walk-right-02-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b10-walk-right-02-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 754
    },
    "index": 10
  },
  {
    "id": "delivery-11",
    "family": "delivery",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B11_handoff_entry_match.png",
    "desktopSrc": "/media/public/home-cinematic/performance/delivery-delivery-b11-handoff-entry-match-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/delivery-delivery-b11-handoff-entry-match-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1538,
      "height": 754
    },
    "index": 11
  },
  {
    "id": "return-00",
    "family": "return",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/return_C01_walk_left.png",
    "desktopSrc": "/media/public/home-cinematic/performance/return-return-c01-walk-left-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/return-return-c01-walk-left-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 423,
      "y": 799,
      "width": 1206,
      "height": 585
    },
    "index": 0
  },
  {
    "id": "return-01",
    "family": "return",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/return_C02_approach_van.png",
    "desktopSrc": "/media/public/home-cinematic/performance/return-return-c02-approach-van-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/return-return-c02-approach-van-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 425,
      "y": 799,
      "width": 1204,
      "height": 562
    },
    "index": 1
  },
  {
    "id": "return-02",
    "family": "return",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/return_C03_enter_van.png",
    "desktopSrc": "/media/public/home-cinematic/performance/return-return-c03-enter-van-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/return-return-c03-enter-van-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 423,
      "y": 798,
      "width": 1205,
      "height": 611
    },
    "index": 2
  },
  {
    "id": "return-03",
    "family": "return",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/return_C04_inside.png",
    "desktopSrc": "/media/public/home-cinematic/performance/return-return-c04-inside-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/return-return-c04-inside-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 3
  },
  {
    "id": "return-04",
    "family": "return",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/return_C05_door_closing_60.png",
    "desktopSrc": "/media/public/home-cinematic/performance/return-return-c05-door-closing-60-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/return-return-c05-door-closing-60-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 4
  },
  {
    "id": "return-05",
    "family": "return",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/return_C06_door_closing_25.png",
    "desktopSrc": "/media/public/home-cinematic/performance/return-return-c06-door-closing-25-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/return-return-c06-door-closing-25-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 5
  },
  {
    "id": "return-06",
    "family": "return",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/return_C07_departure_ready.png",
    "desktopSrc": "/media/public/home-cinematic/performance/return-return-c07-departure-ready-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/performance/return-return-c07-departure-ready-mobile.webp",
    "width": 2048,
    "height": 2048,
    "sourceWidth": 2048,
    "sourceHeight": 2048,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 273,
      "y": 738,
      "width": 1400,
      "height": 654
    },
    "index": 6
  },
  {
    "id": "road-00",
    "family": "road",
    "sourceFile": "public/media/public/images/road.png",
    "desktopSrc": "/media/public/home-cinematic/environment/road-road-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/environment/road-road-mobile.webp",
    "width": 1671,
    "height": 941,
    "sourceWidth": 1671,
    "sourceHeight": 941,
    "aspectRatio": 1.77577045696068,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 0,
      "y": 0,
      "width": 1671,
      "height": 941
    },
    "index": 0
  },
  {
    "id": "red-truck-top-00",
    "family": "red-truck-top",
    "sourceFile": "public/media/public/images/red_truck_top.png",
    "desktopSrc": "/media/public/home-cinematic/freight/red-truck-top-red-truck-top-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/freight/red-truck-top-red-truck-top-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 18,
      "y": 484,
      "width": 1225,
      "height": 299
    },
    "index": 0
  }
] as const satisfies readonly HomeCinematicAsset[];
export const HOME_BOX_SEQUENCE = ["box-00","box-01","box-02","box-03","box-04","box-05","box-06","box-07"] as const;
export const HOME_ROUTE_VAN_SEQUENCE = ["route-van-00","route-van-01","route-van-02","route-van-03","route-van-04","route-van-05","route-van-06"] as const;
export const HOME_HANDOFF_SEQUENCE = ["handoff-00","handoff-01","handoff-02","handoff-03","handoff-04","handoff-05","handoff-06","handoff-07","handoff-08","handoff-09","handoff-10","handoff-11"] as const;
export const HOME_PICKUP_SEQUENCE = ["pickup-00","pickup-01","pickup-02","pickup-03","pickup-04","pickup-05","pickup-06","pickup-07","pickup-08","pickup-09","pickup-10","pickup-11","pickup-12","pickup-13","pickup-14","pickup-15","pickup-16"] as const;
export const HOME_DELIVERY_SEQUENCE = ["delivery-00","delivery-01","delivery-02","delivery-03","delivery-04","delivery-05","delivery-06","delivery-07","delivery-08","delivery-09","delivery-10","delivery-11"] as const;
export const HOME_RETURN_SEQUENCE = ["return-00","return-01","return-02","return-03","return-04","return-05","return-06"] as const;
export const HOME_CINEMATIC_ASSET_BY_ID: Readonly<Record<string, HomeCinematicAsset>> = Object.fromEntries(HOME_CINEMATIC_ASSETS.map((asset) => [asset.id, asset]));
