/* Generated by scripts/media/prepare-home-cinematic-assets.mjs. Do not edit. */
export type HomeCinematicAsset = { id: string; family: string; sourceFile: string; desktopSrc: string; mobileSrc: string; width: number; height: number; sourceWidth: number; sourceHeight: number; aspectRatio: number; hasAlpha: boolean; visibleBounds?: { x: number; y: number; width: number; height: number }; index: number };
export const HOME_CINEMATIC_ASSETS = [
  {
    "id": "route-van-00",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_01_right.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-01-right-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-01-right-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 26,
      "y": 376,
      "width": 1204,
      "height": 528
    },
    "index": 0
  },
  {
    "id": "route-van-01",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_02_turn_15.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-02-turn-15-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-02-turn-15-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 21,
      "y": 362,
      "width": 1208,
      "height": 637
    },
    "index": 1
  },
  {
    "id": "route-van-02",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_03_turn_30.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-03-turn-30-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-03-turn-30-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 19,
      "y": 168,
      "width": 1170,
      "height": 957
    },
    "index": 2
  },
  {
    "id": "route-van-03",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_04_turn_45.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-04-turn-45-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-04-turn-45-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 21,
      "y": 65,
      "width": 1175,
      "height": 1150
    },
    "index": 3
  },
  {
    "id": "route-van-04",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_05_turn_60.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-05-turn-60-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-05-turn-60-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 69,
      "y": 78,
      "width": 1098,
      "height": 1113
    },
    "index": 4
  },
  {
    "id": "route-van-05",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_06_turn_75.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-06-turn-75-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-06-turn-75-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 391,
      "y": 31,
      "width": 535,
      "height": 1173
    },
    "index": 5
  },
  {
    "id": "route-van-06",
    "family": "route-van",
    "sourceFile": "public/media/public/images/KT_COURIER_WHITE_VAN_TOP_DOWN_SEQUENCE/van_road_07_down.png",
    "desktopSrc": "/media/public/home-cinematic/route-van/route-van-van-road-07-down-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/route-van/route-van-van-road-07-down-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 353,
      "y": 22,
      "width": 542,
      "height": 1204
    },
    "index": 6
  },
  {
    "id": "red-truck-top-00",
    "family": "red-truck-top",
    "sourceFile": "public/media/public/images/red_truck_top.png",
    "desktopSrc": "/media/public/home-cinematic/freight/red-truck-top-red-truck-top-desktop.webp",
    "mobileSrc": "/media/public/home-cinematic/freight/red-truck-top-red-truck-top-mobile.webp",
    "width": 1254,
    "height": 1254,
    "sourceWidth": 1254,
    "sourceHeight": 1254,
    "aspectRatio": 1,
    "hasAlpha": true,
    "visibleBounds": {
      "x": 20,
      "y": 484,
      "width": 1222,
      "height": 298
    },
    "index": 0
  }
] as const satisfies readonly HomeCinematicAsset[];
export const HOME_ROUTE_VAN_SEQUENCE = ["route-van-00","route-van-01","route-van-02","route-van-03","route-van-04","route-van-05","route-van-06"] as const;
export const HOME_CINEMATIC_ASSET_BY_ID: Readonly<Record<string, HomeCinematicAsset>> = Object.fromEntries(HOME_CINEMATIC_ASSETS.map((asset) => [asset.id, asset]));
