/* Generated by scripts/media/prepare-home-composite-actors.mjs. Do not edit. */
export const HOME_COMPOSED_ACTORS = [
  {
    "id": "van-open-right",
    "family": "van",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A05_door_open.png",
    "desktop": "/media/public/home-cinematic/composed/van-open-right-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/van-open-right-mobile.webp",
    "width": 1520,
    "height": 910,
    "visibleBounds": {
      "x": 96,
      "y": 199,
      "width": 1399,
      "height": 653
    }
  },
  {
    "id": "van-door-right",
    "family": "van",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/pickup_A00_van_closed_right.png",
    "desktop": "/media/public/home-cinematic/composed/van-door-right-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/van-door-right-mobile.webp",
    "width": 1520,
    "height": 910,
    "visibleBounds": {
      "x": 575,
      "y": 199,
      "width": 360,
      "height": 569
    }
  },
  {
    "id": "van-open-left",
    "family": "van",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B05_door_open.png",
    "desktop": "/media/public/home-cinematic/composed/van-open-left-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/van-open-left-mobile.webp",
    "width": 1520,
    "height": 910,
    "visibleBounds": {
      "x": 93,
      "y": 199,
      "width": 1399,
      "height": 653
    }
  },
  {
    "id": "van-door-left",
    "family": "van",
    "sourceFile": "public/media/public/images/KT_Courier_White_Van_Courier_Performance_Pack/delivery_B00_van_closed_left.png",
    "desktop": "/media/public/home-cinematic/composed/van-door-left-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/van-door-left-mobile.webp",
    "width": 1520,
    "height": 910,
    "visibleBounds": {
      "x": 650,
      "y": 199,
      "width": 360,
      "height": 569
    }
  },
  {
    "id": "courier-carry-right",
    "family": "courier",
    "sourceFile": "public/media/public/images/KT_Courier_20_Transparent_PNG_Assets/10_looking_right_approaching_vehicle.png",
    "desktop": "/media/public/home-cinematic/composed/courier-carry-right-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/courier-carry-right-mobile.webp",
    "width": 1122,
    "height": 1402,
    "visibleBounds": {
      "x": 243,
      "y": 25,
      "width": 660,
      "height": 1334
    }
  },
  {
    "id": "courier-load",
    "family": "courier",
    "sourceFile": "public/media/public/images/KT_Courier_20_Transparent_PNG_Assets/18_loading_unloading_parcel.png",
    "desktop": "/media/public/home-cinematic/composed/courier-load-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/courier-load-mobile.webp",
    "width": 1122,
    "height": 1402,
    "visibleBounds": {
      "x": 177,
      "y": 26,
      "width": 843,
      "height": 1343
    }
  },
  {
    "id": "courier-empty",
    "family": "courier",
    "sourceFile": "public/media/public/images/KT_Courier_20_Transparent_PNG_Assets/16_empty_hands_courier_hero.png",
    "desktop": "/media/public/home-cinematic/composed/courier-empty-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/courier-empty-mobile.webp",
    "width": 1122,
    "height": 1402,
    "visibleBounds": {
      "x": 360,
      "y": 9,
      "width": 429,
      "height": 1371
    }
  },
  {
    "id": "courier-carry-left",
    "family": "courier",
    "sourceFile": "public/media/public/images/KT_Courier_20_Transparent_PNG_Assets/11_looking_left_approaching_vehicle.png",
    "desktop": "/media/public/home-cinematic/composed/courier-carry-left-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/courier-carry-left-mobile.webp",
    "width": 1122,
    "height": 1402,
    "visibleBounds": {
      "x": 258,
      "y": 22,
      "width": 664,
      "height": 1350
    }
  },
  {
    "id": "courier-walk-right",
    "family": "courier",
    "sourceFile": "public/media/public/images/KT_Courier_20_Transparent_PNG_Assets/04_walking_one_parcel_facing_right.png",
    "desktop": "/media/public/home-cinematic/composed/courier-walk-right-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/courier-walk-right-mobile.webp",
    "width": 1122,
    "height": 1402,
    "visibleBounds": {
      "x": 222,
      "y": 31,
      "width": 742,
      "height": 1307
    }
  },
  {
    "id": "courier-walk-left",
    "family": "courier",
    "sourceFile": "public/media/public/images/KT_Courier_20_Transparent_PNG_Assets/05_walking_one_parcel_facing_left.png",
    "desktop": "/media/public/home-cinematic/composed/courier-walk-left-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/courier-walk-left-mobile.webp",
    "width": 1122,
    "height": 1402,
    "visibleBounds": {
      "x": 216,
      "y": 18,
      "width": 775,
      "height": 1324
    }
  },
  {
    "id": "recipient-ready",
    "family": "recipient",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_01_approach.png",
    "desktop": "/media/public/home-cinematic/composed/recipient-ready-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/recipient-ready-mobile.webp",
    "width": 604,
    "height": 1254,
    "visibleBounds": {
      "x": 148,
      "y": 75,
      "width": 382,
      "height": 1107
    }
  },
  {
    "id": "recipient-reach",
    "family": "recipient",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_03_recipient_reach.png",
    "desktop": "/media/public/home-cinematic/composed/recipient-reach-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/recipient-reach-mobile.webp",
    "width": 604,
    "height": 1254,
    "visibleBounds": {
      "x": 0,
      "y": 75,
      "width": 447,
      "height": 1123
    }
  },
  {
    "id": "recipient-carry",
    "family": "recipient",
    "sourceFile": "public/media/public/images/KT_COURIER_HANDOFF_12_PNGS/handoff_12_final_separation.png",
    "desktop": "/media/public/home-cinematic/composed/recipient-carry-desktop.webp",
    "mobile": "/media/public/home-cinematic/composed/recipient-carry-mobile.webp",
    "width": 604,
    "height": 1254,
    "visibleBounds": {
      "x": 143,
      "y": 211,
      "width": 461,
      "height": 946
    }
  }
] as const;
export const HOME_COMPOSED_ACTOR_BY_ID: Readonly<Record<string, (typeof HOME_COMPOSED_ACTORS)[number]>> = Object.fromEntries(HOME_COMPOSED_ACTORS.map((asset) => [asset.id, asset]));
