export type DriverEarningErrorCode =
  | "DRIVER_EARNING_INVALID_COMMAND" | "DRIVER_EARNING_INVALID_SNAPSHOT" | "DRIVER_EARNING_NOT_FOUND"
  | "DRIVER_EARNING_FORBIDDEN" | "DRIVER_EARNING_ACCOUNT_INVALID" | "DRIVER_EARNING_PAYMENT_INVALID"
  | "DRIVER_EARNING_ASSIGNMENT_INVALID" | "DRIVER_EARNING_DELIVERY_EVIDENCE_INVALID"
  | "DRIVER_EARNING_COMMISSION_INVALID" | "DRIVER_EARNING_COMMISSION_OVER_ATTRIBUTED"
  | "DRIVER_EARNING_IDEMPOTENCY_CONFLICT" | "DRIVER_EARNING_SETTLEMENT_ALREADY_ACCRUED"
  | "DRIVER_EARNING_INSUFFICIENT_HELD_FUNDS" | "DRIVER_EARNING_INVALID_STATE"
  | "DRIVER_EARNING_RELEASE_NOT_ELIGIBLE" | "DRIVER_EARNING_REVERSAL_NOT_ALLOWED"
  | "DRIVER_EARNING_REFUND_EVIDENCE_REQUIRED" | "DRIVER_EARNING_REFUND_AFTER_RELEASE"
  | "DRIVER_EARNING_RECONCILIATION_REQUIRED" | "DRIVER_EARNING_PRODUCTION_LOCKED";

export class DriverEarningError extends Error {
  constructor(readonly code: DriverEarningErrorCode, message: string, readonly details?: Readonly<Record<string, string | readonly string[]>>) {
    super(message);
    this.name = "DriverEarningError";
  }
}
