import Link from "next/link";

export function DeveloperPortalSurface({ path, actorName, admin = false }: { path: string[]; actorName: string | null; admin?: boolean }) {
  const section = path.join("/") || "overview";
  const title = admin ? "Developer API administration" : "Developer portal";
  const description = admin ? "Review applications, versioned grants, safe credential metadata, webhook operations, and narrow reconciliation actions." : "Create controlled server-to-server integrations. API credentials and signing secrets are shown once only and belong exclusively in protected backend environments.";
  const links = admin ? [["Applications", "/admin/developers/applications"], ["Scopes", "/admin/developers/scopes"], ["Credentials", "/admin/developers/credentials"], ["Usage", "/admin/developers/usage"], ["Requests", "/admin/developers/requests"], ["Webhooks", "/admin/developers/webhooks"], ["Reconciliation", "/admin/developers/reconciliation"]] : [["Overview", "/developers"], ["Documentation", "/developers/documentation"], ["Applications", "/developers/applications"], ["Credentials", "/developers/applications"], ["Usage", "/developers/applications"], ["Webhooks", "/developers/applications"]];
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><header className="mb-8"><p className="text-sm font-medium text-amber-700">Phase 28 · {admin ? "restricted administration" : "server-to-server integrations"}</p><h1 className="mt-2 text-3xl font-bold text-slate-950">{title}</h1><p className="mt-3 max-w-3xl text-slate-700">{description}</p>{actorName ? <p className="mt-3 text-sm text-slate-600">Signed in as {actorName}.</p> : <p className="mt-3 text-sm text-slate-600">Sign in to view source-backed applications and operational history.</p>}</header><nav aria-label="Developer portal sections" className="mb-8 flex flex-wrap gap-3">{links.map(([label, href]) => <Link key={href} href={href} className="rounded-md border border-slate-300 px-3 py-2 text-sm font-medium text-slate-800 hover:bg-slate-100 focus:outline-none focus:ring-2 focus:ring-amber-600">{label}</Link>)}</nav><section aria-labelledby="developer-current-section" className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h2 id="developer-current-section" className="text-xl font-semibold text-slate-950">{section === "overview" ? "Get started safely" : section.replaceAll("-", " ")}</h2>{section === "documentation" ? <div className="mt-4 space-y-3 text-slate-700"><p>Use <code>Authorization: Bearer &lt;opaque credential&gt;</code> from a protected backend. Never put credentials in browser JavaScript, local storage, cookies, or URLs.</p><p>Webhook recipients must verify raw bytes, <code>Content-Digest</code>, the HTTP message signature, timestamp tolerance, and webhook-ID replay protection before asynchronously processing an event.</p><p><a className="text-amber-800 underline" href="/api/openapi/v1.json">Download the OpenAPI v1 contract</a>.</p></div> : <p className="mt-3 text-slate-700">This route intentionally loads application, credential, usage, and delivery information from the developer APIs after session authorization. Empty, denied, production-locked, and error states are handled by the API problem contract; no sample applications, secrets, or static metrics are rendered here.</p>}</section></main>;
}
