/* eslint-disable @typescript-eslint/no-explicit-any */
import { prisma } from "@/lib/db/prisma";
import { DEVELOPER_SCOPES, DeveloperApiError, type DeveloperScope, productionLocked } from "./contracts";
import { CredentialService, CursorService, DbQuotaService, DbRateLimitService, DeveloperTermsService, IdempotencyService, ScopeGrantService, WebhookSubscriptionService, parseBoundedJson, parsePagination, requireIdempotencyKey, stableRequestHash } from "./services";
import { publicJson, requestId, responseFromError } from "./problem-details";
import { publicCatalog, publicCatalogProduct, publicCancelOrder, publicCreateOrder, publicOrderByReference, publicOrderTracking, publicOrders, publicQuote, publicServiceAreas, publicStoreOrder, publicStoreOrderAction, publicStoreOrders, resolveMachineOwner } from "./public-resource-adapters";
import { assertPublicReference, PublicStoreOrderAcceptRequestSchema, PublicStoreOrderReadyRequestSchema, PublicStoreOrderRejectRequestSchema, PublicWebhookCreateRequestSchema, PublicWebhookPatchRequestSchema, PublicWebhookRetryRequestSchema, PublicWebhookRotateSecretRequestSchema, PublicWebhookVerifyRequestSchema, validatePublicBody } from "./schemas";

const db: any = prisma;
const terms = new DeveloperTermsService(db); const scopeGrants = new ScopeGrantService(db); const credentials = new CredentialService(db, terms); const idempotency = new IdempotencyService(db); const rateLimits = new DbRateLimitService(db); const quotas = new DbQuotaService(db); const webhooks = new WebhookSubscriptionService(db);
export function endpointEnvironment(request: Request): "TEST" | "LIVE" { const configured = process.env.DEVELOPER_API_ENDPOINT_ENVIRONMENT; if (configured === "TEST" || configured === "LIVE") return configured; const hostname = new URL(request.url).hostname; return hostname.startsWith("test.") || hostname.startsWith("api-test.") || process.env.NODE_ENV !== "production" ? "TEST" : "LIVE"; }
function bearer(request: Request): string { if (request.headers.has("cookie")) throw new DeveloperApiError("PUBLIC_API_AUTHENTICATION_FAILED", 401, "Authentication failed."); if (["api_key", "credential", "token"].some((key) => new URL(request.url).searchParams.has(key))) throw new DeveloperApiError("PUBLIC_API_AUTHENTICATION_FAILED", 401, "Authentication failed."); const value = request.headers.get("authorization"); const match = value?.match(/^Bearer ([A-Za-z0-9_-]+)$/); if (!match) throw new DeveloperApiError("PUBLIC_API_AUTHENTICATION_FAILED", 401, "Authentication failed."); return match[1]!; }
async function audit(input: any) { try { await db.developerApiRequestAudit.create({ data: { publicReference: `dreq_${input.requestId}`, requestId: input.requestId, applicationId: input.context?.application?.id ?? null, credentialFingerprint: input.context?.credential?.fingerprint ?? null, environment: input.context?.credential?.environment ?? null, scope: input.scope ?? null, method: input.method, route: input.route, outcome: input.outcome, responseStatus: input.status, durationMs: Math.min(60_000, Math.max(0, Date.now() - input.startedAt)), rateLimitDecision: input.rateLimited ? "LIMITED" : "ALLOWED", safeResourceReference: input.reference?.slice(0, 160) ?? null } }); } catch { /* Audit failure must not disclose persistence internals. */ } }
async function authorize(request: Request, required?: DeveloperScope) { const environment = endpointEnvironment(request); if (productionLocked(environment)) throw new DeveloperApiError("DEVELOPER_API_CONSOLIDATED_VALIDATION_NOT_APPROVED", 423, "The live developer API is not activated."); const context = await credentials.authenticate(bearer(request), environment); if (required) scopeGrants.assertScope(context.grant, required); const owner = await resolveMachineOwner(context.application); return { ...context, owner, environment }; }
async function limit(context: any, routeClass: string, quotaCounter?: "quoteGenerations" | "orderCreations" | "activeWebhookSubscriptions" | "webhookVerificationAttempts" | "manualDeliveryRetries") {
  const policy = await db.developerApiRateLimitPolicyVersion.findFirst({ where: { routeClass, active: true }, orderBy: { version: "desc" } });
  if (!policy) throw new DeveloperApiError("API_RATE_POLICY_MISSING", 503, "No active rate policy is configured for this operation.");
  const result = await rateLimits.check({ policyId: policy.id, dimensions: { credential: context.credential.fingerprint, application: context.application.publicReference, resourceOwner: context.owner.id, scope: context.grant.publicReference, routeClass, environment: context.environment }, maximum: policy.maximumRequests, windowSeconds: policy.windowSeconds });
  if (!result.ok) throw new DeveloperApiError("PUBLIC_API_RATE_LIMITED", 429, "Too many requests. Please retry later.");
  if (!context.grant.quotaPolicyReference) throw new DeveloperApiError("API_QUOTA_POLICY_MISSING", 503, "No active quota policy is configured for this application.");
  const quota = await db.developerApiQuotaPolicyVersion.findFirst({ where: { publicReference: context.grant.quotaPolicyReference, active: true }, orderBy: { version: "desc" } });
  if (!quota) throw new DeveloperApiError("API_QUOTA_POLICY_MISSING", 503, "No active quota policy is configured for this application.");
  const consume = async (counter: "requests" | NonNullable<typeof quotaCounter>) => { const maximum = Number(quota.limits?.[counter]); if (!Number.isInteger(maximum) || maximum < 0) throw new DeveloperApiError("API_QUOTA_POLICY_INVALID", 503, "The active quota policy is invalid."); const accepted = await quotas.consume({ applicationId: context.application.id, ownerUserId: context.owner.id, applicationOwnerUserId: context.application.ownerUserId, environment: context.environment, applicationEnvironment: context.application.environment, policyId: quota.id, counter, maximum }); if (!accepted) throw new DeveloperApiError("API_QUOTA_EXCEEDED", 429, "The approved API quota has been reached."); };
  await consume("requests"); if (quotaCounter) await consume(quotaCounter);
}
function cursorService(): CursorService { const key = process.env.DEVELOPER_API_CURSOR_HMAC_KEY; if (!key) throw new DeveloperApiError("PUBLIC_CURSOR_SIGNING_UNAVAILABLE", 503, "Pagination is temporarily unavailable."); return new CursorService(key); }
function cursorBinding(context: any, route: string, filters: Record<string, string>) { return { applicationId: context.application.id, route, filterHash: stableRequestHash("GET", route, new URLSearchParams(filters), null) }; }
function decodeCursor(raw: string | null, context: any, route: string, filters: Record<string, string>): string | null { if (!raw) return null; const payload = cursorService().decode(raw, cursorBinding(context, route, filters)); return typeof payload.reference === "string" ? payload.reference : (() => { throw new DeveloperApiError("PUBLIC_API_CURSOR_INVALID", 400, "The cursor is invalid."); })(); }
function page(data: any[], nextReference: string | null, hasMore: boolean, limit: number, context: any, route: string, filters: Record<string, string>) { return { data, page: { nextCursor: nextReference ? cursorService().encode({ ...cursorBinding(context, route, filters), reference: nextReference }) : null, hasMore, limit } }; }
async function idempotent(context: any, request: Request, route: string, body: any, run: () => Promise<any>, oneTimeSecretFields: readonly string[] = []) { const key = requireIdempotencyKey(request.headers.get("idempotency-key")); const started = await idempotency.begin({ credentialId: context.credential.id, applicationId: context.application.id, environment: context.environment, method: request.method, route, key, requestHash: stableRequestHash(request.method, route, new URL(request.url).searchParams, body) }); if ("replay" in started) return { body: started.replay.responseBody, status: started.replay.responseStatus!, replay: true }; const output = await run(); const persisted = oneTimeSecretFields.length ? Object.fromEntries(Object.entries(output).filter(([key]) => !oneTimeSecretFields.includes(key))) : output; await idempotency.complete(started.record, 200, persisted, output?.reference); return { body: output, status: 200, replay: false }; }

export async function handlePublicApi(request: Request, segments: string[] = []): Promise<Response> {
  const startedAt = Date.now(); const rid = requestId(request); const route = `/api/v1${segments.length ? `/${segments.join("/")}` : ""}`; let context: any; let scope: string | undefined; try {
    context = await authorize(request); const owner = context.owner;
    const requireScope = async (required: DeveloperScope) => { scope = required; scopeGrants.assertScope(context.grant, required); };
    if (!segments.length && request.method === "GET") { await limit(context, "metadata.read"); return publicJson({ name: "KT Couriers Public API", version: "v1", documentation: "/developers/documentation" }, rid); }
    if (segments[0] === "service-areas" && request.method === "GET") { await limit(context, "metadata.read"); return publicJson({ data: await publicServiceAreas() }, rid); }
    if (segments[0] === "quotes" && request.method === "POST") { await requireScope(DEVELOPER_SCOPES.QUOTES_WRITE); await limit(context, "quotes.write", "quoteGenerations"); const body = await parseBoundedJson(request); const result = await idempotent(context, request, route, body, () => publicQuote(owner, body)); return publicJson(result.body, rid, result.status); }
    if (segments[0] === "orders" && segments.length === 1 && request.method === "GET") { await requireScope(DEVELOPER_SCOPES.ORDERS_READ); const input = parsePagination(new URL(request.url).searchParams, ["status"]); await limit(context, "orders.read"); const result = await publicOrders(owner, { cursor: decodeCursor(input.cursor, context, route, input.filters), limit: input.limit, status: input.filters.status }); return publicJson(page(result.data, result.nextReference, result.hasMore, input.limit, context, route, input.filters), rid); }
    if (segments[0] === "orders" && segments.length === 1 && request.method === "POST") { await requireScope(DEVELOPER_SCOPES.ORDERS_WRITE); await limit(context, "orders.write", "orderCreations"); const body = await parseBoundedJson(request); const result = await idempotent(context, request, route, body, () => publicCreateOrder(owner, body)); return publicJson(result.body, rid, result.status); }
    if (segments[0] === "orders" && segments.length === 2 && request.method === "GET") { await requireScope(DEVELOPER_SCOPES.ORDERS_READ); await limit(context, "orders.read"); return publicJson(await publicOrderByReference(owner, assertPublicReference(segments[1]!)), rid); }
    if (segments[0] === "orders" && segments[2] === "tracking" && request.method === "GET") { await requireScope(DEVELOPER_SCOPES.TRACKING_READ); await limit(context, "tracking.read"); return publicJson(await publicOrderTracking(owner, assertPublicReference(segments[1]!)), rid); }
    if (segments[0] === "orders" && segments[2] === "cancel" && request.method === "POST") { await requireScope(DEVELOPER_SCOPES.ORDERS_CANCEL); await limit(context, "orders.cancel"); const body = await parseBoundedJson(request); const result = await idempotent(context, request, route, body, () => publicCancelOrder(owner, assertPublicReference(segments[1]!), body)); return publicJson(result.body, rid, result.status); }
    if (segments[0] === "catalog" && segments[1] === "products" && segments.length === 2 && request.method === "GET") { await requireScope(DEVELOPER_SCOPES.CATALOG_READ); const input = parsePagination(new URL(request.url).searchParams, ["q"]); await limit(context, "catalog.read"); const result = await publicCatalog(owner, { cursor: decodeCursor(input.cursor, context, route, input.filters), limit: input.limit, query: input.filters.q }); return publicJson(page(result.data, result.nextReference, result.hasMore, input.limit, context, route, input.filters), rid); }
    if (segments[0] === "catalog" && segments[1] === "products" && segments.length === 3 && request.method === "GET") { await requireScope(DEVELOPER_SCOPES.CATALOG_READ); await limit(context, "catalog.read"); return publicJson(await publicCatalogProduct(owner, segments[2]!), rid); }
    if (segments[0] === "store-orders" && segments.length === 1 && request.method === "GET") { await requireScope(DEVELOPER_SCOPES.STORE_ORDERS_READ); const input = parsePagination(new URL(request.url).searchParams); await limit(context, "store-orders.read"); const result = await publicStoreOrders(owner, { ...input, cursor: decodeCursor(input.cursor, context, route, input.filters) }); return publicJson(page(result.data, result.nextReference, result.hasMore, input.limit, context, route, input.filters), rid); }
    if (segments[0] === "store-orders" && segments.length === 2 && request.method === "GET") { await requireScope(DEVELOPER_SCOPES.STORE_ORDERS_READ); await limit(context, "store-orders.read"); return publicJson(await publicStoreOrder(owner, segments[1]!), rid); }
    if (segments[0] === "store-orders" && ["accept", "reject", "ready"].includes(segments[2] ?? "") && request.method === "POST") { await requireScope(DEVELOPER_SCOPES.STORE_ORDERS_MANAGE); await limit(context, "store-orders.manage"); const body = await parseBoundedJson(request); const schema = segments[2] === "accept" ? PublicStoreOrderAcceptRequestSchema : segments[2] === "reject" ? PublicStoreOrderRejectRequestSchema : PublicStoreOrderReadyRequestSchema; const validated = validatePublicBody(schema as any, body); const result = await idempotent(context, request, route, validated, () => publicStoreOrderAction(owner, assertPublicReference(segments[1]!), segments[2]! as any, validated, `dapi:${context.credential.id}:${rid}`, stableRequestHash(request.method, route, new URL(request.url).searchParams, validated))); return publicJson(result.body, rid, result.status); }
    if (segments[0] === "webhooks") return handlePublicWebhook(context, request, segments, rid, route);
    throw new DeveloperApiError("PUBLIC_API_ROUTE_NOT_FOUND", 404, "The requested resource was not found.");
  } catch (error) { const response = responseFromError(error, rid, route); await audit({ requestId: rid, context, scope, method: request.method, route, status: response.status, outcome: error instanceof DeveloperApiError && error.status === 429 ? "RATE_LIMITED" : error instanceof DeveloperApiError && error.status === 423 ? "LOCKED" : "DENIED", startedAt, rateLimited: response.status === 429 }); return response; }
}

async function handlePublicWebhook(context: any, request: Request, segments: string[], rid: string, route: string): Promise<Response> {
  const owner = context.owner; const getOwned = async (reference: string) => { const item = await db.developerWebhookSubscription.findFirst({ where: { publicReference: reference, applicationId: context.application.id } }); if (!item) throw new DeveloperApiError("PUBLIC_API_RESOURCE_NOT_FOUND", 404, "The requested resource was not found."); return item; };
  if (segments.length === 1 && request.method === "GET") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_READ); await limit(context, "webhooks.read"); const data = await db.developerWebhookSubscription.findMany({ where: { applicationId: context.application.id }, orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map((item: any) => ({ reference: item.publicReference, status: item.status, endpoint: item.maskedEndpoint, events: item.eventSelection, verifiedAt: item.verifiedAt })) }, rid); }
  if (segments.length === 1 && request.method === "POST") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_WRITE); await limit(context, "webhooks.create", "activeWebhookSubscriptions"); const body = validatePublicBody(PublicWebhookCreateRequestSchema, await parseBoundedJson(request)); const result = await idempotent(context, request, route, body, async () => { const created = await webhooks.create({ application: context.application, scopes: context.scopes, endpoint: body.endpoint, eventTypes: body.eventTypes }); return { reference: created.subscription.publicReference, status: created.subscription.status, signingSecret: created.secret.value, signingSecretReference: created.secret.reference }; }, ["signingSecret"]); return publicJson(result.body, rid, result.status); }
  const subscription = await getOwned(segments[1]!);
  if (segments.length === 2 && request.method === "GET") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_READ); await limit(context, "webhooks.read"); return publicJson({ reference: subscription.publicReference, status: subscription.status, endpoint: subscription.maskedEndpoint, events: subscription.eventSelection, verifiedAt: subscription.verifiedAt }, rid, 200); }
  if (segments.length === 2 && request.method === "PATCH") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_WRITE); await limit(context, "webhooks.write"); const body = validatePublicBody(PublicWebhookPatchRequestSchema, await parseBoundedJson(request)); const match = request.headers.get("if-match"); if (!match || match !== `\"${subscription.version}\"`) throw new DeveloperApiError("WEBHOOK_ETAG_REQUIRED", 412, "A matching ETag is required."); const updated = await webhooks.update(subscription, body); return publicJson({ reference: updated.publicReference, status: updated.status, endpoint: updated.maskedEndpoint, events: updated.eventSelection }, rid, 200, { etag: `\"${updated.version}\"` }); }
  if (segments[2] === "verify" && request.method === "POST") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_WRITE); await limit(context, "webhooks.verify", "webhookVerificationAttempts"); validatePublicBody(PublicWebhookVerifyRequestSchema, await parseBoundedJson(request)); const verification = await webhooks.requestVerification(subscription); return publicJson({ reference: subscription.publicReference, status: "VERIFYING", verificationReference: verification.verification.publicReference }, rid, 202); }
  if (segments[2] === "rotate-secret" && request.method === "POST") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_WRITE); await limit(context, "credentials.rotate"); validatePublicBody(PublicWebhookRotateSecretRequestSchema, await parseBoundedJson(request)); const rotated = await webhooks.rotateSecret(subscription); return publicJson({ reference: subscription.publicReference, signingSecret: rotated.secret, signingSecretReference: rotated.record.publicReference }, rid); }
  if (segments[2] === "deliveries" && segments.length === 3 && request.method === "GET") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_DELIVERIES_READ); await limit(context, "webhooks.deliveries.read"); const data = await db.developerWebhookDelivery.findMany({ where: { subscriptionId: subscription.id }, orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map((item: any) => ({ reference: item.publicReference, status: item.status, attemptCount: item.attemptCount, nextAttemptAt: item.nextAttemptAt, createdAt: item.createdAt })) }, rid); }
  if (segments[2] === "deliveries" && segments.length === 4 && request.method === "GET") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_DELIVERIES_READ); await limit(context, "webhooks.deliveries.read"); const delivery = await db.developerWebhookDelivery.findFirst({ where: { publicReference: segments[3]!, subscriptionId: subscription.id } }); if (!delivery) throw new DeveloperApiError("PUBLIC_API_RESOURCE_NOT_FOUND", 404, "The requested resource was not found."); return publicJson({ reference: delivery.publicReference, status: delivery.status, attemptCount: delivery.attemptCount, createdAt: delivery.createdAt, nextAttemptAt: delivery.nextAttemptAt }, rid); }
  if (segments[2] === "deliveries" && segments[4] === "retry" && request.method === "POST") { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_DELIVERIES_RETRY); await limit(context, "webhooks.delivery-retry", "manualDeliveryRetries"); const body = validatePublicBody(PublicWebhookRetryRequestSchema, await parseBoundedJson(request)); const result = await idempotent(context, request, route, body, async () => { const delivery = await db.developerWebhookDelivery.findFirst({ where: { publicReference: assertPublicReference(segments[3]!), subscriptionId: subscription.id } }); if (!delivery) throw new DeveloperApiError("WEBHOOK_DELIVERY_NOT_RETRYABLE", 409, "The delivery cannot be retried."); const updated = await webhooks.requestDeliveryRetry(delivery); return { reference: updated.publicReference, status: updated.status, nextAttemptAt: updated.nextAttemptAt }; }); return publicJson(result.body, rid, result.status); }
  if (request.method === "DELETE" && segments.length === 2) { scopeGrants.assertScope(context.grant, DEVELOPER_SCOPES.WEBHOOKS_WRITE); await limit(context, "webhooks.write"); await webhooks.revoke(subscription); return new Response(null, { status: 204, headers: { "x-request-id": rid } }); }
  void owner; throw new DeveloperApiError("PUBLIC_API_ROUTE_NOT_FOUND", 404, "The requested resource was not found.");
}
