/* eslint-disable @typescript-eslint/no-explicit-any */
import { prisma } from "@/lib/db/prisma";
import { getCurrentUser } from "@/lib/auth/current-user";
import { hasPermission } from "@/lib/auth/permissions";
import { PERMISSIONS } from "@/lib/auth/permission-keys";
import { DeveloperApiError, DEVELOPER_SCOPE_KEYS } from "./contracts";
import { DeveloperApplicationService, DeveloperTermsService, CredentialService, ScopeGrantService, WebhookSubscriptionService, parseBoundedJson } from "./services";
import { opaqueReference } from "./crypto";
import { publicJson, requestId, responseFromError } from "./problem-details";

const db: any = prisma;
const terms = new DeveloperTermsService(db); const applications = new DeveloperApplicationService(db); const scopeGrants = new ScopeGrantService(db); const credentials = new CredentialService(db, terms); const webhooks = new WebhookSubscriptionService(db);
type Actor = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;
async function actor(request: Request, permission: string, mutation = false): Promise<Actor> { const user = await getCurrentUser(); if (!user) throw new DeveloperApiError("SESSION_AUTHENTICATION_REQUIRED", 401, "Authentication required."); if (mutation) { const origin = request.headers.get("origin"); const host = request.headers.get("host"); if (!origin || !host || new URL(origin).host !== host) throw new DeveloperApiError("SAME_ORIGIN_REQUIRED", 403, "A same-origin browser request is required."); } if (!(await hasPermission({ userId: user.id, role: user.role, permissionKey: permission }))) throw new DeveloperApiError("DEVELOPER_PERMISSION_DENIED", 403, "Permission denied."); return user; }
async function ownedApplication(reference: string, user: Actor) { const application = await db.developerApplication.findFirst({ where: { publicReference: reference, ownerUserId: user.id } }); if (!application) throw new DeveloperApiError("DEVELOPER_APPLICATION_NOT_FOUND", 404, "The requested application was not found."); return application; }
function applicationDto(application: any) { return { reference: application.publicReference, name: application.name, environment: application.environment, status: application.status, businessPurpose: application.businessPurpose, version: application.version, approvedAt: application.approvedAt, createdAt: application.createdAt, updatedAt: application.updatedAt }; }
function credentialDto(credential: any) { return { reference: credential.publicReference, prefix: credential.prefix, maskedDisplay: credential.maskedDisplay, status: credential.status, expiresAt: credential.expiresAt, lastUsedAt: credential.lastUsedAt, createdAt: credential.createdAt }; }
function webhookDto(subscription: any) { return { reference: subscription.publicReference, status: subscription.status, endpoint: subscription.maskedEndpoint, eventTypes: subscription.eventSelection, verifiedAt: subscription.verifiedAt, updatedAt: subscription.updatedAt }; }

export async function handleDeveloperSessionApi(request: Request, segments: string[]): Promise<Response> {
  const rid = requestId(request); try {
    const mutation = !["GET", "HEAD"].includes(request.method); const first = segments[0];
    if (first === "applications" && segments.length === 1 && request.method === "GET") { const user = await actor(request, PERMISSIONS.DEVELOPER_APPLICATION_READ_OWN); const data = await db.developerApplication.findMany({ where: { ownerUserId: user.id }, orderBy: { createdAt: "desc" } }); return publicJson({ data: data.map(applicationDto) }, rid); }
    if (first === "applications" && segments.length === 1 && request.method === "POST") { const user = await actor(request, PERMISSIONS.DEVELOPER_APPLICATION_MANAGE_OWN, true); const body = await parseBoundedJson(request); let storeId: string | null = null; if (body.storeBound === true) { const store = await prisma.store.findFirst({ where: { ownerUserId: user.id, status: "ACTIVE" }, select: { id: true } }); if (!store) throw new DeveloperApiError("DEVELOPER_STORE_OWNER_REQUIRED", 403, "An active owned store is required."); storeId = store.id; } const application = await applications.create({ ownerUserId: user.id, storeId, environment: body.environment === "LIVE" ? "LIVE" : "TEST", name: String(body.name ?? ""), businessPurpose: String(body.businessPurpose ?? "") }); return publicJson(applicationDto(application), rid, 201); }
    if (first === "applications" && segments.length >= 2) { const reference = segments[1]!; if (segments.length === 2 && request.method === "GET") { const user = await actor(request, PERMISSIONS.DEVELOPER_APPLICATION_READ_OWN); return publicJson(applicationDto(await ownedApplication(reference, user)), rid); }
      if (segments.length === 2 && request.method === "PATCH") { const user = await actor(request, PERMISSIONS.DEVELOPER_APPLICATION_MANAGE_OWN, true); const application = await ownedApplication(reference, user); if (application.status !== "DRAFT") throw new DeveloperApiError("DEVELOPER_APPLICATION_FROZEN", 409, "Only a draft application can be edited."); const body = await parseBoundedJson(request); const ifMatch = request.headers.get("if-match"); if (!ifMatch || ifMatch !== `\"${application.version}\"`) throw new DeveloperApiError("DEVELOPER_APPLICATION_ETAG_REQUIRED", 412, "A matching ETag is required."); const updated = await db.developerApplication.update({ where: { id: application.id }, data: { ...(typeof body.name === "string" ? { name: body.name.slice(0, 120) } : {}), ...(typeof body.businessPurpose === "string" ? { businessPurpose: body.businessPurpose.slice(0, 2000) } : {}), version: { increment: 1 } } }); return publicJson(applicationDto(updated), rid, 200, { etag: `\"${updated.version}\"` }); }
      if (segments[2] === "submit" && request.method === "POST") { const user = await actor(request, PERMISSIONS.DEVELOPER_APPLICATION_SUBMIT_OWN, true); const application = await ownedApplication(reference, user); await terms.accept(application, user.id, { source: "developer-portal", requestId: rid }); return publicJson(applicationDto(await applications.transition(application, "SUBMITTED", user.id)), rid); }
      if (segments[2] === "terms" && segments[3] === "accept" && request.method === "POST") { const user = await actor(request, PERMISSIONS.DEVELOPER_APPLICATION_MANAGE_OWN, true); const application = await ownedApplication(reference, user); const acceptance = await terms.accept(application, user.id, { source: "developer-portal", requestId: rid }); return publicJson({ reference: acceptance.publicReference, acceptedAt: acceptance.acceptedAt }, rid, 201); }
      if (segments[2] === "review-outcome" && request.method === "GET") { const user = await actor(request, PERMISSIONS.DEVELOPER_APPLICATION_READ_OWN); const application = await ownedApplication(reference, user); const review = await db.developerApplicationReview.findFirst({ where: { applicationId: application.id }, orderBy: [{ createdAt: "desc" }, { id: "desc" }] }); return publicJson({ application: applicationDto(application), outcome: review ? { decision: review.decision, createdAt: review.createdAt, safeReason: review.safeReason } : null }, rid); }
      if (segments[2] === "archive" && request.method === "POST") { const user = await actor(request, PERMISSIONS.DEVELOPER_APPLICATION_MANAGE_OWN, true); return publicJson(applicationDto(await applications.transition(await ownedApplication(reference, user), "ARCHIVED", user.id)), rid); }
      if (segments[2] === "credentials") { const user = await actor(request, request.method === "GET" ? PERMISSIONS.DEVELOPER_CREDENTIAL_READ_OWN : PERMISSIONS.DEVELOPER_CREDENTIAL_CREATE_OWN, mutation); const application = await ownedApplication(reference, user); if (request.method === "GET") { const data = await db.developerApiCredential.findMany({ where: { applicationId: application.id }, orderBy: { createdAt: "desc" } }); return publicJson({ data: data.map(credentialDto) }, rid); } if (request.method === "POST") { const body = await parseBoundedJson(request); const grant = await db.developerScopeGrant.findFirst({ where: { applicationId: application.id, status: "ACTIVE" }, orderBy: { version: "desc" } }); if (!grant) throw new DeveloperApiError("DEVELOPER_SCOPE_GRANT_REQUIRED", 409, "An active approved scope grant is required."); const expiresAt = typeof body.expiresAt === "string" ? new Date(body.expiresAt) : null; if (expiresAt && (Number.isNaN(expiresAt.getTime()) || expiresAt <= new Date())) throw new DeveloperApiError("DEVELOPER_CREDENTIAL_EXPIRY_INVALID", 400); const created = await credentials.create({ application, scopeGrant: grant, actorUserId: user.id, expiresAt }); return publicJson({ credential: credentialDto(created.record), secret: created.secret, secretDisplay: "one-time" }, rid, 201); } }
      if (["usage", "request-log"].includes(segments[2] ?? "") && request.method === "GET") { const user = await actor(request, PERMISSIONS.DEVELOPER_API_USAGE_READ_OWN); const application = await ownedApplication(reference, user); if (segments[2] === "usage") { const data = await db.developerApiQuotaUsage.findMany({ where: { applicationId: application.id }, orderBy: { periodStartedAt: "desc" }, take: 31 }); return publicJson({ data: data.map((item: any) => ({ period: item.period, startedAt: item.periodStartedAt, counters: item.counters })) }, rid); } const data = await db.developerApiRequestAudit.findMany({ where: { applicationId: application.id }, orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map((item: any) => ({ reference: item.publicReference, requestId: item.requestId, route: item.route, method: item.method, status: item.responseStatus, createdAt: item.createdAt })) }, rid); }
      if (segments[2] === "webhooks") { const user = await actor(request, request.method === "GET" ? PERMISSIONS.DEVELOPER_WEBHOOK_READ_OWN : PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, mutation); const application = await ownedApplication(reference, user); if (request.method === "GET") { const data = await db.developerWebhookSubscription.findMany({ where: { applicationId: application.id }, orderBy: { createdAt: "desc" } }); return publicJson({ data: data.map(webhookDto) }, rid); } if (request.method === "POST") { const body = await parseBoundedJson(request); const grant = await db.developerScopeGrant.findFirst({ where: { applicationId: application.id, status: "ACTIVE" }, orderBy: { version: "desc" } }); if (!grant) throw new DeveloperApiError("DEVELOPER_SCOPE_GRANT_REQUIRED", 409); const created = await webhooks.create({ application, scopes: Array.isArray(grant.scopes) ? grant.scopes : [], endpoint: String(body.endpoint ?? ""), eventTypes: Array.isArray(body.eventTypes) ? body.eventTypes.filter((entry): entry is string => typeof entry === "string") : [] }); return publicJson({ subscription: webhookDto(created.subscription), signingSecret: created.secret.value, secretDisplay: "one-time" }, rid, 201); } }
    }
    if (first === "credentials" && segments.length === 3 && ["rotate", "revoke", "compromised"].includes(segments[2]!) && request.method === "POST") { const key = segments[2] === "rotate" ? PERMISSIONS.DEVELOPER_CREDENTIAL_ROTATE_OWN : PERMISSIONS.DEVELOPER_CREDENTIAL_REVOKE_OWN; const user = await actor(request, key, true); const credential = await db.developerApiCredential.findFirst({ where: { publicReference: segments[1]! }, include: { application: false } }); if (!credential) throw new DeveloperApiError("DEVELOPER_CREDENTIAL_NOT_FOUND", 404); const application = await ownedApplication((await db.developerApplication.findUnique({ where: { id: credential.applicationId } })).publicReference, user); if (segments[2] === "revoke") return publicJson(credentialDto(await credentials.revoke(credential)), rid); if (segments[2] === "compromised") return publicJson(credentialDto(await credentials.compromise(credential)), rid); const grant = await db.developerScopeGrant.findUnique({ where: { id: credential.scopeGrantId } }); const created = await credentials.rotate({ credential, application, scopeGrant: grant, actorUserId: user.id }); return publicJson({ credential: credentialDto(created.record), secret: created.secret, secretDisplay: "one-time" }, rid); }
    if (first === "webhooks" && segments.length >= 2) { const permission = segments.includes("deliveries") ? PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_READ_OWN : PERMISSIONS.DEVELOPER_WEBHOOK_READ_OWN; const user = await actor(request, permission, mutation); const subscription = await db.developerWebhookSubscription.findFirst({ where: { publicReference: segments[1]!, application: { ownerUserId: user.id } } }); if (!subscription) throw new DeveloperApiError("DEVELOPER_WEBHOOK_NOT_FOUND", 404); if (segments.length === 2 && request.method === "GET") return publicJson(webhookDto(subscription), rid); if (segments.length === 2 && request.method === "PATCH") { await actor(request, PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, true); const body = await parseBoundedJson(request); const etag = request.headers.get("if-match"); if (!etag || etag !== `\"${subscription.version}\"`) throw new DeveloperApiError("DEVELOPER_WEBHOOK_ETAG_REQUIRED", 412); const updated = await db.developerWebhookSubscription.update({ where: { id: subscription.id }, data: { ...(Array.isArray(body.eventTypes) ? { eventSelection: body.eventTypes.filter((entry): entry is string => typeof entry === "string") } : {}), version: { increment: 1 }, status: "DRAFT", verifiedAt: null } }); return publicJson(webhookDto(updated), rid, 200, { etag: `\"${updated.version}\"` }); }
      if (segments[2] === "verify" && request.method === "POST") { await actor(request, PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, true); const result = await webhooks.requestVerification(subscription); return publicJson({ reference: subscription.publicReference, verificationReference: result.verification.publicReference, status: "VERIFYING" }, rid, 202); }
      if (segments[2] === "rotate-secret" && request.method === "POST") { await actor(request, PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, true); const result = await webhooks.rotateSecret(subscription); return publicJson({ reference: subscription.publicReference, signingSecret: result.secret, secretDisplay: "one-time" }, rid); }
      if (segments[2] === "pause" && request.method === "POST") { await actor(request, PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, true); return publicJson(webhookDto(await webhooks.pause(subscription)), rid); }
      if (segments[2] === "resume" && request.method === "POST") { await actor(request, PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, true); return publicJson(webhookDto(await webhooks.resume(subscription)), rid); }
      if (segments[2] === "revoke" && request.method === "POST") { await actor(request, PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, true); return publicJson(webhookDto(await webhooks.revoke(subscription)), rid); }
      if (segments[2] === "deliveries" && request.method === "GET") { const data = await db.developerWebhookDelivery.findMany({ where: { subscriptionId: subscription.id }, orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map((item: any) => ({ reference: item.publicReference, status: item.status, attemptCount: item.attemptCount, createdAt: item.createdAt, nextAttemptAt: item.nextAttemptAt })) }, rid); }
    }
    if (first === "webhook-deliveries" && segments.length === 2 && request.method === "GET") { const user = await actor(request, PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_READ_OWN); const delivery = await db.developerWebhookDelivery.findFirst({ where: { publicReference: segments[1]!, subscription: { application: { ownerUserId: user.id } } } }); if (!delivery) throw new DeveloperApiError("DEVELOPER_WEBHOOK_DELIVERY_NOT_FOUND", 404); return publicJson({ reference: delivery.publicReference, status: delivery.status, attemptCount: delivery.attemptCount, createdAt: delivery.createdAt, nextAttemptAt: delivery.nextAttemptAt }, rid); }
    if (first === "webhook-deliveries" && segments.length === 3 && segments[2] === "retry" && request.method === "POST") { const user = await actor(request, PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_RETRY_OWN, true); const delivery = await db.developerWebhookDelivery.findFirst({ where: { publicReference: segments[1]!, subscription: { application: { ownerUserId: user.id } } } }); if (!delivery) throw new DeveloperApiError("DEVELOPER_WEBHOOK_DELIVERY_NOT_RETRYABLE", 409); const updated = await webhooks.requestDeliveryRetry(delivery); return publicJson({ reference: updated.publicReference, status: updated.status, nextAttemptAt: updated.nextAttemptAt }, rid); }
    throw new DeveloperApiError("DEVELOPER_ROUTE_NOT_FOUND", 404, "The requested resource was not found.");
  } catch (error) { return responseFromError(error, rid, `/api/developer/${segments.join("/")}`); }
}

export async function handleDeveloperAdminApi(request: Request, segments: string[]): Promise<Response> {
  const rid = requestId(request); try {
    const mutation = !["GET", "HEAD"].includes(request.method); const permission = (key: keyof typeof PERMISSIONS) => actor(request, PERMISSIONS[key], mutation); const first = segments[0];
    if (first === "applications" && segments.length === 1 && request.method === "GET") { await permission("DEVELOPER_APPLICATION_READ"); const data = await db.developerApplication.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map(applicationDto) }, rid); }
    if (first === "applications" && segments.length >= 2) { const application = await db.developerApplication.findUnique({ where: { publicReference: segments[1]! } }); if (!application) throw new DeveloperApiError("DEVELOPER_APPLICATION_NOT_FOUND", 404); if (segments.length === 2 && request.method === "GET") { await permission("DEVELOPER_APPLICATION_READ"); return publicJson(applicationDto(application), rid); }
      const action = segments[2]; const permissions: Record<string, keyof typeof PERMISSIONS> = { "assign-reviewer": "DEVELOPER_APPLICATION_REVIEW", approve: "DEVELOPER_APPLICATION_APPROVE", reject: "DEVELOPER_APPLICATION_REJECT", suspend: "DEVELOPER_APPLICATION_SUSPEND", reactivate: "DEVELOPER_APPLICATION_SUSPEND", revoke: "DEVELOPER_APPLICATION_REVOKE" }; if (action && permissions[action] && request.method === "POST") { const user = await permission(permissions[action]!); if (action === "assign-reviewer") { const review = await db.developerApplicationReview.create({ data: { publicReference: opaqueReference("drev"), applicationId: application.id, reviewerUserId: user.id, decision: "ASSIGNED" } }); return publicJson({ reference: review.publicReference, assignedReviewer: user.id }, rid); } if (action === "approve") { const assignment = await db.developerApplicationReview.findFirst({ where: { applicationId: application.id, decision: "ASSIGNED" }, orderBy: { createdAt: "desc" } }); if (assignment?.reviewerUserId === user.id) throw new DeveloperApiError("DEVELOPER_APPROVAL_SEPARATION_REQUIRED", 403, "The assigned reviewer may not approve the application."); } const transition: Record<string, string> = { approve: "APPROVED", reject: "REJECTED", suspend: "SUSPENDED", reactivate: "ACTIVE", revoke: "REVOKED" }; return publicJson(applicationDto(await applications.transition(application, transition[action]!, user.id, { admin: true })), rid); }
      if (action === "scope-grants") { if (request.method === "GET") { await permission("DEVELOPER_SCOPE_READ"); const data = await db.developerScopeGrant.findMany({ where: { applicationId: application.id }, orderBy: { version: "desc" } }); return publicJson({ data }, rid); } if (request.method === "POST") { const user = await permission("DEVELOPER_SCOPE_MANAGE"); const body = await parseBoundedJson(request); const requested = Array.isArray(body.scopes) ? body.scopes.filter((scope): scope is string => typeof scope === "string" && DEVELOPER_SCOPE_KEYS.includes(scope as any)) : []; if (!requested.length) throw new DeveloperApiError("DEVELOPER_SCOPE_INVALID", 400); const count = await db.developerScopeGrant.count({ where: { applicationId: application.id } }); const grant = await db.developerScopeGrant.create({ data: { publicReference: opaqueReference("dscope"), applicationId: application.id, version: count + 1, ownerUserId: application.ownerUserId, storeId: application.storeId, environment: application.environment, scopes: requested, apiVersion: "v1", status: "DRAFT", approvedByUserId: null } }); void user; return publicJson({ reference: grant.publicReference, status: grant.status, scopes: grant.scopes }, rid, 201); } }
    }
    if (first === "scope-grants" && segments.length === 2 && ["approve", "retire"].includes(segments[1] ?? "") === false && request.method === "GET") { await permission("DEVELOPER_SCOPE_READ"); const grant = await db.developerScopeGrant.findUnique({ where: { publicReference: segments[1]! } }); if (!grant) throw new DeveloperApiError("DEVELOPER_SCOPE_GRANT_NOT_FOUND", 404); return publicJson({ reference: grant.publicReference, status: grant.status, scopes: grant.scopes, version: grant.version }, rid); }
    if (first === "scope-grants" && segments.length === 3 && request.method === "POST") { const grant = await db.developerScopeGrant.findUnique({ where: { publicReference: segments[1]! } }); if (!grant) throw new DeveloperApiError("DEVELOPER_SCOPE_GRANT_NOT_FOUND", 404); const application = await db.developerApplication.findUnique({ where: { id: grant.applicationId } }); if (segments[2] === "approve") { const user = await permission("DEVELOPER_SCOPE_GRANT"); return publicJson(await scopeGrants.approve(grant, application, user.id), rid); } if (segments[2] === "retire") { await permission("DEVELOPER_SCOPE_MANAGE"); return publicJson(await db.developerScopeGrant.update({ where: { id: grant.id }, data: { status: "RETIRED" } }), rid); } }
    if (first === "scopes" && request.method === "GET") { await permission("DEVELOPER_SCOPE_READ"); return publicJson({ data: DEVELOPER_SCOPE_KEYS }, rid); }
    if (first === "credentials" && request.method === "GET") { await permission("DEVELOPER_CREDENTIAL_AUDIT_READ"); const data = await db.developerApiCredential.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map(credentialDto) }, rid); }
    if (first === "credentials" && segments.length === 3 && ["revoke", "compromised"].includes(segments[2]!) && request.method === "POST") { await permission("DEVELOPER_CREDENTIAL_REVOKE"); const credential = await db.developerApiCredential.findUnique({ where: { publicReference: segments[1]! } }); if (!credential) throw new DeveloperApiError("DEVELOPER_CREDENTIAL_NOT_FOUND", 404); return publicJson(credentialDto(segments[2] === "revoke" ? await credentials.revoke(credential) : await credentials.compromise(credential)), rid); }
    if (first === "usage" && request.method === "GET") { await permission("DEVELOPER_API_USAGE_READ"); const data = await db.developerApiQuotaUsage.findMany({ orderBy: { updatedAt: "desc" }, take: 100 }); return publicJson({ data }, rid); }
    if (first === "requests" && request.method === "GET") { await permission("DEVELOPER_API_REQUEST_AUDIT_READ"); if (segments.length === 2) { const entry = await db.developerApiRequestAudit.findUnique({ where: { publicReference: segments[1]! } }); if (!entry) throw new DeveloperApiError("DEVELOPER_REQUEST_NOT_FOUND", 404); return publicJson({ reference: entry.publicReference, requestId: entry.requestId, applicationId: entry.applicationId, route: entry.route, method: entry.method, responseStatus: entry.responseStatus, outcome: entry.outcome, createdAt: entry.createdAt }, rid); } const data = await db.developerApiRequestAudit.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map((entry: any) => ({ reference: entry.publicReference, requestId: entry.requestId, applicationId: entry.applicationId, route: entry.route, method: entry.method, responseStatus: entry.responseStatus, createdAt: entry.createdAt })) }, rid); }
    if (first === "webhooks" && request.method === "GET") { await permission("DEVELOPER_WEBHOOK_READ"); if (segments.length === 2) { const subscription = await db.developerWebhookSubscription.findUnique({ where: { publicReference: segments[1]! } }); if (!subscription) throw new DeveloperApiError("DEVELOPER_WEBHOOK_NOT_FOUND", 404); return publicJson(webhookDto(subscription), rid); } const data = await db.developerWebhookSubscription.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map(webhookDto) }, rid); }
    if (first === "webhooks" && segments.length === 3 && segments[2] === "disable" && request.method === "POST") { await permission("DEVELOPER_WEBHOOK_DISABLE"); const subscription = await db.developerWebhookSubscription.findUnique({ where: { publicReference: segments[1]! } }); if (!subscription) throw new DeveloperApiError("DEVELOPER_WEBHOOK_NOT_FOUND", 404); return publicJson(webhookDto(await webhooks.disable(subscription)), rid); }
    if (first === "webhook-deliveries" && request.method === "GET") { await permission("DEVELOPER_WEBHOOK_DELIVERY_READ"); if (segments.length === 2) { const item = await db.developerWebhookDelivery.findUnique({ where: { publicReference: segments[1]! } }); if (!item) throw new DeveloperApiError("DEVELOPER_WEBHOOK_DELIVERY_NOT_FOUND", 404); return publicJson({ reference: item.publicReference, status: item.status, attemptCount: item.attemptCount, createdAt: item.createdAt, nextAttemptAt: item.nextAttemptAt }, rid); } const data = await db.developerWebhookDelivery.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data: data.map((item: any) => ({ reference: item.publicReference, status: item.status, attemptCount: item.attemptCount, createdAt: item.createdAt })) }, rid); }
    if (first === "webhook-deliveries" && segments.length === 3 && segments[2] === "retry" && request.method === "POST") { await permission("DEVELOPER_WEBHOOK_DELIVERY_RETRY"); const delivery = await db.developerWebhookDelivery.findUnique({ where: { publicReference: segments[1]! } }); if (!delivery) throw new DeveloperApiError("DEVELOPER_WEBHOOK_DELIVERY_NOT_RETRYABLE", 409); const updated = await webhooks.requestDeliveryRetry(delivery); return publicJson({ reference: updated.publicReference, status: updated.status }, rid); }
    if (first === "reconciliation" && request.method === "GET") { await permission("DEVELOPER_RECONCILIATION_READ"); const data = await db.developerApiReconciliationCase.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); return publicJson({ data }, rid); }
    throw new DeveloperApiError("DEVELOPER_ADMIN_ROUTE_NOT_FOUND", 404, "The requested resource was not found.");
  } catch (error) { return responseFromError(error, rid, `/api/admin/developers/${segments.join("/")}`); }
}
