/* eslint-disable @typescript-eslint/no-explicit-any -- in-memory repository fixture intentionally models a dynamic persistence adapter. */
import { afterEach, describe, expect, it, vi } from "vitest";
import { resolveMarketplaceCartLine } from "@/lib/marketplace-checkout/cart.service";
import { addCartLine, claimGuestCart, clearCart, mergeGuestAndCustomerCarts, updateCartLineQuantity, type MarketplaceCartMutationRepository, type MarketplaceCartState } from "@/lib/marketplace-checkout/cart-mutation.service";
const customer = { type: "CUSTOMER" as const, userId: "customer" }; const guest = { type: "GUEST" as const, guestTokenHash: "guest" };
const selection = { offerReference: "offer", variantReference: "variant", productReference: "product", storeId: "store", fulfilmentMode: "COURIER_DELIVERY", publicationVersion: "p1", priceVersion: "price1", unitPrice: "10.00", quantity: 1, modifiers: [] };
function repository(initial: MarketplaceCartState): MarketplaceCartMutationRepository & { state: MarketplaceCartState; receipts: Map<string, any>; transactions: number; lockCartByOwner(owner: any): Promise<MarketplaceCartState | null>; markMerged(): Promise<void>; create(owner: any): Promise<MarketplaceCartState> } { const value: any = { state: initial, receipts: new Map(), transactions: 0, transaction: async (work: any) => { value.transactions += 1; return work(); }, lockCart: async (id: string) => value.state.id === id ? value.state : null, lockCartByOwner: async (owner: any) => (value.state.owner.type === owner.type || owner.type === "GUEST") ? value.state : null, findCartByOwner: async () => value.state, saveCart: async (cart: MarketplaceCartState) => { value.state = cart; }, readOperation: async (_: string, operationId: string) => value.receipts.get(operationId) ?? null, appendOperation: async (_: string, operationId: string, requestHash: string, result: any, type: string) => value.receipts.set(operationId, { requestHash, result, type }), markMerged: async () => {}, create: async () => value.state }; return value; }
describe("marketplace cart mutation service", () => {
  afterEach(() => vi.unstubAllEnvs());
  it("does not resolve cart lines while public marketplace exposure is locked", async () => { vi.stubEnv("KT_LOCAL_STOREFRONT_VALIDATION", "false"); await expect(resolveMarketplaceCartLine({ offerReference: "offer", variantReference: "variant", quantity: 1, modifiers: [] })).rejects.toMatchObject({ code: "CONSOLIDATED_VALIDATION_NOT_APPROVED" }); });
  it("adds an idempotent server-resolved line and replays same meaning", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "ACTIVE", version: 1, lines: [] }); const first = await addCartLine(repo, { cartId: "cart", owner: customer, mutation: { operationId: "operation-add-1", requestHash: "a", expectedVersion: 1 }, selection }); const replay = await addCartLine(repo, { cartId: "cart", owner: customer, mutation: { operationId: "operation-add-1", requestHash: "a", expectedVersion: 1 }, selection }); expect(first.cart.lines).toHaveLength(1); expect(replay.replayed).toBe(true); });
  it("rejects changed-request replay and locked carts", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "CHECKOUT_LOCKED", version: 1, lines: [] }); await expect(addCartLine(repo, { cartId: "cart", owner: customer, mutation: { operationId: "operation-add-2", requestHash: "a", expectedVersion: 1 }, selection })).rejects.toThrow("CART_MUTATION_NOT_ALLOWED"); });
  it("revalidates quantity without accepting a price", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "ACTIVE", version: 1, lines: [{ publicReference: "line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }); const result = await updateCartLineQuantity(repo, { cartId: "cart", lineReference: "line", owner: customer, mutation: { operationId: "operation-quantity-1", requestHash: "q", expectedVersion: 1 }, quantity: 2, revalidate: async (_line, quantity) => ({ ...selection, quantity, unitPrice: "11.00" }) }); expect(result.cart.lines[0]?.selection.unitPrice).toBe("11.00"); expect(result.cart.lines[0]?.quantity).toBe(2); });
  it("clears only an owned mutable cart", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "ACTIVE", version: 1, lines: [{ publicReference: "line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }); await clearCart(repo, { cartId: "cart", owner: customer, mutation: { operationId: "operation-clear-1", requestHash: "c", expectedVersion: 1 } }); expect(repo.state.lines).toHaveLength(0); });
  it("claims a guest cart for a customer without dropping lines", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: guest, status: "ACTIVE", version: 1, lines: [{ publicReference: "line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }); const result = await claimGuestCart(repo, { guestOwner: guest, customerOwner: customer, mutation: { operationId: "operation-claim-1", requestHash: "claim", expectedVersion: 1 }, revalidate: async (line) => line.selection }); expect(result.cart.owner).toEqual(customer); expect(result.cart.lines).toHaveLength(1); });
  it("merges through one transaction and records the canonical merge operation", async () => { const customerCart: MarketplaceCartState = { id: "customer-cart", publicReference: "customer-cart-ref", owner: customer, status: "ACTIVE", version: 1, lines: [] }; const guestCart: MarketplaceCartState = { id: "guest-cart", publicReference: "guest-cart-ref", owner: guest, status: "ACTIVE", version: 1, lines: [{ publicReference: "guest-line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }; const repo = repository(customerCart); const result = await mergeGuestAndCustomerCarts(repo, { guestCart, customerCart, customerOwner: customer, mutation: { operationId: "operation-merge-1", requestHash: "merge", expectedVersion: 1 }, revalidate: async (line) => ({ ...line.selection, unitPrice: "11.00" }) }); expect(repo.transactions).toBe(1); expect(result.cart.lines[0]?.selection.unitPrice).toBe("11.00"); expect(repo.receipts.get("operation-merge-1")?.type).toBe("MERGE"); });
  it("rejects cross-owner cart access attempts", async () => { const otherCustomer = { type: "CUSTOMER" as const, userId: "other-customer" }; const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "ACTIVE", version: 1, lines: [] }); await expect(addCartLine(repo, { cartId: "cart", owner: otherCustomer, mutation: { operationId: "op-cross", requestHash: "hash", expectedVersion: 1 }, selection })).rejects.toThrow("Cart is unavailable."); });
  it("rejects claim when guest cart item revalidation fails", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: guest, status: "ACTIVE", version: 1, lines: [{ publicReference: "guest-line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }); await expect(claimGuestCart(repo, { guestOwner: guest, customerOwner: customer, mutation: { operationId: "op-fail-claim", requestHash: "hash-claim-fail", expectedVersion: 1 }, revalidate: async () => { throw new Error("Unavailable product"); } })).rejects.toThrow("A guest-cart item is no longer available."); });
  it("replays existing claim operation deterministically", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: guest, status: "ACTIVE", version: 1, lines: [{ publicReference: "guest-line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }); const first = await claimGuestCart(repo, { guestOwner: guest, customerOwner: customer, mutation: { operationId: "op-claim-replay", requestHash: "hash-replay", expectedVersion: 1 }, revalidate: async (line) => line.selection }); const replay = await claimGuestCart(repo, { guestOwner: guest, customerOwner: customer, mutation: { operationId: "op-claim-replay", requestHash: "hash-replay", expectedVersion: 1 }, revalidate: async (line) => line.selection }); expect(first.replayed).toBe(false); expect(replay.replayed).toBe(true); expect(replay.cart.id).toBe(first.cart.id); });
});
