/* eslint-disable @typescript-eslint/no-explicit-any -- in-memory repository fixture intentionally models a dynamic persistence adapter. */
import { describe, expect, it } from "vitest";
import { addCartLine, claimGuestCart, clearCart, updateCartLineQuantity, type MarketplaceCartMutationRepository, type MarketplaceCartState } from "@/lib/marketplace-checkout/cart-mutation.service";
const customer = { type: "CUSTOMER" as const, userId: "customer" }; const guest = { type: "GUEST" as const, guestTokenHash: "guest" };
const selection = { offerReference: "offer", variantReference: "variant", productReference: "product", storeId: "store", fulfilmentMode: "COURIER_DELIVERY", publicationVersion: "p1", priceVersion: "price1", unitPrice: "10.00", quantity: 1, modifiers: [] };
function repository(initial: MarketplaceCartState): MarketplaceCartMutationRepository & { state: MarketplaceCartState; receipts: Map<string, any>; lockCartByOwner(owner: any): Promise<MarketplaceCartState | null>; markMerged(): Promise<void>; create(owner: any): Promise<MarketplaceCartState> } { const value: any = { state: initial, receipts: new Map(), transaction: async (work: any) => work(), lockCart: async (id: string) => value.state.id === id ? value.state : null, lockCartByOwner: async (owner: any) => value.state.owner.type === owner.type ? value.state : null, findCartByOwner: async () => value.state, saveCart: async (cart: MarketplaceCartState) => { value.state = cart; }, readOperation: async (_: string, operationId: string) => value.receipts.get(operationId) ?? null, appendOperation: async (_: string, operationId: string, requestHash: string, result: any) => value.receipts.set(operationId, { requestHash, result }), markMerged: async () => {}, create: async () => value.state }; return value; }
describe("marketplace cart mutation service", () => {
  it("adds an idempotent server-resolved line and replays same meaning", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "ACTIVE", version: 1, lines: [] }); const first = await addCartLine(repo, { cartId: "cart", owner: customer, mutation: { operationId: "operation-add-1", requestHash: "a", expectedVersion: 1 }, selection }); const replay = await addCartLine(repo, { cartId: "cart", owner: customer, mutation: { operationId: "operation-add-1", requestHash: "a", expectedVersion: 1 }, selection }); expect(first.cart.lines).toHaveLength(1); expect(replay.replayed).toBe(true); });
  it("rejects changed-request replay and locked carts", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "CHECKOUT_LOCKED", version: 1, lines: [] }); await expect(addCartLine(repo, { cartId: "cart", owner: customer, mutation: { operationId: "operation-add-2", requestHash: "a", expectedVersion: 1 }, selection })).rejects.toThrow("CART_MUTATION_NOT_ALLOWED"); });
  it("revalidates quantity without accepting a price", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "ACTIVE", version: 1, lines: [{ publicReference: "line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }); const result = await updateCartLineQuantity(repo, { cartId: "cart", lineReference: "line", owner: customer, mutation: { operationId: "operation-quantity-1", requestHash: "q", expectedVersion: 1 }, quantity: 2, revalidate: async (_line, quantity) => ({ ...selection, quantity, unitPrice: "11.00" }) }); expect(result.cart.lines[0]?.selection.unitPrice).toBe("11.00"); expect(result.cart.lines[0]?.quantity).toBe(2); });
  it("clears only an owned mutable cart", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: customer, status: "ACTIVE", version: 1, lines: [{ publicReference: "line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }); await clearCart(repo, { cartId: "cart", owner: customer, mutation: { operationId: "operation-clear-1", requestHash: "c", expectedVersion: 1 } }); expect(repo.state.lines).toHaveLength(0); });
  it("claims a guest cart for a customer without dropping lines", async () => { const repo = repository({ id: "cart", publicReference: "cart-ref", owner: guest, status: "ACTIVE", version: 1, lines: [{ publicReference: "line", storeId: "store", quantity: 1, fingerprint: "fingerprint", selection }] }); const result = await claimGuestCart(repo as any, { guestOwner: guest, customerOwner: customer, mutation: { operationId: "operation-claim-1", requestHash: "claim", expectedVersion: 1 } }); expect(result.cart.owner).toEqual(customer); expect(result.cart.lines).toHaveLength(1); });
});
