/* eslint-disable @typescript-eslint/no-explicit-any -- in-memory financial transaction fixture deliberately has minimal dynamic methods. */
import { describe, expect, it } from "vitest";
import { consumeMarketplaceCheckoutReservation, holdReservationForUncertainPayment, reserveMarketplaceCheckoutInventory } from "@/lib/marketplace-checkout/inventory-reservation.service";
import { finalizePaidMarketplaceCheckout } from "@/lib/marketplace-checkout/marketplace-checkout-finalization.service";
import { prepareMarketplaceCheckoutPayment } from "@/lib/marketplace-checkout/marketplace-payment-preparation.service";
describe("marketplace financial runtime services", () => {
  it("locks stable inventory order, reserves, holds and consumes exactly once", async () => { const moves: string[] = []; let reservation: any = null; const repository: any = { transaction: async (work: any) => work(), lockCheckout: async () => ({ id: "checkout", status: "READY_FOR_REVIEW", acceptedFingerprint: "fingerprint", reviewAcceptedAt: new Date() }), lockLevelsInStableOrder: async (ids: string[]) => { expect(ids).toEqual(["a", "b"]); return ids.map((id) => ({ id, onHand: 10, reserved: 0, available: 10 })); }, findActiveReservation: async () => reservation, createReservation: async (item: any) => (reservation = item), updateReservation: async (_: string, patch: any) => (reservation = { ...reservation, ...patch }), applyLevelReservation: async () => {}, applyLevelCommitment: async () => {}, appendMovement: async (item: any) => { moves.push(item.type); }, updateCheckout: async () => {} }; const created = await reserveMarketplaceCheckoutInventory(repository, { checkoutId: "checkout", publicReference: "reservation", commercialFingerprint: "fingerprint", expiresAt: new Date(Date.now() + 60_000), operationId: "operation-reserve-1", lines: [{ lineReference: "line-a", inventoryLevelId: "b", inventoryItemReference: "item-b", locationReference: "location", quantity: 1 }, { lineReference: "line-b", inventoryLevelId: "a", inventoryItemReference: "item-a", locationReference: "location", quantity: 1 }] }); await holdReservationForUncertainPayment(repository, created, "payment"); await consumeMarketplaceCheckoutReservation(repository, { reservation, paymentId: "payment", operationId: "operation-consume-1" }); expect(moves).toEqual(["RESERVATION", "RESERVATION", "SALE_COMMITMENT", "SALE_COMMITMENT"]); });
  it("binds one exact accepted checkout payment and replays same payment", async () => { let linked = ""; const result = await prepareMarketplaceCheckoutPayment({ transaction: async (work) => work(), lockCheckout: async () => ({ id: "checkout", publicReference: "checkout-ref", customerUserId: null, guestAccessTokenHash: null, status: "RESERVED", grandTotal: "25.00", currency: "ZAR", acceptedFingerprint: "fingerprint", payment: null }), linkPayment: async (_checkout, payment) => { linked = payment; }, transitionCheckout: async () => {} }, { prepareMarketplacePayment: async () => ({ paymentReference: "payment-ref", paymentId: "payment", amount: "25.00", currency: "ZAR", providerAction: null, replayed: false }) }, { checkoutReference: "checkout-ref", payerEmail: "guest@example.test", operationId: "operation-payment-1", testApproval: { approved: true } }); expect(result.paymentReference).toBe("payment-ref"); expect(linked).toBe("payment"); });
  it("creates a parent and every store order only after verified payment", async () => { const calls: string[] = []; const result = await finalizePaidMarketplaceCheckout({ transaction: async (work) => work(), lockVerifiedSuccessfulPayment: async () => ({ id: "payment", publicReference: "payment-ref", status: "SUCCEEDED", amount: "10.00", currency: "ZAR", marketplaceCheckoutId: "checkout" }), findOrderByCheckout: async () => null, lockCheckout: async () => ({ id: "checkout", publicReference: "checkout-ref", cartId: "cart", status: "PAYMENT_CONFIRMED", currency: "ZAR", grandTotal: "10.00", commercialFingerprint: "fingerprint", customerUserId: null, storeGroups: [{ storeId: "store", storeReference: "store", merchandiseSubtotal: "10.00", modifierSubtotal: "0.00", deliveryFee: "0.00", groupTotal: "10.00", sellerIdentityEvidence: null, taxEvidence: null, termsReference: null, refundPolicyReference: null, lines: [], settlement: { commissionPlanReference: null, commissionPlanVersion: null, sellerBasis: "10.00", commissionAmount: "1.00", storeEarningAmount: "9.00", deliveryFeeResidual: "0.00", sourceEvidenceFingerprint: "f", sourceSettlementEvidenceId: "evidence", sourceCheckoutId: "checkout", sourceCheckoutReviewVersion: 2, sourceCheckoutStoreGroupId: "group", sourceCommercialFingerprint: "fingerprint" } }] }), lockReservation: async () => ({ id: "reservation", status: "ACTIVE", commercialFingerprint: "fingerprint" }), consumeReservation: async () => { calls.push("consume"); }, createMarketplaceOrder: async () => ({ id: "order", publicReference: "order-ref" }), createMarketplaceStoreOrder: async () => ({ id: "store-order", publicReference: "store-order-ref" }), createOrderLineEvidence: async () => {}, createSettlementSnapshot: async () => { calls.push("settlement"); }, completeCheckoutAndConvertCart: async () => { calls.push("complete"); } }, { paymentId: "payment", checkoutId: "checkout", operationId: "operation-finalize-1", testApproval: { approved: true } }); expect(result).toEqual({ publicReference: "order-ref", replayed: false }); expect(calls).toEqual(["consume", "settlement", "complete"]); });
});
