import { notFound } from "next/navigation";
import { AdministrationPanel } from "@/components/protected-v2/admin/AdministrationRoutePrimitives";
import { ProtectedPageHeader } from "@/components/protected-v2/surfaces/ProtectedPageHeader";
import { StoreEarningReversalForm } from "@/components/store-earnings/StoreEarningReversalForm";
import { PERMISSIONS } from "@/lib/auth/permission-keys";
import { getFinanceStoreEarning } from "@/lib/services/store-earning-query.service";
import { hasStoreEarningFinancePermission, requireStoreEarningFinancePagePermission } from "@/lib/store-earnings/finance-permission";

export default async function AdminStoreEarningDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireStoreEarningFinancePagePermission(PERMISSIONS.STORE_EARNINGS_READ); const earning = await getFinanceStoreEarning((await params).id); if (!earning) notFound(); const canReverse = (earning.status === "ACCRUED" || earning.status === "RECONCILIATION_REQUIRED") && await hasStoreEarningFinancePermission(user, PERMISSIONS.STORE_EARNINGS_REVERSE);
  return <div className="max-w-6xl space-y-6"><ProtectedPageHeader eyebrow="Finance store entitlement" title="Store Earnings" description={`${earning.publicReference} — ${earning.status}`} /><AdministrationPanel><dl className="grid gap-x-6 gap-y-2 text-sm sm:grid-cols-[12rem_minmax(0,1fr)] [&>dt]:font-semibold [&>dd]:min-w-0 [&>dd]:break-words"><dt>Store</dt><dd>{earning.storePublicReference}</dd><dt>Subject</dt><dd>{earning.subjectPublicReference}</dd><dt>Payment</dt><dd>{earning.paymentPublicReference}</dd><dt>Settlement version</dt><dd>{earning.settlementVersion}</dd><dt>Basis</dt><dd>R {earning.settlementBasisAmount}</dd><dt>Attributed commission</dt><dd>R {earning.attributedCommissionAmount}</dd><dt>Net earning</dt><dd>R {earning.originalEarningAmount}</dd><dt>Refund reserved / refunded</dt><dd>R {earning.refundReservedAmount} / R {earning.refundedAmount}</dd><dt>Available payable</dt><dd>R {earning.availablePayableAmount}</dd><dt>Release eligibility</dt><dd>{earning.releaseEligibleAt ?? "Not established"}</dd><dt>Accrual / release / reversal journals</dt><dd>{earning.journals.accrual} / {earning.journals.release ?? "None"} / {earning.journals.reversal ?? "None"}</dd></dl></AdministrationPanel><AdministrationPanel><h2 className="mb-3 text-lg font-semibold">Commission attribution</h2><div className="eo-table-wrap" role="region" aria-label="Store earning commission attribution" tabIndex={0}><table className="eo-table min-w-[900px]" aria-label="Store earning commission attribution"><thead><tr><th>Charge</th><th>Allocation</th><th>Accrual</th><th>Amount</th><th>Status</th></tr></thead><tbody>{earning.commissionCharges.map((charge) => <tr key={charge.publicReference}><td>{charge.publicReference}</td><td>{charge.commissionAllocationReference}</td><td>{charge.commissionAccrualReference}</td><td className="is-numeric whitespace-nowrap">R {charge.amount}</td><td>{charge.allocationStatus}</td></tr>)}</tbody></table></div></AdministrationPanel><AdministrationPanel><h2 className="mb-3 text-lg font-semibold">History and reconciliation</h2><ul className="space-y-2 break-words text-sm">{earning.history.map((event, index) => <li key={`${event.createdAt}-${index}`}>{event.toStatus} — {event.reasonCode ?? "No reason"} — {event.createdAt}</li>)}</ul><ul className="space-y-2 break-words text-sm">{earning.reconciliation.map((record) => <li key={record.publicReference}>{record.publicReference}: {record.reason} / {record.status}</li>)}</ul></AdministrationPanel>{canReverse ? <AdministrationPanel><StoreEarningReversalForm earningId={earning.id} /></AdministrationPanel> : null}</div>;
}
