import Link from "next/link";
import Image from "next/image";
import type { StorefrontDocument, StorefrontProductCard } from "@/lib/storefront/storefront-types";
import { AVAILABILITY_ADVISORY, availabilityLabel } from "@/lib/storefront/storefront-availability-policy";
import { marketplaceCategoriesHref, marketplaceHref, marketplaceProductHref, marketplaceStoresHref, marketplaceVariantHref } from "@/lib/public-marketplace/routes";

export function StorefrontHeader() { return <><a href="#storefront-content" className="sr-only focus:not-sr-only focus:absolute focus:z-50 focus:m-3 focus:rounded focus:bg-white focus:p-3">Skip to shop content</a><section className="border-b border-black/10 bg-white"><div className="container-public flex flex-wrap items-center justify-between gap-3 py-3"><Link className="font-display text-lg font-black text-[var(--kt-brand-navy)]" href={marketplaceHref()}>Shop</Link><nav aria-label="Shop navigation" className="flex gap-4 text-sm font-semibold"><Link href={marketplaceCategoriesHref()}>Categories</Link><Link href={marketplaceStoresHref()}>Stores</Link></nav></div></section></>; }
export function PriceDisplay({ price, from = false }: { price: { amount: string; currency: "ZAR"; unitAmount?: string; unit?: string; quantity?: string }; from?: boolean }) { return <p className="font-semibold text-[var(--kt-brand-navy)]">{from ? "From " : ""}{new Intl.NumberFormat("en-ZA", { style: "currency", currency: price.currency }).format(Number(price.amount))}<span className="ml-1 text-xs font-normal text-[var(--kt-text-muted)]">VAT included</span>{price.unitAmount && price.unit ? <span className="block text-sm font-normal text-[var(--kt-text-muted)]">{new Intl.NumberFormat("en-ZA", { style: "currency", currency: price.currency }).format(Number(price.unitAmount))} per {price.unit}</span> : null}</p>; }
export function AvailabilityBadge({ value }: { value: StorefrontDocument["availability"] }) { return <span className="inline-flex rounded-full bg-[var(--kt-studio-mist)] px-2.5 py-1 text-xs font-semibold text-[var(--kt-brand-navy)]">{availabilityLabel(value)}</span>; }
export function ProductMedia({ media, title, className = "" }: { media?: StorefrontDocument["primaryMedia"]; title: string; className?: string }) { return media ? <Image src={`/api/catalog/media/${media.publicReference}`} width={media.width} height={media.height} alt={media.alt} className={`h-full w-full rounded-xl object-cover ${className}`} sizes="(max-width: 1024px) 100vw, 50vw" /> : <div className={`h-full w-full bg-[var(--kt-studio-mist)] ${className}`} aria-label={`${title} image unavailable`} role="img" />; }
export function ProductCard({ product }: { product: StorefrontProductCard }) { const href = marketplaceVariantHref(product.productSlug, product.productReference, product.representativeVariantReference) ?? marketplaceProductHref(product.productSlug, product.productReference) ?? marketplaceHref(); return <article className="flex min-w-0 flex-col rounded-xl border border-black/10 bg-white p-4 shadow-sm"><div className="aspect-square overflow-hidden rounded-lg"><ProductMedia media={product.primaryMedia} title={product.title} /></div> <div className="mt-4 space-y-2"><h2 className="font-display text-lg font-bold text-[var(--kt-brand-navy)]"><Link href={href}>{product.title}</Link></h2>{product.brandName ? <p className="text-sm text-[var(--kt-text-muted)]">{product.brandName}</p> : null}<PriceDisplay price={{ amount: product.price.amount, currency: product.price.currency }} from={product.price.from} /><AvailabilityBadge value={product.availability} /></div></article>; }
export function ProductGrid({ products }: { products: StorefrontProductCard[] }) { return <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <ProductCard key={product.productReference} product={product} />)}</div>; }
export function StorefrontEmptyState({ title, children }: { title: string; children: React.ReactNode }) { return <div role="status" className="rounded-xl border border-dashed border-black/20 bg-white p-8 text-center"><h2 className="font-display text-xl font-bold text-[var(--kt-brand-navy)]">{title}</h2><p className="mt-2 text-[var(--kt-text-muted)]">{children}</p></div>; }
export function Breadcrumbs({ items }: { items: Array<{ label: string; href?: string }> }) { return <nav aria-label="Breadcrumb" className="mb-5 text-sm text-[var(--kt-text-muted)]"><ol className="flex flex-wrap gap-2">{items.map((item, index) => <li key={`${item.label}:${index}`} className="flex gap-2">{index > 0 ? <span aria-hidden>/</span> : null}{item.href ? <Link href={item.href}>{item.label}</Link> : <span aria-current="page">{item.label}</span>}</li>)}</ol></nav>; }
export function OfferList({ offers }: { offers: StorefrontDocument[] }) { return <section aria-labelledby="offers-heading" className="space-y-3"><h2 id="offers-heading" className="font-display text-2xl font-bold text-[var(--kt-brand-navy)]">Available offers</h2>{offers.map((offer) => <article className="rounded-xl border border-black/10 bg-white p-4" key={offer.publicReference}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{offer.storeSlug}</h3><p className="text-sm text-[var(--kt-text-muted)]">{offer.fulfilmentMode.replaceAll("_", " ")}</p></div><PriceDisplay price={offer.price} /></div><div className="mt-3 flex flex-wrap gap-2"><AvailabilityBadge value={offer.availability} /><span className="text-sm text-[var(--kt-text-muted)]">{AVAILABILITY_ADVISORY}</span></div></article>)}</section>; }
