import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
const root = process.cwd(); const read = (file: string) => readFileSync(join(root, file), "utf8");
describe("Phase 28 source authority audit", () => {
  it("uses opaque scoped bearer credentials and no OAuth or JWT API-key authority", () => { const source = read("lib/developer-api/gateway.ts") + read("lib/developer-api/crypto.ts"); expect(source).toContain("authorization"); expect(source).toContain("Bearer"); expect(source).not.toMatch(/jwt|oauth|refresh[_-]?token/i); expect(source).not.toMatch(/query.*credential/i); });
  it("authenticates the API root and rejects inactive credential owners", () => { const gateway = read("lib/developer-api/gateway.ts"); const owner = read("lib/developer-api/public-resource-adapters.ts"); expect(gateway.indexOf("context = await authorize(request)")).toBeLessThan(gateway.indexOf('!segments.length && request.method === "GET"')); expect(owner).toContain('user.status !== "ACTIVE"'); });
  it("keeps public route files free of direct Prisma business mutation", () => { const route = read("app/api/v1/[...segments]/route.ts"); expect(route).not.toMatch(/prisma\.|\.create\(|\.update\(|\.delete\(/); expect(route).toContain("handlePublicApi"); });
  it("contains strict webhook endpoint and signature controls", () => { const source = read("lib/developer-api/services.ts"); expect(source).toContain("validateWebhookEndpoint"); expect(source).toContain("isIP"); expect(source).toContain("content-digest"); expect(source).toContain("@target-uri"); expect(source).not.toMatch(/redirect:\s*"follow"/); });
  it("keeps the processor runner source-backed and the public event projection explicit", () => { const runner = read("scripts/phase28-processor-runner.ts"); const processor = read("lib/developer-api/processor-service.ts"); const projection = read("lib/developer-api/webhook-projection.ts"); expect(runner).toContain("processors.select"); expect(runner).not.toContain("selectedCandidates: 0"); expect(processor).toContain("orderBy"); expect(projection).toContain("payloadHash"); expect(projection).toContain("developerWebhookDelivery.create"); });
  it("keeps the migration additive and free of operational data", () => { const migration = read("prisma/migrations/20260727000000_phase28_public_api_webhooks/migration.sql"); expect(migration).toContain('CREATE TABLE "DeveloperApplication"'); expect(migration).not.toMatch(/\bDROP\b|\bINSERT\b|\bUPDATE\b/i); });
  it("publishes a safe contract and discovery document", () => { expect(read("app/.well-known/api-catalog/route.ts")).toContain("openapi"); expect(read("lib/developer-api/openapi.ts")).toContain("3.1.2"); expect(read("openapi/kt-couriers-v1.json")).toContain("/webhooks"); });
});
