import { beforeEach, describe, expect, it } from "vitest";
import { DEVELOPER_SCOPE_KEYS, DEVELOPER_SCOPES, DeveloperApiError, allowsScope, productionLocked } from "@/lib/developer-api/contracts";
import { CursorService, classifyWebhookFailure, classifyWebhookResponse, contentDigest, parsePagination, retryAt, signWebhookRequest, validateWebhookEndpoint } from "@/lib/developer-api/services";
import { credentialFingerprint, generateCredential, maskCredential, validateCredentialFormat } from "@/lib/developer-api/crypto";

beforeEach(() => { process.env.DEVELOPER_API_CREDENTIAL_HMAC_KEY = "x".repeat(48); process.env.DEVELOPER_WEBHOOK_ENCRYPTION_KEY = Buffer.alloc(32, 7).toString("base64"); });
describe("Phase 28 public developer API policy", () => {
  it("has an exact read-only financial scope extension with no wildcard or financial administration scope", () => { expect(DEVELOPER_SCOPE_KEYS).toHaveLength(15); expect(DEVELOPER_SCOPE_KEYS).toEqual(expect.arrayContaining([DEVELOPER_SCOPES.PAYMENTS_READ, DEVELOPER_SCOPES.REFUNDS_READ, DEVELOPER_SCOPES.SUBSCRIPTIONS_READ])); expect(DEVELOPER_SCOPE_KEYS).not.toContain("*"); expect(DEVELOPER_SCOPE_KEYS.some((scope) => /finance|wallet|withdraw|admin|recruitment|promoter/.test(scope))).toBe(false); expect(allowsScope([DEVELOPER_SCOPES.ORDERS_READ], DEVELOPER_SCOPES.ORDERS_WRITE)).toBe(false); });
  it("creates high-entropy opaque environment-prefixed credentials without exposing their hash", () => { const credential = generateCredential("TEST"); expect(validateCredentialFormat(credential)).toBe("TEST"); expect(credential).toMatch(/^kt_test_/); expect(credential.length).toBeGreaterThan(50); expect(maskCredential(credential)).not.toContain(credential.slice(12, -4)); expect(credentialFingerprint(credential)).toMatch(/^[a-f0-9]{64}$/); });
  it("binds cursor payloads and rejects filter mismatches", () => { const cursor = new CursorService("z".repeat(48)); const token = cursor.encode({ owner: "owner-a", status: "ACTIVE", last: "ref-a" }); expect(cursor.decode(token, { owner: "owner-a", status: "ACTIVE" }).last).toBe("ref-a"); expect(() => cursor.decode(token, { owner: "owner-b", status: "ACTIVE" })).toThrow(DeveloperApiError); });
  it("bounds pagination and rejects arbitrary filters", () => { expect(parsePagination(new URLSearchParams("limit=25&status=ACTIVE"), ["status"])).toMatchObject({ limit: 25, filters: { status: "ACTIVE" } }); expect(() => parsePagination(new URLSearchParams("limit=101"))).toThrow(DeveloperApiError); expect(() => parsePagination(new URLSearchParams("include=owner"))).toThrow(DeveloperApiError); });
  it("rejects private webhook destinations before delivery", async () => { await expect(validateWebhookEndpoint("https://example.test/hook", { resolver: async () => [{ address: "127.0.0.1" }] })).rejects.toThrow(DeveloperApiError); await expect(validateWebhookEndpoint("http://example.test/hook", { resolver: async () => [{ address: "8.8.8.8" }] })).rejects.toThrow(DeveloperApiError); });
  it("signs raw webhook bytes with digest and covered headers", () => { const raw = Buffer.from('{"event":"x"}'); const signed = signWebhookRequest({ secret: "s".repeat(32), method: "POST", targetUri: "https://example.test/hook", rawBody: raw, webhookId: "evt_1", timestamp: "2026-07-27T00:00:00.000Z", keyId: "v1" }); expect(signed["content-digest"]).toBe(contentDigest(raw)); expect(signed["signature-input"]).toContain("@target-uri"); expect(signed.signature).toMatch(/^sig1=:/); });
  it("uses bounded retries and never treats a redirect as success", () => { expect(classifyWebhookResponse(302).retryable).toBe(false); expect(classifyWebhookResponse(429).retryable).toBe(true); expect(classifyWebhookResponse(410).disableEndpoint).toBe(true); expect(retryAt(99).getTime()).toBeGreaterThan(Date.now()); });
  it("does not retry blocked endpoints or oversized webhook responses", () => { expect(classifyWebhookFailure(new DeveloperApiError("WEBHOOK_RESPONSE_TOO_LARGE", 502)).retryable).toBe(false); expect(classifyWebhookFailure(new DeveloperApiError("WEBHOOK_ENDPOINT_UNSAFE", 400)).retryable).toBe(false); });
  it("keeps live activation locked", () => { expect(productionLocked("LIVE")).toBe(true); expect(productionLocked("TEST")).toBe(false); });
});
