import Link from "next/link";
import { EditorialTable, MetricTile, OperationalPanel, ProtectedContentGrid, ProtectedPageFrame, ProtectedPageHeader, ProtectedState, ProtectedStatus } from "@/components/protected-v2";
import { DEVELOPER_API_PRODUCTION_LOCK_REASON, DEVELOPER_API_VERSION, WEBHOOK_EVENT_CATALOG } from "@/lib/developer-api/contracts";
import { selectDeveloperOperationalState, getDeveloperApplicationStatus, getDeveloperCredentialStatus, getDeveloperDeliveryStatus, getDeveloperEnvironmentStatus, getDeveloperWebhookStatus, type DeveloperPortalRoute } from "@/lib/developer-presentation";
import type { DeveloperApplicationRecord, DeveloperCredentialRecord, DeveloperDeliveryRecord, DeveloperOwnerCapabilities, DeveloperPresentationSnapshot, DeveloperQuotaRecord, DeveloperRequestRecord, DeveloperWebhookRecord } from "@/lib/developer-presentation";
import { DeveloperApplicationCreateForm, DeveloperCredentialActions, DeveloperDeliveryRetryAction, DeveloperWebhookActions, DeveloperWebhookCreateForm } from "./DeveloperPortalActions";
import styles from "./developer-pages.module.css";

const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const shortDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium" }).format(new Date(value)) : "—";
const eventTypes = Object.keys(WEBHOOK_EVENT_CATALOG);

function DeveloperPage({ children, eyebrow, title, description, actions, rail }: { children: React.ReactNode; eyebrow: string; title: string; description: string; actions?: React.ReactNode; rail?: React.ReactNode }) {
  return <div className={styles.scope}><ProtectedPageFrame><ProtectedPageHeader eyebrow={eyebrow} title={title} description={description} actions={actions} />{rail ? <ProtectedContentGrid contextRail={rail}>{children}</ProtectedContentGrid> : children}</ProtectedPageFrame></div>;
}

function ApplicationStatus({ application }: { application: DeveloperApplicationRecord }) { const status = getDeveloperApplicationStatus(application.status); return <ProtectedStatus label={status.label} tone={status.tone} />; }
function CredentialStatus({ credential }: { credential: DeveloperCredentialRecord }) { const status = getDeveloperCredentialStatus(credential.status); return <ProtectedStatus label={status.label} tone={status.tone} />; }
function WebhookStatus({ webhook }: { webhook: DeveloperWebhookRecord }) { const status = getDeveloperWebhookStatus(webhook.status); return <ProtectedStatus label={status.label} tone={status.tone} />; }
function DeliveryStatus({ delivery }: { delivery: DeveloperDeliveryRecord }) { const status = getDeveloperDeliveryStatus(delivery.status); return <ProtectedStatus label={status.label} tone={status.tone} />; }

function ApplicationTable({ applications }: { applications: readonly DeveloperApplicationRecord[] }) {
  return <EditorialTable caption="Owner-scoped developer applications" mobileMode="stack" rows={applications} emptyState={<p className="eo-table-empty" role="status">No developer applications are available.</p>} columns={[
    { id: "application", header: "Application", priority: "primary", cell: (application) => <Link className="font-semibold text-[var(--eo-operational)] hover:underline" href={`/developers/applications/${application.reference}`}>{application.name}</Link> },
    { id: "environment", header: "Environment", cell: (application) => { const environment = getDeveloperEnvironmentStatus(application.environment, application.productionLocked); return <ProtectedStatus label={environment.label} tone={environment.tone} />; } },
    { id: "status", header: "Lifecycle", cell: (application) => <ApplicationStatus application={application} /> },
    { id: "scopes", header: "Approved scopes", align: "end", priority: "secondary", cell: (application) => application.scopeGrants.flatMap((grant) => grant.scopes.filter((scope) => scope.state === "approved")).length },
    { id: "created", header: "Created", priority: "optional", cell: (application) => shortDate(application.createdAt) },
  ]} />;
}

function CredentialTable({ credentials, capabilities }: { credentials: readonly DeveloperCredentialRecord[]; capabilities: DeveloperOwnerCapabilities }) {
  return <EditorialTable caption="Owner-scoped credential records" mobileMode="stack" rows={credentials} emptyState={<p className="eo-table-empty" role="status">No credential records are available.</p>} columns={[
    { id: "credential", header: "Credential", priority: "primary", cell: (credential) => <div><code>{credential.maskedDisplay}</code><p className={styles.recordMeta}>{credential.applicationName}</p></div> },
    { id: "environment", header: "Environment", cell: (credential) => credential.environment === "TEST" ? "Test" : "Live" },
    { id: "status", header: "State", cell: (credential) => <CredentialStatus credential={credential} /> },
    { id: "used", header: "Last used", priority: "secondary", cell: (credential) => dateTime(credential.lastUsedAt) },
    { id: "expires", header: "Expires", priority: "optional", cell: (credential) => dateTime(credential.expiresAt) },
    { id: "actions", header: "Security action", priority: "secondary", cell: (credential) => <DeveloperCredentialActions credentialReference={credential.reference} canCreate={false} canRotate={capabilities.canRotateCredentials && credential.status === "ACTIVE"} canRevoke={capabilities.canRevokeCredentials && !["REVOKED", "EXPIRED"].includes(credential.status)} /> },
  ]} />;
}

function WebhookTable({ webhooks }: { webhooks: readonly DeveloperWebhookRecord[] }) {
  return <EditorialTable caption="Owner-scoped webhook endpoints" mobileMode="stack" rows={webhooks} emptyState={<p className="eo-table-empty" role="status">No webhook endpoints are available.</p>} columns={[
    { id: "endpoint", header: "Endpoint", priority: "primary", cell: (webhook) => <Link className="font-mono text-sm font-semibold text-[var(--eo-operational)] hover:underline" href={`/developers/webhooks/${webhook.reference}`}>{webhook.endpoint}</Link> },
    { id: "application", header: "Application", priority: "secondary", cell: (webhook) => webhook.applicationName },
    { id: "environment", header: "Environment", cell: (webhook) => webhook.environment === "TEST" ? "Test" : "Live" },
    { id: "state", header: "State", cell: (webhook) => <WebhookStatus webhook={webhook} /> },
    { id: "subscriptions", header: "Events", align: "end", priority: "secondary", cell: (webhook) => webhook.eventTypes.length },
  ]} />;
}

function DeliveryTable({ deliveries }: { deliveries: readonly DeveloperDeliveryRecord[] }) {
  return <EditorialTable caption="Safe webhook delivery metadata" mobileMode="stack" rows={deliveries} emptyState={<p className="eo-table-empty" role="status">No webhook deliveries are available.</p>} columns={[
    { id: "event", header: "Event", priority: "primary", cell: (delivery) => <Link className="font-mono text-sm font-semibold text-[var(--eo-operational)] hover:underline" href={`/developers/webhook-deliveries/${delivery.reference}`}>{delivery.eventType ?? "Event metadata unavailable"}</Link> },
    { id: "endpoint", header: "Endpoint", priority: "secondary", cell: (delivery) => delivery.webhookEndpoint },
    { id: "state", header: "Delivery state", cell: (delivery) => <DeliveryStatus delivery={delivery} /> },
    { id: "attempts", header: "Attempts", align: "end", priority: "secondary", cell: (delivery) => delivery.attemptCount },
    { id: "created", header: "Created", priority: "optional", cell: (delivery) => dateTime(delivery.createdAt) },
  ]} />;
}

function QuotaTable({ quotas }: { quotas: readonly DeveloperQuotaRecord[] }) {
  const rows = quotas.flatMap((quota) => Object.entries(quota.counters).map(([dimension, used]) => ({ id: `${quota.id}-${dimension}`, applicationName: quota.applicationName, dimension, used, period: quota.period, startedAt: quota.startedAt })));
  return <EditorialTable caption="Recorded quota usage" mobileMode="stack" rows={rows} emptyState={<p className="eo-table-empty" role="status">No owner-scoped quota usage is available.</p>} columns={[
    { id: "application", header: "Application", priority: "primary", cell: (row) => row.applicationName },
    { id: "dimension", header: "Quota dimension", cell: (row) => row.dimension },
    { id: "used", header: "Recorded use", align: "end", cell: (row) => row.used },
    { id: "period", header: "Period", priority: "secondary", cell: (row) => row.period },
    { id: "started", header: "Period started", priority: "optional", cell: (row) => dateTime(row.startedAt) },
  ]} />;
}

function RequestTable({ requests }: { requests: readonly DeveloperRequestRecord[] }) {
  return <EditorialTable caption="Owner-scoped API request metadata" mobileMode="stack" rows={requests} emptyState={<p className="eo-table-empty" role="status">No developer API request activity is available.</p>} columns={[
    { id: "request", header: "Request", priority: "primary", cell: (request) => <code>{request.requestId}</code> },
    { id: "operation", header: "Operation", cell: (request) => <span><code>{request.method}</code> {request.route}</span> },
    { id: "status", header: "Response", align: "end", cell: (request) => request.responseStatus },
    { id: "application", header: "Application", priority: "secondary", cell: (request) => request.applicationName },
    { id: "at", header: "Recorded", priority: "optional", cell: (request) => dateTime(request.createdAt) },
  ]} />;
}

function ScopeList({ application }: { application: DeveloperApplicationRecord }) {
  const scopes = application.scopeGrants.flatMap((grant) => grant.scopes.map((scope) => ({ ...scope, grantStatus: grant.status, environment: grant.environment })));
  return <ul aria-label="Application scope grants" className={styles.scopeList}>{scopes.length ? scopes.map((scope, index) => <li key={`${scope.key}-${scope.grantStatus}-${index}`}><div><code>{scope.key}</code><p>{scope.description ?? "No safe description is available for this canonical scope."}</p></div><ProtectedStatus label={scope.state === "approved" ? "Approved" : scope.state === "retired" ? "Retired" : "Requested"} tone={scope.state === "approved" ? "success" : scope.state === "retired" ? "neutral" : "warning"} /></li>) : <li><p>No scope grants are available. Requested and approved scopes are never conflated.</p></li>}</ul>;
}

function ApplicationDetail({ application, snapshot, capabilities }: { application: DeveloperApplicationRecord; snapshot: DeveloperPresentationSnapshot; capabilities: DeveloperOwnerCapabilities }) {
  const state = getDeveloperApplicationStatus(application.status);
  const environment = getDeveloperEnvironmentStatus(application.environment, application.productionLocked);
  const credentials = snapshot.credentials.filter((credential) => credential.applicationReference === application.reference);
  const webhooks = snapshot.webhooks.filter((webhook) => webhook.applicationReference === application.reference);
  return <DeveloperPage eyebrow="Application record" title={application.name} description="Owner-scoped application lifecycle, environment, scope and operational records." actions={<Link className="eo-button eo-button--secondary" href="/developers/applications">All applications</Link>} rail={<div className="space-y-4"><OperationalPanel title="Lifecycle" padding="compact"><ProtectedStatus label={state.label} tone={state.tone} /><p className="mt-3 text-sm text-[var(--eo-text-secondary)]">{state.description}</p></OperationalPanel><OperationalPanel title="Environment" padding="compact"><ProtectedStatus label={environment.label} tone={environment.tone} /><p className="mt-3 text-sm text-[var(--eo-text-secondary)]">{environment.description}</p></OperationalPanel></div>}>
    <div className="space-y-5"><OperationalPanel title="Integration purpose" description="Provided by the application owner."><p>{application.businessPurpose}</p><dl className={styles.definitionList}><div><dt>Created</dt><dd>{dateTime(application.createdAt)}</dd></div><div><dt>Terms acceptance</dt><dd>{dateTime(application.termsAcceptedAt)}</dd></div><div><dt>Live access</dt><dd>{application.productionLocked ? "Locked by canonical production-readiness authority" : application.environment === "LIVE" ? "Live environment recorded" : "Not requested"}</dd></div></dl></OperationalPanel><OperationalPanel title="Scopes" description="Canonical scope-grant states; requested scopes are not presented as approved."><ScopeList application={application} /></OperationalPanel><OperationalPanel title="Credentials" description="Credential records expose only their public masked metadata." action={<Link className="eo-text-link" href={`/developers/applications/${application.reference}/credentials`}>View credential workspace</Link>}><CredentialTable credentials={credentials} capabilities={capabilities} /></OperationalPanel><OperationalPanel title="Webhooks" description="Endpoints display the canonical masked endpoint projection only." action={<Link className="eo-text-link" href={`/developers/applications/${application.reference}/webhooks`}>View endpoint workspace</Link>}><WebhookTable webhooks={webhooks} /></OperationalPanel><OperationalPanel title="API activity and quota" description="Request metadata and recorded quota use are available only through their canonical owner-scoped projections."><div className="flex flex-wrap gap-3"><Link className="eo-button eo-button--secondary" href={`/developers/applications/${application.reference}/usage`}>View quota usage</Link><Link className="eo-button eo-button--secondary" href={`/developers/applications/${application.reference}/request-log`}>View request activity</Link></div></OperationalPanel></div>
  </DeveloperPage>;
}

function DeveloperDocumentationPage() {
  const example = "Authorization: Bearer <opaque credential>\nIdempotency-Key: <unique request key>";
  return <DeveloperPage eyebrow="Canonical reference" title="API documentation" description="Use the served OpenAPI document as the only route, schema and operation authority."><div className="space-y-5"><OperationalPanel title="OpenAPI v1" description="The protected portal links to the canonical served document; it does not duplicate a second specification."><a className="eo-button eo-button--primary" href="/api/openapi/v1.json">Download OpenAPI {DEVELOPER_API_VERSION}</a></OperationalPanel><OperationalPanel title="Authentication and idempotency"><p>Use an opaque bearer credential only from a protected server environment. The canonical contract specifies <code>Idempotency-Key</code> only on operations that declare it.</p><pre className={styles.codeBlock} aria-label="Authentication header placeholders" tabIndex={0}><code>{example}</code></pre></OperationalPanel><OperationalPanel title="Errors, scopes and webhooks"><ul className={styles.bulletList}><li>Problem Details follows the canonical RFC 9457-style contract.</li><li>Scopes are granted through the review workflow and are distinct from account permissions.</li><li>Webhook delivery is at least once. Verify the documented digest, signature, timestamp and replay-protection headers before processing.</li></ul></OperationalPanel><OperationalPanel title="Live production access"><ProtectedStatus label="Production validation locked" tone="locked" /><p className="mt-3 text-sm text-[var(--eo-text-secondary)]">{DEVELOPER_API_PRODUCTION_LOCK_REASON}</p></OperationalPanel></div></DeveloperPage>;
}

export function DeveloperAccessRestrictedPage() { return <DeveloperPage eyebrow="Integration workbench" title="Developer access unavailable" description="This authenticated context does not currently have the owner permission required for this developer route."><ProtectedState kind="restricted" title="Permission required" description="Developer navigation is filtered on the server. The API remains the authority for every data read and mutation." /></DeveloperPage>; }

export function DeveloperPortalPage({ route, snapshot, capabilities }: { route: DeveloperPortalRoute; snapshot: DeveloperPresentationSnapshot; capabilities: DeveloperOwnerCapabilities }) {
  if (route.kind === "documentation") return capabilities.canReadDocumentation ? <DeveloperDocumentationPage /> : <DeveloperAccessRestrictedPage />;
  if (route.kind === "not-found") return <DeveloperPage eyebrow="Integration workbench" title="Developer route not found" description="This route is not part of the verified owner portal."><ProtectedState kind="unavailable" title="Route unavailable" description="Use the protected navigator to open a supported developer workspace." /></DeveloperPage>;
  if (!capabilities.canReadApplications && route.kind !== "credentials" && route.kind !== "webhooks" && route.kind !== "usage") return <DeveloperAccessRestrictedPage />;
  if (route.kind === "applications") {
    const operational = selectDeveloperOperationalState({ applicationStatuses: snapshot.applications.map((application) => application.status), hasTermsAcceptance: snapshot.applications.some((application) => application.termsAcceptedAt !== null), credentialStatuses: snapshot.credentials.map((credential) => credential.status), deliveryStatuses: snapshot.deliveries.map((delivery) => delivery.status), hasQuotaUsage: snapshot.quotas.length > 0 });
    const activeCredentials = snapshot.credentials.filter((credential) => credential.status === "ACTIVE").length;
    const activeWebhooks = snapshot.webhooks.filter((webhook) => webhook.status === "ACTIVE").length;
    const failedDeliveries = snapshot.deliveries.filter((delivery) => ["FAILED_RETRYABLE", "FAILED_PERMANENT", "ENDPOINT_DISABLED"].includes(delivery.status)).length;
    return <DeveloperPage eyebrow="Integration workbench" title="Developer applications" description="Application lifecycle comes first; credentials, endpoints and delivery attention follow from source-backed owner records." rail={<div className="space-y-4"><OperationalPanel title={operational.title} padding="compact"><p className="text-sm text-[var(--eo-text-secondary)]">{operational.description}</p></OperationalPanel><OperationalPanel title="Production access" padding="compact"><ProtectedStatus label="Live validation locked" tone="locked" /><p className="mt-3 text-sm text-[var(--eo-text-secondary)]">No live readiness state is inferred from the portal.</p></OperationalPanel></div>}><div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Applications" value={snapshot.applications.length} description="Owner-scoped records" /><MetricTile label="Active credentials" value={activeCredentials} description="Masked records only" /><MetricTile label="Active endpoints" value={activeWebhooks} description="Verified active state" /><MetricTile label="Delivery attention" value={failedDeliveries} description="Canonical failure states" /></div>{capabilities.canManageApplications ? <OperationalPanel title="Create application" description="Submit a controlled integration request. Approval, terms, scopes and environment activation remain canonical."><DeveloperApplicationCreateForm /></OperationalPanel> : null}<OperationalPanel title="Applications" description="Desktop uses an accessible table; compact screens collapse to structured records."><ApplicationTable applications={snapshot.applications} /></OperationalPanel></div></DeveloperPage>;
  }
  if (route.kind === "application-detail") { const application = snapshot.applications.find((entry) => entry.reference === route.applicationReference); return application ? <ApplicationDetail application={application} snapshot={snapshot} capabilities={capabilities} /> : <DeveloperNotFound title="Application unavailable" />; }
  if (route.kind === "application-credentials") { const application = snapshot.applications.find((entry) => entry.reference === route.applicationReference); if (!application) return <DeveloperNotFound title="Application unavailable" />; if (!capabilities.canReadCredentials) return <DeveloperAccessRestrictedPage />; const credentials = snapshot.credentials.filter((credential) => credential.applicationReference === application.reference); return <DeveloperPage eyebrow="Credential workspace" title={`${application.name} credentials`} description="Only safe credential metadata is listed. A newly issued or rotated secret is shown exactly once after a confirmed canonical response." actions={<Link className="eo-button eo-button--secondary" href={`/developers/applications/${application.reference}`}>Application record</Link>}><div className="space-y-5"><OperationalPanel title="Issue credential" description="The server validates approval, terms, environment, scope grants, quota safeguards and owner context before it returns a one-time secret."><DeveloperCredentialActions applicationReference={application.reference} canCreate={capabilities.canCreateCredentials} canRotate={false} canRevoke={false} /></OperationalPanel><OperationalPanel title="Credential records"><CredentialTable credentials={credentials} capabilities={capabilities} /></OperationalPanel></div></DeveloperPage>; }
  if (route.kind === "application-webhooks") { const application = snapshot.applications.find((entry) => entry.reference === route.applicationReference); if (!application) return <DeveloperNotFound title="Application unavailable" />; if (!capabilities.canReadWebhooks) return <DeveloperAccessRestrictedPage />; const webhooks = snapshot.webhooks.filter((webhook) => webhook.applicationReference === application.reference); return <DeveloperPage eyebrow="Webhook workspace" title={`${application.name} endpoints`} description="Endpoint creation, verification, signing-secret issuance and delivery operations remain fully canonical."><div className="space-y-5">{capabilities.canManageWebhooks ? <OperationalPanel title="Create webhook endpoint" description="Only canonical event names are available. The endpoint is not presented as verified until server confirmation."><DeveloperWebhookCreateForm applicationReference={application.reference} eventTypes={eventTypes} /></OperationalPanel> : null}<OperationalPanel title="Endpoints"><WebhookTable webhooks={webhooks} /></OperationalPanel></div></DeveloperPage>; }
  if (route.kind === "application-usage") { const application = snapshot.applications.find((entry) => entry.reference === route.applicationReference); if (!application) return <DeveloperNotFound title="Application unavailable" />; if (!capabilities.canReadUsage) return <DeveloperAccessRestrictedPage />; return <DeveloperPage eyebrow="Quota workspace" title={`${application.name} quota usage`} description="Recorded quota counters are shown without forecasts. Rate-limit windows have no portal-safe projection."><div className="space-y-5"><OperationalPanel title="Recorded quota use"><QuotaTable quotas={snapshot.quotas.filter((quota) => quota.applicationReference === application.reference)} /></OperationalPanel><OperationalPanel title="Rate limits"><ProtectedState kind="unavailable" title="Rate-window state is not available" description="The API enforces rate limits, but no owner-safe remaining/reset projection exists for this portal. No estimate is derived from request activity." /></OperationalPanel></div></DeveloperPage>; }
  if (route.kind === "application-request-log") { const application = snapshot.applications.find((entry) => entry.reference === route.applicationReference); if (!application) return <DeveloperNotFound title="Application unavailable" />; if (!capabilities.canReadUsage) return <DeveloperAccessRestrictedPage />; return <DeveloperPage eyebrow="API activity" title={`${application.name} request activity`} description="Privacy-safe request metadata only; headers, credentials, bodies, query secrets and internal errors are never rendered."><OperationalPanel title="Request metadata"><RequestTable requests={snapshot.requests.filter((request) => request.applicationReference === application.reference)} /></OperationalPanel></DeveloperPage>; }
  if (route.kind === "credentials") return capabilities.canReadCredentials ? <DeveloperPage eyebrow="Credential workspace" title="Credentials" description="All visible records are owner-scoped and masked. Full credential values never appear in history."><OperationalPanel title="Credential records"><CredentialTable credentials={snapshot.credentials} capabilities={capabilities} /></OperationalPanel></DeveloperPage> : <DeveloperAccessRestrictedPage />;
  if (route.kind === "webhooks") return capabilities.canReadWebhooks ? <DeveloperPage eyebrow="Webhook workspace" title="Webhook endpoints" description="Review safe endpoint metadata, verification state, event subscriptions and delivery workspaces."><OperationalPanel title="Endpoints"><WebhookTable webhooks={snapshot.webhooks} /></OperationalPanel></DeveloperPage> : <DeveloperAccessRestrictedPage />;
  if (route.kind === "webhook-detail") { const webhook = snapshot.webhooks.find((entry) => entry.reference === route.webhookReference); if (!webhook) return <DeveloperNotFound title="Webhook endpoint unavailable" />; if (!capabilities.canReadWebhooks) return <DeveloperAccessRestrictedPage />; const status = getDeveloperWebhookStatus(webhook.status); return <DeveloperPage eyebrow="Webhook endpoint" title={webhook.endpoint} description="A masked endpoint projection, exact event subscriptions and canonical operational controls." actions={<Link className="eo-button eo-button--secondary" href={`/developers/webhooks/${webhook.reference}/deliveries`}>View deliveries</Link>} rail={<OperationalPanel title="Endpoint state" padding="compact"><ProtectedStatus label={status.label} tone={status.tone} /><p className="mt-3 text-sm text-[var(--eo-text-secondary)]">{status.description}</p></OperationalPanel>}><div className="space-y-5"><OperationalPanel title="Endpoint details"><dl className={styles.definitionList}><div><dt>Application</dt><dd>{webhook.applicationName}</dd></div><div><dt>Environment</dt><dd>{webhook.environment === "TEST" ? "Test" : "Live"}</dd></div><div><dt>Verified</dt><dd>{dateTime(webhook.verifiedAt)}</dd></div><div><dt>Last updated</dt><dd>{dateTime(webhook.updatedAt)}</dd></div></dl></OperationalPanel><OperationalPanel title="Subscriptions"><ul className={styles.bulletList}>{webhook.eventTypes.map((eventType) => <li key={eventType}><code>{eventType}</code></li>)}</ul></OperationalPanel><OperationalPanel title="Canonical endpoint actions" description="Changes wait for the API response; no verification, signing secret, or retry state is created in the browser."><DeveloperWebhookActions reference={webhook.reference} version={webhook.version} status={webhook.status} canManage={capabilities.canManageWebhooks} eventTypes={webhook.eventTypes} allEventTypes={eventTypes} /></OperationalPanel></div></DeveloperPage>; }
  if (route.kind === "webhook-deliveries") { const webhook = snapshot.webhooks.find((entry) => entry.reference === route.webhookReference); if (!webhook) return <DeveloperNotFound title="Webhook endpoint unavailable" />; if (!capabilities.canReadDeliveries) return <DeveloperAccessRestrictedPage />; return <DeveloperPage eyebrow="Webhook deliveries" title={webhook.endpoint} description="Delivery status and attempts are owner-scoped metadata. Payloads, headers, signatures and secrets are not available in this portal projection."><OperationalPanel title="Delivery history"><DeliveryTable deliveries={snapshot.deliveries.filter((delivery) => delivery.webhookReference === webhook.reference)} /></OperationalPanel></DeveloperPage>; }
  if (route.kind === "delivery-detail") { const delivery = snapshot.deliveries.find((entry) => entry.reference === route.deliveryReference); if (!delivery) return <DeveloperNotFound title="Webhook delivery unavailable" />; if (!capabilities.canReadDeliveries) return <DeveloperAccessRestrictedPage />; const status = getDeveloperDeliveryStatus(delivery.status); const attempts = snapshot.attempts.filter((attempt) => attempt.deliveryReference === delivery.reference); return <DeveloperPage eyebrow="Webhook delivery" title={delivery.eventType ?? "Event metadata unavailable"} description="Safe delivery metadata and canonical attempt history; no payload, request headers, response headers, signature, credentials or customer data are exposed." actions={<Link className="eo-button eo-button--secondary" href={`/developers/webhooks/${delivery.webhookReference}/deliveries`}>Back to deliveries</Link>}><div className="space-y-5"><OperationalPanel title="Delivery state"><ProtectedStatus label={status.label} tone={status.tone} /><dl className={styles.definitionList}><div><dt>Endpoint</dt><dd>{delivery.webhookEndpoint}</dd></div><div><dt>Attempts</dt><dd>{delivery.attemptCount}</dd></div><div><dt>Created</dt><dd>{dateTime(delivery.createdAt)}</dd></div><div><dt>Last attempt</dt><dd>{dateTime(delivery.lastAttemptedAt)}</dd></div></dl></OperationalPanel><OperationalPanel title="Attempt history"><ol aria-label="Webhook delivery attempts" className={styles.attemptList}>{attempts.length ? attempts.map((attempt) => <li key={attempt.id}><strong>Attempt {attempt.attemptNumber}</strong><span>{attempt.status.replaceAll("_", " ")}</span><span>{attempt.responseStatus ? `HTTP ${attempt.responseStatus}` : "No safe response status recorded"}</span><span>{attempt.failureClass ? attempt.failureClass.replaceAll("_", " ") : "No failure category"}</span><time>{dateTime(attempt.completedAt ?? attempt.startedAt)}</time></li>) : <li>No safe attempt history is available.</li>}</ol></OperationalPanel><OperationalPanel title="Retry"><DeveloperDeliveryRetryAction reference={delivery.reference} canRetry={capabilities.canRetryDeliveries && delivery.status === "FAILED_RETRYABLE"} /></OperationalPanel></div></DeveloperPage>; }
  if (route.kind === "usage") return capabilities.canReadUsage ? <DeveloperPage eyebrow="Usage workspace" title="Quota and API activity" description="Recorded quota counters and privacy-safe request metadata remain distinct from rate-limit enforcement."><div className="space-y-5"><OperationalPanel title="Recorded quota usage"><QuotaTable quotas={snapshot.quotas} /></OperationalPanel><OperationalPanel title="API activity"><RequestTable requests={snapshot.requests} /></OperationalPanel><OperationalPanel title="Rate-limit state"><ProtectedState kind="unavailable" title="No portal-safe rate-window projection" description="The developer API enforces its own rate policies. This page does not estimate remaining requests or reset times from audit records." /></OperationalPanel></div></DeveloperPage> : <DeveloperAccessRestrictedPage />;
  return <DeveloperNotFound title="Developer workspace unavailable" />;
}

function DeveloperNotFound({ title }: { title: string }) { return <DeveloperPage eyebrow="Integration workbench" title={title} description="The requested owner-scoped record is not available."><ProtectedState kind="unavailable" title={title} description="The record may not exist, may no longer be owned by this context, or may not be available through the current safe projection." /></DeveloperPage>; }
