import Link from "next/link";

const inputClass = "h-10 rounded-xl border border-[var(--kt-soft-border)] bg-white px-3 text-sm";
const fieldClass = "space-y-1";
const labelClass = "text-xs font-bold text-[var(--kt-text-muted)]";

export function PaymentWebhookFilters({ values }: { values: Record<string, string | undefined> }) {
  return <form method="get" action="/admin/payment-webhooks" className="grid gap-4 md:grid-cols-2 xl:grid-cols-4" aria-label="Payment webhook filters">
    <div className={fieldClass}><label className={labelClass} htmlFor="webhook-environment">Environment</label><select id="webhook-environment" name="environment" className={inputClass} defaultValue={values.environment ?? ""}><option value="">All environments</option><option value="SANDBOX">Sandbox</option><option value="PRODUCTION">Production</option></select></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="webhook-processing-status">Processing status</label><select id="webhook-processing-status" name="processingStatus" className={inputClass} defaultValue={values.processingStatus ?? ""}><option value="">All processing states</option>{["RECEIVED", "REJECTED", "VERIFIED", "APPLIED", "DUPLICATE", "IGNORED_STALE", "RECONCILIATION_REQUIRED", "TEMPORARY_FAILURE"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="webhook-normalized-status">Provider status</label><select id="webhook-normalized-status" name="normalizedStatus" className={inputClass} defaultValue={values.normalizedStatus ?? ""}><option value="">All provider states</option>{["COMPLETE", "PENDING", "FAILED", "UNKNOWN"].map((value) => <option key={value} value={value}>{value}</option>)}</select></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="webhook-reconciliation">Reconciliation</label><select id="webhook-reconciliation" name="reconciliationRequired" className={inputClass} defaultValue={values.reconciliationRequired ?? ""}><option value="">All events</option><option value="true">Required</option><option value="false">Not required</option></select></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="webhook-payment-reference">Payment reference</label><input id="webhook-payment-reference" name="paymentReference" className={inputClass} maxLength={100} defaultValue={values.paymentReference} /></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="webhook-attempt-reference">Attempt reference</label><input id="webhook-attempt-reference" name="attemptReference" className={inputClass} maxLength={100} defaultValue={values.attemptReference} /></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="webhook-from">Received from</label><input id="webhook-from" name="from" type="datetime-local" className={inputClass} defaultValue={values.from} /></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="webhook-to">Received to</label><input id="webhook-to" name="to" type="datetime-local" className={inputClass} defaultValue={values.to} /></div>
    <div className="flex items-end gap-2"><button type="submit" className="h-10 rounded-xl bg-[var(--kt-ink-navy)] px-4 text-sm font-bold text-white">Apply filters</button><Link href="/admin/payment-webhooks" className="inline-flex h-10 items-center px-3 text-sm font-semibold text-[var(--kt-signal-cobalt)]">Clear</Link></div>
  </form>;
}

export function PaymentReconciliationFilters({ values }: { values: Record<string, string | undefined> }) {
  return <form method="get" action="/admin/payment-reconciliation" className="grid gap-4 md:grid-cols-2 xl:grid-cols-4" aria-label="Payment reconciliation filters">
    <div className={fieldClass}><label className={labelClass} htmlFor="reconciliation-status">Case status</label><select id="reconciliation-status" name="status" className={inputClass} defaultValue={values.status ?? ""}><option value="">All statuses</option>{["OPEN", "MONITORING", "RESOLVED", "CLOSED"].map((value) => <option key={value} value={value}>{value}</option>)}</select></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="reconciliation-priority">Priority</label><select id="reconciliation-priority" name="priority" className={inputClass} defaultValue={values.priority ?? ""}><option value="">All priorities</option>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((value) => <option key={value} value={value}>{value}</option>)}</select></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="reconciliation-reason">Reason</label><select id="reconciliation-reason" name="reason" className={inputClass} defaultValue={values.reason ?? ""}><option value="">All reasons</option>{["UNKNOWN_OUTCOME", "CREDENTIAL_VERSION_MISMATCH", "PROVIDER_CONFIRMATION_UNAVAILABLE", "CONFLICTING_PROVIDER_STATUS", "OUT_OF_ORDER_EVENT", "AMOUNT_MISMATCH", "MERCHANT_MISMATCH", "PROVIDER_REFERENCE_CONFLICT", "UNRECOGNIZED_PROVIDER_STATUS", "APPLICATION_FAILURE_AFTER_VERIFICATION", "STALE_PROCESSING_ATTEMPT"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="reconciliation-payment-reference">Payment reference</label><input id="reconciliation-payment-reference" name="paymentReference" className={inputClass} maxLength={100} defaultValue={values.paymentReference} /></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="reconciliation-attempt-reference">Attempt reference</label><input id="reconciliation-attempt-reference" name="attemptReference" className={inputClass} maxLength={100} defaultValue={values.attemptReference} /></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="reconciliation-event-reference">Webhook reference</label><input id="reconciliation-event-reference" name="eventReference" className={inputClass} maxLength={100} defaultValue={values.eventReference} /></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="reconciliation-from">Opened from</label><input id="reconciliation-from" name="from" type="datetime-local" className={inputClass} defaultValue={values.from} /></div>
    <div className={fieldClass}><label className={labelClass} htmlFor="reconciliation-to">Opened to</label><input id="reconciliation-to" name="to" type="datetime-local" className={inputClass} defaultValue={values.to} /></div>
    <div className="flex items-end gap-2"><button type="submit" className="h-10 rounded-xl bg-[var(--kt-ink-navy)] px-4 text-sm font-bold text-white">Apply filters</button><Link href="/admin/payment-reconciliation" className="inline-flex h-10 items-center px-3 text-sm font-semibold text-[var(--kt-signal-cobalt)]">Clear</Link></div>
  </form>;
}
