/* eslint-disable @typescript-eslint/no-explicit-any -- Phase 25 delegates are validated during deferred runtime validation. */
import type { NextRequest } from "next/server";
import { z } from "zod";
import { PERMISSIONS } from "@/lib/auth/permission-keys";
import { requirePromoterAdmin } from "./admin-api-policy";
import { db, isRouteResponse, parsePromoterCommand, promoterJson } from "./route-support";
import { PromoterLifecycleService } from "./lifecycle.service";
import { approvePromoterMarketingAsset, createPromoterMarketingAsset, rejectPromoterMarketingAsset, retirePromoterMarketingAsset, submitPromoterMarketingAsset, updatePromoterMarketingAsset } from "./promoter-marketing-asset.service";
import { activatePromoterAgreementVersion, approvePromoterAgreementVersion, createPromoterAgreementVersion, retirePromoterAgreementVersion, submitPromoterAgreementVersion } from "./promoter-agreement.service";

const op = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._:-]{7,119}$/);
const operationSchema = z.object({ operationId: op, requestHash: z.string().length(64).optional() });
const programTerms = z.object({ attributionWindowDays: z.number().int().min(1).max(3650), qualifyingEventType: z.enum(["CUSTOMER_FIRST_COMPLETED_SETTLED_COURIER_ORDER", "CUSTOMER_FIRST_COMPLETED_SETTLED_MARKETPLACE_ORDER", "BUSINESS_FIRST_COMPLETED_SETTLED_ORDER", "STORE_FIRST_SETTLED_MARKETPLACE_ORDER", "DRIVER_FIRST_COMPLETED_SETTLED_DELIVERY"]), qualificationHoldDays: z.number().int().min(0).max(3650), commissionPlanVersionId: z.string().min(1).max(120), geographicPolicyVersion: z.string().min(1).max(120), fraudPolicyVersion: z.string().min(1).max(120), disclosurePolicyVersion: z.string().min(1).max(120), reversalPolicyVersion: z.string().min(1).max(120), legalTermsVersion: z.string().min(1).max(120), startsAt: z.coerce.date(), endsAt: z.coerce.date().optional(), maximumQualificationsPerPromoter: z.number().int().positive().optional(), maximumQualificationsPerDay: z.number().int().positive().optional(), maximumQualificationsPerSubject: z.number().int().positive().optional() }).strict();
const programCreate = z.object({ operationId: op, requestHash: z.string().length(64).optional(), code: z.string().regex(/^[A-Z0-9_-]{3,48}$/i), name: z.string().min(3).max(160), targetType: z.enum(["CUSTOMER", "BUSINESS_CUSTOMER", "STORE", "DRIVER"]), versionTerms: programTerms }).strict();
const assetCreate = z.object({ operationId: op, programVersionId: z.string().optional(), assetType: z.enum(["SOCIAL_IMAGE", "PRINT_FLYER", "QR_CODE", "TEXT_TEMPLATE", "BUSINESS_OUTREACH_TEMPLATE", "PROGRAM_GUIDE"]), title: z.string().min(3).max(160), description: z.string().max(1000).optional(), trustedAssetReference: z.string().regex(/^[A-Za-z0-9._:-]{6,160}$/), requiredDisclosure: z.enum(["Ad", "Sponsored", "Paid promotion", "Promoter link"]), approvedClaims: z.string().min(3).max(4000), prohibitedAlterations: z.string().min(3).max(4000) }).strict();
const agreementCreate = z.object({ operationId: op, title: z.string().min(8).max(200), termsContent: z.string().min(8).max(20_000), disclosureRequirements: z.string().min(8).max(10_000), prohibitedConduct: z.string().min(8).max(10_000), privacyTerms: z.string().min(8).max(10_000), taxNotice: z.string().min(8).max(10_000), terminationPolicy: z.string().min(8).max(10_000), effectiveFrom: z.coerce.date(), effectiveUntil: z.coerce.date().optional() }).strict();

async function body<T extends z.ZodTypeAny>(request: NextRequest, schema: T) { const value = await parsePromoterCommand(request, schema); return isRouteResponse(value) ? value : value as z.infer<T>; }
async function guard(request: NextRequest, permission: string, path: string) { return requirePromoterAdmin(request, permission, path, true); }
export async function createProgram(request: NextRequest) { const auth = await guard(request, PERMISSIONS.PROMOTER_PROGRAMS_MANAGE, "/api/admin/promoter-programs"); if ("response" in auth) return auth.response; const value = await body(request, programCreate); if (value instanceof Response) return value; try { return promoterJson({ program: await new PromoterLifecycleService(db).createPromoterProgramDraft(value) }, 201); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
export async function updateProgram(request: NextRequest, context: { params: Promise<{ reference: string }> }) { const auth = await guard(request, PERMISSIONS.PROMOTER_PROGRAMS_MANAGE, "/api/admin/promoter-programs/[reference]"); if ("response" in auth) return auth.response; const value = await body(request, programCreate); if (value instanceof Response) return value; const { reference } = await context.params; const program = await db.promoterProgram.findUnique({ where: { publicReference: reference }, include: { versions: { orderBy: { versionNumber: "desc" }, take: 1 } } }); if (!program?.versions[0]) return promoterJson({ error: "PROGRAM_NOT_FOUND" }, 404); try { return promoterJson({ program: await new PromoterLifecycleService(db).updatePromoterProgramDraft({ ...value, programId: program.id, programVersionId: program.versions[0].id }) }); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
export async function programAction(request: NextRequest, context: { params: Promise<{ reference: string }> }, action: "submit" | "approve" | "reject" | "activate" | "pause" | "end") { const permission = action === "submit" || action === "reject" ? PERMISSIONS.PROMOTER_PROGRAMS_REVIEW : action === "approve" ? PERMISSIONS.PROMOTER_PROGRAMS_APPROVE : action === "activate" ? PERMISSIONS.PROMOTER_PROGRAMS_ACTIVATE : action === "pause" ? PERMISSIONS.PROMOTER_PROGRAMS_PAUSE : PERMISSIONS.PROMOTER_PROGRAMS_END; const auth = await guard(request, permission, `/api/admin/promoter-programs/[reference]/${action}`); if ("response" in auth) return auth.response; const value = await body(request, operationSchema); if (value instanceof Response) return value; const { reference } = await context.params; const program = await db.promoterProgram.findUnique({ where: { publicReference: reference }, include: { versions: { orderBy: { versionNumber: "desc" }, take: 1 } } }); if (!program?.versions[0]) return promoterJson({ error: "PROGRAM_NOT_FOUND" }, 404); const service = new PromoterLifecycleService(db); try { const input = { ...value, programId: program.id, programVersionId: program.versions[0].id, approvedByUserId: auth.user.id, createdByUserId: program.versions[0].approvedByUserId }; const result = action === "submit" ? await service.submitPromoterProgram(input) : action === "approve" ? await service.approvePromoterProgram(input) : action === "reject" ? await service.rejectPromoterProgram(input) : action === "activate" ? await service.activatePromoterProgram(input) : action === "pause" ? await service.pausePromoterProgram(input) : await service.endPromoterProgram(input); return promoterJson({ program: result }); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
export async function promoterAction(request: NextRequest, context: { params: Promise<{ reference: string }> }, action: "approve" | "request-changes" | "activate" | "suspend" | "terminate") { const permission = action === "approve" ? PERMISSIONS.PROMOTERS_APPROVE : action === "request-changes" ? PERMISSIONS.PROMOTERS_REVIEW : action === "activate" ? PERMISSIONS.PROMOTERS_ACTIVATE : action === "suspend" ? PERMISSIONS.PROMOTERS_SUSPEND : PERMISSIONS.PROMOTERS_TERMINATE; const auth = await guard(request, permission, `/api/admin/promoters/[reference]/${action}`); if ("response" in auth) return auth.response; const value = await body(request, operationSchema); if (value instanceof Response) return value; const { reference } = await context.params; const account = await db.promoterAccount.findUnique({ where: { publicReference: reference } }); if (!account) return promoterJson({ error: "PROMOTER_NOT_FOUND" }, 404); const service = new PromoterLifecycleService(db); try { const input = { ...value, promoterAccountId: account.id, approved: action === "approve" }; const result = action === "approve" ? await service.reviewPromoterApplication(input) : action === "request-changes" ? await service.requestPromoterAccountChanges(input) : action === "activate" ? await service.activatePromoterAccount(input) : action === "suspend" ? await service.suspendPromoterAccount(input) : await service.terminatePromoterAccount(input); return promoterJson({ promoter: result }); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
export async function createAsset(request: NextRequest) { const auth = await guard(request, PERMISSIONS.PROMOTER_ASSETS_MANAGE, "/api/admin/promoter-assets"); if ("response" in auth) return auth.response; const value = await body(request, assetCreate); if (value instanceof Response) return value; try { return promoterJson({ asset: await createPromoterMarketingAsset(db, value) }, 201); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
export async function updateAsset(request: NextRequest, context: { params: Promise<{ reference: string }> }) { const auth = await guard(request, PERMISSIONS.PROMOTER_ASSETS_MANAGE, "/api/admin/promoter-assets/[reference]"); if ("response" in auth) return auth.response; const value = await body(request, assetCreate); if (value instanceof Response) return value; const { reference } = await context.params; try { return promoterJson({ asset: await updatePromoterMarketingAsset(db, { ...value, reference }) }); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
export async function assetAction(request: NextRequest, context: { params: Promise<{ reference: string }> }, action: "submit" | "approve" | "reject" | "activate" | "retire") { const auth = await guard(request, PERMISSIONS.PROMOTER_ASSETS_MANAGE, `/api/admin/promoter-assets/[reference]/${action}`); if ("response" in auth) return auth.response; const value = await body(request, operationSchema); if (value instanceof Response) return value; const { reference } = await context.params; try { const asset = action === "submit" ? await submitPromoterMarketingAsset(db, { ...value, reference }) : action === "approve" || action === "activate" ? await approvePromoterMarketingAsset(db, { ...value, reference }) : action === "reject" ? await rejectPromoterMarketingAsset(db, { ...value, reference }) : await retirePromoterMarketingAsset(db, { ...value, reference }); return promoterJson({ asset }); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
export async function createAgreement(request: NextRequest) { const auth = await guard(request, PERMISSIONS.PROMOTER_AGREEMENTS_MANAGE, "/api/admin/promoter-agreements"); if ("response" in auth) return auth.response; const value = await body(request, agreementCreate); if (value instanceof Response) return value; try { return promoterJson({ agreement: await createPromoterAgreementVersion(db, value) }, 201); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
export async function agreementAction(request: NextRequest, context: { params: Promise<{ reference: string }> }, action: "submit" | "approve" | "activate" | "retire") { const auth = await guard(request, PERMISSIONS.PROMOTER_AGREEMENTS_MANAGE, `/api/admin/promoter-agreements/[reference]/${action}`); if ("response" in auth) return auth.response; const value = await body(request, operationSchema); if (value instanceof Response) return value; const { reference } = await context.params; try { const input = { ...value, reference, approvedByUserId: auth.user.id }; const agreement = action === "submit" ? await submitPromoterAgreementVersion(db, input) : action === "approve" ? await approvePromoterAgreementVersion(db, input) : action === "activate" ? await activatePromoterAgreementVersion(db, input) : await retirePromoterAgreementVersion(db, input); return promoterJson({ agreement }); } catch (error: any) { return promoterJson({ error: error.code ?? "PROMOTER_INVALID_COMMAND" }, 422); } }
