/* eslint-disable @typescript-eslint/no-explicit-any -- Phase 25 delegates are validated with Prisma in Phase 26.5. */
import { randomUUID } from "node:crypto";
import { PromoterError } from "./errors";
import { assertPromotersProductionReady } from "./production-readiness";
type Db = any;
const types = new Set(["SOCIAL_IMAGE", "PRINT_FLYER", "QR_CODE", "TEXT_TEMPLATE", "BUSINESS_OUTREACH_TEMPLATE", "PROGRAM_GUIDE"]);
const disclosures = new Set(["Ad", "Sponsored", "Paid promotion", "Promoter link"]);
const ref = () => `PMA-${randomUUID().replaceAll("-", "").toUpperCase()}`;
function validate(input: any) { const content = [input.content, input.title, input.description, input.approvedClaims, input.prohibitedAlterations, input.trustedAssetReference].filter(Boolean).join(" "); if (!types.has(input.assetType) || !disclosures.has(input.requiredDisclosure) || !/^[A-Za-z0-9._:-]{6,160}$/.test(input.trustedAssetReference ?? "") || /<\/?(?:script|iframe|img)|javascript:|https?:\/\/|tracking[\s-]?pixel|1x1/i.test(content)) throw new PromoterError("PROMOTER_INVALID_COMMAND", "Marketing assets must be trusted, disclosure-bound, and free of HTML, JavaScript, external pixels, and external destinations."); }
export async function createPromoterMarketingAsset(db: Db, input: any) { assertPromotersProductionReady(); validate(input); return db.promoterMarketingAsset.create({ data: { publicReference: ref(), programVersionId: input.programVersionId ?? null, assetType: input.assetType, title: input.title.trim(), description: input.description?.trim() ?? null, trustedAssetReference: input.trustedAssetReference, requiredDisclosure: input.requiredDisclosure, approvedClaims: input.approvedClaims.trim(), prohibitedAlterations: input.prohibitedAlterations.trim() } }); }
/** Only drafts are mutable; approved assets remain evidence-bound and are retired instead of overwritten. */
export async function updatePromoterMarketingAsset(db: Db, input: any) { assertPromotersProductionReady(); validate(input); const row = await db.promoterMarketingAsset.findUnique({ where: { publicReference: input.reference } }); if (!row || row.status !== "DRAFT") throw new PromoterError("PROMOTER_NOT_ELIGIBLE", "Only a draft marketing asset may be edited."); return db.promoterMarketingAsset.update({ where: { id: row.id }, data: { programVersionId: input.programVersionId ?? null, assetType: input.assetType, title: input.title.trim(), description: input.description?.trim() ?? null, trustedAssetReference: input.trustedAssetReference, requiredDisclosure: input.requiredDisclosure, approvedClaims: input.approvedClaims.trim(), prohibitedAlterations: input.prohibitedAlterations.trim() } }); }
export async function submitPromoterMarketingAsset(db: Db, input: any) { assertPromotersProductionReady(); return db.promoterMarketingAsset.findUnique({ where: { publicReference: input.reference } }); }
export async function approvePromoterMarketingAsset(db: Db, input: any) { assertPromotersProductionReady(); return db.promoterMarketingAsset.update({ where: { publicReference: input.reference }, data: { status: "APPROVED", approvedAt: new Date() } }); }
export async function rejectPromoterMarketingAsset(db: Db, input: any) { assertPromotersProductionReady(); return db.promoterMarketingAsset.update({ where: { publicReference: input.reference }, data: { status: "DRAFT" } }); }
export async function retirePromoterMarketingAsset(db: Db, input: any) { assertPromotersProductionReady(); return db.promoterMarketingAsset.update({ where: { publicReference: input.reference }, data: { status: "RETIRED", retiredAt: new Date() } }); }
export async function listApprovedPromoterAssets(db: Db, programVersionId?: string) { assertPromotersProductionReady(); return db.promoterMarketingAsset.findMany({ where: { status: "APPROVED", ...(programVersionId ? { programVersionId } : {}) }, select: { publicReference: true, assetType: true, title: true, description: true, trustedAssetReference: true, requiredDisclosure: true, approvedClaims: true, prohibitedAlterations: true } }); }
