/**
 * KT COURIERS — AUTHORITATIVE TYPED MEDIA REGISTRY (v2)
 *
 * Generated from Phase A/B media inventory & Sharp WebP derivation.
 * All route components and scenes import media exclusively through this registry.
 */

export interface KTMediaAsset {
  id: string;
  src: string;
  alt: string;
  width: number;
  height: number;
  aspectRatio: number;
  focalPoint: readonly [number, number] | [number, number];
  hasAlpha: boolean;
  webpSrc?: string;
  pngSrc?: string;
  srcSet?: string;
  desktopCrop: "full-bleed" | "optical-center" | "baseline-ground" | "side-anchored";
  mobileCrop: "portrait-slice" | "cab-focus" | "courier-upper" | "horizontal-crawl";
  textSafeRegion: "top-left" | "top-right" | "bottom-left" | "bottom-right" | "center-clear";
  priority?: number;
  role?: string;
}

export const ktMedia = {
  home: {
    heroTruck: {
      sideRight: {
    id: "protagonist.truck.white.side-right",
    src: "/media/public/protagonists/protagonist-truck-white-side-right.webp",
    alt: "KT Couriers long haul transport truck side profile facing right",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.55],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-side-right.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-side-right.png",
    
    desktopCrop: "baseline-ground",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      sideLeft: {
    id: "protagonist.truck.white.side-left",
    src: "/media/public/protagonists/protagonist-truck-white-side-left.webp",
    alt: "KT Couriers long haul transport truck side profile facing left",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.55],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-side-left.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-side-left.png",
    
    desktopCrop: "baseline-ground",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      centeredHero: {
    id: "protagonist.truck.white.centered-hero",
    src: "/media/public/protagonists/protagonist-truck-white-centered-hero.webp",
    alt: "KT Couriers flagship long white truck centered hero profile",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.55],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-centered-hero.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-centered-hero.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      front3qRight: {
    id: "protagonist.truck.white.front-3q-right",
    src: "/media/public/protagonists/protagonist-truck-white-front-3q-right.webp",
    alt: "Front three-quarter view of KT white truck approaching",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.45, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-front-3q-right.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-front-3q-right.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      front3qLeft: {
    id: "protagonist.truck.white.front-3q-left",
    src: "/media/public/protagonists/protagonist-truck-white-front-3q-left.webp",
    alt: "Front three-quarter view of KT white truck angled left",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.55, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-front-3q-left.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-front-3q-left.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      topDownStraight: {
    id: "protagonist.truck.white.top-down-straight",
    src: "/media/public/protagonists/protagonist-truck-white-top-down-straight.webp",
    alt: "Top-down view of KT Couriers white freight truck in transit corridor",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-top-down-straight.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-top-down-straight.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      topDownTurning: {
    id: "protagonist.truck.white.top-down-turning",
    src: "/media/public/protagonists/protagonist-truck-white-top-down-turning.webp",
    alt: "Top-down view of KT freight truck navigating regional transit turn",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-top-down-turning.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-top-down-turning.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      cargoBoxMaterial: {
    id: "protagonist.truck.white.cargo-box-material",
    src: "/media/public/protagonists/protagonist-truck-white-cargo-box-material.webp",
    alt: "Close crop of white trailer side panel acting as transition surface",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-cargo-box-material.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-cargo-box-material.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      cabCrop: {
    id: "protagonist.truck.white.close-crop-front-cab-only",
    src: "/media/public/protagonists/protagonist-truck-white-close-crop-front-cab-only.webp",
    alt: "KT Couriers fleet truck asset 11_close_crop_front_cab_only.png",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-close-crop-front-cab-only.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-close-crop-front-cab-only.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
      rearDoorsOpen: {
    id: "protagonist.truck.white.rear-doors-slightly-open",
    src: "/media/public/protagonists/protagonist-truck-white-rear-doors-slightly-open.webp",
    alt: "KT Couriers fleet truck asset 14_rear_doors_slightly_open.png",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-white-rear-doors-slightly-open.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-white-rear-doors-slightly-open.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-machine",
  },
    },
    van: {
      sideRight: {
    id: "protagonist.van.side-right",
    src: "/media/public/protagonists/protagonist-van-side-right.webp",
    alt: "KT Couriers neighborhood delivery van side view",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-van-side-right.webp",
    pngSrc: "/media/public/protagonists/protagonist-van-side-right.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-lastmile",
  },
      slidingDoorOpen: {
    id: "protagonist.van.sliding-door-open",
    src: "/media/public/protagonists/protagonist-van-sliding-door-open.webp",
    alt: "KT delivery van with sliding side door open for parcel staging",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.55, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-van-sliding-door-open.webp",
    pngSrc: "/media/public/protagonists/protagonist-van-sliding-door-open.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-lastmile",
  },
      rearDoorsOpen: {
    id: "protagonist.van.rear-doors-open",
    src: "/media/public/protagonists/protagonist-van-rear-doors-open.webp",
    alt: "KT delivery van rear cargo doors open ready for loading",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-van-rear-doors-open.webp",
    pngSrc: "/media/public/protagonists/protagonist-van-rear-doors-open.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-lastmile",
  },
      allDoorsOpen: {
    id: "protagonist.van.all-doors-open",
    src: "/media/public/protagonists/protagonist-van-all-doors-open.webp",
    alt: "KT delivery van open for neighborhood merchant collection",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-van-all-doors-open.webp",
    pngSrc: "/media/public/protagonists/protagonist-van-all-doors-open.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-lastmile",
  },
      centeredHero: {
    id: "protagonist.van.centered-hero",
    src: "/media/public/protagonists/protagonist-van-centered-hero.webp",
    alt: "KT Couriers local delivery vehicle centered hero view",
    width: 1254,
    height: 1254,
    aspectRatio: 1,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-van-centered-hero.webp",
    pngSrc: "/media/public/protagonists/protagonist-van-centered-hero.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-lastmile",
  },
      front3qRight: {
    id: "protagonist.van.front-three-quarter-facing-right",
    src: "/media/public/protagonists/protagonist-van-front-three-quarter-facing-right.webp",
    alt: "KT Couriers delivery van asset 03_front_three_quarter_facing_right.png",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-van-front-three-quarter-facing-right.webp",
    pngSrc: "/media/public/protagonists/protagonist-van-front-three-quarter-facing-right.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-lastmile",
  },
    },
    redTruck: {
      sideRight: {
    id: "protagonist.truck.red.side-right",
    src: "/media/public/protagonists/protagonist-truck-red-side-right.webp",
    alt: "KT Couriers heavy freight transport truck with red curtain trailer",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.55],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-red-side-right.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-red-side-right.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 2,
    role: "protagonist-freight",
  },
      centeredHero: {
    id: "protagonist.truck.red.centered-hero",
    src: "/media/public/protagonists/protagonist-truck-red-centered-hero.webp",
    alt: "Heavy logistics red freight truck centered hero profile",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.55],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-red-centered-hero.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-red-centered-hero.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 2,
    role: "protagonist-freight",
  },
      curtainOpen: {
    id: "protagonist.truck.red.curtain-open",
    src: "/media/public/protagonists/protagonist-truck-red-curtain-open.webp",
    alt: "Red freight truck with cargo trailer curtain partially opened",
    width: 1672,
    height: 941,
    aspectRatio: 1.777,
    focalPoint: [0.5, 0.55],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-red-curtain-open.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-red-curtain-open.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 2,
    role: "protagonist-freight",
  },
      front3qRight: {
    id: "protagonist.truck.red.front-three-quarter-view-facing-right",
    src: "/media/public/protagonists/protagonist-truck-red-front-three-quarter-view-facing-right.webp",
    alt: "KT Couriers heavy freight truck 03_front_three_quarter_view_facing_right.png",
    width: 1448,
    height: 1086,
    aspectRatio: 1.333,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-truck-red-front-three-quarter-view-facing-right.webp",
    pngSrc: "/media/public/protagonists/protagonist-truck-red-front-three-quarter-view-facing-right.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 2,
    role: "protagonist-freight",
  },
    },
    courier: {
      heroStanding: {
    id: "protagonist.courier.hero-standing",
    src: "/media/public/protagonists/protagonist-courier-hero-standing.webp",
    alt: "KT Courier standing confidently in uniform holding parcel",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-hero-standing.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-hero-standing.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
      carryOne: {
    id: "protagonist.courier.carry-one-parcel",
    src: "/media/public/protagonists/protagonist-courier-carry-one-parcel.webp",
    alt: "KT Courier carrying parcel ready for transfer",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-carry-one-parcel.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-carry-one-parcel.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
      walkRightCarryOne: {
    id: "protagonist.courier.walk-right-one-parcel",
    src: "/media/public/protagonists/protagonist-courier-walk-right-one-parcel.webp",
    alt: "KT Courier walking briskly to the right delivering a package",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-walk-right-one-parcel.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-walk-right-one-parcel.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
      readyHandover: {
    id: "protagonist.courier.ready-handover",
    src: "/media/public/protagonists/protagonist-courier-ready-handover.webp",
    alt: "KT Courier preparing to hand over package to customer",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-ready-handover.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-ready-handover.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
      extendingHandoff: {
    id: "protagonist.courier.extending-handoff",
    src: "/media/public/protagonists/protagonist-courier-extending-handoff.webp",
    alt: "KT Courier extending parcel forward completing physical delivery",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-extending-handoff.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-extending-handoff.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
      approachVehicle: {
    id: "protagonist.courier.approach-vehicle",
    src: "/media/public/protagonists/protagonist-courier-approach-vehicle.webp",
    alt: "KT Courier approaching transport van with delivery manifest",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-approach-vehicle.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-approach-vehicle.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
      loadingUnloading: {
    id: "protagonist.courier.loading-unloading",
    src: "/media/public/protagonists/protagonist-courier-loading-unloading.webp",
    alt: "KT Courier loading packages into delivery vehicle",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.4],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-loading-unloading.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-loading-unloading.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
      allPoses: [
        {
    id: "protagonist.courier.hero-standing",
    src: "/media/public/protagonists/protagonist-courier-hero-standing.webp",
    alt: "KT Courier standing confidently in uniform holding parcel",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-hero-standing.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-hero-standing.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.carry-one-parcel",
    src: "/media/public/protagonists/protagonist-courier-carry-one-parcel.webp",
    alt: "KT Courier carrying parcel ready for transfer",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-carry-one-parcel.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-carry-one-parcel.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.full-body-two-parcels",
    src: "/media/public/protagonists/protagonist-courier-full-body-two-parcels.webp",
    alt: "KT Courier team member in active delivery pose 03_full_body_two_parcels.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-full-body-two-parcels.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-full-body-two-parcels.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.walk-right-one-parcel",
    src: "/media/public/protagonists/protagonist-courier-walk-right-one-parcel.webp",
    alt: "KT Courier walking briskly to the right delivering a package",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-walk-right-one-parcel.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-walk-right-one-parcel.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.walking-one-parcel-facing-left",
    src: "/media/public/protagonists/protagonist-courier-walking-one-parcel-facing-left.webp",
    alt: "KT Courier team member in active delivery pose 05_walking_one_parcel_facing_left.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-walking-one-parcel-facing-left.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-walking-one-parcel-facing-left.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.walking-two-parcels",
    src: "/media/public/protagonists/protagonist-courier-walking-two-parcels.webp",
    alt: "KT Courier team member in active delivery pose 06_walking_two_parcels.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-walking-two-parcels.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-walking-two-parcels.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.ready-handover",
    src: "/media/public/protagonists/protagonist-courier-ready-handover.webp",
    alt: "KT Courier preparing to hand over package to customer",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-ready-handover.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-ready-handover.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.extending-handoff",
    src: "/media/public/protagonists/protagonist-courier-extending-handoff.webp",
    alt: "KT Courier extending parcel forward completing physical delivery",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-extending-handoff.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-extending-handoff.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.looking-toward-viewer-with-parcel",
    src: "/media/public/protagonists/protagonist-courier-looking-toward-viewer-with-parcel.webp",
    alt: "KT Courier team member in active delivery pose 09_looking_toward_viewer_with_parcel.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-looking-toward-viewer-with-parcel.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-looking-toward-viewer-with-parcel.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.approach-vehicle",
    src: "/media/public/protagonists/protagonist-courier-approach-vehicle.webp",
    alt: "KT Courier approaching transport van with delivery manifest",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.35],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-approach-vehicle.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-approach-vehicle.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.looking-left-approaching-vehicle",
    src: "/media/public/protagonists/protagonist-courier-looking-left-approaching-vehicle.webp",
    alt: "KT Courier team member in active delivery pose 11_looking_left_approaching_vehicle.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-looking-left-approaching-vehicle.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-looking-left-approaching-vehicle.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.placing-parcel-down",
    src: "/media/public/protagonists/protagonist-courier-placing-parcel-down.webp",
    alt: "KT Courier team member in active delivery pose 12_placing_parcel_down.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-placing-parcel-down.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-placing-parcel-down.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.lifting-parcel-up",
    src: "/media/public/protagonists/protagonist-courier-lifting-parcel-up.webp",
    alt: "KT Courier team member in active delivery pose 13_lifting_parcel_up.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-lifting-parcel-up.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-lifting-parcel-up.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.small-parcel-one-hand",
    src: "/media/public/protagonists/protagonist-courier-small-parcel-one-hand.webp",
    alt: "KT Courier team member in active delivery pose 14_small_parcel_one_hand.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-small-parcel-one-hand.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-small-parcel-one-hand.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.medium-box-under-arm",
    src: "/media/public/protagonists/protagonist-courier-medium-box-under-arm.webp",
    alt: "KT Courier team member in active delivery pose 15_medium_box_under_arm.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-medium-box-under-arm.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-medium-box-under-arm.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.empty-hands-courier-hero",
    src: "/media/public/protagonists/protagonist-courier-empty-hands-courier-hero.webp",
    alt: "KT Courier team member in active delivery pose 16_empty_hands_courier_hero.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-empty-hands-courier-hero.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-empty-hands-courier-hero.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.forward-gesture-with-parcel",
    src: "/media/public/protagonists/protagonist-courier-forward-gesture-with-parcel.webp",
    alt: "KT Courier team member in active delivery pose 17_forward_gesture_with_parcel.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-forward-gesture-with-parcel.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-forward-gesture-with-parcel.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.loading-unloading",
    src: "/media/public/protagonists/protagonist-courier-loading-unloading.webp",
    alt: "KT Courier loading packages into delivery vehicle",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.4],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-loading-unloading.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-loading-unloading.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.half-body-holding-parcel",
    src: "/media/public/protagonists/protagonist-courier-half-body-holding-parcel.webp",
    alt: "KT Courier team member in active delivery pose 19_half_body_holding_parcel.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-half-body-holding-parcel.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-half-body-holding-parcel.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  },
        {
    id: "protagonist.courier.close-crop-upper-body-portrait",
    src: "/media/public/protagonists/protagonist-courier-close-crop-upper-body-portrait.webp",
    alt: "KT Courier team member in active delivery pose 20_close_crop_upper_body_portrait.png",
    width: 1122,
    height: 1402,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    webpSrc: "/media/public/protagonists/protagonist-courier-close-crop-upper-body-portrait.webp",
    pngSrc: "/media/public/protagonists/protagonist-courier-close-crop-upper-body-portrait.png",
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "protagonist-human",
  }
      ] as readonly KTMediaAsset[],
    },
  },

  categories: {
    fashion: {
      hero: {
    id: "photo.fashion.rosebank-leather-bags",
    src: "/media/public/derived/photo-fashion-rosebank-leather-bags-1440w.webp",
    alt: "Artisan leather bags and goods at Rosebank market ready for dispatch",
    width: 2560,
    height: 1707,
    aspectRatio: 1.5,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-fashion-rosebank-leather-bags-640w.webp 640w, /media/public/derived/photo-fashion-rosebank-leather-bags-960w.webp 960w, /media/public/derived/photo-fashion-rosebank-leather-bags-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
      streetLook1: {
    id: "photo.fashion.jhb-editorial-coat",
    src: "/media/public/derived/photo-fashion-jhb-editorial-coat-1440w.webp",
    alt: "Contemporary Johannesburg street fashion brown coat editorial",
    width: 2048,
    height: 2560,
    aspectRatio: 0.8,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-fashion-jhb-editorial-coat-640w.webp 640w, /media/public/derived/photo-fashion-jhb-editorial-coat-960w.webp 960w, /media/public/derived/photo-fashion-jhb-editorial-coat-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
      streetLook2: {
    id: "photo.fashion.jhb-editorial-white",
    src: "/media/public/derived/photo-fashion-jhb-editorial-white-1440w.webp",
    alt: "South African urban apparel and streetwear editorial",
    width: 1922,
    height: 2560,
    aspectRatio: 0.751,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-fashion-jhb-editorial-white-640w.webp 640w, /media/public/derived/photo-fashion-jhb-editorial-white-960w.webp 960w, /media/public/derived/photo-fashion-jhb-editorial-white-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
      urbanGraffiti: {
    id: "photo.fashion.jhb-street-graffiti",
    src: "/media/public/derived/photo-fashion-jhb-street-graffiti-1440w.webp",
    alt: "Urban South African fashion portrait against textured city wall",
    width: 1922,
    height: 2560,
    aspectRatio: 0.751,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-fashion-jhb-street-graffiti-640w.webp 640w, /media/public/derived/photo-fashion-jhb-street-graffiti-960w.webp 960w, /media/public/derived/photo-fashion-jhb-street-graffiti-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 2,
    role: "editorial-commerce",
  },
    },
    groceries: {
      hero: {
    id: "photo.grocery.fruit-crates-overhead",
    src: "/media/public/derived/photo-grocery-fruit-crates-overhead-1440w.webp",
    alt: "Crates of fresh South African market fruit ready for local grocery dispatch",
    width: 2560,
    height: 1600,
    aspectRatio: 1.6,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-grocery-fruit-crates-overhead-640w.webp 640w, /media/public/derived/photo-grocery-fruit-crates-overhead-960w.webp 960w, /media/public/derived/photo-grocery-fruit-crates-overhead-1440w.webp 1440w",
    desktopCrop: "full-bleed",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
      freshGreens: {
    id: "photo.grocery.vegetables-crate",
    src: "/media/public/derived/photo-grocery-vegetables-crate-1440w.webp",
    alt: "Farm fresh greens and market vegetables packed for delivery",
    width: 2560,
    height: 1702,
    aspectRatio: 1.504,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-grocery-vegetables-crate-640w.webp 640w, /media/public/derived/photo-grocery-vegetables-crate-960w.webp 960w, /media/public/derived/photo-grocery-vegetables-crate-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
    },
    foodDining: {
      hero: {
    id: "photo.food.prepared-grain-bowl",
    src: "/media/public/derived/photo-food-prepared-grain-bowl-1440w.webp",
    alt: "Artisan grain bowl prepared in local kitchen for rapid delivery",
    width: 2560,
    height: 1702,
    aspectRatio: 1.504,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-food-prepared-grain-bowl-640w.webp 640w, /media/public/derived/photo-food-prepared-grain-bowl-960w.webp 960w, /media/public/derived/photo-food-prepared-grain-bowl-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
      kitchenPlating: {
    id: "photo.food.kitchen-plating-pass",
    src: "/media/public/derived/photo-food-kitchen-plating-pass-1440w.webp",
    alt: "Commercial kitchen chef preparing warm orders for delivery dispatch",
    width: 5410,
    height: 3607,
    aspectRatio: 1.5,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-food-kitchen-plating-pass-640w.webp 640w, /media/public/derived/photo-food-kitchen-plating-pass-960w.webp 960w, /media/public/derived/photo-food-kitchen-plating-pass-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
    },
    homeLiving: {
      hero: {
    id: "photo.commerce.cape-town-market-ceramics",
    src: "/media/public/derived/photo-commerce-cape-town-market-ceramics-1440w.webp",
    alt: "Artisanal ceramic tableware from Cape Town market makers",
    width: 2560,
    height: 1702,
    aspectRatio: 1.504,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-commerce-cape-town-market-ceramics-640w.webp 640w, /media/public/derived/photo-commerce-cape-town-market-ceramics-960w.webp 960w, /media/public/derived/photo-commerce-cape-town-market-ceramics-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
      interiorVessel: {
    id: "photo.commerce.sculptural-ceramics-vessel",
    src: "/media/public/derived/photo-commerce-sculptural-ceramics-vessel-1440w.webp",
    alt: "Handcrafted architectural ceramic vessel for fragile courier transport",
    width: 3840,
    height: 2160,
    aspectRatio: 1.778,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-commerce-sculptural-ceramics-vessel-640w.webp 640w, /media/public/derived/photo-commerce-sculptural-ceramics-vessel-960w.webp 960w, /media/public/derived/photo-commerce-sculptural-ceramics-vessel-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
    },
    healthWellness: {
      hero: {
    id: "photo.wellness.amber-apothecary-bottles",
    src: "/media/public/derived/photo-wellness-amber-apothecary-bottles-1440w.webp",
    alt: "Amber glass apothecary droppers and botanical wellness formulations",
    width: 4252,
    height: 6378,
    aspectRatio: 0.667,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-wellness-amber-apothecary-bottles-640w.webp 640w, /media/public/derived/photo-wellness-amber-apothecary-bottles-960w.webp 960w, /media/public/derived/photo-wellness-amber-apothecary-bottles-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
      apothecaryJars: {
    id: "photo.wellness.herbal-jars-dispensary",
    src: "/media/public/derived/photo-wellness-herbal-jars-dispensary-1440w.webp",
    alt: "Natural botanical creams and skincare jars arranged for dispatch",
    width: 6475,
    height: 4317,
    aspectRatio: 1.5,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-wellness-herbal-jars-dispensary-640w.webp 640w, /media/public/derived/photo-wellness-herbal-jars-dispensary-960w.webp 960w, /media/public/derived/photo-wellness-herbal-jars-dispensary-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
      essentialOils: {
    id: "photo.wellness.organic-botanical-serum",
    src: "/media/public/derived/photo-wellness-organic-botanical-serum-1440w.webp",
    alt: "Sealed organic botanical skincare serum ready for express transit",
    width: 2400,
    height: 2400,
    aspectRatio: 1,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-wellness-organic-botanical-serum-640w.webp 640w, /media/public/derived/photo-wellness-organic-botanical-serum-960w.webp 960w, /media/public/derived/photo-wellness-organic-botanical-serum-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
    },
  },

  routes: {
    nightTransitCorridor: {
    id: "photo.route.night-highway-transit",
    src: "/media/public/derived/photo-route-night-highway-transit-1920w.webp",
    alt: "Night transit freight route with vehicle light trails across highway",
    width: 5472,
    height: 3648,
    aspectRatio: 1.5,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-route-night-highway-transit-960w.webp 960w, /media/public/derived/photo-route-night-highway-transit-1440w.webp 1440w, /media/public/derived/photo-route-night-highway-transit-1920w.webp 1920w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "route-environment",
  },
    aerialHighway: {
    id: "photo.route.overhead-cloverleaf-interchange",
    src: "/media/public/derived/photo-route-overhead-cloverleaf-interchange-1920w.webp",
    alt: "Geometric highway interchange connecting north-south logistics corridors",
    width: 8192,
    height: 4608,
    aspectRatio: 1.778,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-route-overhead-cloverleaf-interchange-960w.webp 960w, /media/public/derived/photo-route-overhead-cloverleaf-interchange-1440w.webp 1440w, /media/public/derived/photo-route-overhead-cloverleaf-interchange-1920w.webp 1920w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "route-environment",
  },
    gautengTransitLine: {
    id: "photo.route.gauteng-transit-corridor",
    src: "/media/public/derived/photo-route-gauteng-transit-corridor-1920w.webp",
    alt: "Aerial perspective over Gauteng transit highway corridor",
    width: 6240,
    height: 4160,
    aspectRatio: 1.5,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-route-gauteng-transit-corridor-960w.webp 960w, /media/public/derived/photo-route-gauteng-transit-corridor-1440w.webp 1440w, /media/public/derived/photo-route-gauteng-transit-corridor-1920w.webp 1920w",
    desktopCrop: "full-bleed",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "route-environment",
  },
    johannesburgCorridor: {
    id: "photo.route.long-haul-freeway-vista",
    src: "/media/public/derived/photo-route-long-haul-freeway-vista-1920w.webp",
    alt: "Long haul freight transport freeway extending across landscape",
    width: 7360,
    height: 4912,
    aspectRatio: 1.498,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-route-long-haul-freeway-vista-960w.webp 960w, /media/public/derived/photo-route-long-haul-freeway-vista-1440w.webp 1440w, /media/public/derived/photo-route-long-haul-freeway-vista-1920w.webp 1920w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "route-environment",
  },
    mabonengWorkshop: {
    id: "photo.prep.maboneng-fleet-depot",
    src: "/media/public/derived/photo-prep-maboneng-fleet-depot-1440w.webp",
    alt: "Vehicle fleet preparation workshop in Maboneng, Johannesburg",
    width: 2560,
    height: 1707,
    aspectRatio: 1.5,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-prep-maboneng-fleet-depot-640w.webp 640w, /media/public/derived/photo-prep-maboneng-fleet-depot-960w.webp 960w, /media/public/derived/photo-prep-maboneng-fleet-depot-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 2,
    role: "merchant-prep",
  },
  },

  documentary: {
    driverArrival: {
    id: "photo.courier.doorstep-driver-arrival",
    src: "/media/public/derived/photo-courier-doorstep-driver-arrival-1440w.webp",
    alt: "KT Courier arriving at destination doorstep with customer package",
    width: 1600,
    height: 1068,
    aspectRatio: 1.498,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-courier-doorstep-driver-arrival-640w.webp 640w, /media/public/derived/photo-courier-doorstep-driver-arrival-960w.webp 960w, /media/public/derived/photo-courier-doorstep-driver-arrival-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "courier-human",
  },
    pickup: {
    id: "photo.courier.merchant-pickup-handoff",
    src: "/media/public/derived/photo-courier-merchant-pickup-handoff-1440w.webp",
    alt: "Courier verifying barcode manifest during merchant collection",
    width: 1600,
    height: 1068,
    aspectRatio: 1.498,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-courier-merchant-pickup-handoff-640w.webp 640w, /media/public/derived/photo-courier-merchant-pickup-handoff-960w.webp 960w, /media/public/derived/photo-courier-merchant-pickup-handoff-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "courier-human",
  },
    trackingCheck: {
    id: "photo.courier.digital-manifest-check",
    src: "/media/public/derived/photo-courier-digital-manifest-check-1440w.webp",
    alt: "Driver verifying digital dispatch route manifest beside vehicle",
    width: 1600,
    height: 1068,
    aspectRatio: 1.498,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-courier-digital-manifest-check-640w.webp 640w, /media/public/derived/photo-courier-digital-manifest-check-960w.webp 960w, /media/public/derived/photo-courier-digital-manifest-check-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "courier-human",
  },
    handoffDetail: {
    id: "photo.courier.recipient-physical-handoff",
    src: "/media/public/derived/photo-courier-recipient-physical-handoff-1440w.webp",
    alt: "Close up physical parcel exchange between courier and customer",
    width: 1600,
    height: 1068,
    aspectRatio: 1.498,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-courier-recipient-physical-handoff-640w.webp 640w, /media/public/derived/photo-courier-recipient-physical-handoff-960w.webp 960w, /media/public/derived/photo-courier-recipient-physical-handoff-1440w.webp 1440w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "courier-human",
  },
  },

  auth: {
    customer: {
    id: "photo.courier.recipient-receiving-delivery",
    src: "/media/public/derived/photo-courier-recipient-receiving-delivery-960w.webp",
    alt: "Customer receiving delivered goods safely at front entrance",
    width: 1000,
    height: 1500,
    aspectRatio: 0.667,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-courier-recipient-receiving-delivery-640w.webp 640w, /media/public/derived/photo-courier-recipient-receiving-delivery-960w.webp 960w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "courier-human",
  },
    merchant: {
    id: "photo.prep.artisan-box-assembly",
    src: "/media/public/derived/photo-prep-artisan-box-assembly-960w.webp",
    alt: "Artisan workshop merchant taping and assembling branded shipping box",
    width: 1001,
    height: 1500,
    aspectRatio: 0.667,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-prep-artisan-box-assembly-640w.webp 640w, /media/public/derived/photo-prep-artisan-box-assembly-960w.webp 960w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "merchant-prep",
  },
    product: {
    id: "photo.commerce.clean-packaged-goods-stack",
    src: "/media/public/derived/photo-commerce-clean-packaged-goods-stack-960w.webp",
    alt: "Branded parcels and curated retail goods ready for shipping",
    width: 1000,
    height: 1500,
    aspectRatio: 0.667,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-commerce-clean-packaged-goods-stack-640w.webp 640w, /media/public/derived/photo-commerce-clean-packaged-goods-stack-960w.webp 960w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 1,
    role: "editorial-commerce",
  },
    recovery: {
    id: "photo.auth.recovery-keycard",
    src: "/media/public/derived/photo-auth-recovery-keycard-960w.webp",
    alt: "Secure account verification and recovery authentication visual",
    width: 1000,
    height: 1500,
    aspectRatio: 0.667,
    focalPoint: [0.5, 0.5],
    hasAlpha: false,
    
    
    srcSet: "/media/public/derived/photo-auth-recovery-keycard-640w.webp 640w, /media/public/derived/photo-auth-recovery-keycard-960w.webp 960w",
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 2,
    role: "editorial-commerce",
  },
  },

  illustrations: {
    orderDelivery: {
    id: "illustration.order-delivery",
    src: "/media/public/illustrations/Order Delivery.svg",
    alt: "Operational illustration for Order Delivery",
    width: 800,
    height: 800,
    aspectRatio: 1,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    
    
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 4,
    role: "illustration-vector",
  },
    packageDelivery: {
    id: "illustration.package-delivery",
    src: "/media/public/illustrations/Package delivery.svg",
    alt: "Operational illustration for Package delivery",
    width: 800,
    height: 800,
    aspectRatio: 1,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    
    
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 4,
    role: "illustration-vector",
  },
    gpsLocation: {
    id: "illustration.gps-location",
    src: "/media/public/illustrations/gps location.svg",
    alt: "Operational illustration for gps location",
    width: 800,
    height: 800,
    aspectRatio: 1,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    
    
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 4,
    role: "illustration-vector",
  },
    onlineShopping: {
    id: "illustration.kt-ill-online-shopping",
    src: "/media/public/illustrations/kt-ill-online-shopping.svg",
    alt: "Operational illustration for kt-ill-online-shopping",
    width: 800,
    height: 800,
    aspectRatio: 1,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    
    
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 4,
    role: "illustration-vector",
  },
    motionOrderState: {
    id: "illustration.kt-motion-order-state",
    src: "/media/public/illustrations/kt-motion-order-state.svg",
    alt: "Operational illustration for kt-motion-order-state",
    width: 800,
    height: 800,
    aspectRatio: 1,
    focalPoint: [0.5, 0.5],
    hasAlpha: true,
    
    
    
    desktopCrop: "optical-center",
    mobileCrop: "portrait-slice",
    textSafeRegion: "center-clear",
    priority: 4,
    role: "illustration-vector",
  },
  },
} as const;

export const sceneManifests = {
  homepage: {
    scene00_02_hero: [
      ktMedia.home.heroTruck.sideRight,
      ktMedia.home.heroTruck.centeredHero,
    ],
    scene05_07_marketplace: [
      ktMedia.home.heroTruck.cargoBoxMaterial,
      ktMedia.categories.fashion.hero,
      ktMedia.categories.groceries.hero,
      ktMedia.categories.foodDining.hero,
      ktMedia.categories.homeLiving.hero,
      ktMedia.categories.healthWellness.hero,
    ],
    scene08_10_handoff: [
      ktMedia.documentary.pickup,
      ktMedia.home.van.slidingDoorOpen,
      ktMedia.home.courier.carryOne,
      ktMedia.home.courier.readyHandover,
      ktMedia.documentary.handoffDetail,
    ],
    scene11_12_route: [
      ktMedia.home.heroTruck.topDownStraight,
      ktMedia.home.heroTruck.topDownTurning,
      ktMedia.routes.aerialHighway,
      ktMedia.home.redTruck.sideRight,
    ],
    scene13_14_arrival: [
      ktMedia.home.courier.extendingHandoff,
      ktMedia.home.courier.heroStanding,
    ],
  },
  shop: {
    threshold: [ktMedia.categories.fashion.hero],
    categories: [
      ktMedia.categories.fashion.hero,
      ktMedia.categories.groceries.hero,
      ktMedia.categories.foodDining.hero,
      ktMedia.categories.healthWellness.hero,
      ktMedia.categories.homeLiving.hero,
    ],
  },
} as const;

export function getMediaSrcSet(asset: KTMediaAsset): string | undefined {
  return asset.srcSet;
}

export function getRouteLcpAsset(pathname: string): KTMediaAsset | null {
  if (pathname === "/") return ktMedia.home.heroTruck.sideRight;
  if (pathname.startsWith("/shop/categories")) return ktMedia.categories.fashion.hero;
  if (pathname.startsWith("/shop")) return ktMedia.categories.fashion.hero;
  if (pathname.startsWith("/services/freight")) return ktMedia.home.redTruck.sideRight;
  if (pathname.startsWith("/services/parcel")) return ktMedia.home.courier.heroStanding;
  if (pathname.startsWith("/services/grocery") || pathname.startsWith("/services/food")) return ktMedia.home.van.sideRight;
  if (pathname.startsWith("/about")) return ktMedia.routes.mabonengWorkshop;
  if (pathname.startsWith("/login") || pathname.startsWith("/signup")) return ktMedia.auth.customer;
  return null;
}
