import Link from "next/link";
import {
  ActivityTimeline,
  EditorialTable,
  MetricTile,
  OperationalPanel,
  ProtectedContentGrid,
  ProtectedPageFrame,
  ProtectedPageHeader,
  ProtectedState,
  ProtectedStatus,
} from "@/components/protected-v2";
import { RouteQueueIllustration } from "@/components/protected-v2/illustrations/RouteQueueIllustration";
import { SecureLedgerIllustration } from "@/components/protected-v2/illustrations/SecureLedgerIllustration";
import type {
  PromoterAccountProjection,
  PromoterEarningRecord,
  PromoterReferralRecord,
  PromoterWithdrawalRecord,
} from "@/lib/promoter-presentation/promoter-data";
import {
  formatPromoterDate,
  formatPromoterDateTime,
  formatPromoterMoney,
  getPromoterEarningPresentation,
  getPromoterLifecyclePresentation,
  getPromoterQualificationPresentation,
  getPromoterReferralPresentation,
  getPromoterWithdrawalPresentation,
  selectPromoterOperationalState,
} from "@/lib/promoter-presentation";
import styles from "./promoter-pages.module.css";

export function PromoterAction({ href, children, primary = false }: { href: string; children: React.ReactNode; primary?: boolean }) {
  return <Link className={`${styles.action} ${primary ? styles.actionPrimary : ""}`} href={href}>{children}</Link>;
}

export function PromoterPage({ eyebrow = "Promoter programme", title, description, actions, children }: { eyebrow?: string; title: string; description?: string; actions?: React.ReactNode; children: React.ReactNode }) {
  return <div className={styles.scope}><ProtectedPageFrame><ProtectedPageHeader eyebrow={eyebrow} title={title} description={description} actions={actions} />{children}</ProtectedPageFrame></div>;
}

export function PromoterAccountUnavailablePage({ title = "Promoter programme unavailable" }: { title?: string }) {
  return <PromoterPage title={title} description="A promoter-account projection is not available for this session."><ProtectedState kind="unavailable" title="Programme account unavailable" description="The current account state could not be loaded safely. No referral or financial state is assumed." illustration={<RouteQueueIllustration className="h-24 w-32" />} action={<PromoterAction href="/promoter/support">Get support</PromoterAction>} /></PromoterPage>;
}

export function PromoterAccessRestrictedPage({ account, title = "Promoter records unavailable" }: { account: PromoterAccountProjection; title?: string }) {
  const lifecycle = getPromoterLifecyclePresentation(account.status);
  return <PromoterPage title={title} description="This route does not expose promoter records for the current account condition or permission set."><ProtectedState kind={lifecycle.restricted ? "restricted" : "unavailable"} title={lifecycle.label} description={lifecycle.restricted ? lifecycle.description : "The required promoter permission is not available. No records are shown."} illustration={<RouteQueueIllustration className="h-24 w-32" />} action={lifecycle.actionHref && lifecycle.actionLabel ? <PromoterAction href={lifecycle.actionHref}>{lifecycle.actionLabel}</PromoterAction> : undefined} /></PromoterPage>;
}

export function PromoterOverviewPage({
  account,
  referralCodes,
  referrals,
  wallet,
  pendingQualificationCount,
  activeCodeCount,
  heldEarnings,
  pendingWithdrawalCount,
  unreadNotifications,
}: {
  account: PromoterAccountProjection;
  referralCodes: readonly { id: string; publicReference: string; maskedDisplay: string; status: string; expiresAt: Date | null; channelName: string | null }[];
  referrals: readonly PromoterReferralRecord[];
  wallet: { availableBalance: unknown; pendingBalance: unknown; lockedBalance: unknown; currency: string; status: string } | null;
  pendingQualificationCount: number;
  activeCodeCount: number;
  heldEarnings: unknown;
  pendingWithdrawalCount: number;
  unreadNotifications: number;
}) {
  const lifecycle = getPromoterLifecyclePresentation(account.status);
  const operational = selectPromoterOperationalState({ ...account, pendingQualificationCount, hasRecentReferralActivity: referrals.length > 0 });
  const primaryCode = referralCodes.find((code) => code.status === "ACTIVE") ?? null;
  const recent = referrals.slice(0, 5);
  const lifecyclePanel = <OperationalPanel title="Programme state" description="The current account lifecycle is determined by the canonical promoter authority." padding="compact"><div className={styles.summary}><ProtectedStatus label={lifecycle.label} tone={lifecycle.tone} /><p className={styles.notice}>{lifecycle.description}</p>{lifecycle.actionHref && lifecycle.actionLabel ? <div className={styles.actions}><PromoterAction href={lifecycle.actionHref}>{lifecycle.actionLabel}</PromoterAction></div> : null}</div></OperationalPanel>;
  const financialRail = <div className="space-y-4"><OperationalPanel title="Earning context" padding="compact"><dl className={styles.facts}><div><dt>Available balance</dt><dd>{wallet ? formatPromoterMoney(wallet.availableBalance, wallet.currency) : "Not provisioned"}</dd></div><div><dt>Held earnings</dt><dd>{formatPromoterMoney(heldEarnings)}</dd></div><div><dt>Withdrawal requests in progress</dt><dd>{pendingWithdrawalCount}</dd></div></dl><p className={styles.notice}>Availability and withdrawal eligibility remain server-authoritative. New promoter withdrawal requests are currently production locked.</p></OperationalPanel><OperationalPanel title="Account updates" padding="compact"><p className={styles.notice}>{unreadNotifications ? `${unreadNotifications} unread programme notification${unreadNotifications === 1 ? "" : "s"}.` : "No unread programme notifications."}</p><div className={`${styles.actions} mt-3`}><PromoterAction href="/promoter/notifications">View notifications</PromoterAction></div></OperationalPanel></div>;
  return <PromoterPage title={account.displayName ?? "Promoter overview"} description="A referral ledger for programme state, owned activity, qualification, and earning records." actions={<PromoterAction href="/promoter/links" primary>Referral tools</PromoterAction>}><ProtectedContentGrid contextRail={financialRail}><div className="space-y-6">{lifecyclePanel}<div className={styles.metricGrid} aria-label="Promoter programme summary"><MetricTile label="Pending qualification" value={pendingQualificationCount} description="Owned records awaiting a final qualification state" /><MetricTile label="Active referral codes" value={activeCodeCount} description="Current owned code records" /><MetricTile label="Held earnings" value={formatPromoterMoney(heldEarnings)} description="Held, not available" /><MetricTile label="Available balance" value={wallet ? formatPromoterMoney(wallet.availableBalance, wallet.currency) : "Not provisioned"} description="Current wallet projection" /></div><OperationalPanel title="Current referral tool" description="Referral tools remain canonical records; this application never constructs a link or identifier.">{primaryCode ? <div className={styles.summary}><div className={styles.recordHead}><div><p className={styles.reference}>{primaryCode.maskedDisplay}</p><p className={styles.recordMeta}>{primaryCode.channelName ? `Channel: ${primaryCode.channelName}` : "No channel is associated with this code."}</p></div><ProtectedStatus label="Active" tone="success" /></div><p className={styles.notice}>Only the masked code is available in the current promoter-safe projection. A server-confirmed share URL is not provided, so copy and share controls are intentionally absent.</p><div className={styles.actions}><PromoterAction href="/promoter/links">View referral tools</PromoterAction></div></div> : <ProtectedState kind={lifecycle.restricted ? "restricted" : "empty"} title={lifecycle.restricted ? "Referral tools unavailable" : "No active referral code"} description={lifecycle.restricted ? "The programme state does not make referral tools available." : "A referral code appears only after the canonical authority creates an owned record."} action={<PromoterAction href="/promoter/links">View referral tools</PromoterAction>} />}</OperationalPanel><OperationalPanel title="Qualification activity" description={`Operational presentation: ${operational.replaceAll("_", " ").toLowerCase()}. Recent owned attribution records are shown without customer identity.`} action={<PromoterAction href="/promoter/referrals">View all referrals</PromoterAction>}><PromoterReferralRecords referrals={recent} /></OperationalPanel></div></ProtectedContentGrid></PromoterPage>;
}

export function PromoterReferralRecords({ referrals }: { referrals: readonly PromoterReferralRecord[] }) {
  if (!referrals.length) return <ProtectedState kind="empty" title="No attributed referrals" description="An attributed referral appears here only after the canonical attribution authority creates an owned record." illustration={<RouteQueueIllustration className="h-24 w-32" />} />;
  return <><div className={styles.desktopOnly}><EditorialTable caption="Owned attributed referral records" mobileMode="priority" rows={referrals} columns={[{ id: "reference", header: "Referral", priority: "primary", cell: (row) => <Link className={styles.reference} href={`/promoter/referrals/${row.publicReference}`}>{row.publicReference}</Link> }, { id: "state", header: "Attribution", priority: "primary", cell: (row) => { const item = getPromoterReferralPresentation(row.status); return <ProtectedStatus label={item.label} tone={item.tone} />; } }, { id: "qualification", header: "Qualification", priority: "secondary", cell: (row) => { const item = getPromoterQualificationPresentation(row.qualification?.status); return <ProtectedStatus label={item.label} tone={item.tone} />; } }, { id: "attributed", header: "Attributed", priority: "secondary", cell: (row) => formatPromoterDate(row.attributedAt) }, { id: "action", header: "", priority: "optional", align: "end", cell: (row) => <PromoterAction href={`/promoter/referrals/${row.publicReference}`}>View record</PromoterAction> }]} /></div><ul aria-label="Owned attributed referral records" className={`${styles.recordList} ${styles.mobileOnly}`}>{referrals.map((row) => { const referral = getPromoterReferralPresentation(row.status); const qualification = getPromoterQualificationPresentation(row.qualification?.status); return <li className={styles.record} key={row.id}><div className={styles.recordHead}><div><Link className={styles.reference} href={`/promoter/referrals/${row.publicReference}`}>{row.publicReference}</Link><p className={styles.recordMeta}>Attributed {formatPromoterDate(row.attributedAt)}</p></div><ProtectedStatus label={qualification.label} tone={qualification.tone} /></div><p className={styles.recordCopy}>{referral.label} · {qualification.description}</p><div className={styles.actions}><PromoterAction href={`/promoter/referrals/${row.publicReference}`}>View referral</PromoterAction></div></li>; })}</ul></>;
}

export function PromoterReferralsPage({ referrals }: { referrals: readonly PromoterReferralRecord[] }) {
  return <PromoterPage title="Attributed referrals" description="Owned, privacy-safe attribution records. Customer identity, order details, network data, and attribution evidence are not shown."><OperationalPanel title="Referral activity" description="The current API supplies no promoter-supported filters or pagination, so this view does not simulate either."><PromoterReferralRecords referrals={referrals} /></OperationalPanel></PromoterPage>;
}

function destinationLabel(destinationType: string | null | undefined): string {
  if (destinationType === "CUSTOMER_REGISTRATION") return "Customer registration";
  if (destinationType === "STORE_APPLICATION") return "Store application";
  return "Approved internal destination";
}

export function PromoterReferralDetailPage({ referral }: { referral: PromoterReferralRecord }) {
  const referralStatus = getPromoterReferralPresentation(referral.status);
  const qualification = getPromoterQualificationPresentation(referral.qualification?.status);
  const timeline = [
    { id: "attributed", title: "Attributed", description: "An owned referral attribution was recorded.", timestamp: formatPromoterDateTime(referral.attributedAt), tone: "information" as const },
    ...(referral.qualification ? [{ id: "qualification-recorded", title: qualification.label, description: qualification.description, timestamp: formatPromoterDateTime(referral.qualification.createdAt), tone: qualification.tone }] : []),
    ...(referral.qualification?.qualifiedAt ? [{ id: "qualified-at", title: "Qualification timestamp", description: "A canonical qualification timestamp is available.", timestamp: formatPromoterDateTime(referral.qualification.qualifiedAt), tone: qualification.tone }] : []),
    ...(referral.qualification?.releasedAt ? [{ id: "released-at", title: "Release timestamp", description: "A canonical release timestamp is available. This is not automatically a payout confirmation.", timestamp: formatPromoterDateTime(referral.qualification.releasedAt), tone: "success" as const }] : []),
  ];
  return <PromoterPage eyebrow="Attributed referral" title={referral.publicReference} description="A promoter-safe record of one owned attribution." actions={<PromoterAction href="/promoter/referrals">Back to referrals</PromoterAction>}><div className="space-y-6"><OperationalPanel title="Current state"><div className={styles.summary}><div className={styles.actions}><ProtectedStatus label={referralStatus.label} tone={referralStatus.tone} /><ProtectedStatus label={qualification.label} tone={qualification.tone} /></div><p className={styles.notice}>{qualification.description}</p><dl className={styles.facts}><div><dt>Attributed</dt><dd>{formatPromoterDateTime(referral.attributedAt)}</dd></div><div><dt>Source</dt><dd>{destinationLabel(referral.touch?.destinationType)}</dd></div>{referral.qualification?.holdUntil ? <div><dt>Hold until</dt><dd>{formatPromoterDate(referral.qualification.holdUntil)}</dd></div> : null}</dl></div></OperationalPanel><OperationalPanel title="Recorded activity" description="Only timestamped events present in the promoter-safe projection are listed."><ActivityTimeline ariaLabel="Referral activity timeline" items={timeline} /></OperationalPanel></div></PromoterPage>;
}

export function PromoterEarningRecords({ earnings }: { earnings: readonly PromoterEarningRecord[] }) {
  if (!earnings.length) return <ProtectedState kind="empty" title="No earning records" description="An earning appears only after the canonical qualification and earning authorities create it." illustration={<SecureLedgerIllustration className="h-24 w-32" />} />;
  return <><div className={styles.desktopOnly}><EditorialTable caption="Promoter earning records" mobileMode="stack" rows={earnings} columns={[{ id: "reference", header: "Earning", cell: (row) => <Link className={styles.reference} href={`/promoter/earnings/${row.publicReference}`}>{row.publicReference}</Link> }, { id: "amount", header: "Amount", align: "end", cell: (row) => formatPromoterMoney(row.grossAmount, row.currency) }, { id: "state", header: "State", cell: (row) => { const item = getPromoterEarningPresentation(row.status); return <ProtectedStatus label={item.label} tone={item.tone} />; } }, { id: "hold", header: "Hold/release date", cell: (row) => formatPromoterDate(row.releasedAt ?? row.holdUntil) }, { id: "action", header: "", align: "end", cell: (row) => <PromoterAction href={`/promoter/earnings/${row.publicReference}`}>View record</PromoterAction> }]} /></div><ul aria-label="Promoter earning records" className={`${styles.recordList} ${styles.mobileOnly}`}>{earnings.map((row) => { const item = getPromoterEarningPresentation(row.status); return <li className={styles.record} key={row.id}><div className={styles.recordHead}><div><Link className={styles.reference} href={`/promoter/earnings/${row.publicReference}`}>{row.publicReference}</Link><p className={styles.recordMeta}>{formatPromoterMoney(row.grossAmount, row.currency)}</p></div><ProtectedStatus label={item.label} tone={item.tone} /></div><p className={styles.recordCopy}>{item.description}</p><div className={styles.actions}><PromoterAction href={`/promoter/earnings/${row.publicReference}`}>View earning</PromoterAction></div></li>; })}</ul></>;
}

export function PromoterEarningsPage({ earnings, heldEarnings, wallet }: { earnings: readonly PromoterEarningRecord[]; heldEarnings: unknown; wallet: { availableBalance: unknown; pendingBalance: unknown; lockedBalance: unknown; currency: string; status: string } | null }) {
  return <PromoterPage title="Earnings" description="Source-backed earning records. Held funds, released funds, and withdrawals are distinct states."><div className="space-y-6"><div className={styles.metricGrid} aria-label="Promoter earnings summary"><MetricTile label="Held earnings" value={formatPromoterMoney(heldEarnings)} description="Not available to withdraw" /><MetricTile label="Available balance" value={wallet ? formatPromoterMoney(wallet.availableBalance, wallet.currency) : "Not provisioned"} description="Current wallet projection" /><MetricTile label="Pending wallet balance" value={wallet ? formatPromoterMoney(wallet.pendingBalance, wallet.currency) : "Not provisioned"} description="Wallet projection only" /><MetricTile label="Locked wallet balance" value={wallet ? formatPromoterMoney(wallet.lockedBalance, wallet.currency) : "Not provisioned"} description="Not available to withdraw" /></div><OperationalPanel title="Earning history" description="Amounts are formatted from server-issued decimal values. No commission calculation or payout forecast is performed in the browser."><PromoterEarningRecords earnings={earnings} /></OperationalPanel></div></PromoterPage>;
}

export function PromoterEarningDetailPage({ earning }: { earning: PromoterEarningRecord }) {
  const state = getPromoterEarningPresentation(earning.status);
  const events = [
    ...(earning.accruedAt ? [{ id: "accrued", title: "Accrued", description: "A canonical earning accrual timestamp is available.", timestamp: formatPromoterDateTime(earning.accruedAt), tone: "warning" as const }] : []),
    ...(earning.releasedAt ? [{ id: "released", title: "Released", description: "Released does not automatically mean paid out.", timestamp: formatPromoterDateTime(earning.releasedAt), tone: "success" as const }] : []),
    ...(earning.reversedAt ? [{ id: "reversed", title: "Reversed", description: "No internal review or fraud evidence is displayed.", timestamp: formatPromoterDateTime(earning.reversedAt), tone: "danger" as const }] : []),
  ];
  return <PromoterPage eyebrow="Earning record" title={earning.publicReference} description="A promoter-safe financial projection for one canonical earning." actions={<PromoterAction href="/promoter/earnings">Back to earnings</PromoterAction>}><div className="space-y-6"><OperationalPanel title="Financial state"><div className={styles.summary}><ProtectedStatus label={state.label} tone={state.tone} /><p className={styles.notice}>{state.description}</p><dl className={styles.facts}><div><dt>Gross amount</dt><dd>{formatPromoterMoney(earning.grossAmount, earning.currency)}</dd></div><div><dt>Available amount</dt><dd>{formatPromoterMoney(earning.payableAmount, earning.currency)}</dd></div><div><dt>Reversed amount</dt><dd>{formatPromoterMoney(earning.reversedAmount, earning.currency)}</dd></div><div><dt>Withdrawn amount</dt><dd>{formatPromoterMoney(earning.withdrawnAmount, earning.currency)}</dd></div><div><dt>Hold until</dt><dd>{formatPromoterDate(earning.holdUntil)}</dd></div>{earning.qualificationReference ? <div><dt>Qualification reference</dt><dd><span className={styles.reference}>{earning.qualificationReference}</span></dd></div> : null}</dl></div></OperationalPanel>{events.length ? <OperationalPanel title="Recorded financial activity"><ActivityTimeline ariaLabel="Earning activity timeline" items={events} /></OperationalPanel> : <OperationalPanel title="Recorded financial activity"><p className={styles.notice}>No promoter-safe earning timestamps are available beyond the current state.</p></OperationalPanel>}</div></PromoterPage>;
}

export function PromoterWalletPage({ wallet }: { wallet: { availableBalance: unknown; pendingBalance: unknown; lockedBalance: unknown; currency: string; status: string } | null }) {
  return <PromoterPage title="Wallet projection" description="A read-only promoter wallet projection. Internal ledger accounts and journal records are not shown.">{wallet ? <div className="space-y-6"><div className={styles.metricGrid} aria-label="Promoter wallet balances"><MetricTile label="Available" value={formatPromoterMoney(wallet.availableBalance, wallet.currency)} description="Current source-backed balance" /><MetricTile label="Pending" value={formatPromoterMoney(wallet.pendingBalance, wallet.currency)} description="Not available" /><MetricTile label="Locked" value={formatPromoterMoney(wallet.lockedBalance, wallet.currency)} description="Not available" /><MetricTile label="Wallet state" value={wallet.status.replaceAll("_", " ")} description="Current record state" /></div><OperationalPanel title="Withdrawal boundary"><p className={styles.notice}>A wallet balance does not by itself determine withdrawal eligibility. The canonical promoter withdrawal path remains production locked.</p><div className={`${styles.actions} mt-4`}><PromoterAction href="/promoter/withdrawals">View withdrawals</PromoterAction></div></OperationalPanel></div> : <ProtectedState kind="unavailable" title="Wallet not provisioned" description="No promoter wallet projection currently exists. This page does not create one." illustration={<SecureLedgerIllustration className="h-24 w-32" />} />}</PromoterPage>;
}

export function PromoterWithdrawalsPage({ withdrawals, wallet }: { withdrawals: readonly PromoterWithdrawalRecord[]; wallet: { availableBalance: unknown; pendingBalance: unknown; lockedBalance: unknown; currency: string; status: string } | null }) {
  return <PromoterPage title="Withdrawals" description="Canonical withdrawal history and current source-backed balance. New promoter withdrawal requests remain production locked."><div className="space-y-6"><OperationalPanel title="Withdrawal availability" description="No withdrawal request form is rendered while the canonical promoter production lock is active."><dl className={styles.facts}><div><dt>Current available balance</dt><dd>{wallet ? formatPromoterMoney(wallet.availableBalance, wallet.currency) : "Not provisioned"}</dd></div><div><dt>Withdrawal action</dt><dd>Unavailable</dd></div></dl><p className={`${styles.notice} mt-4`}>This page does not infer eligibility, payout timing, minimums, or payout completion.</p></OperationalPanel><OperationalPanel title="Withdrawal history">{withdrawals.length ? <><div className={styles.desktopOnly}><EditorialTable caption="Promoter withdrawal requests" mobileMode="stack" rows={withdrawals} columns={[{ id: "reference", header: "Reference", cell: (row) => <span className={styles.reference}>{row.publicReference}</span> }, { id: "amount", header: "Amount", align: "end", cell: (row) => formatPromoterMoney(row.amount, row.currency) }, { id: "state", header: "State", cell: (row) => { const state = getPromoterWithdrawalPresentation(row.status); return <ProtectedStatus label={state.label} tone={state.tone} />; } }, { id: "destination", header: "Destination", cell: (row) => row.destination ?? "Destination unavailable" }, { id: "requested", header: "Requested", cell: (row) => formatPromoterDate(row.createdAt) }]} /></div><ul aria-label="Promoter withdrawal requests" className={`${styles.recordList} ${styles.mobileOnly}`}>{withdrawals.map((row) => { const state = getPromoterWithdrawalPresentation(row.status); return <li key={row.id} className={styles.record}><div className={styles.recordHead}><div><p className={styles.reference}>{row.publicReference}</p><p className={styles.recordMeta}>{formatPromoterMoney(row.amount, row.currency)} · {formatPromoterDate(row.createdAt)}</p></div><ProtectedStatus label={state.label} tone={state.tone} /></div><p className={styles.recordCopy}>{state.description}</p><p className={styles.recordMeta}>{row.destination ?? "Destination unavailable"}</p></li>; })}</ul></> : <ProtectedState kind="empty" title="No withdrawal requests" description="A request appears only after the canonical withdrawal authority accepts it." illustration={<SecureLedgerIllustration className="h-24 w-32" />} />}</OperationalPanel></div></PromoterPage>;
}

export function PromoterReferralToolsPage({ codes }: { codes: readonly { id: string; publicReference: string; maskedDisplay: string; status: string; startsAt: Date | null; expiresAt: Date | null; createdAt: Date; channelName: string | null }[] }) {
  return <PromoterPage title="Referral tools" description="Owned referral-code records. The current authority provides masked code values only and no server-confirmed share URL."><OperationalPanel title="Referral codes" description="The creation and archival endpoints remain protected by the current production lock, so no unavailable mutation controls are shown.">{codes.length ? <><div className={styles.desktopOnly}><EditorialTable caption="Owned referral codes" mobileMode="stack" rows={codes} columns={[{ id: "code", header: "Code", cell: (code) => <span className={styles.reference}>{code.maskedDisplay}</span> }, { id: "channel", header: "Channel", cell: (code) => code.channelName ?? "No channel" }, { id: "state", header: "State", cell: (code) => <ProtectedStatus label={code.status.replaceAll("_", " ")} tone={code.status === "ACTIVE" ? "success" : "neutral"} /> }, { id: "created", header: "Created", cell: (code) => formatPromoterDate(code.createdAt) }, { id: "expires", header: "Expiry", cell: (code) => formatPromoterDate(code.expiresAt) }]} /></div><ul aria-label="Owned referral codes" className={`${styles.recordList} ${styles.mobileOnly}`}>{codes.map((code) => <li key={code.id} className={styles.record}><div className={styles.recordHead}><div><p className={styles.reference}>{code.maskedDisplay}</p><p className={styles.recordMeta}>{code.channelName ?? "No channel"}</p></div><ProtectedStatus label={code.status.replaceAll("_", " ")} tone={code.status === "ACTIVE" ? "success" : "neutral"} /></div><p className={styles.recordCopy}>Created {formatPromoterDate(code.createdAt)}{code.expiresAt ? ` · Expires ${formatPromoterDate(code.expiresAt)}` : ""}</p></li>)}</ul></> : <ProtectedState kind="empty" title="No referral codes" description="A code appears here only after the canonical referral-code authority creates an owned record." illustration={<RouteQueueIllustration className="h-24 w-32" />} />}</OperationalPanel><OperationalPanel title="Share and link safety"><p className={styles.notice}>No full referral code, canonical shareable URL, or QR-code authority is exposed to this page. To avoid exposing a partial or unsafe value, copy, native share, and QR actions are not rendered.</p></OperationalPanel></PromoterPage>;
}

export function PromoterProgramPage({ programs, selected }: { programs: readonly { id: string; publicReference: string; name: string; targetType: string; status: string; enrollmentStatus: string | null; startsAt: Date; endsAt: Date | null }[]; selected?: { id: string; publicReference: string; name: string; targetType: string; status: string; enrollmentStatus: string | null; startsAt: Date; endsAt: Date | null } | null }) {
  if (selected) return <PromoterPage eyebrow="Programme" title={selected.name} description="Only promoter-safe programme facts are shown; commission terms and hidden programme controls are not exposed." actions={<PromoterAction href="/promoter/programs">Back to programmes</PromoterAction>}><OperationalPanel title="Programme record"><dl className={styles.facts}><div><dt>Programme reference</dt><dd>{selected.publicReference}</dd></div><div><dt>Target</dt><dd>{selected.targetType.replaceAll("_", " ")}</dd></div><div><dt>Programme state</dt><dd>{selected.status.replaceAll("_", " ")}</dd></div><div><dt>Your enrolment</dt><dd>{selected.enrollmentStatus?.replaceAll("_", " ") ?? "Not enrolled"}</dd></div><div><dt>Starts</dt><dd>{formatPromoterDate(selected.startsAt)}</dd></div>{selected.endsAt ? <div><dt>Ends</dt><dd>{formatPromoterDate(selected.endsAt)}</dd></div> : null}</dl><p className={`${styles.notice} mt-4`}>Programme enrolment is a canonical mutation and is not exposed while production validation is locked.</p></OperationalPanel></PromoterPage>;
  return <PromoterPage title="Programmes" description="Active promoter programmes available in the current canonical projection."><OperationalPanel title="Available programmes">{programs.length ? <ul className={styles.recordList} aria-label="Available promoter programmes">{programs.map((program) => <li className={styles.record} key={program.id}><div className={styles.recordHead}><div><Link className={styles.recordTitle} href={`/promoter/programs/${program.publicReference}`}>{program.name}</Link><p className={styles.recordMeta}>{program.targetType.replaceAll("_", " ")} · {formatPromoterDate(program.startsAt)}</p></div><ProtectedStatus label={program.enrollmentStatus ? `Enrolment: ${program.enrollmentStatus.replaceAll("_", " ")}` : "Not enrolled"} tone={program.enrollmentStatus === "ACTIVE" ? "success" : "neutral"} /></div><div className={styles.actions}><PromoterAction href={`/promoter/programs/${program.publicReference}`}>View programme</PromoterAction></div></li>)}</ul> : <ProtectedState kind="empty" title="No active programmes" description="No active programme is currently supplied by the canonical programme authority." />}</OperationalPanel></PromoterPage>;
}

export function PromoterProfilePage({ account, compliance = false }: { account: PromoterAccountProjection; compliance?: boolean }) {
  const lifecycle = getPromoterLifecyclePresentation(account.status);
  return <PromoterPage title={compliance ? "Compliance readiness" : "Promoter profile"} description={compliance ? "Promoter-safe readiness states. Internal evidence and reviewer information are not shown." : "The promoter profile projection contains only current programme-safe fields."}><OperationalPanel title={compliance ? "Readiness status" : "Profile status"}><dl className={styles.facts}>{!compliance ? <><div><dt>Display name</dt><dd>{account.displayName ?? "Not set"}</dd></div><div><dt>Programme reference</dt><dd>{account.publicReference}</dd></div></> : null}<div><dt>Programme state</dt><dd><ProtectedStatus label={lifecycle.label} tone={lifecycle.tone} /></dd></div><div><dt>Identity readiness</dt><dd>{account.identityStatus.replaceAll("_", " ")}</dd></div><div><dt>Tax profile readiness</dt><dd>{account.taxProfileStatus.replaceAll("_", " ")}</dd></div><div><dt>Payout readiness</dt><dd>{account.payoutReadinessStatus.replaceAll("_", " ")}</dd></div><div><dt>Agreement state</dt><dd>{account.agreementStatus.replaceAll("_", " ")}</dd></div></dl><p className={`${styles.notice} mt-4`}>Profile and compliance updates are canonical mutations and remain unavailable while production validation is locked. This surface does not display internal evidence, tax data, or payout details.</p></OperationalPanel></PromoterPage>;
}

export function PromoterAssetsPage({ assets }: { assets: readonly { id: string; publicReference: string; title: string; description: string | null; status: string; requiredDisclosure: string; approvedAt: Date | null }[] }) {
  return <PromoterPage title="Approved marketing assets" description="Approved asset records and required disclosure only. This route does not expose trusted storage references or create downloadable URLs."><OperationalPanel title="Available assets">{assets.length ? <ul className={styles.recordList} aria-label="Approved marketing assets">{assets.map((asset) => <li className={styles.record} key={asset.id}><div className={styles.recordHead}><div><h2 className={styles.recordTitle}>{asset.title}</h2><p className={styles.recordMeta}>{asset.approvedAt ? `Approved ${formatPromoterDate(asset.approvedAt)}` : "Approval date unavailable"}</p></div><ProtectedStatus label={asset.status.replaceAll("_", " ")} tone="success" /></div>{asset.description ? <p className={styles.recordCopy}>{asset.description}</p> : null}<p className={styles.recordCopy}><strong>Required disclosure:</strong> {asset.requiredDisclosure}</p></li>)}</ul> : <ProtectedState kind="empty" title="No approved assets" description="A marketing asset appears here only when the canonical asset authority makes it available." />}</OperationalPanel></PromoterPage>;
}

export function PromoterPerformancePage() {
  return <PromoterPage title="Performance reporting" description="Promoter performance reporting is not presented without a dedicated promoter-safe reporting projection."><ProtectedState kind="unavailable" title="Reporting is not available" description="This route intentionally does not show visits, impressions, click counts, conversion rates, growth, rankings, forecasts, or campaign metrics. Those values are not a promoter-safe reporting projection for this experience." illustration={<RouteQueueIllustration className="h-24 w-32" />} action={<PromoterAction href="/promoter/referrals">View attributed referrals</PromoterAction>} /></PromoterPage>;
}

export function PromoterDisputesPage({ disputes, selected }: { disputes: readonly { id: string; publicReference: string; category: string; status: string; safeResolution: string | null; createdAt: Date; updatedAt: Date }[]; selected?: { id: string; publicReference: string; category: string; status: string; safeResolution: string | null; createdAt: Date; updatedAt: Date } | null }) {
  if (selected) return <PromoterPage eyebrow="Referral dispute" title={selected.publicReference} description="A promoter-safe dispute record." actions={<PromoterAction href="/promoter/disputes">Back to disputes</PromoterAction>}><OperationalPanel title="Dispute state"><dl className={styles.facts}><div><dt>Category</dt><dd>{selected.category.replaceAll("_", " ")}</dd></div><div><dt>Status</dt><dd>{selected.status.replaceAll("_", " ")}</dd></div><div><dt>Created</dt><dd>{formatPromoterDate(selected.createdAt)}</dd></div><div><dt>Last updated</dt><dd>{formatPromoterDate(selected.updatedAt)}</dd></div></dl>{selected.safeResolution ? <p className={`${styles.notice} mt-4`}>{selected.safeResolution}</p> : <p className={`${styles.notice} mt-4`}>No promoter-safe resolution is available yet.</p>}</OperationalPanel></PromoterPage>;
  return <PromoterPage title="Disputes" description="Owned referral and earning dispute records. Creating or attaching evidence remains locked with the canonical mutation authority."><OperationalPanel title="Your dispute records">{disputes.length ? <ul className={styles.recordList} aria-label="Promoter disputes">{disputes.map((dispute) => <li className={styles.record} key={dispute.id}><div className={styles.recordHead}><div><Link className={styles.reference} href={`/promoter/disputes/${dispute.publicReference}`}>{dispute.publicReference}</Link><p className={styles.recordMeta}>{dispute.category.replaceAll("_", " ")} · {formatPromoterDate(dispute.createdAt)}</p></div><ProtectedStatus label={dispute.status.replaceAll("_", " ")} tone={dispute.status === "CLOSED" ? "success" : "information"} /></div><div className={styles.actions}><PromoterAction href={`/promoter/disputes/${dispute.publicReference}`}>View dispute</PromoterAction></div></li>)}</ul> : <ProtectedState kind="empty" title="No disputes" description="A dispute appears only after the canonical dispute authority accepts it." />}</OperationalPanel></PromoterPage>;
}

export function PromoterNotificationsPage({ notifications }: { notifications: readonly { id: string; title: string; body: string; state: string; createdAt: Date; actionRoute: string | null }[] }) {
  return <PromoterPage title="Notifications" description="Owned programme notifications. Delivery channel and preference claims are not inferred."><OperationalPanel title="Programme updates">{notifications.length ? <ul className={styles.recordList} aria-label="Promoter notifications">{notifications.map((notification) => <li className={styles.record} key={notification.id}><div className={styles.recordHead}><div><h2 className={styles.recordTitle}>{notification.title}</h2><p className={styles.recordMeta}>{formatPromoterDateTime(notification.createdAt)}</p></div><ProtectedStatus label={notification.state.replaceAll("_", " ")} tone={notification.state === "UNREAD" ? "information" : "neutral"} /></div><p className={styles.recordCopy}>{notification.body}</p>{notification.actionRoute?.startsWith("/promoter/") ? <div className={styles.actions}><PromoterAction href={notification.actionRoute}>Open related record</PromoterAction></div> : null}</li>)}</ul> : <ProtectedState kind="empty" title="No notifications" description="There are no current programme notifications in the owned inbox projection." />}</OperationalPanel></PromoterPage>;
}

export function PromoterSupportPage() {
  return <PromoterPage title="Support" description="The live promoter route tree has no separate promoter support-ticket projection or contact form."><ProtectedState kind="unavailable" title="Support requests are not available here" description="This route stays available, but it does not invent a contact channel or ticket record. Use the existing dispute route only for a referral or earning dispute that is supported by the canonical authority." action={<PromoterAction href="/promoter/disputes">View disputes</PromoterAction>} /></PromoterPage>;
}
