/* eslint-disable @typescript-eslint/no-explicit-any */
import type { NextRequest } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requireAdminApiPermission } from "@/lib/auth/admin-api";
import { PERMISSIONS } from "@/lib/auth/permission-keys";
import { newSubscriptionReference } from "@/lib/subscriptions/subscription-plan.service";
import { subscriptionApiError, subscriptionJson } from "@/lib/subscriptions/api-policy";

export async function GET(request: NextRequest) { const auth = await requireAdminApiPermission(PERMISSIONS.SUBSCRIPTION_PLANS_READ, { request }); if (auth.response) return auth.response; try { return subscriptionJson({ plans: await (prisma as any).subscriptionPlanVersion.findMany({ include: { program: { select: { publicReference: true, code: true } }, benefits: true }, orderBy: { createdAt: "desc" } }) }); } catch (error) { return subscriptionApiError(error); } }
export async function POST(request: NextRequest) { const auth = await requireAdminApiPermission(PERMISSIONS.SUBSCRIPTION_PLANS_CREATE, { request }); if (auth.response) return auth.response; try { const body = await request.json() as Record<string, any>; if (!body || typeof body.programId !== "string" || typeof body.displayName !== "string" || typeof body.priceAmount !== "string" || !Array.isArray(body.benefits)) return subscriptionJson({ error: "Invalid subscription plan draft." }, 422); const count = await (prisma as any).subscriptionPlanVersion.count({ where: { programId: body.programId } }); const plan = await (prisma as any).subscriptionPlanVersion.create({ data: { publicReference: newSubscriptionReference("subplan"), programId: body.programId, versionNumber: count + 1, status: "DRAFT", displayName: body.displayName.trim(), shortDescription: String(body.shortDescription ?? ""), fullDescription: String(body.fullDescription ?? ""), contractTermType: body.contractTermType ?? "ROLLING_MONTH_TO_MONTH", billingInterval: "MONTH", billingIntervalCount: 1, currency: "ZAR", priceAmount: body.priceAmount, taxTreatment: String(body.taxTreatment ?? "INCLUDED"), includedTaxAmount: body.includedTaxAmount ?? null, cancellationPolicyVersion: String(body.cancellationPolicyVersion ?? "subscription-cancellation-v1"), renewalPolicyVersion: String(body.renewalPolicyVersion ?? "subscription-renewal-v1"), dunningPolicyVersion: String(body.dunningPolicyVersion ?? "subscription-dunning-v1"), entitlementPolicyVersion: String(body.entitlementPolicyVersion ?? "subscription-entitlement-v1"), legalDocumentVersion: String(body.legalDocumentVersion ?? "subscription-terms-v1"), benefits: { create: body.benefits.map((benefit: any) => ({ publicReference: newSubscriptionReference("subbenefit"), benefitType: benefit.benefitType, subjectType: benefit.subjectType, valueType: benefit.valueType, amount: benefit.amount ?? null, quantity: benefit.quantity ?? null, period: String(benefit.period ?? "BILLING_CYCLE"), usageCap: benefit.usageCap ?? null, eligibilityConditions: benefit.eligibilityConditions ?? null, permittedConsumingPhase: benefit.permittedConsumingPhase, stackingPolicy: "NO_PROMOTION_STACKING", reversalPolicy: benefit.reversalPolicy ?? "RELEASE_UNCONSUMED", sourceVersion: String(benefit.sourceVersion ?? "v1") })) } } }); return subscriptionJson({ plan }, 201); } catch (error) { return subscriptionApiError(error); } }
