export type PaymentErrorCode =
  | "PAYMENT_NOT_FOUND"
  | "PAYMENT_ORDER_NOT_FOUND"
  | "PAYMENT_ORDER_NOT_PAYABLE"
  | "PAYMENT_ORDER_ALREADY_PAID"
  | "PAYMENT_PAYER_NOT_AUTHORIZED"
  | "PAYMENT_INVALID_AMOUNT"
  | "PAYMENT_CURRENCY_UNSUPPORTED"
  | "PAYMENT_IDEMPOTENCY_CONFLICT"
  | "PAYMENT_ATTEMPT_NOT_FOUND"
  | "PAYMENT_ATTEMPT_IDEMPOTENCY_CONFLICT"
  | "PAYMENT_ATTEMPT_ALREADY_FINAL"
  | "PAYMENT_STATE_TRANSITION_INVALID"
  | "PAYMENT_ATTEMPT_TRANSITION_INVALID"
  | "PAYMENT_PROVIDER_NOT_SUPPORTED"
  | "PAYMENT_PROVIDER_NOT_CONFIGURED"
  | "PAYMENT_PROVIDER_CAPABILITY_UNSUPPORTED"
  | "PAYMENT_PROVIDER_CONFIGURATION_INVALID"
  | "PAYMENT_PROVIDER_TIMEOUT"
  | "PAYMENT_PROVIDER_UNAVAILABLE"
  | "PAYMENT_PROVIDER_RESPONSE_INVALID"
  | "PAYMENT_PROVIDER_REDIRECT_INVALID"
  | "PAYMENT_PROVIDER_OUTCOME_UNKNOWN"
  | "PAYMENT_PROVIDER_REFERENCE_CONFLICT"
  | "PAYMENT_CONCURRENCY_CONFLICT"
  | "PAYMENT_METADATA_INVALID"
  | "PAYFAST_NOT_CONFIGURED"
  | "PAYFAST_CONFIGURATION_INVALID"
  | "PAYFAST_PRODUCTION_NOT_READY"
  | "PAYFAST_MERCHANT_REFERENCE_INVALID"
  | "PAYFAST_PAYER_EMAIL_REQUIRED"
  | "PAYFAST_FIELD_INVALID"
  | "PAYFAST_FIELD_TOO_LONG"
  | "PAYFAST_SIGNATURE_GENERATION_FAILED"
  | "PAYFAST_PROCESSING_ENDPOINT_INVALID"
  | "PAYFAST_CALLBACK_URL_INVALID"
  | "PAYFAST_CHECKOUT_NOT_AVAILABLE"
  | "PAYFAST_ATTEMPT_NOT_ACTIONABLE"
  | "PAYFAST_FORM_ACTION_INVALID"
  | "PAYFAST_ITN_TRANSPORT_INVALID"
  | "PAYFAST_ITN_BODY_TOO_LARGE"
  | "PAYFAST_ITN_BODY_TIMEOUT"
  | "PAYFAST_ITN_FORM_INVALID"
  | "PAYFAST_ITN_FIELDS_INVALID"
  | "PAYFAST_ITN_SIGNATURE_INVALID"
  | "PAYFAST_SOURCE_ADDRESS_INVALID"
  | "PAYFAST_SOURCE_ADDRESS_UNAVAILABLE"
  | "PAYFAST_SOURCE_DNS_UNAVAILABLE"
  | "PAYFAST_SOURCE_NOT_ALLOWED"
  | "PAYFAST_CREDENTIAL_VERSION_MISMATCH"
  | "PAYFAST_MERCHANT_MISMATCH"
  | "PAYFAST_AMOUNT_MISMATCH"
  | "PAYFAST_CONFIRMATION_INVALID"
  | "PAYFAST_CONFIRMATION_UNAVAILABLE"
  | "PAYFAST_EVENT_CONFLICT"
  | "PAYFAST_APPLICATION_UNAVAILABLE";

export class PaymentError extends Error {
  constructor(
    public readonly code: PaymentErrorCode,
    message: string,
    public readonly retryable = false,
    options?: { cause?: unknown },
  ) {
    super(message, options?.cause === undefined ? undefined : { cause: options.cause });
    this.name = "PaymentError";
  }
}

export function paymentError(code: PaymentErrorCode, message: string): PaymentError {
  return new PaymentError(code, message);
}
