import { describe, expect, it } from "vitest";
import { DEFAULT_ADMIN_PERMISSION_KEYS, PERMISSIONS } from "@/lib/auth/permission-keys";

describe("Phase 27 permissions", () => {
  it("keeps editing, approval, publication and delivery retry separate", () => {
    expect(PERMISSIONS.NOTIFICATION_TEMPLATE_MANAGE).not.toBe(PERMISSIONS.NOTIFICATION_TEMPLATE_APPROVE);
    expect(PERMISSIONS.NOTIFICATION_TEMPLATE_APPROVE).not.toBe(PERMISSIONS.NOTIFICATION_TEMPLATE_PUBLISH);
    expect(PERMISSIONS.NOTIFICATION_ROUTE_MANAGE).not.toBe(PERMISSIONS.NOTIFICATION_ROUTE_ACTIVATE);
    expect(PERMISSIONS.NOTIFICATION_DELIVERY_RETRY).not.toBe(PERMISSIONS.NOTIFICATION_SUPPRESSION_MANAGE);
  });

  it("does not grant destructive notification controls by default", () => {
    expect(DEFAULT_ADMIN_PERMISSION_KEYS).toContain(PERMISSIONS.NOTIFICATION_CATEGORY_READ);
    expect(DEFAULT_ADMIN_PERMISSION_KEYS).not.toContain(PERMISSIONS.NOTIFICATION_TEMPLATE_MANAGE);
    expect(DEFAULT_ADMIN_PERMISSION_KEYS).not.toContain(PERMISSIONS.NOTIFICATION_DELIVERY_RETRY);
    expect(DEFAULT_ADMIN_PERMISSION_KEYS).not.toContain(PERMISSIONS.NOTIFICATION_RESTRICTED_METADATA_READ);
  });
});
