/* eslint-disable @typescript-eslint/no-explicit-any -- Prisma client generation is intentionally deferred. */
import Link from "next/link";
import { prisma } from "@/lib/db/prisma";
import { resolveNotificationProductionComposition } from "@/lib/notifications/composition-root";

const labels: Record<string, string> = { category: "Category", template: "Template", route: "Route", delivery: "Delivery", suppression: "Suppression", provider: "Provider readiness", reconciliation: "Reconciliation" };
export async function AdminNotificationOperations() {
  const db: Record<string, any> = prisma as any;
  const [categories, templates, routes, deliveries, suppressions, reconciliation] = await Promise.all([db.notificationCategory.count(), db.notificationTemplate.count(), db.notificationEventRoute.count(), db.notificationDelivery.count(), db.notificationSuppression.count({ where: { active: true } }), db.notificationReconciliationCase.count({ where: { status: { in: ["OPEN", "IN_PROGRESS"] } } })]);
  const composition = resolveNotificationProductionComposition();
  const entries = [["Categories", categories, "/admin/notifications/categories"], ["Templates", templates, "/admin/notifications/templates"], ["Routes", routes, "/admin/notifications/routes"], ["Deliveries", deliveries, "/admin/notifications/deliveries"], ["Suppressions", suppressions, "/admin/notifications/suppressions"], ["Reconciliation required", reconciliation, "/admin/notifications/reconciliation"]] as const;
  return <section className="space-y-4" aria-label="Notification operations"><div><h1 className="font-display text-2xl font-black text-[var(--kt-navy)]">Notification operations</h1><p className="text-sm text-[var(--kt-text-muted)]">Canonical configuration, delivery and reconciliation surfaces.</p></div>{composition.status === "LOCKED" ? <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950">External delivery is locked; provider readiness only is available.</p> : null}<ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{entries.map(([label, count, href]) => <li key={href}><Link href={href} className="block rounded-xl border border-[var(--kt-soft-border)] bg-white p-4 hover:border-[var(--kt-signal-cobalt)]"><p className="text-sm text-[var(--kt-text-muted)]">{label}</p><p className="mt-1 text-2xl font-black text-[var(--kt-navy)]">{count}</p></Link></li>)}</ul></section>;
}
export async function AdminNotificationSurface({ kind, reference }: { kind: keyof typeof labels; reference?: string }) {
  const db: Record<string, any> = prisma as any;
  const models: Record<string, string> = { category: "notificationCategory", template: "notificationTemplate", route: "notificationEventRoute", delivery: "notificationDelivery", suppression: "notificationSuppression", provider: "notificationEndpoint", reconciliation: "notificationReconciliationCase" };
  const model = models[kind];
  if (!model) return null;
  const composition = resolveNotificationProductionComposition();
  const rows = reference ? [await db[model].findUnique({ where: { publicReference: reference } })].filter(Boolean) : await db[model].findMany({ orderBy: { createdAt: "desc" }, take: 50 });
  return <section className="space-y-5"><header><h1 className="font-display text-2xl font-black text-[var(--kt-navy)]">{labels[kind]}</h1><p className="text-sm text-[var(--kt-text-muted)]">Source-backed canonical notification authority.</p></header>{composition.status === "LOCKED" ? <p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950">Provider delivery is locked pending Phase 30 validation.</p> : null}<div className="rounded-xl border border-[var(--kt-soft-border)] bg-white divide-y divide-[var(--kt-soft-border)]">{rows.length === 0 ? <p className="p-4 text-sm text-[var(--kt-text-muted)]">No {labels[kind].toLowerCase()} records.</p> : rows.map((row: any) => { const state = row.status ?? (row.active === false ? "RETIRED" : "ACTIVE"); const ref = row.publicReference; return <article key={row.id} className="p-4 flex justify-between gap-3"><div><p className="font-semibold text-[var(--kt-navy)]">{row.key ?? ref}</p><p className="text-xs text-[var(--kt-text-muted)]">{ref}</p></div><span className="rounded-full bg-[var(--kt-cloud-blue)] px-2 py-1 h-fit text-xs font-bold text-[var(--kt-navy)]">{state}</span></article>; })}</div>{!reference && <p className="text-xs text-[var(--kt-text-muted)]"><Link className="underline" href="/admin/notifications/providers">View provider readiness</Link> · Pending, queued, retry scheduled, suppressed and reconciliation states are displayed from canonical records.</p>}</section>;
}
