import { UserRole } from "@/types/db";

export const PERMISSIONS = {
  ADMIN_DASHBOARD_READ: "admin.dashboard.read",

  USERS_READ: "users.read",
  USERS_UPDATE: "users.update",
  USERS_SUSPEND: "users.suspend",

  EMPLOYEES_READ: "employees.read",
  EMPLOYEES_CREATE: "employees.create",
  EMPLOYEES_UPDATE: "employees.update",
  EMPLOYEES_PERMISSIONS_MANAGE: "employees.permissions.manage",

  CUSTOMERS_READ: "customers.read",
  CUSTOMERS_UPDATE: "customers.update",

  STORES_READ: "stores.read",
  STORES_UPDATE: "stores.update",
  STORES_APPROVE: "stores.approve",
  STORES_FEATURE: "stores.feature",

  DRIVERS_READ: "drivers.read",
  DRIVERS_CREATE: "drivers.create",
  DRIVERS_UPDATE: "drivers.update",
  DRIVERS_STATUS_MANAGE: "drivers.status.manage",
  DRIVERS_REGIONS_MANAGE: "drivers.regions.manage",

  ORDERS_READ: "orders.read",
  ORDERS_UPDATE: "orders.update",
  ORDERS_STATUS_MANAGE: "orders.status.manage",
  ORDERS_CANCEL: "orders.cancel",

  DISPATCH_READ: "dispatch.read",
  DISPATCH_ASSIGN: "dispatch.assign",
  DISPATCH_REASSIGN: "dispatch.reassign",
  DISPATCH_UNASSIGN: "dispatch.unassign",
  DISPATCH_OVERRIDE: "dispatch.override",

  REGIONS_READ: "regions.read",
  REGIONS_MANAGE: "regions.manage",

  PRICING_READ: "pricing.read",
  PRICING_MANAGE: "pricing.manage",

  SETTINGS_READ: "settings.read",
  SETTINGS_UPDATE: "settings.update",

  ACTIVITY_READ: "activity.read",

  EMAILS_READ: "emails.read",
  EMAILS_TEST: "emails.test",

  CONTACTS_READ: "contacts.read",
  CONTACTS_UPDATE: "contacts.update",

  SECURITY_READ: "security.read",
  SECURITY_SESSIONS_MANAGE: "security.sessions.manage",

  FINANCE_READ: "finance.read",
  LEDGER_READ: "ledger.read",
  PAYMENTS_READ: "payments.read",
  PAYMENT_PROVIDERS_READ: "payment_providers.read",
  PAYMENT_WEBHOOKS_READ: "payment_webhooks.read",
  PAYMENT_RECONCILIATION_READ: "payment_reconciliation.read",
  FINANCE_DASHBOARD_READ: "finance_dashboard.read",
  WITHDRAWALS_READ: "withdrawals.read",
  WITHDRAWALS_REVIEW: "withdrawals.review",
  WITHDRAWALS_APPROVE: "withdrawals.approve",
  WITHDRAWALS_PROCESS: "withdrawals.process",
  WITHDRAWALS_RECONCILE: "withdrawals.reconcile",
  PAYOUT_DESTINATIONS_READ: "payout_destinations.read",
  PAYOUT_DESTINATIONS_MANAGE: "payout_destinations.manage",
  COMMISSION_PLANS_READ: "commission_plans.read",
  COMMISSION_PLANS_MANAGE: "commission_plans.manage",
  COMMISSION_PLANS_REVIEW: "commission_plans.review",
  COMMISSION_PLANS_APPROVE: "commission_plans.approve",
  COMMISSIONS_READ: "commissions.read",
  COMMISSIONS_REVERSE: "commissions.reverse",
  COMMISSION_RECONCILIATION_READ: "commission_reconciliation.read",
  FINANCE_COMMISSIONS_READ: "finance_commissions.read",
  CUSTOMER_WALLETS_READ: "customer_wallets.read",
  REFUNDS_READ: "refunds.read",
  REFUNDS_REVIEW: "refunds.review",
  REFUNDS_APPROVE: "refunds.approve",
  REFUNDS_PROCESS: "refunds.process",
  REFUNDS_RECONCILE: "refunds.reconcile",
  REFUND_PROVIDER_STATUS_READ: "refund_provider_status.read",
  FINANCE_REFUNDS_READ: "finance_refunds.read",
  STORE_EARNINGS_READ: "store_earnings.read",
  STORE_EARNINGS_REVERSE: "store_earnings.reverse",
  STORE_EARNINGS_RECONCILE: "store_earnings.reconcile",
  FINANCE_STORE_EARNINGS_READ: "finance_store_earnings.read",
  DRIVER_EARNINGS_READ: "driver_earnings.read",
  DRIVER_EARNINGS_REVERSE: "driver_earnings.reverse",
  DRIVER_EARNINGS_RECONCILE: "driver_earnings.reconcile",
  FINANCE_DRIVER_EARNINGS_READ: "finance_driver_earnings.read",

  CATALOG_READ: "catalog.read",
  CATALOG_MANAGE: "catalog.manage",
  CATALOG_SUBMIT: "catalog.submit",
  CATALOG_MODERATION_READ: "catalog_moderation.read",
  CATALOG_MODERATION_REVIEW: "catalog_moderation.review",
  CATALOG_MODERATION_APPROVE: "catalog_moderation.approve",
  CATALOG_MODERATION_SUSPEND: "catalog_moderation.suspend",
  CATALOG_TAXONOMY_READ: "catalog_taxonomy.read",
  CATALOG_TAXONOMY_MANAGE: "catalog_taxonomy.manage",
  CATALOG_PRODUCT_TYPES_READ: "catalog_product_types.read",
  CATALOG_PRODUCT_TYPES_MANAGE: "catalog_product_types.manage",
  CATALOG_PRODUCT_TYPES_APPROVE: "catalog_product_types.approve",
  CATALOG_PRICING_READ: "catalog_pricing.read",
  CATALOG_PRICING_MANAGE: "catalog_pricing.manage",
  CATALOG_INVENTORY_READ: "catalog_inventory.read",
  CATALOG_INVENTORY_MANAGE: "catalog_inventory.manage",
  CATALOG_IMPORTS_READ: "catalog_imports.read",
  CATALOG_IMPORTS_MANAGE: "catalog_imports.manage",

  STOREFRONT_PREVIEW_READ: "storefront_preview.read",
  STOREFRONT_COLLECTIONS_READ: "storefront_collections.read",
  STOREFRONT_COLLECTIONS_MANAGE: "storefront_collections.manage",
  STOREFRONT_SEARCH_SYNONYMS_READ: "storefront_search_synonyms.read",
  STOREFRONT_SEARCH_SYNONYMS_MANAGE: "storefront_search_synonyms.manage",
  STOREFRONT_PROJECTIONS_READ: "storefront_projections.read",
  STOREFRONT_PROJECTIONS_RECONCILE: "storefront_projections.reconcile",

  MARKETPLACE_CHECKOUT_READ: "marketplace_checkout.read",
  MARKETPLACE_CHECKOUT_RECONCILE: "marketplace_checkout.reconcile",
  MARKETPLACE_ORDERS_READ: "marketplace_orders.read",
  INVENTORY_RESERVATIONS_READ: "inventory_reservations.read",
  INVENTORY_RESERVATIONS_RECONCILE: "inventory_reservations.reconcile",
  MARKETPLACE_SETTLEMENT_READ: "marketplace_settlement.read",
  MARKETPLACE_SETTLEMENT_RECONCILE: "marketplace_settlement.reconcile",
  STORE_ORDERS_READ: "store_orders.read",
  STORE_ORDERS_REVIEW: "store_orders.review",
  STORE_ORDERS_ACCEPT: "store_orders.accept",
  STORE_ORDERS_REJECT: "store_orders.reject",
  STORE_ORDERS_AVAILABILITY: "store_orders.availability",
  STORE_ORDERS_SUBSTITUTIONS: "store_orders.substitutions",
  STORE_ORDERS_PREPARE: "store_orders.prepare",
  STORE_ORDERS_HANDOFF: "store_orders.handoff",
  STORE_ORDERS_RECONCILE: "store_orders.reconcile",
  STORE_ORDERS_RESCAN: "store_orders.rescan",
  STORE_ORDERS_RETRY_ADJUSTMENT: "store_orders.retry_adjustment",
  STORE_ORDERS_RETRY_REFUND: "store_orders.retry_refund",
  STORE_ORDERS_RETRY_DELIVERY: "store_orders.retry_delivery",
  STORE_ORDERS_RECONCILE_HANDOFF: "store_orders.reconcile_handoff",
  STORE_ORDER_POLICIES_MANAGE: "store_order_policies.manage",
  STORE_ORDER_POLICIES_APPROVE: "store_order_policies.approve",

  SUBSCRIPTIONS_READ: "subscriptions.read",
  SUBSCRIPTIONS_MANAGE_OWN: "subscriptions.manage_own",
  STORE_SUBSCRIPTIONS_READ: "store_subscriptions.read",
  STORE_SUBSCRIPTIONS_MANAGE: "store_subscriptions.manage",
  STORE_SUBSCRIPTIONS_BILLING: "store_subscriptions.billing",
  SUBSCRIPTION_PROGRAMS_READ: "subscription_programs.read",
  SUBSCRIPTION_PROGRAMS_MANAGE: "subscription_programs.manage",
  SUBSCRIPTION_PLANS_READ: "subscription_plans.read",
  SUBSCRIPTION_PLANS_CREATE: "subscription_plans.create",
  SUBSCRIPTION_PLANS_REVIEW: "subscription_plans.review",
  SUBSCRIPTION_PLANS_APPROVE: "subscription_plans.approve",
  SUBSCRIPTION_PLANS_ACTIVATE: "subscription_plans.activate",
  SUBSCRIPTION_PLANS_RETIRE: "subscription_plans.retire",
  SUBSCRIPTION_CONTRACTS_READ: "subscription_contracts.read",
  SUBSCRIPTION_CONTRACTS_RECONCILE: "subscription_contracts.reconcile",
  SUBSCRIPTION_BILLING_READ: "subscription_billing.read",
  SUBSCRIPTION_BILLING_RECONCILE: "subscription_billing.reconcile",
  SUBSCRIPTION_ENTITLEMENTS_READ: "subscription_entitlements.read",
  SUBSCRIPTION_ENTITLEMENTS_RECONCILE: "subscription_entitlements.reconcile",
  REPORTS_READ: "reports.read",
  REPORTS_EXPORT: "reports.export",

  // Phase 23: Promotions
  PROMOTIONS_READ: "promotions.read",
  PROMOTIONS_MANAGE: "promotions.manage",
  PROMOTIONS_SUBMIT: "promotions.submit",
  PROMOTIONS_REVIEW: "promotions.review",
  PROMOTIONS_APPROVE: "promotions.approve",
  PROMOTIONS_ACTIVATE: "promotions.activate",
  PROMOTIONS_PAUSE: "promotions.pause",
  PROMOTIONS_END: "promotions.end",
  PROMOTIONS_BUDGET_READ: "promotions.budget.read",
  PROMOTIONS_BUDGET_MANAGE: "promotions.budget.manage",
  PROMOTIONS_CODES_READ: "promotions.codes.read",
  PROMOTIONS_CODES_MANAGE: "promotions.codes.manage",
  PROMOTIONS_REDEMPTIONS_READ: "promotions.redemptions.read",
  PROMOTIONS_RECONCILIATION_READ: "promotions.reconciliation.read",
  PROMOTIONS_RECONCILIATION_MANAGE: "promotions.reconciliation.manage",
  STORE_PROMOTIONS_MANAGE: "store_promotions.manage",

  // Phase 24: Advertising
  ADVERTISING_READ: "advertising.read",
  ADVERTISING_MANAGE_OWN_STORE: "advertising.manage_own_store",
  ADVERTISING_SUBMIT_OWN_STORE: "advertising.submit_own_store",
  ADVERTISING_FUND_OWN_STORE: "advertising.fund_own_store",
  ADVERTISING_PAUSE_OWN_STORE: "advertising.pause_own_store",
  ADVERTISING_END_OWN_STORE: "advertising.end_own_store",
  ADVERTISING_CAMPAIGNS_READ: "advertising_campaigns.read",
  ADVERTISING_CAMPAIGNS_REVIEW: "advertising_campaigns.review",
  ADVERTISING_CAMPAIGNS_APPROVE: "advertising_campaigns.approve",
  ADVERTISING_CAMPAIGNS_ACTIVATE: "advertising_campaigns.activate",
  ADVERTISING_CAMPAIGNS_PAUSE: "advertising_campaigns.pause",
  ADVERTISING_CAMPAIGNS_SUSPEND: "advertising_campaigns.suspend",
  ADVERTISING_CAMPAIGNS_END: "advertising_campaigns.end",
  ADVERTISING_PLACEMENTS_READ: "advertising_placements.read",
  ADVERTISING_PLACEMENTS_MANAGE: "advertising_placements.manage",
  ADVERTISING_RATE_CARDS_READ: "advertising_rate_cards.read",
  ADVERTISING_RATE_CARDS_MANAGE: "advertising_rate_cards.manage",
  ADVERTISING_MEASUREMENT_READ: "advertising_measurement.read",
  ADVERTISING_INVALID_TRAFFIC_READ: "advertising_invalid_traffic.read",
  ADVERTISING_INVALID_TRAFFIC_REVIEW: "advertising_invalid_traffic.review",
  ADVERTISING_RECONCILIATION_READ: "advertising_reconciliation.read",
  ADVERTISING_RECONCILIATION_MANAGE: "advertising_reconciliation.manage",

  // Phase 25: separately enrolled commercial promoters only.
  PROMOTER_PROFILE_READ_OWN: "promoter_profile.read_own",
  PROMOTER_PROFILE_MANAGE_OWN: "promoter_profile.manage_own",
  PROMOTER_PROGRAMS_READ: "promoter_programs.read",
  PROMOTER_PROGRAMS_ENROLL: "promoter_programs.enroll",
  PROMOTER_CHANNELS_MANAGE_OWN: "promoter_channels.manage_own",
  PROMOTER_CODES_MANAGE_OWN: "promoter_codes.manage_own",
  PROMOTER_REFERRALS_READ_OWN: "promoter_referrals.read_own",
  PROMOTER_EARNINGS_READ_OWN: "promoter_earnings.read_own",
  PROMOTER_WALLET_READ_OWN: "promoter_wallet.read_own",
  PROMOTER_WITHDRAWALS_CREATE_OWN: "promoter_withdrawals.create_own",
  PROMOTER_PERFORMANCE_READ_OWN: "promoter_performance.read_own",
  PROMOTER_ASSETS_READ: "promoter_assets.read",
  PROMOTER_DISPUTES_MANAGE_OWN: "promoter_disputes.manage_own",
  PROMOTERS_READ: "promoters.read",
  PROMOTERS_REVIEW: "promoters.review",
  PROMOTERS_APPROVE: "promoters.approve",
  PROMOTERS_ACTIVATE: "promoters.activate",
  PROMOTERS_SUSPEND: "promoters.suspend",
  PROMOTERS_TERMINATE: "promoters.terminate",
  PROMOTER_PROGRAMS_MANAGE: "promoter_programs.manage",
  PROMOTER_PROGRAMS_REVIEW: "promoter_programs.review",
  PROMOTER_PROGRAMS_APPROVE: "promoter_programs.approve",
  PROMOTER_PROGRAMS_ACTIVATE: "promoter_programs.activate",
  PROMOTER_PROGRAMS_PAUSE: "promoter_programs.pause",
  PROMOTER_PROGRAMS_END: "promoter_programs.end",
  PROMOTER_ATTRIBUTIONS_READ: "promoter_attributions.read",
  PROMOTER_QUALIFICATIONS_READ: "promoter_qualifications.read",
  PROMOTER_EARNINGS_READ: "promoter_earnings.read",
  PROMOTER_FRAUD_READ: "promoter_fraud.read",
  PROMOTER_FRAUD_MANAGE: "promoter_fraud.manage",
  PROMOTER_RECONCILIATION_READ: "promoter_reconciliation.read",
  PROMOTER_RECONCILIATION_MANAGE: "promoter_reconciliation.manage",
  PROMOTER_DISPUTES_READ: "promoter_disputes.read",
  PROMOTER_DISPUTES_MANAGE: "promoter_disputes.manage",
  PROMOTER_ASSETS_MANAGE: "promoter_assets.manage",
  PROMOTER_AGREEMENTS_MANAGE: "promoter_agreements.manage",

  // Phase 26: Recruitment & Workforce Onboarding
  RECRUITMENT_OPENINGS_READ_PUBLIC: "recruitment_openings.read_public",
  APPLICANT_PROFILE_READ_OWN: "applicant_profile.read_own",
  APPLICANT_PROFILE_MANAGE_OWN: "applicant_profile.manage_own",
  APPLICANT_APPLICATIONS_CREATE_OWN: "applicant_applications.create_own",
  APPLICANT_APPLICATIONS_READ_OWN: "applicant_applications.read_own",
  APPLICANT_APPLICATIONS_MANAGE_DRAFT_OWN: "applicant_applications.manage_draft_own",
  APPLICANT_APPLICATIONS_SUBMIT_OWN: "applicant_applications.submit_own",
  APPLICANT_APPLICATIONS_WITHDRAW_OWN: "applicant_applications.withdraw_own",
  APPLICANT_DOCUMENTS_MANAGE_OWN: "applicant_documents.manage_own",
  APPLICANT_INTERVIEWS_READ_OWN: "applicant_interviews.read_own",
  APPLICANT_INTERVIEWS_SCHEDULE_OWN: "applicant_interviews.schedule_own",
  APPLICANT_CHECKS_READ_OWN: "applicant_checks.read_own",
  APPLICANT_CHECKS_CONSENT_OWN: "applicant_checks.consent_own",
  APPLICANT_OFFERS_READ_OWN: "applicant_offers.read_own",
  APPLICANT_OFFERS_RESPOND_OWN: "applicant_offers.respond_own",
  APPLICANT_PRIVACY_MANAGE_OWN: "applicant_privacy.manage_own",
  RECRUITMENT_READ: "recruitment.read",
  RECRUITMENT_REQUISITIONS_MANAGE: "recruitment_requisitions.manage",
  RECRUITMENT_REQUISITIONS_APPROVE: "recruitment_requisitions.approve",
  RECRUITMENT_OPENINGS_MANAGE: "recruitment_openings.manage",
  RECRUITMENT_OPENINGS_REVIEW: "recruitment_openings.review",
  RECRUITMENT_OPENINGS_PUBLISH: "recruitment_openings.publish",
  RECRUITMENT_APPLICATIONS_READ: "recruitment_applications.read",
  RECRUITMENT_APPLICATIONS_REVIEW: "recruitment_applications.review",
  RECRUITMENT_APPLICATIONS_ASSIGN: "recruitment_applications.assign",
  RECRUITMENT_DECISIONS_CREATE: "recruitment_decisions.create",
  RECRUITMENT_INTERVIEWS_MANAGE: "recruitment_interviews.manage",
  RECRUITMENT_SCORECARDS_SUBMIT: "recruitment_scorecards.submit",
  RECRUITMENT_CHECKS_READ: "recruitment_checks.read",
  RECRUITMENT_CHECKS_REQUEST: "recruitment_checks.request",
  RECRUITMENT_CHECKS_REVIEW: "recruitment_checks.review",
  RECRUITMENT_OFFERS_MANAGE: "recruitment_offers.manage",
  RECRUITMENT_OFFERS_APPROVE: "recruitment_offers.approve",
  RECRUITMENT_HANDOFFS_READ: "recruitment_handoffs.read",
  RECRUITMENT_HANDOFFS_PROCESS: "recruitment_handoffs.process",
  RECRUITMENT_FRAUD_READ: "recruitment_fraud.read",
  RECRUITMENT_FRAUD_MANAGE: "recruitment_fraud.manage",
  RECRUITMENT_RECONCILIATION_READ: "recruitment_reconciliation.read",
  RECRUITMENT_RECONCILIATION_MANAGE: "recruitment_reconciliation.manage",
  RECRUITMENT_PRIVACY_MANAGE: "recruitment_privacy.manage",
  RECRUITMENT_RETENTION_MANAGE: "recruitment_retention.manage",
  RECRUITMENT_EMPLOYMENT_EQUITY_READ: "recruitment_employment_equity.read",
  RECRUITMENT_EMPLOYMENT_EQUITY_MANAGE: "recruitment_employment_equity.manage",

  // Phase 27: Notification delivery authority
  NOTIFICATION_READ_OWN: "notification.read_own",
  NOTIFICATION_MANAGE_OWN_READ_STATE: "notification.manage_own_read_state",
  NOTIFICATION_MANAGE_OWN_PREFERENCES: "notification.manage_own_preferences",
  NOTIFICATION_MANAGE_OWN_PUSH_ENDPOINTS: "notification.manage_own_push_endpoints",
  NOTIFICATION_MANAGE_OWN_MARKETING_CONSENT: "notification.manage_own_marketing_consent",
  NOTIFICATION_CATEGORY_READ: "notification_category.read",
  NOTIFICATION_CATEGORY_MANAGE: "notification_category.manage",
  NOTIFICATION_TEMPLATE_READ: "notification_template.read",
  NOTIFICATION_TEMPLATE_MANAGE: "notification_template.manage",
  NOTIFICATION_TEMPLATE_APPROVE: "notification_template.approve",
  NOTIFICATION_TEMPLATE_PUBLISH: "notification_template.publish",
  NOTIFICATION_TEMPLATE_RETIRE: "notification_template.retire",
  NOTIFICATION_ROUTE_READ: "notification_route.read",
  NOTIFICATION_ROUTE_MANAGE: "notification_route.manage",
  NOTIFICATION_ROUTE_APPROVE: "notification_route.approve",
  NOTIFICATION_ROUTE_ACTIVATE: "notification_route.activate",
  NOTIFICATION_ROUTE_RETIRE: "notification_route.retire",
  NOTIFICATION_DELIVERY_READ: "notification_delivery.read",
  NOTIFICATION_DELIVERY_RETRY: "notification_delivery.retry",
  NOTIFICATION_DELIVERY_CANCEL: "notification_delivery.cancel",
  NOTIFICATION_SUPPRESSION_READ: "notification_suppression.read",
  NOTIFICATION_SUPPRESSION_MANAGE: "notification_suppression.manage",
  NOTIFICATION_PROVIDER_STATUS_READ: "notification_provider_status.read",
  NOTIFICATION_RECONCILIATION_READ: "notification_reconciliation.read",
  NOTIFICATION_RECONCILIATION_RETRY: "notification_reconciliation.retry",
  NOTIFICATION_AUDIT_READ: "notification_audit.read",
  NOTIFICATION_RESTRICTED_METADATA_READ: "notification_restricted_metadata.read",

  // Phase 28: public developer API — self-service remains owner-bound in route policy.
  DEVELOPER_APPLICATION_READ_OWN: "developer_application.read_own",
  DEVELOPER_APPLICATION_MANAGE_OWN: "developer_application.manage_own",
  DEVELOPER_APPLICATION_SUBMIT_OWN: "developer_application.submit_own",
  DEVELOPER_CREDENTIAL_READ_OWN: "developer_credential.read_own",
  DEVELOPER_CREDENTIAL_CREATE_OWN: "developer_credential.create_own",
  DEVELOPER_CREDENTIAL_ROTATE_OWN: "developer_credential.rotate_own",
  DEVELOPER_CREDENTIAL_REVOKE_OWN: "developer_credential.revoke_own",
  DEVELOPER_WEBHOOK_READ_OWN: "developer_webhook.read_own",
  DEVELOPER_WEBHOOK_MANAGE_OWN: "developer_webhook.manage_own",
  DEVELOPER_WEBHOOK_DELIVERY_READ_OWN: "developer_webhook_delivery.read_own",
  DEVELOPER_WEBHOOK_DELIVERY_RETRY_OWN: "developer_webhook_delivery.retry_own",
  DEVELOPER_API_USAGE_READ_OWN: "developer_api_usage.read_own",
  DEVELOPER_DOCUMENTATION_READ: "developer_documentation.read",
  DEVELOPER_APPLICATION_READ: "developer_application.read",
  DEVELOPER_APPLICATION_REVIEW: "developer_application.review",
  DEVELOPER_APPLICATION_APPROVE: "developer_application.approve",
  DEVELOPER_APPLICATION_REJECT: "developer_application.reject",
  DEVELOPER_APPLICATION_SUSPEND: "developer_application.suspend",
  DEVELOPER_APPLICATION_REVOKE: "developer_application.revoke",
  DEVELOPER_SCOPE_READ: "developer_scope.read",
  DEVELOPER_SCOPE_MANAGE: "developer_scope.manage",
  DEVELOPER_SCOPE_GRANT: "developer_scope.grant",
  DEVELOPER_CREDENTIAL_AUDIT_READ: "developer_credential_audit.read",
  DEVELOPER_CREDENTIAL_REVOKE: "developer_credential.revoke",
  DEVELOPER_API_REQUEST_AUDIT_READ: "developer_api_request_audit.read",
  DEVELOPER_API_USAGE_READ: "developer_api_usage.read",
  DEVELOPER_WEBHOOK_READ: "developer_webhook.read",
  DEVELOPER_WEBHOOK_OPERATE: "developer_webhook.operate",
  DEVELOPER_WEBHOOK_DISABLE: "developer_webhook.disable",
  DEVELOPER_WEBHOOK_DELIVERY_READ: "developer_webhook_delivery.read",
  DEVELOPER_WEBHOOK_DELIVERY_RETRY: "developer_webhook_delivery.retry",
  DEVELOPER_RECONCILIATION_READ: "developer_reconciliation.read",
  DEVELOPER_RECONCILIATION_RETRY: "developer_reconciliation.retry",
  DEVELOPER_RESTRICTED_METADATA_READ: "developer_restricted_metadata.read",
  REPORT_READ_OWN: "report.read_own",
  REPORT_GENERATE_OWN: "report.generate_own",
  REPORT_EXPORT_OWN: "report.export_own",
  REPORT_DOWNLOAD_OWN: "report.download_own",
  STORE_REPORT_READ: "store_report.read",
  STORE_REPORT_GENERATE: "store_report.generate",
  STORE_REPORT_EXPORT: "store_report.export",
  DRIVER_REPORT_READ_OWN: "driver_report.read_own",
  DRIVER_REPORT_EXPORT_OWN: "driver_report.export_own",
  PROMOTER_REPORT_READ_OWN: "promoter_report.read_own",
  PROMOTER_REPORT_EXPORT_OWN: "promoter_report.export_own",
  DEVELOPER_REPORT_READ_OWN: "developer_report.read_own",
  DEVELOPER_REPORT_EXPORT_OWN: "developer_report.export_own",
  REPORT_DEFINITION_READ: "report_definition.read",
  REPORT_DEFINITION_MANAGE: "report_definition.manage",
  REPORT_DEFINITION_PUBLISH: "report_definition.publish",
  REPORT_JOB_READ: "report_job.read",
  REPORT_JOB_CANCEL: "report_job.cancel",
  REPORT_JOB_RETRY: "report_job.retry",
  REPORT_ARTIFACT_READ: "report_artifact.read",
  REPORT_ARTIFACT_EXPIRE: "report_artifact.expire",
  REPORT_RESTRICTED_DATA_READ: "report_restricted_data.read",
  REPORT_RECONCILIATION_READ: "report_reconciliation.read",
  REPORT_RECONCILIATION_RETRY: "report_reconciliation.retry",

  SYSTEM_READINESS_READ: "system_readiness.read",
  INCIDENTS_READ: "incidents.read",
  INCIDENTS_MANAGE: "incidents.manage",
  PRIVACY_REQUESTS_READ: "privacy_requests.read",
  PRIVACY_REQUESTS_MANAGE: "privacy_requests.manage",
  LEGAL_DOCUMENTS_READ: "legal_documents.read",
  LEGAL_DOCUMENTS_MANAGE: "legal_documents.manage",
  LEGAL_DOCUMENTS_PUBLISH: "legal_documents.publish",
  PROCESSORS_READ: "processors.read",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export interface SystemPermissionDefinition {
  key: PermissionKey;
  name: string;
  category: string;
  description: string;
}

export const SYSTEM_PERMISSION_DEFINITIONS: SystemPermissionDefinition[] = [
  {
    key: PERMISSIONS.ADMIN_DASHBOARD_READ,
    name: "Read admin dashboard",
    category: "Command Centre",
    description: "View the admin command centre overview.",
  },
  {
    key: PERMISSIONS.USERS_READ,
    name: "Read users",
    category: "Users",
    description: "View user records in the admin command centre.",
  },
  {
    key: PERMISSIONS.USERS_UPDATE,
    name: "Update users",
    category: "Users",
    description: "Update safe user profile fields from the admin command centre.",
  },
  {
    key: PERMISSIONS.USERS_SUSPEND,
    name: "Suspend users",
    category: "Users",
    description: "Suspend, disable, or reactivate user accounts.",
  },
  {
    key: PERMISSIONS.EMPLOYEES_READ,
    name: "Read employees",
    category: "Employees",
    description: "View admin employee accounts and profiles.",
  },
  {
    key: PERMISSIONS.EMPLOYEES_CREATE,
    name: "Create employees",
    category: "Employees",
    description: "Create admin employee accounts.",
  },
  {
    key: PERMISSIONS.EMPLOYEES_UPDATE,
    name: "Update employees",
    category: "Employees",
    description: "Update admin employee profile fields.",
  },
  {
    key: PERMISSIONS.EMPLOYEES_PERMISSIONS_MANAGE,
    name: "Manage employee permissions",
    category: "Employees",
    description: "Manage explicit permission overrides for admin employees.",
  },
  {
    key: PERMISSIONS.CUSTOMERS_READ,
    name: "Read customers",
    category: "Customers",
    description: "View customer accounts and customer-facing records.",
  },
  {
    key: PERMISSIONS.CUSTOMERS_UPDATE,
    name: "Update customers",
    category: "Customers",
    description: "Update safe customer profile fields.",
  },
  {
    key: PERMISSIONS.STORES_READ,
    name: "Read stores",
    category: "Stores",
    description: "View store accounts and store records.",
  },
  {
    key: PERMISSIONS.STORES_UPDATE,
    name: "Update stores",
    category: "Stores",
    description: "Update store records.",
  },
  {
    key: PERMISSIONS.STORES_APPROVE,
    name: "Approve stores",
    category: "Stores",
    description: "Approve or change store account status.",
  },
  {
    key: PERMISSIONS.STORES_FEATURE,
    name: "Feature stores",
    category: "Stores",
    description: "Manage featured store placement.",
  },
  {
    key: PERMISSIONS.DRIVERS_READ,
    name: "Read drivers",
    category: "Drivers",
    description: "View driver profiles and operational driver data.",
  },
  {
    key: PERMISSIONS.DRIVERS_CREATE,
    name: "Create drivers",
    category: "Drivers",
    description: "Create or link driver profiles from the admin command centre.",
  },
  {
    key: PERMISSIONS.DRIVERS_UPDATE,
    name: "Update drivers",
    category: "Drivers",
    description: "Update driver profile and onboarding fields.",
  },
  {
    key: PERMISSIONS.DRIVERS_STATUS_MANAGE,
    name: "Manage driver status",
    category: "Drivers",
    description: "Change driver status and availability.",
  },
  {
    key: PERMISSIONS.DRIVERS_REGIONS_MANAGE,
    name: "Manage driver regions",
    category: "Drivers",
    description: "Assign delivery regions to drivers.",
  },
  {
    key: PERMISSIONS.ORDERS_READ,
    name: "Read orders",
    category: "Orders",
    description: "View delivery orders and operational order details.",
  },
  {
    key: PERMISSIONS.ORDERS_UPDATE,
    name: "Update orders",
    category: "Orders",
    description: "Update safe operational order fields and notes.",
  },
  {
    key: PERMISSIONS.ORDERS_STATUS_MANAGE,
    name: "Manage order status",
    category: "Orders",
    description: "Change operational order status.",
  },
  {
    key: PERMISSIONS.ORDERS_CANCEL,
    name: "Cancel orders",
    category: "Orders",
    description: "Cancel delivery orders from the admin command centre.",
  },
  {
    key: PERMISSIONS.DISPATCH_READ,
    name: "Read dispatch",
    category: "Dispatch",
    description: "View dispatch board, assignment, and exception data.",
  },
  {
    key: PERMISSIONS.DISPATCH_ASSIGN,
    name: "Assign dispatch",
    category: "Dispatch",
    description: "Assign drivers to orders.",
  },
  {
    key: PERMISSIONS.DISPATCH_REASSIGN,
    name: "Reassign dispatch",
    category: "Dispatch",
    description: "Replace a pre-custody driver assignment.",
  },
  {
    key: PERMISSIONS.DISPATCH_UNASSIGN,
    name: "Unassign dispatch",
    category: "Dispatch",
    description: "Revoke a pre-custody driver assignment.",
  },
  {
    key: PERMISSIONS.DISPATCH_OVERRIDE,
    name: "Override dispatch",
    category: "Dispatch",
    description: "Reassign or unassign drivers and perform dispatch overrides.",
  },
  {
    key: PERMISSIONS.REGIONS_READ,
    name: "Read regions",
    category: "Regions",
    description: "View delivery regions.",
  },
  {
    key: PERMISSIONS.REGIONS_MANAGE,
    name: "Manage regions",
    category: "Regions",
    description: "Create and update delivery regions.",
  },
  {
    key: PERMISSIONS.PRICING_READ,
    name: "Read pricing",
    category: "Pricing",
    description: "View pricing rules.",
  },
  {
    key: PERMISSIONS.PRICING_MANAGE,
    name: "Manage pricing",
    category: "Pricing",
    description: "Create, update, or disable pricing rules.",
  },
  {
    key: PERMISSIONS.SETTINGS_READ,
    name: "Read settings",
    category: "Settings",
    description: "View platform settings.",
  },
  {
    key: PERMISSIONS.SETTINGS_UPDATE,
    name: "Update settings",
    category: "Settings",
    description: "Update platform settings.",
  },
  {
    key: PERMISSIONS.ACTIVITY_READ,
    name: "Read activity",
    category: "Activity",
    description: "View admin activity logs.",
  },
  {
    key: PERMISSIONS.EMAILS_READ,
    name: "Read emails",
    category: "Emails",
    description: "View email logs.",
  },
  {
    key: PERMISSIONS.EMAILS_TEST,
    name: "Test emails",
    category: "Emails",
    description: "Send test emails from the admin command centre.",
  },
  {
    key: PERMISSIONS.CONTACTS_READ,
    name: "Read contacts",
    category: "Contacts",
    description: "View contact form messages.",
  },
  {
    key: PERMISSIONS.CONTACTS_UPDATE,
    name: "Update contacts",
    category: "Contacts",
    description: "Update contact message status.",
  },
  {
    key: PERMISSIONS.SECURITY_READ,
    name: "Read security events",
    category: "Security",
    description: "View security events and access-control audit records.",
  },
  {
    key: PERMISSIONS.SECURITY_SESSIONS_MANAGE,
    name: "Manage user sessions",
    category: "Security",
    description: "List and revoke user sessions with attributable security evidence.",
  },
  {
    key: PERMISSIONS.FINANCE_READ,
    name: "Read finance",
    category: "Finance",
    description: "Future permission placeholder for finance module access.",
  },
  {
    key: PERMISSIONS.LEDGER_READ,
    name: "Read ledger",
    category: "Finance",
    description: "Inspect immutable ledger accounts, journals, and entries.",
  },
  {
    key: PERMISSIONS.PAYMENTS_READ,
    name: "Read payments",
    category: "Finance",
    description: "Inspect provider-neutral payment and attempt lifecycle records.",
  },
  {
    key: PERMISSIONS.PAYMENT_PROVIDERS_READ,
    name: "Read payment providers",
    category: "Finance",
    description: "Inspect safe payment-provider readiness and capability metadata.",
  },
  {
    key: PERMISSIONS.PAYMENT_WEBHOOKS_READ,
    name: "Read payment webhooks",
    category: "Finance",
    description: "Inspect safe Payfast notification verification and application evidence.",
  },
  {
    key: PERMISSIONS.PAYMENT_RECONCILIATION_READ,
    name: "Read payment reconciliation",
    category: "Finance",
    description: "Inspect unresolved and resolved payment reconciliation cases without mutation authority.",
  },
  {
    key: PERMISSIONS.FINANCE_DASHBOARD_READ,
    name: "Read finance dashboard",
    category: "Finance",
    description: "View safe finance overview metrics and withdrawal liability monitoring.",
  },
  {
    key: PERMISSIONS.WITHDRAWALS_READ,
    name: "Read withdrawals",
    category: "Finance",
    description: "Inspect owner-safe withdrawal records and immutable financial evidence.",
  },
  {
    key: PERMISSIONS.WITHDRAWALS_REVIEW,
    name: "Review withdrawals",
    category: "Finance",
    description: "Start finance review and reject withdrawal requests with atomic release evidence.",
  },
  {
    key: PERMISSIONS.WITHDRAWALS_APPROVE,
    name: "Approve withdrawals",
    category: "Finance",
    description: "Approve eligible withdrawal requests without ledger movement.",
  },
  {
    key: PERMISSIONS.WITHDRAWALS_PROCESS,
    name: "Process withdrawals",
    category: "Finance",
    description: "Start, evidence, and complete manual external payout processing under dual control.",
  },
  {
    key: PERMISSIONS.WITHDRAWALS_RECONCILE,
    name: "Read withdrawal reconciliation",
    category: "Finance",
    description: "Inspect withdrawal reconciliation cases without a mark-paid bypass.",
  },
  {
    key: PERMISSIONS.PAYOUT_DESTINATIONS_READ,
    name: "Read payout destinations",
    category: "Finance",
    description: "Inspect masked owner payout destination references.",
  },
  {
    key: PERMISSIONS.PAYOUT_DESTINATIONS_MANAGE,
    name: "Manage payout destinations",
    category: "Finance",
    description: "Register and transition masked opaque payout destinations.",
  },
  {
    key: PERMISSIONS.COMMISSION_PLANS_READ,
    name: "Read commission plans",
    category: "Finance",
    description: "Inspect versioned commission policy drafts and immutable active versions.",
  },
  {
    key: PERMISSIONS.COMMISSION_PLANS_MANAGE,
    name: "Manage commission plan drafts",
    category: "Finance",
    description: "Create and update draft commission policy versions only.",
  },
  {
    key: PERMISSIONS.COMMISSION_PLANS_REVIEW,
    name: "Review commission plans",
    category: "Finance",
    description: "Submit and reject commission policy versions for review.",
  },
  {
    key: PERMISSIONS.COMMISSION_PLANS_APPROVE,
    name: "Approve commission plans",
    category: "Finance",
    description: "Independently approve commission policy versions before activation.",
  },
  {
    key: PERMISSIONS.COMMISSIONS_READ,
    name: "Read commissions",
    category: "Finance",
    description: "Inspect immutable commission accrual, allocation, and journal evidence.",
  },
  {
    key: PERMISSIONS.COMMISSIONS_REVERSE,
    name: "Reverse commissions",
    category: "Finance",
    description: "Initiate a canonical exact commission reversal when downstream release has not occurred.",
  },
  {
    key: PERMISSIONS.COMMISSION_RECONCILIATION_READ,
    name: "Read commission reconciliation",
    category: "Finance",
    description: "Inspect commission reconciliation cases without manual financial override authority.",
  },
  {
    key: PERMISSIONS.FINANCE_COMMISSIONS_READ,
    name: "Read finance commission metrics",
    category: "Finance",
    description: "View exact-string commission metrics in the finance overview.",
  },
  {
    key: PERMISSIONS.CUSTOMER_WALLETS_READ,
    name: "Read customer wallets",
    category: "Finance",
    description: "Inspect customer wallet liability balances and safe transaction evidence without adjustment authority.",
  },
  {
    key: PERMISSIONS.REFUNDS_READ,
    name: "Read refunds",
    category: "Finance",
    description: "Inspect refund aggregates, histories, methods and immutable accounting evidence.",
  },
  {
    key: PERMISSIONS.REFUNDS_REVIEW,
    name: "Review refunds",
    category: "Finance",
    description: "Begin finance review and reject eligible refund requests with exact reservation release.",
  },
  {
    key: PERMISSIONS.REFUNDS_APPROVE,
    name: "Approve refunds",
    category: "Finance",
    description: "Approve coherent refund reservations under mandatory requester separation.",
  },
  {
    key: PERMISSIONS.REFUNDS_PROCESS,
    name: "Process refunds",
    category: "Finance",
    description: "Complete approved wallet refunds or start provider refund orchestration under maker-checker controls.",
  },
  {
    key: PERMISSIONS.REFUNDS_RECONCILE,
    name: "Reconcile refunds",
    category: "Finance",
    description: "Query reviewed provider status and inspect refund reconciliation without a mark-success bypass.",
  },
  {
    key: PERMISSIONS.REFUND_PROVIDER_STATUS_READ,
    name: "Read refund provider status",
    category: "Finance",
    description: "Inspect safe normalized provider refund status without credentials or raw responses.",
  },
  {
    key: PERMISSIONS.FINANCE_REFUNDS_READ,
    name: "Read finance refund metrics",
    category: "Finance",
    description: "View exact refund and customer-wallet liability metrics in finance reporting.",
  },
  {
    key: PERMISSIONS.STORE_EARNINGS_READ,
    name: "Read store earnings evidence",
    category: "Finance",
    description: "Inspect immutable store earning, settlement, commission attribution and ledger evidence.",
  },
  {
    key: PERMISSIONS.STORE_EARNINGS_REVERSE,
    name: "Reverse store earnings",
    category: "Finance",
    description: "Initiate the canonical exact remaining store earning reversal when release and refund evidence permit it.",
  },
  {
    key: PERMISSIONS.STORE_EARNINGS_RECONCILE,
    name: "Reconcile store earnings",
    category: "Finance",
    description: "Inspect store earning reconciliation and run canonical resolution paths without balance overrides.",
  },
  {
    key: PERMISSIONS.FINANCE_STORE_EARNINGS_READ,
    name: "Read finance store earning metrics",
    category: "Finance",
    description: "View exact store earning liabilities, releases, refunds and reconciliation metrics.",
  },
  {
    key: PERMISSIONS.DRIVER_EARNINGS_READ,
    name: "Read driver earnings evidence",
    category: "Finance",
    description: "Inspect immutable driver earning, delivery settlement, commission attribution and ledger evidence.",
  },
  {
    key: PERMISSIONS.DRIVER_EARNINGS_REVERSE,
    name: "Reverse driver earnings",
    category: "Finance",
    description: "Initiate a reviewed exact remaining driver earning reversal with authoritative evidence.",
  },
  {
    key: PERMISSIONS.DRIVER_EARNINGS_RECONCILE,
    name: "Reconcile driver earnings",
    category: "Finance",
    description: "Inspect driver earning reconciliation without manual financial overrides.",
  },
  {
    key: PERMISSIONS.FINANCE_DRIVER_EARNINGS_READ,
    name: "Read finance driver earning metrics",
    category: "Finance",
    description: "View exact driver earning liabilities, releases, refunds and reconciliation metrics.",
  },
  {
    key: PERMISSIONS.CATALOG_READ,
    name: "Read store catalog",
    category: "Catalog",
    description: "View owned catalog products, offers, prices and readiness evidence.",
  },
  {
    key: PERMISSIONS.CATALOG_MANAGE,
    name: "Manage catalog drafts",
    category: "Catalog",
    description: "Create and update owned draft products, variants, offers and modifiers.",
  },
  {
    key: PERMISSIONS.CATALOG_SUBMIT,
    name: "Submit catalog records",
    category: "Catalog",
    description: "Submit owned draft products and offers for reviewed moderation.",
  },
  {
    key: PERMISSIONS.CATALOG_MODERATION_READ,
    name: "Read catalog moderation",
    category: "Catalog Administration",
    description: "View catalog moderation cases and immutable history.",
  },
  {
    key: PERMISSIONS.CATALOG_MODERATION_REVIEW,
    name: "Review catalog moderation",
    category: "Catalog Administration",
    description: "Review catalog cases and request bounded changes.",
  },
  {
    key: PERMISSIONS.CATALOG_MODERATION_APPROVE,
    name: "Approve catalog moderation",
    category: "Catalog Administration",
    description: "Record reviewed approval without bypassing hard validation or the production lock.",
  },
  {
    key: PERMISSIONS.CATALOG_MODERATION_SUSPEND,
    name: "Suspend catalog records",
    category: "Catalog Administration",
    description: "Safely suspend products or offers with immutable reason evidence.",
  },
  {
    key: PERMISSIONS.CATALOG_TAXONOMY_READ,
    name: "Read catalog taxonomy",
    category: "Catalog Administration",
    description: "View category hierarchy and product-type mappings.",
  },
  {
    key: PERMISSIONS.CATALOG_TAXONOMY_MANAGE,
    name: "Manage catalog taxonomy",
    category: "Catalog Administration",
    description: "Create and update non-destructive taxonomy records.",
  },
  {
    key: PERMISSIONS.CATALOG_PRODUCT_TYPES_READ,
    name: "Read product types",
    category: "Catalog Administration",
    description: "View versioned product-type schemas and lifecycle evidence.",
  },
  {
    key: PERMISSIONS.CATALOG_PRODUCT_TYPES_MANAGE,
    name: "Manage product-type drafts",
    category: "Catalog Administration",
    description: "Create and update draft product-type schema versions.",
  },
  {
    key: PERMISSIONS.CATALOG_PRODUCT_TYPES_APPROVE,
    name: "Approve product types",
    category: "Catalog Administration",
    description: "Approve reviewed product-type versions; activation remains source-locked.",
  },
  {
    key: PERMISSIONS.CATALOG_PRICING_READ,
    name: "Read catalog prices",
    category: "Catalog",
    description: "View exact ZAR VAT-inclusive offer price versions.",
  },
  {
    key: PERMISSIONS.CATALOG_PRICING_MANAGE,
    name: "Manage catalog price drafts",
    category: "Catalog",
    description: "Create owned immutable price versions without promotional fields.",
  },
  {
    key: PERMISSIONS.CATALOG_INVENTORY_READ,
    name: "Read catalog inventory",
    category: "Catalog",
    description: "View owned location inventory projections and movement evidence.",
  },
  {
    key: PERMISSIONS.CATALOG_INVENTORY_MANAGE,
    name: "Manage catalog inventory",
    category: "Catalog",
    description: "Post idempotent owned inventory movements; direct stock overwrite is prohibited.",
  },
  {
    key: PERMISSIONS.CATALOG_IMPORTS_READ,
    name: "Read catalog imports",
    category: "Catalog",
    description: "View owned catalog import jobs and row-level validation results.",
  },
  {
    key: PERMISSIONS.CATALOG_IMPORTS_MANAGE,
    name: "Manage catalog imports",
    category: "Catalog",
    description: "Create bounded CSV dry-runs and idempotently apply draft-only imports.",
  },
  {
    key: PERMISSIONS.STOREFRONT_PREVIEW_READ,
    name: "Preview storefront evidence",
    category: "Storefront",
    description: "Preview source-locked storefront evidence privately without public cache or indexing.",
  },
  {
    key: PERMISSIONS.STOREFRONT_COLLECTIONS_READ,
    name: "Read storefront collections",
    category: "Storefront",
    description: "Inspect editorial storefront collection lifecycle and safe item references.",
  },
  {
    key: PERMISSIONS.STOREFRONT_COLLECTIONS_MANAGE,
    name: "Manage storefront collections",
    category: "Storefront",
    description: "Create and manage reviewed editorial storefront collection drafts only.",
  },
  {
    key: PERMISSIONS.STOREFRONT_SEARCH_SYNONYMS_READ,
    name: "Read storefront search synonyms",
    category: "Storefront",
    description: "Inspect reviewed storefront search synonym versions.",
  },
  {
    key: PERMISSIONS.STOREFRONT_SEARCH_SYNONYMS_MANAGE,
    name: "Manage storefront search synonyms",
    category: "Storefront",
    description: "Create and review deterministic storefront synonym drafts; active versions remain immutable.",
  },
  {
    key: PERMISSIONS.STOREFRONT_PROJECTIONS_READ,
    name: "Read storefront projections",
    category: "Storefront",
    description: "Inspect source-locked storefront projection and cache evidence.",
  },
  {
    key: PERMISSIONS.STOREFRONT_PROJECTIONS_RECONCILE,
    name: "Reconcile storefront projections",
    category: "Storefront",
    description: "Run safe storefront projection reconciliation without public-data override authority.",
  },
  {
    key: PERMISSIONS.MARKETPLACE_CHECKOUT_READ,
    name: "Read marketplace checkouts",
    category: "Marketplace checkout",
    description: "Inspect owner-safe checkout evidence without payment or commercial overrides.",
  },
  {
    key: PERMISSIONS.MARKETPLACE_CHECKOUT_RECONCILE,
    name: "Reconcile marketplace checkouts",
    category: "Marketplace checkout",
    description: "Run canonical checkout reconciliation without a mark-paid or mark-completed bypass.",
  },
  {
    key: PERMISSIONS.MARKETPLACE_ORDERS_READ,
    name: "Read marketplace orders",
    category: "Marketplace checkout",
    description: "Inspect immutable parent and store-order evidence.",
  },
  {
    key: PERMISSIONS.INVENTORY_RESERVATIONS_READ,
    name: "Read inventory reservations",
    category: "Marketplace checkout",
    description: "Inspect reservation evidence and expiry state without direct inventory mutation.",
  },
  {
    key: PERMISSIONS.INVENTORY_RESERVATIONS_RECONCILE,
    name: "Reconcile inventory reservations",
    category: "Marketplace checkout",
    description: "Run canonical reservation reconciliation; unknown payment holds are never released automatically.",
  },
  {
    key: PERMISSIONS.MARKETPLACE_SETTLEMENT_READ,
    name: "Read marketplace settlement",
    category: "Marketplace checkout",
    description: "Inspect frozen commission and store earning settlement evidence.",
  },
  {
    key: PERMISSIONS.MARKETPLACE_SETTLEMENT_RECONCILE,
    name: "Reconcile marketplace settlement",
    category: "Marketplace checkout",
    description: "Run canonical settlement reconciliation without financial balance overrides.",
  },
  { key: PERMISSIONS.STORE_ORDERS_READ, name: "Read store orders", category: "Store orders", description: "View the owned store operational queue and safe fulfilment evidence." },
  { key: PERMISSIONS.STORE_ORDERS_REVIEW, name: "Review store orders", category: "Store orders", description: "Begin bounded review of an owned marketplace store order." },
  { key: PERMISSIONS.STORE_ORDERS_ACCEPT, name: "Accept store orders", category: "Store orders", description: "Accept an available owned store order through the canonical workflow." },
  { key: PERMISSIONS.STORE_ORDERS_REJECT, name: "Reject store orders", category: "Store orders", description: "Reject an unaccepted owned store order with a structured reason." },
  { key: PERMISSIONS.STORE_ORDERS_AVAILABILITY, name: "Resolve availability", category: "Store orders", description: "Confirm line availability and report immutable store-order issues." },
  { key: PERMISSIONS.STORE_ORDERS_SUBSTITUTIONS, name: "Propose substitutions", category: "Store orders", description: "Propose same-store customer-authorised substitutions only." },
  { key: PERMISSIONS.STORE_ORDERS_PREPARE, name: "Prepare store orders", category: "Store orders", description: "Start preparation, update a bounded estimate, and mark orders ready." },
  { key: PERMISSIONS.STORE_ORDERS_HANDOFF, name: "Verify store handoff", category: "Store orders", description: "Complete verified pickup handoff without delivery-completion authority." },
  { key: PERMISSIONS.STORE_ORDERS_RECONCILE, name: "Read store-order reconciliation", category: "Store orders", description: "Inspect store-order reconciliation and retry canonical operations only." },
  { key: PERMISSIONS.STORE_ORDERS_RESCAN, name: "Rescan store orders", category: "Store orders", description: "Run guarded coherence scans without overriding financial or delivery state." },
  { key: PERMISSIONS.STORE_ORDERS_RETRY_ADJUSTMENT, name: "Retry store-order adjustments", category: "Store orders", description: "Retry the canonical Phase 14/16/15 adjustment composition only." },
  { key: PERMISSIONS.STORE_ORDERS_RETRY_REFUND, name: "Retry store-order refunds", category: "Store orders", description: "Retry canonical Phase 15 refund handling only." },
  { key: PERMISSIONS.STORE_ORDERS_RETRY_DELIVERY, name: "Retry delivery bridge", category: "Store orders", description: "Retry existing courier-order bridge creation only." },
  { key: PERMISSIONS.STORE_ORDERS_RECONCILE_HANDOFF, name: "Reconcile store handoff", category: "Store orders", description: "Reconcile Phase 8 assignment and custody evidence without delivery completion authority." },
  { key: PERMISSIONS.STORE_ORDER_POLICIES_MANAGE, name: "Manage store-order policies", category: "Store orders", description: "Create and submit bounded operational-policy drafts." },
  { key: PERMISSIONS.STORE_ORDER_POLICIES_APPROVE, name: "Approve store-order policies", category: "Store orders", description: "Approve and activate immutable operational-policy versions." },
  { key: PERMISSIONS.SUBSCRIPTIONS_READ, name: "Read own memberships", category: "Subscriptions", description: "View the caller's safe customer membership evidence." },
  { key: PERMISSIONS.SUBSCRIPTIONS_MANAGE_OWN, name: "Manage own memberships", category: "Subscriptions", description: "Review, acknowledge, pay for and cancel the caller's memberships." },
  { key: PERMISSIONS.STORE_SUBSCRIPTIONS_READ, name: "Read store memberships", category: "Subscriptions", description: "View safe subscription evidence for an owned store." },
  { key: PERMISSIONS.STORE_SUBSCRIPTIONS_MANAGE, name: "Manage store memberships", category: "Subscriptions", description: "Manage an owned store membership without provider-token access." },
  { key: PERMISSIONS.STORE_SUBSCRIPTIONS_BILLING, name: "Bill store memberships", category: "Subscriptions", description: "Act as an authorised store billing payer; explicit deny overrides this grant." },
  { key: PERMISSIONS.SUBSCRIPTION_PROGRAMS_READ, name: "Read subscription programs", category: "Subscriptions", description: "Inspect subscription program grouping records." },
  { key: PERMISSIONS.SUBSCRIPTION_PROGRAMS_MANAGE, name: "Manage subscription programs", category: "Subscriptions", description: "Create and retire subscription program grouping records." },
  { key: PERMISSIONS.SUBSCRIPTION_PLANS_READ, name: "Read subscription plans", category: "Subscriptions", description: "Inspect plan-version evidence." },
  { key: PERMISSIONS.SUBSCRIPTION_PLANS_CREATE, name: "Create subscription plans", category: "Subscriptions", description: "Create draft subscription plan versions only." },
  { key: PERMISSIONS.SUBSCRIPTION_PLANS_REVIEW, name: "Review subscription plans", category: "Subscriptions", description: "Submit and review subscription plan versions." },
  { key: PERMISSIONS.SUBSCRIPTION_PLANS_APPROVE, name: "Approve subscription plans", category: "Subscriptions", description: "Approve versioned subscription plan terms." },
  { key: PERMISSIONS.SUBSCRIPTION_PLANS_ACTIVATE, name: "Activate subscription plans", category: "Subscriptions", description: "Activate approved plans only through the source-locked lifecycle." },
  { key: PERMISSIONS.SUBSCRIPTION_PLANS_RETIRE, name: "Retire subscription plans", category: "Subscriptions", description: "Retire active plan versions without altering contracts." },
  { key: PERMISSIONS.SUBSCRIPTION_CONTRACTS_READ, name: "Read subscription contracts", category: "Subscriptions", description: "Inspect safe contract evidence without manual financial override." },
  { key: PERMISSIONS.SUBSCRIPTION_CONTRACTS_RECONCILE, name: "Reconcile subscription contracts", category: "Subscriptions", description: "Run canonical contract recovery and provider-sync checks." },
  { key: PERMISSIONS.SUBSCRIPTION_BILLING_READ, name: "Read subscription billing", category: "Subscriptions", description: "Inspect invoices, cycles and payment references safely." },
  { key: PERMISSIONS.SUBSCRIPTION_BILLING_RECONCILE, name: "Reconcile subscription billing", category: "Subscriptions", description: "Open or rescan billing coherence cases without mark-paid authority." },
  { key: PERMISSIONS.SUBSCRIPTION_ENTITLEMENTS_READ, name: "Read subscription entitlements", category: "Subscriptions", description: "Inspect safe entitlement balances and usage evidence." },
  { key: PERMISSIONS.SUBSCRIPTION_ENTITLEMENTS_RECONCILE, name: "Reconcile subscription entitlements", category: "Subscriptions", description: "Run canonical entitlement reconciliation without manual grant authority." },
  {
    key: PERMISSIONS.REPORTS_READ,
    name: "Read reports",
    category: "Reports",
    description: "Future permission placeholder for report viewing.",
  },
  {
    key: PERMISSIONS.REPORTS_EXPORT,
    name: "Export reports",
    category: "Reports",
    description: "Future permission placeholder for report exports.",
  },
  { key: PERMISSIONS.PROMOTIONS_READ, name: "Read promotions", category: "Promotions", description: "Inspect promotion campaigns, versions, and safe lifecycle evidence." },
  { key: PERMISSIONS.PROMOTIONS_MANAGE, name: "Manage promotion drafts", category: "Promotions", description: "Create and update draft promotion campaigns and versions." },
  { key: PERMISSIONS.PROMOTIONS_SUBMIT, name: "Submit promotions", category: "Promotions", description: "Submit draft promotion versions for review." },
  { key: PERMISSIONS.PROMOTIONS_REVIEW, name: "Review promotions", category: "Promotions", description: "Review submitted promotion versions." },
  { key: PERMISSIONS.PROMOTIONS_APPROVE, name: "Approve promotions", category: "Promotions", description: "Approve reviewed promotion versions without bypassing the production lock." },
  { key: PERMISSIONS.PROMOTIONS_ACTIVATE, name: "Activate promotions", category: "Promotions", description: "Activate approved promotions through the source-locked lifecycle." },
  { key: PERMISSIONS.PROMOTIONS_PAUSE, name: "Pause promotions", category: "Promotions", description: "Pause active promotions." },
  { key: PERMISSIONS.PROMOTIONS_END, name: "End promotions", category: "Promotions", description: "End active or paused promotions." },
  { key: PERMISSIONS.PROMOTIONS_BUDGET_READ, name: "Read promotion budgets", category: "Promotions", description: "Inspect promotion budget status and movement evidence." },
  { key: PERMISSIONS.PROMOTIONS_BUDGET_MANAGE, name: "Manage promotion budgets", category: "Promotions", description: "Increase or decrease approved promotion budgets." },
  { key: PERMISSIONS.PROMOTIONS_CODES_READ, name: "Read promotion codes", category: "Promotions", description: "Inspect masked promotion code evidence and batch status." },
  { key: PERMISSIONS.PROMOTIONS_CODES_MANAGE, name: "Manage promotion codes", category: "Promotions", description: "Generate promotion code batches." },
  { key: PERMISSIONS.PROMOTIONS_REDEMPTIONS_READ, name: "Read promotion redemptions", category: "Promotions", description: "Inspect safe promotion redemption and allocation evidence." },
  { key: PERMISSIONS.PROMOTIONS_RECONCILIATION_READ, name: "Read promotion reconciliation", category: "Promotions", description: "Inspect promotion reconciliation cases without manual override authority." },
  { key: PERMISSIONS.PROMOTIONS_RECONCILIATION_MANAGE, name: "Manage promotion reconciliation", category: "Promotions", description: "Run canonical promotion reconciliation paths only." },
  { key: PERMISSIONS.STORE_PROMOTIONS_MANAGE, name: "Manage store promotions", category: "Promotions", description: "Create, submit, pause and end owned store promotion campaigns." },
  { key: PERMISSIONS.ADVERTISING_READ, name: "Read advertising", category: "Advertising", description: "View advertising accounts, campaigns, and reports." },
  { key: PERMISSIONS.ADVERTISING_MANAGE_OWN_STORE, name: "Manage own store advertising", category: "Advertising", description: "Create and edit campaigns for own store." },
  { key: PERMISSIONS.ADVERTISING_SUBMIT_OWN_STORE, name: "Submit own store campaigns", category: "Advertising", description: "Submit own store campaigns for review." },
  { key: PERMISSIONS.ADVERTISING_FUND_OWN_STORE, name: "Fund own store campaigns", category: "Advertising", description: "Transfer funds from store wallet to campaign budget." },
  { key: PERMISSIONS.ADVERTISING_PAUSE_OWN_STORE, name: "Pause own store campaigns", category: "Advertising", description: "Pause active campaigns for own store." },
  { key: PERMISSIONS.ADVERTISING_END_OWN_STORE, name: "End own store campaigns", category: "Advertising", description: "End active campaigns for own store." },
  { key: PERMISSIONS.ADVERTISING_CAMPAIGNS_READ, name: "Read campaigns", category: "Advertising Administration", description: "View all advertising campaigns." },
  { key: PERMISSIONS.ADVERTISING_CAMPAIGNS_REVIEW, name: "Review campaigns", category: "Advertising Administration", description: "Review and moderate campaign submissions." },
  { key: PERMISSIONS.ADVERTISING_CAMPAIGNS_APPROVE, name: "Approve campaigns", category: "Advertising Administration", description: "Approve campaign drafts." },
  { key: PERMISSIONS.ADVERTISING_CAMPAIGNS_ACTIVATE, name: "Activate campaigns", category: "Advertising Administration", description: "Activate approved campaigns." },
  { key: PERMISSIONS.ADVERTISING_CAMPAIGNS_PAUSE, name: "Pause campaigns", category: "Advertising Administration", description: "Pause active campaigns." },
  { key: PERMISSIONS.ADVERTISING_CAMPAIGNS_SUSPEND, name: "Suspend campaigns", category: "Advertising Administration", description: "Suspend active campaigns." },
  { key: PERMISSIONS.ADVERTISING_CAMPAIGNS_END, name: "End campaigns", category: "Advertising Administration", description: "End active campaigns." },
  { key: PERMISSIONS.ADVERTISING_PLACEMENTS_READ, name: "Read placements", category: "Advertising Administration", description: "View placement definitions." },
  { key: PERMISSIONS.ADVERTISING_PLACEMENTS_MANAGE, name: "Manage placements", category: "Advertising Administration", description: "Create and edit placement definitions." },
  { key: PERMISSIONS.ADVERTISING_RATE_CARDS_READ, name: "Read rate cards", category: "Advertising Administration", description: "View rate card versions." },
  { key: PERMISSIONS.ADVERTISING_RATE_CARDS_MANAGE, name: "Manage rate cards", category: "Advertising Administration", description: "Create and edit rate card versions." },
  { key: PERMISSIONS.ADVERTISING_MEASUREMENT_READ, name: "Read measurement events", category: "Advertising Administration", description: "Inspect ad serving and click measurement events." },
  { key: PERMISSIONS.ADVERTISING_INVALID_TRAFFIC_READ, name: "Read invalid traffic reports", category: "Advertising Administration", description: "Inspect filtered invalid traffic events." },
  { key: PERMISSIONS.ADVERTISING_INVALID_TRAFFIC_REVIEW, name: "Review invalid traffic cases", category: "Advertising Administration", description: "Perform manual review of suspect traffic." },
  { key: PERMISSIONS.ADVERTISING_RECONCILIATION_READ, name: "Read reconciliation cases", category: "Advertising Administration", description: "View advertising reconciliation cases." },
  { key: PERMISSIONS.ADVERTISING_RECONCILIATION_MANAGE, name: "Manage reconciliation cases", category: "Advertising Administration", description: "Resolve advertising reconciliation cases." },
  { key: PERMISSIONS.PROMOTER_PROFILE_READ_OWN, name: "Read own promoter profile", category: "Promoters", description: "Read the authenticated promoter's safe profile." },
  { key: PERMISSIONS.PROMOTER_PROFILE_MANAGE_OWN, name: "Manage own promoter profile", category: "Promoters", description: "Manage the authenticated promoter's permitted profile fields." },
  { key: PERMISSIONS.PROMOTER_PROGRAMS_READ, name: "Read promoter programs", category: "Promoters", description: "Read available promoter programs." },
  { key: PERMISSIONS.PROMOTER_PROGRAMS_ENROLL, name: "Enrol in promoter programs", category: "Promoters", description: "Request own enrolment through the canonical lifecycle." },
  { key: PERMISSIONS.PROMOTER_CHANNELS_MANAGE_OWN, name: "Manage own promoter channels", category: "Promoters", description: "Manage owned approved referral channels." },
  { key: PERMISSIONS.PROMOTER_CODES_MANAGE_OWN, name: "Manage own referral codes", category: "Promoters", description: "Create and archive owned masked referral codes." },
  { key: PERMISSIONS.PROMOTER_REFERRALS_READ_OWN, name: "Read own referral activity", category: "Promoters", description: "Read privacy-safe owned referral activity." },
  { key: PERMISSIONS.PROMOTER_EARNINGS_READ_OWN, name: "Read own promoter earnings", category: "Promoters", description: "Read held, payable, withdrawn and reversed own earnings." },
  { key: PERMISSIONS.PROMOTER_WALLET_READ_OWN, name: "Read own promoter wallet", category: "Promoters", description: "Read a safe wallet projection without mutation authority." },
  { key: PERMISSIONS.PROMOTER_WITHDRAWALS_CREATE_OWN, name: "Request own promoter withdrawals", category: "Promoters", description: "Request withdrawals through the canonical withdrawal authority." },
  { key: PERMISSIONS.PROMOTER_PERFORMANCE_READ_OWN, name: "Read own promoter performance", category: "Promoters", description: "Read aggregate privacy-safe performance metrics." },
  { key: PERMISSIONS.PROMOTER_ASSETS_READ, name: "Read approved promoter assets", category: "Promoters", description: "Read approved trusted marketing assets." },
  { key: PERMISSIONS.PROMOTER_DISPUTES_MANAGE_OWN, name: "Manage own promoter disputes", category: "Promoters", description: "Create and add evidence to owned disputes." },
  { key: PERMISSIONS.PROMOTERS_READ, name: "Read promoters", category: "Promoter Administration", description: "Read promoter accounts and safe operational evidence." },
  { key: PERMISSIONS.PROMOTERS_REVIEW, name: "Review promoters", category: "Promoter Administration", description: "Review promoter applications and compliance evidence." },
  { key: PERMISSIONS.PROMOTERS_APPROVE, name: "Approve promoters", category: "Promoter Administration", description: "Approve promoters through the canonical lifecycle." },
  { key: PERMISSIONS.PROMOTERS_ACTIVATE, name: "Activate promoters", category: "Promoter Administration", description: "Activate eligible promoters through the canonical lifecycle." },
  { key: PERMISSIONS.PROMOTERS_SUSPEND, name: "Suspend promoters", category: "Promoter Administration", description: "Suspend promoters through the canonical lifecycle." },
  { key: PERMISSIONS.PROMOTERS_TERMINATE, name: "Terminate promoters", category: "Promoter Administration", description: "Terminate promoters through the canonical lifecycle." },
  { key: PERMISSIONS.PROMOTER_PROGRAMS_MANAGE, name: "Manage promoter program drafts", category: "Promoter Administration", description: "Manage promoter program drafts." },
  { key: PERMISSIONS.PROMOTER_PROGRAMS_REVIEW, name: "Review promoter programs", category: "Promoter Administration", description: "Review promoter program versions." },
  { key: PERMISSIONS.PROMOTER_PROGRAMS_APPROVE, name: "Approve promoter programs", category: "Promoter Administration", description: "Approve valid customer or store programs." },
  { key: PERMISSIONS.PROMOTER_PROGRAMS_ACTIVATE, name: "Activate promoter programs", category: "Promoter Administration", description: "Activate valid approved programs." },
  { key: PERMISSIONS.PROMOTER_PROGRAMS_PAUSE, name: "Pause promoter programs", category: "Promoter Administration", description: "Pause active promoter programs." },
  { key: PERMISSIONS.PROMOTER_PROGRAMS_END, name: "End promoter programs", category: "Promoter Administration", description: "End promoter programs." },
  { key: PERMISSIONS.PROMOTER_ATTRIBUTIONS_READ, name: "Read promoter attributions", category: "Promoter Administration", description: "Read canonical attribution evidence." },
  { key: PERMISSIONS.PROMOTER_QUALIFICATIONS_READ, name: "Read promoter qualifications", category: "Promoter Administration", description: "Read canonical qualification evidence." },
  { key: PERMISSIONS.PROMOTER_EARNINGS_READ, name: "Read promoter earnings", category: "Promoter Administration", description: "Read promoter earning evidence." },
  { key: PERMISSIONS.PROMOTER_FRAUD_READ, name: "Read promoter fraud", category: "Promoter Administration", description: "Read safe fraud-case evidence." },
  { key: PERMISSIONS.PROMOTER_FRAUD_MANAGE, name: "Manage promoter fraud", category: "Promoter Administration", description: "Review, clear, confirm and rescan fraud cases canonically." },
  { key: PERMISSIONS.PROMOTER_RECONCILIATION_READ, name: "Read promoter reconciliation", category: "Promoter Administration", description: "Read promoter reconciliation cases." },
  { key: PERMISSIONS.PROMOTER_RECONCILIATION_MANAGE, name: "Manage promoter reconciliation", category: "Promoter Administration", description: "Run only canonical reconciliation recovery actions." },
  { key: PERMISSIONS.PROMOTER_DISPUTES_READ, name: "Read promoter disputes", category: "Promoter Administration", description: "Read safe promoter disputes." },
  { key: PERMISSIONS.PROMOTER_DISPUTES_MANAGE, name: "Manage promoter disputes", category: "Promoter Administration", description: "Review, respond to and close promoter disputes." },
  { key: PERMISSIONS.PROMOTER_ASSETS_MANAGE, name: "Manage promoter assets", category: "Promoter Administration", description: "Approve and retire trusted promoter assets." },
  { key: PERMISSIONS.PROMOTER_AGREEMENTS_MANAGE, name: "Manage promoter agreements", category: "Promoter Administration", description: "Manage agreement versions without acceptance authority." },
  // Phase 26: Recruitment & Workforce Onboarding
  { key: PERMISSIONS.RECRUITMENT_OPENINGS_READ_PUBLIC, name: "Read public recruitment openings", category: "Recruitment", description: "Read public published openings." },
  { key: PERMISSIONS.APPLICANT_PROFILE_READ_OWN, name: "Read own applicant profile", category: "Recruitment", description: "Read the authenticated applicant's profile." },
  { key: PERMISSIONS.APPLICANT_PROFILE_MANAGE_OWN, name: "Manage own applicant profile", category: "Recruitment", description: "Manage the authenticated applicant's profile." },
  { key: PERMISSIONS.APPLICANT_APPLICATIONS_CREATE_OWN, name: "Create own applicant application", category: "Recruitment", description: "Start draft recruitment applications." },
  { key: PERMISSIONS.APPLICANT_APPLICATIONS_READ_OWN, name: "Read own applicant applications", category: "Recruitment", description: "Read owned recruitment applications." },
  { key: PERMISSIONS.APPLICANT_APPLICATIONS_MANAGE_DRAFT_OWN, name: "Manage own draft applications", category: "Recruitment", description: "Update draft applications." },
  { key: PERMISSIONS.APPLICANT_APPLICATIONS_SUBMIT_OWN, name: "Submit own application", category: "Recruitment", description: "Submit applications through canonical gates." },
  { key: PERMISSIONS.APPLICANT_APPLICATIONS_WITHDRAW_OWN, name: "Withdraw own application", category: "Recruitment", description: "Withdraw submitted applications." },
  { key: PERMISSIONS.APPLICANT_DOCUMENTS_MANAGE_OWN, name: "Manage own application documents", category: "Recruitment", description: "Upload and manage applicant documents." },
  { key: PERMISSIONS.APPLICANT_INTERVIEWS_READ_OWN, name: "Read own interviews", category: "Recruitment", description: "Read owned interview schedules." },
  { key: PERMISSIONS.APPLICANT_INTERVIEWS_SCHEDULE_OWN, name: "Schedule own interview slot", category: "Recruitment", description: "Select interview slots." },
  { key: PERMISSIONS.APPLICANT_CHECKS_READ_OWN, name: "Read own background check requests", category: "Recruitment", description: "Read owned check requests." },
  { key: PERMISSIONS.APPLICANT_CHECKS_CONSENT_OWN, name: "Consent to own background checks", category: "Recruitment", description: "Record consent for background checks." },
  { key: PERMISSIONS.APPLICANT_OFFERS_READ_OWN, name: "Read own recruitment offers", category: "Recruitment", description: "Read owned employment or driver offers." },
  { key: PERMISSIONS.APPLICANT_OFFERS_RESPOND_OWN, name: "Respond to own recruitment offer", category: "Recruitment", description: "Accept or decline recruitment offers." },
  { key: PERMISSIONS.APPLICANT_PRIVACY_MANAGE_OWN, name: "Manage own recruitment privacy", category: "Recruitment", description: "Manage data deletion/export requests." },
  { key: PERMISSIONS.RECRUITMENT_READ, name: "Read recruitment administration", category: "Recruitment Administration", description: "Read recruitment pipelines and applications." },
  { key: PERMISSIONS.RECRUITMENT_REQUISITIONS_MANAGE, name: "Manage recruitment requisitions", category: "Recruitment Administration", description: "Create and update requisitions." },
  { key: PERMISSIONS.RECRUITMENT_REQUISITIONS_APPROVE, name: "Approve recruitment requisitions", category: "Recruitment Administration", description: "Approve workforce requisitions." },
  { key: PERMISSIONS.RECRUITMENT_OPENINGS_MANAGE, name: "Manage recruitment openings", category: "Recruitment Administration", description: "Manage job openings." },
  { key: PERMISSIONS.RECRUITMENT_OPENINGS_REVIEW, name: "Review recruitment openings", category: "Recruitment Administration", description: "Review opening postings." },
  { key: PERMISSIONS.RECRUITMENT_OPENINGS_PUBLISH, name: "Publish recruitment openings", category: "Recruitment Administration", description: "Publish job openings." },
  { key: PERMISSIONS.RECRUITMENT_APPLICATIONS_READ, name: "Read recruitment applications", category: "Recruitment Administration", description: "Read candidate applications." },
  { key: PERMISSIONS.RECRUITMENT_APPLICATIONS_REVIEW, name: "Review recruitment applications", category: "Recruitment Administration", description: "Review candidate applications." },
  { key: PERMISSIONS.RECRUITMENT_APPLICATIONS_ASSIGN, name: "Assign recruitment applications", category: "Recruitment Administration", description: "Assign screeners or recruiters." },
  { key: PERMISSIONS.RECRUITMENT_DECISIONS_CREATE, name: "Record recruitment decisions", category: "Recruitment Administration", description: "Record candidate progression decisions." },
  { key: PERMISSIONS.RECRUITMENT_INTERVIEWS_MANAGE, name: "Manage recruitment interviews", category: "Recruitment Administration", description: "Schedule and manage interview slots." },
  { key: PERMISSIONS.RECRUITMENT_SCORECARDS_SUBMIT, name: "Submit interview scorecards", category: "Recruitment Administration", description: "Submit candidate scorecards." },
  { key: PERMISSIONS.RECRUITMENT_CHECKS_READ, name: "Read recruitment background checks", category: "Recruitment Administration", description: "Read background check statuses." },
  { key: PERMISSIONS.RECRUITMENT_CHECKS_REQUEST, name: "Request recruitment background checks", category: "Recruitment Administration", description: "Trigger background check requests." },
  { key: PERMISSIONS.RECRUITMENT_CHECKS_REVIEW, name: "Review recruitment background checks", category: "Recruitment Administration", description: "Review background check findings." },
  { key: PERMISSIONS.RECRUITMENT_OFFERS_MANAGE, name: "Manage recruitment offers", category: "Recruitment Administration", description: "Draft and update candidate offers." },
  { key: PERMISSIONS.RECRUITMENT_OFFERS_APPROVE, name: "Approve recruitment offers", category: "Recruitment Administration", description: "Approve candidate offers." },
  { key: PERMISSIONS.RECRUITMENT_HANDOFFS_READ, name: "Read recruitment handoffs", category: "Recruitment Administration", description: "Read onboarding handoff events." },
  { key: PERMISSIONS.RECRUITMENT_HANDOFFS_PROCESS, name: "Process recruitment handoffs", category: "Recruitment Administration", description: "Process candidate onboarding handoffs." },
  { key: PERMISSIONS.RECRUITMENT_FRAUD_READ, name: "Read recruitment fraud cases", category: "Recruitment Administration", description: "Read recruitment fraud flags." },
  { key: PERMISSIONS.RECRUITMENT_FRAUD_MANAGE, name: "Manage recruitment fraud cases", category: "Recruitment Administration", description: "Investigate and resolve recruitment fraud flags." },
  { key: PERMISSIONS.RECRUITMENT_RECONCILIATION_READ, name: "Read recruitment reconciliation", category: "Recruitment Administration", description: "Read recruitment state reconciliation cases." },
  { key: PERMISSIONS.RECRUITMENT_RECONCILIATION_MANAGE, name: "Manage recruitment reconciliation", category: "Recruitment Administration", description: "Resolve recruitment state reconciliation cases." },
  { key: PERMISSIONS.RECRUITMENT_PRIVACY_MANAGE, name: "Manage recruitment privacy compliance", category: "Recruitment Administration", description: "Handle recruitment privacy requests." },
  { key: PERMISSIONS.RECRUITMENT_RETENTION_MANAGE, name: "Manage recruitment retention policy", category: "Recruitment Administration", description: "Enforce recruitment document retention rules." },
  { key: PERMISSIONS.RECRUITMENT_EMPLOYMENT_EQUITY_READ, name: "Read employment equity reports", category: "Recruitment Administration", description: "Read anonymised employment equity metrics." },
  { key: PERMISSIONS.RECRUITMENT_EMPLOYMENT_EQUITY_MANAGE, name: "Manage employment equity compliance", category: "Recruitment Administration", description: "Manage employment equity reporting." },
  { key: PERMISSIONS.NOTIFICATION_READ_OWN, name: "Read own notifications", category: "Notifications", description: "Read the authenticated user's inbox." },
  { key: PERMISSIONS.NOTIFICATION_MANAGE_OWN_READ_STATE, name: "Manage own read state", category: "Notifications", description: "Read, unread and archive own notifications." },
  { key: PERMISSIONS.NOTIFICATION_MANAGE_OWN_PREFERENCES, name: "Manage own notification preferences", category: "Notifications", description: "Manage preference, quiet-hour and digest settings." },
  { key: PERMISSIONS.NOTIFICATION_MANAGE_OWN_PUSH_ENDPOINTS, name: "Manage own push endpoints", category: "Notifications", description: "Register and revoke owned push endpoints." },
  { key: PERMISSIONS.NOTIFICATION_MANAGE_OWN_MARKETING_CONSENT, name: "Manage own marketing consent", category: "Notifications", description: "Grant or revoke channel-specific marketing consent." },
  { key: PERMISSIONS.NOTIFICATION_CATEGORY_READ, name: "Read notification categories", category: "Notification Administration", description: "Read categories." },
  { key: PERMISSIONS.NOTIFICATION_CATEGORY_MANAGE, name: "Manage notification categories", category: "Notification Administration", description: "Manage categories." },
  { key: PERMISSIONS.NOTIFICATION_TEMPLATE_READ, name: "Read notification templates", category: "Notification Administration", description: "Read templates." },
  { key: PERMISSIONS.NOTIFICATION_TEMPLATE_MANAGE, name: "Manage notification templates", category: "Notification Administration", description: "Edit draft templates." },
  { key: PERMISSIONS.NOTIFICATION_TEMPLATE_APPROVE, name: "Approve notification templates", category: "Notification Administration", description: "Approve template versions." },
  { key: PERMISSIONS.NOTIFICATION_TEMPLATE_PUBLISH, name: "Publish notification templates", category: "Notification Administration", description: "Publish approved template versions." },
  { key: PERMISSIONS.NOTIFICATION_TEMPLATE_RETIRE, name: "Retire notification templates", category: "Notification Administration", description: "Retire template versions." },
  { key: PERMISSIONS.NOTIFICATION_ROUTE_READ, name: "Read notification routes", category: "Notification Administration", description: "Read event routes." },
  { key: PERMISSIONS.NOTIFICATION_ROUTE_MANAGE, name: "Manage notification routes", category: "Notification Administration", description: "Edit draft event routes." },
  { key: PERMISSIONS.NOTIFICATION_ROUTE_APPROVE, name: "Approve notification routes", category: "Notification Administration", description: "Approve route versions." },
  { key: PERMISSIONS.NOTIFICATION_ROUTE_ACTIVATE, name: "Activate notification routes", category: "Notification Administration", description: "Activate approved route versions." },
  { key: PERMISSIONS.NOTIFICATION_ROUTE_RETIRE, name: "Retire notification routes", category: "Notification Administration", description: "Retire route versions." },
  { key: PERMISSIONS.NOTIFICATION_DELIVERY_READ, name: "Read notification deliveries", category: "Notification Operations", description: "Read safe delivery metadata." },
  { key: PERMISSIONS.NOTIFICATION_DELIVERY_RETRY, name: "Retry notification delivery", category: "Notification Operations", description: "Retry eligible deliveries." },
  { key: PERMISSIONS.NOTIFICATION_DELIVERY_CANCEL, name: "Cancel notification delivery", category: "Notification Operations", description: "Cancel queued deliveries." },
  { key: PERMISSIONS.NOTIFICATION_SUPPRESSION_READ, name: "Read suppressions", category: "Notification Operations", description: "Read suppression evidence." },
  { key: PERMISSIONS.NOTIFICATION_SUPPRESSION_MANAGE, name: "Manage suppressions", category: "Notification Operations", description: "Review allowed suppression records." },
  { key: PERMISSIONS.NOTIFICATION_PROVIDER_STATUS_READ, name: "Read provider status", category: "Notification Operations", description: "Read configuration readiness only." },
  { key: PERMISSIONS.NOTIFICATION_RECONCILIATION_READ, name: "Read notification reconciliation", category: "Notification Operations", description: "Read reconciliation cases." },
  { key: PERMISSIONS.NOTIFICATION_RECONCILIATION_RETRY, name: "Retry notification reconciliation", category: "Notification Operations", description: "Execute narrow recovery actions." },
  { key: PERMISSIONS.NOTIFICATION_AUDIT_READ, name: "Read notification audit", category: "Notification Operations", description: "Read safe notification audit evidence." },
  { key: PERMISSIONS.NOTIFICATION_RESTRICTED_METADATA_READ, name: "Read restricted notification metadata", category: "Notification Operations", description: "Read restricted metadata under exact authority." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_READ_OWN, name: "Read own developer applications", category: "Developer API", description: "Read applications owned by the authenticated user." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_MANAGE_OWN, name: "Manage own developer applications", category: "Developer API", description: "Create and edit owned draft developer applications." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_SUBMIT_OWN, name: "Submit own developer applications", category: "Developer API", description: "Submit owned developer applications for review." },
  { key: PERMISSIONS.DEVELOPER_CREDENTIAL_READ_OWN, name: "Read own developer credentials", category: "Developer API", description: "Read masked credentials for owned applications." },
  { key: PERMISSIONS.DEVELOPER_CREDENTIAL_CREATE_OWN, name: "Create own developer credentials", category: "Developer API", description: "Issue credentials after approval and terms acceptance." },
  { key: PERMISSIONS.DEVELOPER_CREDENTIAL_ROTATE_OWN, name: "Rotate own developer credentials", category: "Developer API", description: "Rotate owned credentials with bounded overlap." },
  { key: PERMISSIONS.DEVELOPER_CREDENTIAL_REVOKE_OWN, name: "Revoke own developer credentials", category: "Developer API", description: "Revoke owned credentials." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_READ_OWN, name: "Read own developer webhooks", category: "Developer API", description: "Read owned webhook subscriptions." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, name: "Manage own developer webhooks", category: "Developer API", description: "Manage verified owned webhook subscriptions." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_READ_OWN, name: "Read own webhook deliveries", category: "Developer API", description: "Read safe delivery metadata for owned subscriptions." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_RETRY_OWN, name: "Retry own webhook deliveries", category: "Developer API", description: "Request eligible safe delivery retries." },
  { key: PERMISSIONS.DEVELOPER_API_USAGE_READ_OWN, name: "Read own developer API usage", category: "Developer API", description: "Read quota and request usage for owned applications." },
  { key: PERMISSIONS.DEVELOPER_DOCUMENTATION_READ, name: "Read developer documentation", category: "Developer API", description: "Read developer API documentation." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_READ, name: "Read developer applications", category: "Developer API Administration", description: "Read developer applications for review." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_REVIEW, name: "Review developer applications", category: "Developer API Administration", description: "Assign and review developer applications." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_APPROVE, name: "Approve developer applications", category: "Developer API Administration", description: "Approve developer applications." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_REJECT, name: "Reject developer applications", category: "Developer API Administration", description: "Reject developer applications." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_SUSPEND, name: "Suspend developer applications", category: "Developer API Administration", description: "Suspend developer applications." },
  { key: PERMISSIONS.DEVELOPER_APPLICATION_REVOKE, name: "Revoke developer applications", category: "Developer API Administration", description: "Revoke developer applications." },
  { key: PERMISSIONS.DEVELOPER_SCOPE_READ, name: "Read developer scopes", category: "Developer API Administration", description: "Read canonical developer scope definitions and grants." },
  { key: PERMISSIONS.DEVELOPER_SCOPE_MANAGE, name: "Manage developer scopes", category: "Developer API Administration", description: "Manage scope definitions only." },
  { key: PERMISSIONS.DEVELOPER_SCOPE_GRANT, name: "Grant developer scopes", category: "Developer API Administration", description: "Approve versioned scope grants." },
  { key: PERMISSIONS.DEVELOPER_CREDENTIAL_AUDIT_READ, name: "Audit developer credentials", category: "Developer API Administration", description: "Read safe credential audit metadata." },
  { key: PERMISSIONS.DEVELOPER_CREDENTIAL_REVOKE, name: "Revoke developer credentials", category: "Developer API Administration", description: "Revoke or mark compromised credentials." },
  { key: PERMISSIONS.DEVELOPER_API_REQUEST_AUDIT_READ, name: "Read developer request audit", category: "Developer API Administration", description: "Read privacy-safe public request audit records." },
  { key: PERMISSIONS.DEVELOPER_API_USAGE_READ, name: "Read developer API usage", category: "Developer API Administration", description: "Read developer quota and usage metadata." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_READ, name: "Read developer webhooks", category: "Developer API Administration", description: "Read developer webhook subscriptions." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_OPERATE, name: "Operate developer webhooks", category: "Developer API Administration", description: "Operate safe developer webhook workflows." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_DISABLE, name: "Disable developer webhooks", category: "Developer API Administration", description: "Disable unsafe developer webhook subscriptions." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_READ, name: "Read developer webhook deliveries", category: "Developer API Administration", description: "Read safe delivery history." },
  { key: PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_RETRY, name: "Retry developer webhook deliveries", category: "Developer API Administration", description: "Request safe delivery retries." },
  { key: PERMISSIONS.DEVELOPER_RECONCILIATION_READ, name: "Read developer reconciliation", category: "Developer API Administration", description: "Read developer API reconciliation cases." },
  { key: PERMISSIONS.DEVELOPER_RECONCILIATION_RETRY, name: "Retry developer reconciliation", category: "Developer API Administration", description: "Run narrow reconciliation actions." },
  { key: PERMISSIONS.DEVELOPER_RESTRICTED_METADATA_READ, name: "Read restricted developer metadata", category: "Developer API Administration", description: "Read restricted metadata under exact authority." },
  { key: PERMISSIONS.REPORT_READ_OWN, name: "Read own reports", category: "Reporting", description: "Read reports owned by the caller." },
  { key: PERMISSIONS.REPORT_GENERATE_OWN, name: "Generate own reports", category: "Reporting", description: "Request execution of self-service reports." },
  { key: PERMISSIONS.REPORT_EXPORT_OWN, name: "Export own reports", category: "Reporting", description: "Export self-service reports in CSV or JSON." },
  { key: PERMISSIONS.REPORT_DOWNLOAD_OWN, name: "Download own report artifacts", category: "Reporting", description: "Download generated export artifacts using secure short-lived links." },
  { key: PERMISSIONS.STORE_REPORT_READ, name: "Read store reports", category: "Reporting", description: "Read store operational and financial reports for owned stores." },
  { key: PERMISSIONS.STORE_REPORT_GENERATE, name: "Generate store reports", category: "Reporting", description: "Request store report generation." },
  { key: PERMISSIONS.STORE_REPORT_EXPORT, name: "Export store reports", category: "Reporting", description: "Export store report artifacts." },
  { key: PERMISSIONS.DRIVER_REPORT_READ_OWN, name: "Read own driver reports", category: "Reporting", description: "Read delivery and earnings reports for authenticated driver." },
  { key: PERMISSIONS.DRIVER_REPORT_EXPORT_OWN, name: "Export own driver reports", category: "Reporting", description: "Export driver reports." },
  { key: PERMISSIONS.PROMOTER_REPORT_READ_OWN, name: "Read own promoter reports", category: "Reporting", description: "Read referral performance and earnings reports for promoter." },
  { key: PERMISSIONS.PROMOTER_REPORT_EXPORT_OWN, name: "Export own promoter reports", category: "Reporting", description: "Export promoter reports." },
  { key: PERMISSIONS.DEVELOPER_REPORT_READ_OWN, name: "Read own developer API reports", category: "Reporting", description: "Read developer API usage and request audit reports." },
  { key: PERMISSIONS.DEVELOPER_REPORT_EXPORT_OWN, name: "Export own developer API reports", category: "Reporting", description: "Export developer API reports." },
  { key: PERMISSIONS.REPORT_DEFINITION_READ, name: "Read report definitions", category: "Reporting Administration", description: "Read report definitions and versions." },
  { key: PERMISSIONS.REPORT_DEFINITION_MANAGE, name: "Manage report definitions", category: "Reporting Administration", description: "Create and update draft report definitions." },
  { key: PERMISSIONS.REPORT_DEFINITION_PUBLISH, name: "Publish report definitions", category: "Reporting Administration", description: "Approve and publish versioned report definitions." },
  { key: PERMISSIONS.REPORT_JOB_READ, name: "Read report jobs", category: "Reporting Administration", description: "Read execution state of all system report jobs." },
  { key: PERMISSIONS.REPORT_JOB_CANCEL, name: "Cancel report jobs", category: "Reporting Administration", description: "Cancel running or queued report jobs." },
  { key: PERMISSIONS.REPORT_JOB_RETRY, name: "Retry report jobs", category: "Reporting Administration", description: "Retry failed report jobs." },
  { key: PERMISSIONS.REPORT_ARTIFACT_READ, name: "Read report artifacts", category: "Reporting Administration", description: "Inspect generated export artifact metadata." },
  { key: PERMISSIONS.REPORT_ARTIFACT_EXPIRE, name: "Expire report artifacts", category: "Reporting Administration", description: "Manually expire export artifacts." },
  { key: PERMISSIONS.REPORT_RESTRICTED_DATA_READ, name: "Read restricted reporting data", category: "Reporting Administration", description: "Access high-sensitivity report projections under exact permission." },
  { key: PERMISSIONS.REPORT_RECONCILIATION_READ, name: "Read report reconciliation", category: "Reporting Administration", description: "Inspect reporting reconciliation cases." },
  { key: PERMISSIONS.REPORT_RECONCILIATION_RETRY, name: "Retry report reconciliation", category: "Reporting Administration", description: "Run report reconciliation recovery actions." },
  { key: PERMISSIONS.SYSTEM_READINESS_READ, name: "Read system readiness diagnostics", category: "Command Centre", description: "Read safe privileged readiness and production-lock diagnostics." },
  { key: PERMISSIONS.INCIDENTS_READ, name: "Read operational incidents", category: "Command Centre", description: "Read operational incident records and safe timelines." },
  { key: PERMISSIONS.INCIDENTS_MANAGE, name: "Manage operational incidents", category: "Command Centre", description: "Create and transition operational incidents." },
  { key: PERMISSIONS.PRIVACY_REQUESTS_READ, name: "Read privacy requests", category: "Governance", description: "Read identity-verified privacy request records." },
  { key: PERMISSIONS.PRIVACY_REQUESTS_MANAGE, name: "Manage privacy requests", category: "Governance", description: "Transition privacy requests after verification and hold review." },
  { key: PERMISSIONS.LEGAL_DOCUMENTS_READ, name: "Read legal document versions", category: "Governance", description: "Read legal-document version metadata." },
  { key: PERMISSIONS.LEGAL_DOCUMENTS_MANAGE, name: "Manage legal document drafts", category: "Governance", description: "Create legal-document drafts with immutable content hashes." },
  { key: PERMISSIONS.LEGAL_DOCUMENTS_PUBLISH, name: "Publish legal document versions", category: "Governance", description: "Publish immutable legal-document versions." },
  { key: PERMISSIONS.PROCESSORS_READ, name: "Read processor status", category: "Command Centre", description: "Read safe processor-run and lease visibility." },
];

export const DEFAULT_ADMIN_PERMISSION_KEYS: PermissionKey[] = [
  PERMISSIONS.ADMIN_DASHBOARD_READ,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.CUSTOMERS_READ,
  PERMISSIONS.STORES_READ,
  PERMISSIONS.DRIVERS_READ,
  PERMISSIONS.ORDERS_READ,
  PERMISSIONS.DISPATCH_READ,
  PERMISSIONS.REGIONS_READ,
  PERMISSIONS.PRICING_READ,
  PERMISSIONS.ACTIVITY_READ,
  PERMISSIONS.EMAILS_READ,
  PERMISSIONS.CONTACTS_READ,
  PERMISSIONS.LEDGER_READ,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.PAYMENT_PROVIDERS_READ,
  PERMISSIONS.PAYMENT_WEBHOOKS_READ,
  PERMISSIONS.PAYMENT_RECONCILIATION_READ,
  PERMISSIONS.FINANCE_DASHBOARD_READ,
  PERMISSIONS.WITHDRAWALS_READ,
  PERMISSIONS.PAYOUT_DESTINATIONS_READ,
  PERMISSIONS.COMMISSION_PLANS_READ,
  PERMISSIONS.COMMISSIONS_READ,
  PERMISSIONS.COMMISSION_RECONCILIATION_READ,
  PERMISSIONS.FINANCE_COMMISSIONS_READ,
  PERMISSIONS.CUSTOMER_WALLETS_READ,
  PERMISSIONS.REFUNDS_READ,
  PERMISSIONS.REFUND_PROVIDER_STATUS_READ,
  PERMISSIONS.FINANCE_REFUNDS_READ,
  PERMISSIONS.STORE_EARNINGS_READ,
  PERMISSIONS.FINANCE_STORE_EARNINGS_READ,
  PERMISSIONS.DRIVER_EARNINGS_READ,
  PERMISSIONS.FINANCE_DRIVER_EARNINGS_READ,
  PERMISSIONS.CATALOG_READ,
  PERMISSIONS.CATALOG_MODERATION_READ,
  PERMISSIONS.CATALOG_TAXONOMY_READ,
  PERMISSIONS.CATALOG_PRODUCT_TYPES_READ,
  PERMISSIONS.CATALOG_PRICING_READ,
  PERMISSIONS.CATALOG_INVENTORY_READ,
  PERMISSIONS.CATALOG_IMPORTS_READ,
  PERMISSIONS.STOREFRONT_PREVIEW_READ,
  PERMISSIONS.STOREFRONT_COLLECTIONS_READ,
  PERMISSIONS.STOREFRONT_SEARCH_SYNONYMS_READ,
  PERMISSIONS.STOREFRONT_PROJECTIONS_READ,
  PERMISSIONS.MARKETPLACE_CHECKOUT_READ,
  PERMISSIONS.MARKETPLACE_ORDERS_READ,
  PERMISSIONS.INVENTORY_RESERVATIONS_READ,
  PERMISSIONS.MARKETPLACE_SETTLEMENT_READ,
  PERMISSIONS.STORE_ORDERS_READ,
  PERMISSIONS.STORE_ORDERS_RECONCILE,
  PERMISSIONS.STORE_ORDERS_RESCAN,
  PERMISSIONS.STORE_ORDERS_RETRY_ADJUSTMENT,
  PERMISSIONS.STORE_ORDERS_RETRY_REFUND,
  PERMISSIONS.STORE_ORDERS_RETRY_DELIVERY,
  PERMISSIONS.STORE_ORDERS_RECONCILE_HANDOFF,
  PERMISSIONS.STORE_ORDER_POLICIES_MANAGE,
  PERMISSIONS.STORE_ORDER_POLICIES_APPROVE,
  PERMISSIONS.SUBSCRIPTION_PROGRAMS_READ,
  PERMISSIONS.SUBSCRIPTION_PROGRAMS_MANAGE,
  PERMISSIONS.SUBSCRIPTION_PLANS_READ,
  PERMISSIONS.SUBSCRIPTION_PLANS_CREATE,
  PERMISSIONS.SUBSCRIPTION_PLANS_REVIEW,
  PERMISSIONS.SUBSCRIPTION_PLANS_APPROVE,
  PERMISSIONS.SUBSCRIPTION_PLANS_ACTIVATE,
  PERMISSIONS.SUBSCRIPTION_PLANS_RETIRE,
  PERMISSIONS.SUBSCRIPTION_CONTRACTS_READ,
  PERMISSIONS.SUBSCRIPTION_CONTRACTS_RECONCILE,
  PERMISSIONS.SUBSCRIPTION_BILLING_READ,
  PERMISSIONS.SUBSCRIPTION_BILLING_RECONCILE,
  PERMISSIONS.SUBSCRIPTION_ENTITLEMENTS_READ,
  PERMISSIONS.SUBSCRIPTION_ENTITLEMENTS_RECONCILE,
  PERMISSIONS.PROMOTIONS_READ,
  PERMISSIONS.PROMOTIONS_MANAGE,
  PERMISSIONS.PROMOTIONS_SUBMIT,
  PERMISSIONS.PROMOTIONS_REVIEW,
  PERMISSIONS.PROMOTIONS_APPROVE,
  PERMISSIONS.PROMOTIONS_ACTIVATE,
  PERMISSIONS.PROMOTIONS_PAUSE,
  PERMISSIONS.PROMOTIONS_END,
  PERMISSIONS.PROMOTIONS_BUDGET_READ,
  PERMISSIONS.PROMOTIONS_BUDGET_MANAGE,
  PERMISSIONS.PROMOTIONS_CODES_READ,
  PERMISSIONS.PROMOTIONS_CODES_MANAGE,
  PERMISSIONS.PROMOTIONS_REDEMPTIONS_READ,
  PERMISSIONS.PROMOTIONS_RECONCILIATION_READ,
  PERMISSIONS.PROMOTIONS_RECONCILIATION_MANAGE,
  PERMISSIONS.ADVERTISING_READ,
  PERMISSIONS.ADVERTISING_CAMPAIGNS_READ,
  PERMISSIONS.ADVERTISING_CAMPAIGNS_REVIEW,
  PERMISSIONS.ADVERTISING_CAMPAIGNS_APPROVE,
  PERMISSIONS.ADVERTISING_CAMPAIGNS_ACTIVATE,
  PERMISSIONS.ADVERTISING_CAMPAIGNS_PAUSE,
  PERMISSIONS.ADVERTISING_CAMPAIGNS_SUSPEND,
  PERMISSIONS.ADVERTISING_CAMPAIGNS_END,
  PERMISSIONS.ADVERTISING_PLACEMENTS_READ,
  PERMISSIONS.ADVERTISING_PLACEMENTS_MANAGE,
  PERMISSIONS.ADVERTISING_RATE_CARDS_READ,
  PERMISSIONS.ADVERTISING_RATE_CARDS_MANAGE,
  PERMISSIONS.ADVERTISING_MEASUREMENT_READ,
  PERMISSIONS.ADVERTISING_INVALID_TRAFFIC_READ,
  PERMISSIONS.ADVERTISING_INVALID_TRAFFIC_REVIEW,
  PERMISSIONS.ADVERTISING_RECONCILIATION_READ,
  PERMISSIONS.ADVERTISING_RECONCILIATION_MANAGE,
  PERMISSIONS.PROMOTERS_READ,
  PERMISSIONS.PROMOTERS_REVIEW,
  PERMISSIONS.PROMOTERS_APPROVE,
  PERMISSIONS.PROMOTERS_ACTIVATE,
  PERMISSIONS.PROMOTERS_SUSPEND,
  PERMISSIONS.PROMOTERS_TERMINATE,
  PERMISSIONS.PROMOTER_PROGRAMS_MANAGE,
  PERMISSIONS.PROMOTER_PROGRAMS_REVIEW,
  PERMISSIONS.PROMOTER_PROGRAMS_APPROVE,
  PERMISSIONS.PROMOTER_PROGRAMS_ACTIVATE,
  PERMISSIONS.PROMOTER_PROGRAMS_PAUSE,
  PERMISSIONS.PROMOTER_PROGRAMS_END,
  PERMISSIONS.PROMOTER_ATTRIBUTIONS_READ,
  PERMISSIONS.PROMOTER_QUALIFICATIONS_READ,
  PERMISSIONS.PROMOTER_EARNINGS_READ,
  PERMISSIONS.PROMOTER_FRAUD_READ,
  PERMISSIONS.PROMOTER_FRAUD_MANAGE,
  PERMISSIONS.PROMOTER_RECONCILIATION_READ,
  PERMISSIONS.PROMOTER_RECONCILIATION_MANAGE,
  PERMISSIONS.PROMOTER_DISPUTES_READ,
  PERMISSIONS.PROMOTER_DISPUTES_MANAGE,
  PERMISSIONS.PROMOTER_ASSETS_MANAGE,
  PERMISSIONS.PROMOTER_AGREEMENTS_MANAGE,
  PERMISSIONS.RECRUITMENT_READ,
  PERMISSIONS.RECRUITMENT_REQUISITIONS_MANAGE,
  PERMISSIONS.RECRUITMENT_REQUISITIONS_APPROVE,
  PERMISSIONS.RECRUITMENT_OPENINGS_MANAGE,
  PERMISSIONS.RECRUITMENT_OPENINGS_REVIEW,
  PERMISSIONS.RECRUITMENT_OPENINGS_PUBLISH,
  PERMISSIONS.RECRUITMENT_APPLICATIONS_READ,
  PERMISSIONS.RECRUITMENT_APPLICATIONS_REVIEW,
  PERMISSIONS.RECRUITMENT_APPLICATIONS_ASSIGN,
  PERMISSIONS.RECRUITMENT_DECISIONS_CREATE,
  PERMISSIONS.RECRUITMENT_INTERVIEWS_MANAGE,
  PERMISSIONS.RECRUITMENT_SCORECARDS_SUBMIT,
  PERMISSIONS.RECRUITMENT_CHECKS_READ,
  PERMISSIONS.RECRUITMENT_CHECKS_REQUEST,
  PERMISSIONS.RECRUITMENT_CHECKS_REVIEW,
  PERMISSIONS.RECRUITMENT_OFFERS_MANAGE,
  PERMISSIONS.RECRUITMENT_OFFERS_APPROVE,
  PERMISSIONS.RECRUITMENT_HANDOFFS_READ,
  PERMISSIONS.RECRUITMENT_HANDOFFS_PROCESS,
  PERMISSIONS.RECRUITMENT_FRAUD_READ,
  PERMISSIONS.RECRUITMENT_FRAUD_MANAGE,
  PERMISSIONS.RECRUITMENT_RECONCILIATION_READ,
  PERMISSIONS.RECRUITMENT_RECONCILIATION_MANAGE,
  PERMISSIONS.RECRUITMENT_PRIVACY_MANAGE,
  PERMISSIONS.RECRUITMENT_RETENTION_MANAGE,
  PERMISSIONS.RECRUITMENT_EMPLOYMENT_EQUITY_READ,
  PERMISSIONS.RECRUITMENT_EMPLOYMENT_EQUITY_MANAGE,
  PERMISSIONS.NOTIFICATION_CATEGORY_READ,
  PERMISSIONS.NOTIFICATION_TEMPLATE_READ,
  PERMISSIONS.NOTIFICATION_ROUTE_READ,
  PERMISSIONS.NOTIFICATION_DELIVERY_READ,
  PERMISSIONS.NOTIFICATION_SUPPRESSION_READ,
  PERMISSIONS.NOTIFICATION_PROVIDER_STATUS_READ,
  PERMISSIONS.NOTIFICATION_RECONCILIATION_READ,
  PERMISSIONS.REPORT_DEFINITION_READ,
  PERMISSIONS.REPORT_JOB_READ,
  PERMISSIONS.REPORT_ARTIFACT_READ,
  PERMISSIONS.REPORT_RECONCILIATION_READ,
  PERMISSIONS.SYSTEM_READINESS_READ,
  PERMISSIONS.SECURITY_SESSIONS_MANAGE,
  PERMISSIONS.INCIDENTS_READ,
  PERMISSIONS.PRIVACY_REQUESTS_READ,
  PERMISSIONS.LEGAL_DOCUMENTS_READ,
  PERMISSIONS.PROCESSORS_READ,
];

export const SELF_REPORT_PERMISSION_KEYS: PermissionKey[] = [
  PERMISSIONS.REPORT_READ_OWN,
  PERMISSIONS.REPORT_GENERATE_OWN,
  PERMISSIONS.REPORT_EXPORT_OWN,
  PERMISSIONS.REPORT_DOWNLOAD_OWN,
];

export const DEFAULT_STORE_CATALOG_PERMISSION_KEYS: PermissionKey[] = [
  PERMISSIONS.CATALOG_READ,
  PERMISSIONS.CATALOG_MANAGE,
  PERMISSIONS.CATALOG_SUBMIT,
  PERMISSIONS.CATALOG_PRICING_READ,
  PERMISSIONS.CATALOG_PRICING_MANAGE,
  PERMISSIONS.CATALOG_INVENTORY_READ,
  PERMISSIONS.CATALOG_INVENTORY_MANAGE,
  PERMISSIONS.CATALOG_IMPORTS_READ,
  PERMISSIONS.CATALOG_IMPORTS_MANAGE,
  PERMISSIONS.STORE_ORDERS_READ,
  PERMISSIONS.STORE_ORDERS_REVIEW,
  PERMISSIONS.STORE_ORDERS_ACCEPT,
  PERMISSIONS.STORE_ORDERS_REJECT,
  PERMISSIONS.STORE_ORDERS_AVAILABILITY,
  PERMISSIONS.STORE_ORDERS_SUBSTITUTIONS,
  PERMISSIONS.STORE_ORDERS_PREPARE,
  PERMISSIONS.STORE_ORDERS_HANDOFF,
  PERMISSIONS.STORE_SUBSCRIPTIONS_READ,
  PERMISSIONS.STORE_SUBSCRIPTIONS_MANAGE,
  PERMISSIONS.STORE_SUBSCRIPTIONS_BILLING,
  PERMISSIONS.STORE_PROMOTIONS_MANAGE,
  PERMISSIONS.PROMOTIONS_READ,
  PERMISSIONS.ADVERTISING_READ,
  PERMISSIONS.ADVERTISING_MANAGE_OWN_STORE,
  PERMISSIONS.ADVERTISING_SUBMIT_OWN_STORE,
  PERMISSIONS.ADVERTISING_FUND_OWN_STORE,
  PERMISSIONS.ADVERTISING_PAUSE_OWN_STORE,
  PERMISSIONS.ADVERTISING_END_OWN_STORE,
  PERMISSIONS.STORE_REPORT_READ,
  PERMISSIONS.STORE_REPORT_GENERATE,
  PERMISSIONS.STORE_REPORT_EXPORT,
];

export const SELF_NOTIFICATION_PERMISSION_KEYS: PermissionKey[] = [
  PERMISSIONS.NOTIFICATION_READ_OWN,
  PERMISSIONS.NOTIFICATION_MANAGE_OWN_READ_STATE,
  PERMISSIONS.NOTIFICATION_MANAGE_OWN_PREFERENCES,
  PERMISSIONS.NOTIFICATION_MANAGE_OWN_PUSH_ENDPOINTS,
  PERMISSIONS.NOTIFICATION_MANAGE_OWN_MARKETING_CONSENT,
];

export const SELF_DEVELOPER_PERMISSION_KEYS: PermissionKey[] = [
  PERMISSIONS.DEVELOPER_APPLICATION_READ_OWN, PERMISSIONS.DEVELOPER_APPLICATION_MANAGE_OWN, PERMISSIONS.DEVELOPER_APPLICATION_SUBMIT_OWN,
  PERMISSIONS.DEVELOPER_CREDENTIAL_READ_OWN, PERMISSIONS.DEVELOPER_CREDENTIAL_CREATE_OWN, PERMISSIONS.DEVELOPER_CREDENTIAL_ROTATE_OWN, PERMISSIONS.DEVELOPER_CREDENTIAL_REVOKE_OWN,
  PERMISSIONS.DEVELOPER_WEBHOOK_READ_OWN, PERMISSIONS.DEVELOPER_WEBHOOK_MANAGE_OWN, PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_READ_OWN, PERMISSIONS.DEVELOPER_WEBHOOK_DELIVERY_RETRY_OWN,
  PERMISSIONS.DEVELOPER_API_USAGE_READ_OWN, PERMISSIONS.DEVELOPER_DOCUMENTATION_READ,
  PERMISSIONS.DEVELOPER_REPORT_READ_OWN, PERMISSIONS.DEVELOPER_REPORT_EXPORT_OWN,
];

export const ROLE_DEFAULT_PERMISSION_KEYS: Partial<Record<UserRole, PermissionKey[]>> = {
  [UserRole.ADMIN]: DEFAULT_ADMIN_PERMISSION_KEYS,
  [UserRole.CUSTOMER]: [...SELF_NOTIFICATION_PERMISSION_KEYS, ...SELF_DEVELOPER_PERMISSION_KEYS, ...SELF_REPORT_PERMISSION_KEYS],
  [UserRole.STORE]: [...SELF_NOTIFICATION_PERMISSION_KEYS, ...SELF_DEVELOPER_PERMISSION_KEYS, ...SELF_REPORT_PERMISSION_KEYS, ...DEFAULT_STORE_CATALOG_PERMISSION_KEYS],
  [UserRole.DRIVER]: [...SELF_NOTIFICATION_PERMISSION_KEYS, PERMISSIONS.DRIVER_REPORT_READ_OWN, PERMISSIONS.DRIVER_REPORT_EXPORT_OWN, PERMISSIONS.REPORT_DOWNLOAD_OWN],
  [UserRole.PROMOTER]: [
    PERMISSIONS.PROMOTER_PROFILE_READ_OWN, PERMISSIONS.PROMOTER_PROFILE_MANAGE_OWN, PERMISSIONS.PROMOTER_PROGRAMS_READ, PERMISSIONS.PROMOTER_PROGRAMS_ENROLL, PERMISSIONS.PROMOTER_CHANNELS_MANAGE_OWN, PERMISSIONS.PROMOTER_CODES_MANAGE_OWN, PERMISSIONS.PROMOTER_REFERRALS_READ_OWN, PERMISSIONS.PROMOTER_EARNINGS_READ_OWN, PERMISSIONS.PROMOTER_WALLET_READ_OWN, PERMISSIONS.PROMOTER_WITHDRAWALS_CREATE_OWN, PERMISSIONS.PROMOTER_PERFORMANCE_READ_OWN, PERMISSIONS.PROMOTER_ASSETS_READ, PERMISSIONS.PROMOTER_DISPUTES_MANAGE_OWN,
    PERMISSIONS.PROMOTER_REPORT_READ_OWN, PERMISSIONS.PROMOTER_REPORT_EXPORT_OWN, PERMISSIONS.REPORT_DOWNLOAD_OWN,
    ...SELF_NOTIFICATION_PERMISSION_KEYS,
  ],
};

export function isSystemPermissionKey(key: string): key is PermissionKey {
  return SYSTEM_PERMISSION_DEFINITIONS.some((permission) => permission.key === key);
}
